---
output: html_document
editor_options: 
  chunk_output_type: console
---

# R Modulo 4.2 - Decomposição da diversidade {#partdiv}

### RESUMO {-}

Na ecologia de comunidades, a diversidade de espécies é uma medida importante para entender a complexidade e a estrutura de uma comunidade de organismos. Vamos explorar algumas das métricas comuns usadas para avaliar a diversidade de espécies.

### Apresentação {-}

Na ecologia de comunidades, a diversidade de espécies é uma medida importante para entender a complexidade e a estrutura de uma comunidade de organismos. Vamos explorar algumas das métricas comuns usadas para avaliar a diversidade de espécies. Essas métricas são usadas para avaliar a diversidade e a estrutura de comunidades ecológicas. Elas podem fornecer informações importantes sobre como as diferentes espécies interagem em um ecossistema e como a diversidade de espécies pode ser afetada por mudanças ambientais ou distúrbios [@RN357].

## Sobre os dados

Usaremos para esse tutorial dois conjuntos de dados. A **Matriz comunitária** ([ppbio06c-peixes.xlsx](https://docs.google.com/spreadsheets/d/1Olyew6L3SCFeSXWJC54Ak3MKmgHD3sTK/edit?usp=drive_link&ouid=101766125969589673518&rtpof=true&sd=true)) de dados coletados no Programa de Pesquisa em Biodiversidade - PPBio (Veja [Programa de Pesquisa em Biodiversidade -- PPBio](https://ppbio.inpa.gov.br/Sobre)). Esses são dados de espécies de peixes distribuidas em diversas unidades amostrais (UA's ou sítios). Essa é a **matriz bruta de dados**, porque os valores ainda não foram ajustados para os valores de Captura Por Unidade de Esforço (CPUE), nem foram relativizados ou transformados.

Além disso usaremos a **tabela de agrupamentos** ([ppbio06-grupos](https://docs.google.com/spreadsheets/d/1H52eBBxZ1k-6Xgrse87etq6mq3mMUTZi/edit?usp=drive_link&ouid=101766125969589673518&rtpof=true&sd=true))  

**Revise as informações sobre as bases de dados no capítulo [Bases de Dados](\@ref(bases)). A matriz de dados para esse Módulo pode ser baixada na seção [Arquivos disponíveis](\@ref(arqs)).**

**Revise o capítulo anterior [Estrutura da Comunidade](\@ref(estrcom))**

## Organização básica

## Apêndices {.unnumbered}

### Sites consultados {.unnumbered}
[Primeira coluna para nomes das linhas](www.link.com) 

### Script limpo {-}

Aqui apresento o scrip na íntegra sem os textos ou outros comentários. Você pode copiar e colar no R para executa-lo. Lembre de remover os [`#`]{style=color:green} ou [`##`]{style=color:green} caso necessite executar essas linhas.

```{r, eval=FALSE, echo=FALSE, purl=FALSE}
knitr::purl(input = "02-shared.Rmd", output = "script-rmd2-4-2.txt", documentation = 0)
Script <- readLines("script-rmd2-4-2.txt")
Script <- Script[Script != ""]
writeLines(Script, "script-rmd2-4-2.txt")
cat(Script, sep = "\n")
```

## Referências {-}
