--- 
title: "Fundamentos de Ecologia Numérica"
subtitle: "Disciplina de Ecologia Numérica do Curso de Ciências Biológicas do Campus V da UEPB"
author: 
  - Prof. Elvio S. F. Medeiros  
  - Laboratório de Ecologia
  - Universidade Estadual da Paraíba
  - Campus V, João Pessoa, PB
date: "Last updated: `r format(Sys.time(), '%d/%m/%Y %H:%M:%S')`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography:
  - refs/my_references-x9.bib
  - packages.bib
csl: refs/abnt.csl
link-citations: yes
github-repo: rstudio/fundamentos_de_ecologia_numerica
description: ".... The output format for this example is bookdown::gitbook."
---

# Apresentação

## Motivação

Este é um site experimental da disciplina de graduação de Ecologia Numérica do Curso de Ciências Biológicas da Universidade Estadual da Paraíba.

O site experimental da disciplina de Ecologia Numérica da UEPB é uma plataforma criada com o objetivo de apresentar exemplos didáticos aos alunos, explorando diferentes conceitos e técnicas utilizadas na análise de dados em Ecologia. É importante destacar que os exemplos apresentados no site podem conter imprecisões ou códigos demasiado extensos (aparentemente desnecessários para um ecólogo e programador de R mais experiente), mas isso é proposital, pois a finalidade é oferecer um material didático para os alunos, que possa facilitar a compreensão dos conceitos abordados durante as aulas. Dessa forma, o site é uma ferramenta complementar às aulas presenciais, que busca fornecer exemplos práticos e didáticos para os estudantes de Ecologia Numérica da UEPB.

Como mencionado, a finalidade é didatica e de apresentar o tema seguindo passo-a-passo e contextualizando com dados ecológicos reais. Por isso, além das informações sobre o conteúdo do site experimental da disciplina de ecologia numérica da UEPB, é importante destacar que qualquer erro ou problema relacionado ao site pode ser reportado ao [responsável pelo site](elviomedeiros@servidor.uepb.edu.br).

É fundamental que os usuários do site compreendam que plágio e outras formas de má conduta acadêmica são inaceitáveis e podem ter sérias consequências. O [responsável pelo site](elviomedeiros@servidor.uepb.edu.br) se compromete a remover qualquer conteúdo ofensivo ou sem citar a devida fonte consultada, que possa ter sido publicado erroneamente ou por engano.

## Organização do livro

Este livro é organizado em `QUATRO` partes:

Na `PARTE I`, são apresentadas as bases teóricas fundamentais sobre ecologia numérica e análise multivariada.

Na `PARTE II`, é apresentada a fundamentação teórica para o entedimento dos conjuntos de dados que são trabalhados ao longo da `PARTE III` e execução das estatísticas descritas.

Na `PARTE III`, são apresentados os Módulos do RStudio, na forma de tutoriais discutidos, que podem ser executados passo-a-passo.

Por fim, na `PARTE IV`, são apresentadas informações gerais de apoio para o melhor entendimento do conteúdo, como uma lista geral das tabelas usadas na `PARTE II`, um glossário de termos, bibliografia geral, entre outras fontes de informação.

## Como estudar por esse livro?

Simples! Siga a sequência que é apresentada.

  - Estude a teoria (`PARTE I`), certifique-se de que entende os conceitos e é capaz de tomar decisões fundamentadas na teoria. Revise/relembre do Ensino Médio a matemática necessária (Conjuntos, Matriz, Álgebra, Teorema de Pitágoras, etc.).
  - Leia a fundamentação das bases de dados que usará subsequentemente (`PARTE II`). Mas lembre, você não precisa ser especialista nos grupos taxonômicos apresentados aqui como exemplo. O ecólogo trabalha com dados, e eles falam por si só.
  - Parta para a ação (`PARTE III`), começe com os primeiros módulos do R, siga as instruções passo-a-passo, execute linha por linha de código, atente para os resultados.
  - Consulte os detalhes e referências apresentados na `PARTE IV`.

### Para um estudo aprofundado

