<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title> 13 Correlação e Regressão | Fundamentos de Ecologia Numérica</title>
<meta name="author" content="Prof. Elvio S. F. Medeiros">
<meta name="author" content="Laboratório de Ecologia">
<meta name="author" content="Universidade Estadual da Paraíba">
<meta name="author" content="Campus V, João Pessoa, PB">
<meta name="description" content="RESUMO A estatística descritiva tem um papel importante a desempenhar na ciência. Quando problemas específicos são tratados na ciência, os dados precisam ser coletados, analisados e apresentados...">
<meta name="generator" content="bookdown 0.47 with bs4_book()">
<meta property="og:title" content=" 13 Correlação e Regressão | Fundamentos de Ecologia Numérica">
<meta property="og:type" content="book">
<meta property="og:description" content="RESUMO A estatística descritiva tem um papel importante a desempenhar na ciência. Quando problemas específicos são tratados na ciência, os dados precisam ser coletados, analisados e apresentados...">
<meta name="twitter:card" content="summary">
<meta name="twitter:title" content=" 13 Correlação e Regressão | Fundamentos de Ecologia Numérica">
<meta name="twitter:description" content="RESUMO A estatística descritiva tem um papel importante a desempenhar na ciência. Quando problemas específicos são tratados na ciência, os dados precisam ser coletados, analisados e apresentados...">
<!-- JS --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/fuse.js/6.4.6/fuse.js" integrity="sha512-zv6Ywkjyktsohkbp9bb45V6tEMoWhzFzXis+LrMehmJZZSys19Yxf1dopHx7WzIKxr5tK2dVcYmaCk2uqdjF4A==" crossorigin="anonymous"></script><script src="https://kit.fontawesome.com/6ecbd6c532.js" crossorigin="anonymous"></script><script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link href="libs/bootstrap-4.6.0/bootstrap.min.css" rel="stylesheet">
<script src="libs/bootstrap-4.6.0/bootstrap.bundle.min.js"></script><script src="libs/bs3compat-0.11.0/transition.js"></script><script src="libs/bs3compat-0.11.0/tabs.js"></script><script src="libs/bs3compat-0.11.0/bs3compat.js"></script><link href="libs/bs4_book-1.0.0/bs4_book.css" rel="stylesheet">
<script src="libs/bs4_book-1.0.0/bs4_book.js"></script><script src="libs/kePrint-0.0.1/kePrint.js"></script><link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet">
<link href="libs/bsTable-3.3.7/bootstrapTable.min.css" rel="stylesheet">
<script src="libs/bsTable-3.3.7/bootstrapTable.js"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/autocomplete.js/0.38.0/autocomplete.jquery.min.js" integrity="sha512-GU9ayf+66Xx2TmpxqJpliWbT5PiGYxpaG8rfnBEk1LL8l1KGkRShhngwdXK1UgqhAzWpZHSiYPc09/NwDQIGyg==" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/mark.min.js" integrity="sha512-5CYOlHXGh6QpOFA/TeTylKLWfB3ftPsde7AnmhuitiTX4K5SqCLBeKro6sPS8ilsz1Q4NRx3v8Ko2IBiszzdww==" crossorigin="anonymous"></script><!-- CSS --><style type="text/css">
    
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  </style>
<style type="text/css">
    /* Used with Pandoc 2.11+ new --citeproc when CSL is used */
    div.csl-bib-body { }
    div.csl-entry {
      clear: both;
          margin-bottom: 1em;
        }
    .hanging div.csl-entry {
      margin-left:2em;
      text-indent:-2em;
    }
    div.csl-left-margin {
      min-width:2em;
      float:left;
    }
    div.csl-right-inline {
      margin-left:2em;
      padding-left:1em;
    }
    div.csl-indent {
      margin-left: 2em;
    }
  </style>
<link rel="stylesheet" href="style.css">
</head>
<body data-spy="scroll" data-target="#toc">

<div class="container-fluid">
<div class="row">
  <header class="col-sm-12 col-lg-3 sidebar sidebar-book"><a class="sr-only sr-only-focusable" href="#content">Skip to main content</a>

    <div class="d-flex align-items-start justify-content-between">
      <h1>
        <a href="index.html" title="Disciplina de Ecologia Numérica do Curso de Ciências Biológicas do Campus V da UEPB">Fundamentos de Ecologia Numérica</a>:
        <small class="text-muted">Disciplina de Ecologia Numérica do Curso de Ciências Biológicas do Campus V da UEPB</small>
      </h1>
      <button class="btn btn-outline-primary d-lg-none ml-2 mt-1" type="button" data-toggle="collapse" data-target="#main-nav" aria-expanded="true" aria-controls="main-nav"><i class="fas fa-bars"></i><span class="sr-only">Show table of contents</span></button>
    </div>

    <div id="main-nav" class="collapse-lg">
      <form role="search">
        <input id="search" class="form-control" type="search" placeholder="Search" aria-label="Search">
</form>

      <nav aria-label="Table of contents"><h2>Table of contents</h2>
        <ul class="book-toc list-unstyled">
<li><a class="" href="index.html">Fundamentos de Ecologia Numérica</a></li>
<li><a class="" href="motiv.html">Motivação</a></li>
<li><a class="" href="plano.html">Plano de estudo</a></li>
<li><a class="" href="org.html">Organização do livro</a></li>
<li><a class="" href="estudar.html">Como estudar por esse livro?</a></li>
<li><a class="" href="cita.html">Como citar esse livro</a></li>
<li><a class="" href="download.html">Download da versão impressa</a></li>
<li class="book-part">I. INTRODUÇÃO</li>
<li><a class="" href="ferram.html"><span class="header-section-number">1</span> Ferramentas</a></li>
<li><a class="" href="rrstu.html"><span class="header-section-number">2</span> Introdução ao R/RStudio</a></li>
<li class="book-part">II. TEORIA</li>
<li><a class="" href="amd.html"><span class="header-section-number">3</span> Teoria 1 - Introdução à Análise Multivariada de Dados (AMD)</a></li>
<li><a class="" href="tiposE.html"><span class="header-section-number">4</span> Teoria 2 - Tipos de dados usados em AMD</a></li>
<li><a class="" href="reltrnsT.html"><span class="header-section-number">5</span> Teoria 3 - Relativizações e transformações de dados</a></li>
<li class="book-part">III. BASES DE DADOS</li>
<li><a class="" href="bases.html"><span class="header-section-number">6</span> Bases de dados. Dados do PPBio Semiárido</a></li>
<li><a class="" href="basepeixes.html"><span class="header-section-number">7</span> Base de dados I - Peixes</a></li>
<li><a class="" href="basehab.html"><span class="header-section-number">8</span> Base de dados II - Habitat</a></li>
<li class="book-part">IV. ESTATÍSTICAS DESCRITIVAS</li>
<li><a class="" href="tiposR.html"><span class="header-section-number">9</span> R Módulo 1 - Sintaxe e Tipos de dados no R</a></li>
<li><a class="" href="xls.html"><span class="header-section-number">10</span> R Módulo 2 - Importando planilhas de dados</a></li>
<li><a class="" href="norm.html"><span class="header-section-number">11</span> R Módulo 3.1 - Estatísticas descritivas e normalidade</a></li>
<li><a class="" href="testes.html"><span class="header-section-number">12</span> R Módulo 3.2 - Testes estatísticos</a></li>
<li><a class="active" href="correg.html"><span class="header-section-number">13</span> Correlação e Regressão</a></li>
<li><a class="" href="regmul.html"><span class="header-section-number">14</span> Regressão múltipla</a></li>
<li><a class="" href="mlgs.html"><span class="header-section-number">15</span> Modelos lineares generalizados (GLMs)</a></li>
<li><a class="" href="estrcom.html"><span class="header-section-number">16</span> R Módulo 4.1 - Estrutura da comunidade</a></li>
<li><a class="" href="partdiv.html"><span class="header-section-number">17</span> R Modulo 4.2 - Decomposição da diversidade</a></li>
<li><a class="" href="estrhab.html"><span class="header-section-number">18</span> R Módulo 4.3 - Estrutura do habitat</a></li>
<li class="book-part">V. ANÁLISES MULTIVARIADAS</li>
<li><a class="" href="reltrns.html"><span class="header-section-number">19</span> R Modulo 5 - Relativizações e transformações</a></li>
<li><a class="" href="outcentr.html"><span class="header-section-number">20</span> R Módulo 6 - Análise de outliers baseada no desvio padrão do centróide</a></li>
<li><a class="" href="upgma.html"><span class="header-section-number">21</span> R Módulo 7 - Análise de Classificação Hierárquica - SAHN</a></li>
<li><a class="" href="kmeans.html"><span class="header-section-number">22</span> R Módulo 8 - Análise de Classificação Não-hierárquica - K-Means</a></li>
<li class="book-part">VI. INFORMAÇÕES GERAIS</li>
<li><a class="" href="nomes.html"><span class="header-section-number">23</span> Nomenclatura das matrizes em AMD</a></li>
<li><a class="" href="bibliografia-geral.html">Bibliografia Geral</a></li>
</ul>

        <div class="book-extra">
          
        </div>
      </nav>
</div>
  </header><main class="col-sm-12 col-md-9 col-lg-7" id="content"><div id="correg" class="section level1" number="13">
<h1>
<span class="header-section-number"> 13</span> Correlação e Regressão<a class="anchor" aria-label="anchor" href="#correg"><i class="fas fa-link"></i></a>
</h1>
<div id="resumo-8" class="section level3 unnumbered">
<h3>RESUMO<a class="anchor" aria-label="anchor" href="#resumo-8"><i class="fas fa-link"></i></a>
</h3>
<p>A estatística descritiva tem um papel importante a desempenhar na ciência. Quando problemas específicos são tratados na ciência, os dados precisam ser coletados, analisados e apresentados de forma concisa para que outros possam se beneficiar do que foi encontrado.</p>
</div>
<div id="apresentação-8" class="section level3 unnumbered">
<h3>Apresentação<a class="anchor" aria-label="anchor" href="#apresenta%C3%A7%C3%A3o-8"><i class="fas fa-link"></i></a>
</h3>
<p>A estatística descritiva tem um papel importante a desempenhar na ciência. Quando problemas específicos são tratados na ciência, os dados precisam ser coletados, analisados e apresentados de forma concisa para que outros possam se beneficiar do que foi encontrado. Geralmente não é possível apresentar um conjunto de dados completo em uma publicação ou em um seminário e, mesmo que fosse, é improvável isso permitisse uma boa comunicação dos resultados da pesquisa. Em vez disso, os dados são geralmente resumidos como tabelas de frequência, histogramas e estatísticas descritivas que os leitores ou ouvintes podem assimilar prontamente, mas que ainda transmitem os elementos essenciais do conjunto de dados original. O principal objetivo do cálculo das estatísticas descritivas é transmitir informações essenciais contidas em um conjunto de dados da forma mais concisa e clara possível.</p>
</div>
<div id="correlação" class="section level2" number="13.1">
<h2>
<span class="header-section-number">13.1</span> Correlação<a class="anchor" aria-label="anchor" href="#correla%C3%A7%C3%A3o"><i class="fas fa-link"></i></a>
</h2>
<p>O <strong>coeficiente de correlação produto-momento de Pearson (<span class="math inline">\(r\)</span>)</strong> descreve a relação entre duas variáveis numéricas contínuas. A análise de correlação também pode ser aplicada entre variáveis categóricas binárias (coeficiente Phi) ou entre uma variável numérica contínua e uma variável categórica binária (correlação ponto-bisserial) <span class="citation">(<a href="#ref-coakes2001">COAKES; STEED, 2001</a>)</span>, porém essas abordagens não constituem o foco do presente texto.</p>
<p>Quando os pressupostos da correlação não podem ser adequadamente atendidos, utiliza-se uma alternativa não-paramétrica, a <strong>correlação por postos de Spearman (<span class="math inline">\(\rho\)</span>)</strong>.</p>
<p>Neste capítulo serão abordadas:</p>
<ul>
<li>Correlação simples bivariada (coeficiente de correlação produto-momento de Pearson)<br>
</li>
<li>Correlação de Spearman (bivariada não-paramétrica)<br>
</li>
<li>Correlação parcial</li>
</ul>
<p>A correlação bivariada simples, refere-se à correlação entre duas variáveis contínuas e é a medida mais comum de relação linear.</p>
<p>Esse coeficiente possui valores possíveis variando de:</p>
<p>-1 a +1,</p>
<p>onde o valor indica a força da relação, enquanto o sinal indica a direção da relação.</p>
<p>A correlação parcial fornece uma medida única de associação linear entre duas variáveis, ajustando para os efeitos de uma ou mais variáveis adicionais.</p>
<p>As duas fórmulas medem aspectos diferentes da relação entre duas variáveis.</p>
<div id="coeficiente-de-correlação-de-pearson-r" class="section level3" number="13.1.1">
<h3>
<span class="header-section-number">13.1.1</span> Coeficiente de correlação de Pearson (<span class="math inline">\(r\)</span>)<a class="anchor" aria-label="anchor" href="#coeficiente-de-correla%C3%A7%C3%A3o-de-pearson-r"><i class="fas fa-link"></i></a>
</h3>
<p><span class="math display">\[
r=\frac{\sum_{i=1}^{n}(x_i-\bar{x})(y_i-\bar{y})}
{\sqrt{\sum_{i=1}^{n}(x_i-\bar{x})^2}
\sqrt{\sum_{i=1}^{n}(y_i-\bar{y})^2}}
\]</span></p>
<p>onde:</p>
<ul>
<li>
<span class="math inline">\(x_i\)</span> e <span class="math inline">\(y_i\)</span>: valores observados das variáveis (x) e (y) para a observação (i);</li>
<li>
<span class="math inline">\(\bar{x}\)</span> e <span class="math inline">\(\bar{y}\)</span>: médias de (x) e (y);</li>
<li>
<span class="math inline">\(n\)</span>: número de observações.</li>
</ul>
<div id="como-a-fórmula-funciona" class="section level4" number="13.1.1.1">
<h4>
<span class="header-section-number">13.1.1.1</span> Como a fórmula funciona<a class="anchor" aria-label="anchor" href="#como-a-f%C3%B3rmula-funciona"><i class="fas fa-link"></i></a>
</h4>
<p>Primeiro, calculamos o desvio de cada observação em relação à média:</p>
<p><span class="math display">\[
x_i-\bar{x}
\]</span></p>
<p>e</p>
<p><span class="math display">\[
y_i-\bar{y}
\]</span>
Segundo, multiplicamos os desvios das duas variáveis:</p>
<p><span class="math display">\[
(x_i-\bar{x})(y_i-\bar{y}).
\]</span></p>
<p>Se <strong>ambos os desvios forem positivos ou ambos negativos</strong>, o produto é positivo, indicando associação positiva. Se <strong>um desvio for positivo e o outro negativo</strong>, o produto é negativo, indicando associação negativa.</p>
<p>Terceiro, somamos todos esses produtos, obtendo uma medida da covariação entre as variáveis.</p>
<p>Por último, dividimos pelo produto dos desvios padrão, padronizando o resultado para que ele varie entre -1 e 1.</p>
<p>Assim:</p>
<p><span class="math inline">\(r=1\)</span>: correlação positiva perfeita;
<span class="math inline">\(r=-1\)</span>: correlação negativa perfeita;
<span class="math inline">\(r=0\)</span>: ausência de correlação linear.</p>
</div>
</div>
<div id="coeficiente-de-determinação-r2" class="section level3" number="13.1.2">
<h3>
<span class="header-section-number">13.1.2</span> Coeficiente de determinação (<span class="math inline">\(r^2\)</span>)<a class="anchor" aria-label="anchor" href="#coeficiente-de-determina%C3%A7%C3%A3o-r2"><i class="fas fa-link"></i></a>
</h3>
<p>Na regressão linear simples, temos:</p>
<p><span class="math display">\[
R^2=\frac{\text{SQ}*{\text{Regressão}}}
{\text{SQ}*{\text{Total}}}.
\]</span></p>
<p>onde:</p>
<ul>
<li>
<span class="math inline">\(\text{SQ}_{\text{Total}}\)</span>: soma de quadrados total, representa toda a variação da variável resposta.</li>
</ul>
<p>e</p>
<p><span class="math display">\[
  \text{SQ}*{\text{Total}}
  =\sum*{i=1}^{n}(y_i-\bar{y})^2
\]</span></p>
<ul>
<li>
<span class="math inline">\(\text{SQ}_{\text{Regressão}}\)</span>: soma de quadrados explicada pelo modelo.</li>
</ul>
<p>Finalmente,</p>
<p><span class="math display">\[
  \text{SQ}*{\text{Regressão}}
  =\sum*{i=1}^{n}(\hat y_i-\bar y)^2
\]</span></p>
<p>onde <span class="math inline">\(\hat y_i\)</span> é o valor previsto pela regressão.</p>
<div id="como-a-fórmula-funciona-1" class="section level4" number="13.1.2.1">
<h4>
<span class="header-section-number">13.1.2.1</span> Como a fórmula funciona<a class="anchor" aria-label="anchor" href="#como-a-f%C3%B3rmula-funciona-1"><i class="fas fa-link"></i></a>
</h4>
<p>O coeficiente de determinação calcula a fração da variação total de (y) que é explicada pela regressão.</p>
<p>Por exemplo, se</p>
<p><span class="math inline">\(\text{SQ}_{\text{Regressão}}=80\)</span>
<span class="math inline">\(\text{SQ}_{\text{Total}}=100\)</span>,</p>
<p>então</p>
<p><span class="math display">\[
r^2=\frac{80}{100}=0.80.
\]</span></p>
<p>Isso significa que <strong>80% da variação da variável resposta é explicada pelo modelo</strong>, enquanto os 20% restantes são atribuídos a outros fatores ou ao erro aleatório.</p>
</div>
</div>
<div id="relação-entre-r-e-r2" class="section level3" number="13.1.3">
<h3>
<span class="header-section-number">13.1.3</span> Relação entre <span class="math inline">\(r\)</span> e <span class="math inline">\(R^2\)</span><a class="anchor" aria-label="anchor" href="#rela%C3%A7%C3%A3o-entre-r-e-r2"><i class="fas fa-link"></i></a>
</h3>
<p>Na regressão linear simples existe apenas uma variável explicativa, e vale a relação</p>
<p><span class="math display">\[
r^2=R^2
\]</span></p>
<p>Assim, se</p>
<p><span class="math display">\[
r=0.90,
\]</span></p>
<p>então</p>
<p><span class="math display">\[
R^2=0.90^2=0.81.
\]</span></p>
<p>Ou seja, a correlação mede a <strong>força e a direção</strong> da relação linear entre duas variáveis, enquanto o coeficiente de determinação mede <strong>quanto da variação da variável resposta é explicada pelo modelo de regressão</strong>.</p>
<div id="não-confundir-com-resíduos" class="section level4" number="13.1.3.1">
<h4>
<span class="header-section-number">13.1.3.1</span> Não confundir com <strong>resíduos</strong><a class="anchor" aria-label="anchor" href="#n%C3%A3o-confundir-com-res%C3%ADduos"><i class="fas fa-link"></i></a>
</h4>
<p>No desvio em relação à média</p>
<p><span class="math display">\[
x_i - \bar{x}
\]</span></p>
<p>é o <strong>desvio da observação em relação à média</strong> da variável (x).</p>
<p>Ele indica quanto um valor observado está acima ou abaixo da média e é utilizado no cálculo da variância, covariância e da correlação de Pearson.</p>
<p>Na regressão, o resíduo é</p>
<p><span class="math display">\[
e_i = y_i - \hat{y}_i,
\]</span></p>
<p>onde:</p>
<ul>
<li>
<span class="math inline">\(y_i\)</span>: valor observado;</li>
<li>
<span class="math inline">\(\hat{y}_i\)</span>: valor previsto pelo modelo.</li>
</ul>
<p>O resíduo mede o <strong>erro de predição</strong> da regressão, ou seja, a distância vertical entre o ponto observado e a reta ajustada.</p>
</div>
<div id="pressupostos-4" class="section level4" number="13.1.3.2">
<h4>
<span class="header-section-number">13.1.3.2</span> Pressupostos<a class="anchor" aria-label="anchor" href="#pressupostos-4"><i class="fas fa-link"></i></a>
</h4>
<p>A análise de correlação possui vários pressupostos:</p>
<ol style="list-style-type: decimal">
<li>Pares relacionados: Os dados devem ser coletados em pares relacionados. Ou seja, se houver um escore na variável x, deve haver também um escore correspondente na variável y para o mesmo participante.<br>
</li>
<li>Escala de medida: Os dados devem possuir natureza intervalar ou de razão.<br>
</li>
<li>Normalidade: Os escores de cada variável devem apresentar distribuição normal.<br>
</li>
<li>
<strong>Linearidade</strong>: A relação entre as duas variáveis deve ser linear.<br>
</li>
<li>Homoscedasticidade: A variabilidade dos escores de uma variável deve ser aproximadamente a mesma em todos os valores da outra variável. Ou seja, refere-se à forma como os escores se distribuem uniformemente em torno da linha de regressão.</li>
</ol>
<p>Os pressupostos 1 e 2 dependem do delineamento da pesquisa.</p>
<p>O pressuposto 3 pode ser avaliado utilizando os procedimentos descritos nos capítulos anteriores.</p>
<p>Os pressupostos 4 e 5 podem ser avaliados examinando gráficos de dispersão (<em>scatterplots</em>) das variáveis.</p>
</div>
</div>
</div>
<div id="sobre-os-dados-2" class="section level2" number="13.2">
<h2>
<span class="header-section-number">13.2</span> Sobre os dados<a class="anchor" aria-label="anchor" href="#sobre-os-dados-2"><i class="fas fa-link"></i></a>
</h2>
<div class="infobox2 stopred">
<div class="center">
<p><span style="color:white"><strong>ATENÇÃO</strong></span></p>
</div>
<p>Os links para baixar as planilhas necessárias para repetir esse tutorial podem ser encontrados na seção <a href="bases.html#arqs">Arquivos disponíveis</a> do Capítulo <a href="bases.html#bases">Bases de dados</a>.</p>
<div class="center">
<p>Ou, baixe aqui o arquivo <a href="matrizes/tucuna.xlsx">tucuna.xlsx</a></p>
</div>
</div>
</div>
<div id="organização-básica-3" class="section level2" number="13.3">
<h2>
<span class="header-section-number">13.3</span> Organização básica<a class="anchor" aria-label="anchor" href="#organiza%C3%A7%C3%A3o-b%C3%A1sica-3"><i class="fas fa-link"></i></a>
</h2>
<div class="sourceCode" id="cb209"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/grDevices/dev.html">dev.off</a></span><span class="op">(</span><span class="op">)</span> <span class="co">#apaga os graficos, se houver algum</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/rm.html">rm</a></span><span class="op">(</span>list<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/ls.html">ls</a></span><span class="op">(</span>all<span class="op">=</span><span class="cn">TRUE</span><span class="op">)</span><span class="op">)</span> <span class="co">#limpa a memória</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/cat.html">cat</a></span><span class="op">(</span><span class="st">"\014"</span><span class="op">)</span> <span class="co">#limpa o console </span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/options.html">options</a></span><span class="op">(</span>scipen <span class="op">=</span> <span class="fl">999</span><span class="op">)</span> <span class="co">#sem notação científica, oposto de scipen = 0</span></span></code></pre></div>
<p>Instalando os pacotes necessários para esse módulo</p>
<div class="sourceCode" id="cb210"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/utils/install.packages.html">install.packages</a></span><span class="op">(</span><span class="st">"openxlsx"</span><span class="op">)</span> <span class="co">#importa arquivos do excel</span></span></code></pre></div>
<div class="sourceCode" id="cb211"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://ycphs.github.io/openxlsx/index.html">openxlsx</a></span><span class="op">)</span></span></code></pre></div>
<div class="sourceCode" id="cb212"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/getwd.html">getwd</a></span><span class="op">(</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/getwd.html">setwd</a></span><span class="op">(</span><span class="st">"C:/Seu/Diretório/De/Trabalho"</span><span class="op">)</span></span></code></pre></div>
</div>
<div id="importando-a-planilha-3" class="section level2" number="13.4">
<h2>
<span class="header-section-number">13.4</span> Importando a planilha<a class="anchor" aria-label="anchor" href="#importando-a-planilha-3"><i class="fas fa-link"></i></a>
</h2>
<p>Vamos importar a planilha de dados univariados <code>tucuna.xlsx</code>. Note que o símbolo <span style="color:green"><code>#</code></span> em programação R significa que o texto que vem depois dele é um comentário e não será executado pelo programa. Isso é útil para explicar o código ou deixar anotações. Ajuste a segunda linha do código abaixo para refletir <span style="color:blue">“C:/Seu/Diretório/De/Trabalho/Planilha.xlsx”</span>.</p>
<div class="sourceCode" id="cb213"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://ycphs.github.io/openxlsx/index.html">openxlsx</a></span><span class="op">)</span></span>
<span><span class="va">univ</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/openxlsx/man/read.xlsx.html">read.xlsx</a></span><span class="op">(</span><span class="st">"D:/Elvio/OneDrive/Disciplinas/_EcoNumerica/5.Matrizes/tucuna.xlsx"</span>,</span>
<span>                    rowNames <span class="op">=</span> <span class="cn">T</span>, colNames <span class="op">=</span> <span class="cn">T</span>,</span>
<span>                    sheet <span class="op">=</span> <span class="st">"tucuna"</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">univ</span>, <span class="fl">10</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">univ</span><span class="op">[</span>, <span class="fl">1</span><span class="op">:</span><span class="fl">5</span><span class="op">]</span>, <span class="fl">10</span><span class="op">)</span></span></code></pre></div>
<pre><code>##       CT_cm  PT_g CP_cm Ctubo_cm  PC_g     p_PT Pest_g Cest_cm gr_est    ir_est
## TU001  32.4 468.8  27.2     39.8 458.9 2.111775    3.9     7.7      I 0.8319113
## TU002  33.4 520.0  28.8     14.3 507.4 2.423077    5.9    10.0      I 1.1346154
## TU003  27.3 301.5  23.8     13.0 283.4 6.003317   15.5    10.2    III 5.1409619
## TU004  13.2  28.2  11.0     16.5  27.7 1.773050    0.3     4.3      I 1.0638298
## TU005  14.3  38.9  11.9     15.5  37.7 3.084833    0.8     4.5    III 2.0565553
## TU006  22.7 431.7  20.5     24.2 418.7 3.011350    9.9     6.4    III 2.2932592
## TU007  23.2 544.0  19.2     25.0 520.1 4.393382    6.8     7.5     II 1.2500000
## TU008  13.5 161.6  11.5     17.5 157.0 2.846535    4.1     6.8     II 2.5371287
## TU009  24.6 200.5  20.5     25.7 195.9 2.294264    2.5     7.6     II 1.2468828
## TU010  19.4  86.7  16.0     18.3  84.5 2.537486    0.7     5.1      I 0.8073818
##       Pint_g Cint_cm gr_int    ir_int Pgon_g Cgon_cm          emg         ig
## TU001    4.8    38.3     II 1.0238908    1.2       7      IMATURO 0.25597270
## TU002    5.3    13.3     II 1.0192308    1.4     6.5       MADURO 0.26923077
## TU003    2.4    12.0     II 0.7960199    0.2     7.7 EM MATURACAO 0.06633499
## TU004    0.1    16.0     II 0.3546099    0.1       5      IMATURO 0.35460993
## TU005    0.3    15.0     II 0.7712082    0.1     3.2      IMATURO 0.25706941
## TU006    2.7    23.7     II 0.6254343    0.4     7.8 EM MATURACAO 0.09265694
## TU007    3.3    24.5     II 0.6066176   13.8     7.9       MADURO 2.53676471
## TU008    0.4    17.0      I 0.2475248    0.1     2.5      IMATURO 0.06188119
## TU009    2.0    25.3     II 0.9975062    0.1     6.5 EM MATURACAO 0.04987531
## TU010    1.4    17.7     II 1.6147636    0.1       6      IMATURO 0.11534025
##       mes periodo estação    sexo   sexo2
## TU001 ago chuvoso inverno   MACHO   FEMEA
## TU002 ago chuvoso inverno   MACHO   FEMEA
## TU003 ago chuvoso inverno   MACHO   FEMEA
## TU004 ago chuvoso inverno   MACHO   FEMEA
## TU005 ago chuvoso inverno   MACHO   FEMEA
## TU006 set chuvoso inverno   MACHO   FEMEA
## TU007 set chuvoso inverno   FEMEA   MACHO
## TU008 set chuvoso inverno imaturo imaturo
## TU009 set chuvoso inverno   MACHO   FEMEA
## TU010 set chuvoso inverno   MACHO   FEMEA
##       CT_cm  PT_g CP_cm Ctubo_cm  PC_g
## TU001  32.4 468.8  27.2     39.8 458.9
## TU002  33.4 520.0  28.8     14.3 507.4
## TU003  27.3 301.5  23.8     13.0 283.4
## TU004  13.2  28.2  11.0     16.5  27.7
## TU005  14.3  38.9  11.9     15.5  37.7
## TU006  22.7 431.7  20.5     24.2 418.7
## TU007  23.2 544.0  19.2     25.0 520.1
## TU008  13.5 161.6  11.5     17.5 157.0
## TU009  24.6 200.5  20.5     25.7 195.9
## TU010  19.4  86.7  16.0     18.3  84.5</code></pre>
<p>Exibindo os dados importados (esses comando são “case-sensitive” <code>ignore.case(object)</code>).</p>
<div class="sourceCode" id="cb215"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co">#View(univ)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="va">univ</span><span class="op">[</span><span class="fl">1</span><span class="op">:</span><span class="fl">5</span>,<span class="fl">1</span><span class="op">:</span><span class="fl">5</span><span class="op">]</span><span class="op">)</span></span>
<span><span class="va">univ</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/str.html">str</a></span><span class="op">(</span><span class="va">univ</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/mode.html">mode</a></span><span class="op">(</span><span class="va">univ</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/class.html">class</a></span><span class="op">(</span><span class="va">univ</span><span class="op">)</span></span></code></pre></div>
<div id="exemplos-3" class="section level4" number="13.4.0.1">
<h4>
<span class="header-section-number">13.4.0.1</span> Exemplos<a class="anchor" aria-label="anchor" href="#exemplos-3"><i class="fas fa-link"></i></a>
</h4>
</div>
</div>
<div id="correlação-simples-bivariada" class="section level2" number="13.5">
<h2>
<span class="header-section-number">13.5</span> Correlação simples (bivariada)<a class="anchor" aria-label="anchor" href="#correla%C3%A7%C3%A3o-simples-bivariada"><i class="fas fa-link"></i></a>
</h2>
<p>No caso dos dados de dinâmica populacional do tucunaré (<em>Cichla ocellaris</em>), pode-se investigar a relação entre duas variáveis biométricas contínuas, como o comprimento padrão (CP_cm) e o comprimento total (CT_cm).</p>
<p>Suspeita-se que exista uma relação linear positiva entre essas variáveis, uma vez que indivíduos com maior comprimento padrão tendem também a apresentar maior comprimento total.</p>
<p>Assim, pode-se utilizar a correlação produto-momento de Pearson para responder à seguinte questão:</p>
<ol style="list-style-type: decimal">
<li>Existe correlação significativa entre o comprimento padrão e o comprimento total dos indivíduos?</li>
</ol>
<p>Hipótese nula (<span class="math inline">\(H_0\)</span>): não existe correlação linear entre as duas variáveis na população.<br>
Hipótese alternativa (<span class="math inline">\(H_1\)</span>): existe correlação linear entre as duas variáveis na população.</p>
<p>Nesse caso, utiliza-se:</p>
<div class="sourceCode" id="cb216"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">df</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span><span class="va">univ</span><span class="op">$</span><span class="va">CP_cm</span>, <span class="va">univ</span><span class="op">$</span><span class="va">CT_cm</span>, <span class="va">univ</span><span class="op">$</span><span class="va">PT_g</span><span class="op">)</span></span>
<span><span class="co">#df</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">df</span><span class="op">[</span>,<span class="fl">1</span><span class="op">:</span><span class="fl">2</span><span class="op">]</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Teste de Pearson</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/cor.html">cor</a></span><span class="op">(</span><span class="va">df</span>, method<span class="op">=</span><span class="st">"pearson"</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/cor.test.html">cor.test</a></span><span class="op">(</span><span class="va">univ</span><span class="op">$</span><span class="va">CP_cm</span>, <span class="va">univ</span><span class="op">$</span><span class="va">CT_cm</span>,</span>
<span>         method <span class="op">=</span> <span class="st">"pearson"</span><span class="op">)</span> <span class="co">#"pearson", "kendall", "spearman"</span></span>
<span></span>
<span><span class="co"># Teste de Spearman</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/cor.html">cor</a></span><span class="op">(</span><span class="va">df</span><span class="op">[</span>,<span class="fl">1</span><span class="op">:</span><span class="fl">2</span><span class="op">]</span>, method<span class="op">=</span><span class="st">"spearman"</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/cor.test.html">cor.test</a></span><span class="op">(</span><span class="va">univ</span><span class="op">$</span><span class="va">CT_cm</span>, <span class="va">univ</span><span class="op">$</span><span class="va">CP_cm</span>,</span>
<span>         method<span class="op">=</span><span class="st">"spearman"</span><span class="op">)</span></span></code></pre></div>
<pre><code>##            univ.CP_cm univ.CT_cm univ.PT_g
## univ.CP_cm  1.0000000  0.9990120 0.9039503
## univ.CT_cm  0.9990120  1.0000000 0.9057485
## univ.PT_g   0.9039503  0.9057485 1.0000000
## 
##  Pearson's product-moment correlation
## 
## data:  univ$CP_cm and univ$CT_cm
## t = 467.22, df = 432, p-value &lt; 2.2e-16
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  0.9988068 0.9991819
## sample estimates:
##      cor 
## 0.999012 
## 
##            univ.CP_cm univ.CT_cm
## univ.CP_cm  1.0000000  0.9976789
## univ.CT_cm  0.9976789  1.0000000
## 
##  Spearman's rank correlation rho
## 
## data:  univ$CT_cm and univ$CP_cm
## S = 31624, p-value &lt; 2.2e-16
## alternative hypothesis: true rho is not equal to 0
## sample estimates:
##       rho 
## 0.9976789</code></pre>
<div class="inline-figure"><img src="fundamentos_de_ecologia_numerica_files/figure-html/unnamed-chunk-133-1.png" alt="" width="672"></div>
<p>Interpretação:</p>
<p>Os resultados da <strong>correlação de Pearson</strong> (<code>cor.test(x, y, method = "pearson")</code>) revelam a <strong>estatística do teste</strong>, t = 467.22 (para 432 <strong>graus de liberdade</strong>), indicando forte evidência contra a hipótese nula, e o <strong>valor de p</strong>, &lt;0.001, indicando que a correlação é estatisticamente significativa. Também é mostrado o <strong>coeficiente de correlação</strong> (r) de 0.999 e o intervalo de confiança (95%) de 0.9988 ≤ ρ ≤ 0.9992.</p>
<p>Em uma correlação simples (bivariada), não existe uma distinção estatística obrigatória entre variável explicativa (independente) e variável resposta (dependente). A correlação mede apenas a força e a direção da associação entre duas variáveis (sem assumir causalidade), e o coeficiente de correlação é o mesmo independentemente da ordem das variáveis.</p>
<p>Entretanto, quando se faz um gráfico de dispersão, por convenção:</p>
<p>Eixo x (horizontal): variável explicativa (independente), quando houver uma hipótese causal;<br>
Eixo y (vertical): variável resposta (dependente).</p>
<p>Por exemplo, nos dados de tucunaré, como nosso objetivo é verificar se o comprimento padrão (CP) explica o comprimento total (CT), temos que:</p>
<p>x: comprimento padrão (CP_cm)<br>
y: comprimento total (CT_cm)</p>
<p>Se pretendemos ajustar uma <strong>regressão linear</strong>, a variável explicativa deve ser colocada no eixo x e a variável resposta no eixo y, pois a reta de regressão depende dessa escolha (veremos isso a seguir).</p>
<p>Na <strong>correlação de Spearman</strong>, os dados são transformados em <em>ranks</em> (postos).</p>
<div class="inline-table"><table class="table table-sm">
<thead><tr class="header">
<th>valor</th>
<th>rank</th>
</tr></thead>
<tbody>
<tr class="odd">
<td>10</td>
<td>1</td>
</tr>
<tr class="even">
<td>12</td>
<td>2</td>
</tr>
<tr class="odd">
<td>12</td>
<td>2</td>
</tr>
<tr class="even">
<td>15</td>
<td>4</td>
</tr>
</tbody>
</table></div>
<p>Quando existem valores repetidos, no exemplo acima, 12 e 12, ocorrem empates (<em>ties</em>). O teste exato de Spearman assume ranks únicos, sem valores repetidos. Como nossos dados possuem medidas repetidas (muito comum em biometria), o R usa uma aproximação assintótica (removendo os empates), em vez do cálculo exato. Isso não invalida o teste, em caso de amostras grandes, mas significa uma limitação do teste de correlação não-paramétrico.</p>
<p>O QUE REPORTAR (Pearson): Foi observada correlação linear positiva extremamente forte entre o comprimento padrão (CP_cm) e o comprimento total (CT_cm) dos indivíduos analisados (correlação de Pearson: r = 0,957; p &lt; 0,001; n = 434).</p>
<p>O QUE REPORTAR (spearman): Foi observada correlação positiva significativa entre comprimento padrão (CP_cm) e o comprimento total (CT_cm) (Spearman: <span class="math inline">\(\rho\)</span> = 0,998; p &lt; 0,001).</p>
</div>
<div id="correlação-parcial" class="section level2" number="13.6">
<h2>
<span class="header-section-number">13.6</span> Correlação parcial<a class="anchor" aria-label="anchor" href="#correla%C3%A7%C3%A3o-parcial"><i class="fas fa-link"></i></a>
</h2>
<p>Além disso, pode-se avaliar se essa relação permanece significativa quando o efeito de uma variável adicional, como o peso corporal (<code>PT_g</code>) ou o período do ano (<code>periodo</code>), é controlada na análise. Nesse caso, a correlação parcial remove a parte da correlação explicada pelo peso. Ou seja, a correlação parcial faz a mesma coisa da bivariada, mas controla o efeito de uma terceira variável.</p>
<p>Espera-se que peixes mais pesados tendem a aumentar em ambos os comprimentos (CP e CT). Podemos, portanto, correlacionar CP_cm e CT_cm, e controlar pelo peso, para responder a seguinte questão:</p>
<ol style="list-style-type: decimal">
<li>Comprimento padrão e comprimento total ainda se correlacionam independentemente do peso?</li>
</ol>
<p>Hipótese nula (<span class="math inline">\(H_0\)</span>): não existe correlação linear entre as duas variáveis na população, após controlar o efeito de uma terceira variável.<br>
Hipótese alternativa (<span class="math inline">\(H_1\)</span>): existe correlação linear entre as duas variáveis na população, após controlar o efeito de uma terceira variável.</p>
<div class="sourceCode" id="cb218"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/cor.html">cor</a></span><span class="op">(</span></span>
<span>  <span class="va">univ</span><span class="op">[</span>, <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"CP_cm"</span>, <span class="st">"CT_cm"</span>, <span class="st">"PT_g"</span><span class="op">)</span><span class="op">]</span>,</span>
<span>  use <span class="op">=</span> <span class="st">"complete.obs"</span></span>
<span><span class="op">)</span></span>
<span><span class="co">#install.packages("ppcor")</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va">ppcor</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/ppcor/man/pcor.test.html">pcor.test</a></span><span class="op">(</span></span>
<span>  <span class="va">univ</span><span class="op">$</span><span class="va">CP_cm</span>,</span>
<span>  <span class="va">univ</span><span class="op">$</span><span class="va">CT_cm</span>,</span>
<span>  <span class="va">univ</span><span class="op">$</span><span class="va">PT_g</span></span>
<span><span class="op">)</span></span></code></pre></div>
<pre><code>##           CP_cm     CT_cm      PT_g
## CP_cm 1.0000000 0.9990120 0.9039503
## CT_cm 0.9990120 1.0000000 0.9057485
## PT_g  0.9039503 0.9057485 1.0000000
##    estimate p.value statistic   n gp  Method
## 1 0.9945978       0  198.9168 434  1 pearson</code></pre>
<p>Interpretação:</p>
<p>O resultado da <strong>correlação parcial</strong> (<code><a href="https://rdrr.io/pkg/ppcor/man/pcor.test.html">pcor.test()</a></code>) de Pearson, isto é, a correlação entre CP_cm e CT_cm após controlar o efeito de uma terceira variável (PT_g), demonstra um <strong>coeficiente de correlação parcial</strong> <span class="math inline">\(r_p\)</span> de 0.9946 (<em>estimate</em>), mesmo após remover o efeito do peso (PT_g). A <strong>estaística t</strong> (<em>statistic</em>) de 198.92 utilizada para testar a significância da correlação parcial e o <strong>número de observações</strong> (n) também são apresentados. O <strong>número de variáveis controladas</strong> (neste caso, apenas PT_g), é demonstrado em
gp = 1. O <strong>valor de p</strong> (&lt;0,001) é extremamente pequeno. Finalmemte, o <strong>método utilizado</strong> (correlação parcial de Pearson) é apresentado.</p>
<p>Tivemos uma correlação parcial extremamente forte e positiva (r = 0.955) entre CP_cm e CT_cm, mesmo após remover o efeito do PT_g (peso total) (p &lt; 0,001). Isso indica que a associação entre comprimento padrão e comprimento total permanece muito forte independentemente do peso corporal.</p>
<p>O QUE REPORTAR: Análise de correlação parcial revelou associação positiva extremamente forte entre comprimento padrão e comprimento total, mesmo após o controle do peso corporal (r = 0,955; p &lt; 0,001).</p>
</div>
<div id="regressão-simples" class="section level2" number="13.7">
<h2>
<span class="header-section-number">13.7</span> Regressão simples<a class="anchor" aria-label="anchor" href="#regress%C3%A3o-simples"><i class="fas fa-link"></i></a>
</h2>
<p>Nesse texto, optei por tratar correlação e regressão linear como diferentes aspectos de uma mesma análise (seguindo a visão de <span class="citation">MCDONALD (<a href="#ref-mcdonald2014">2014</a>)</span>), apesar de que também podemos considerar correlação e regressão linear como um único teste estatístico <span class="citation">(<a href="#ref-cleophas2016">CLEOPHAS; ZWINDERMAN, 2016</a>; <a href="#ref-coakes2001">COAKES; STEED, 2001</a>)</span>.</p>
<p>A principal diferença entre correlação e regressão é que, na correlação, ambas as variáveis medidas são amostradas aleatoriamente a partir de uma população, enquanto na regressão os valores da variável independente (x) costumam ser escolhidos ou controlados pelo pesquisador <span class="citation">(<a href="#ref-mcdonald2014">MCDONALD, 2014</a>)</span>.</p>
<p>No nosso exemplo, o pesquisador interessado na biometria de <em>Cichla ocellaris</em> deseja compreender a relação entre o comprimento padrão e o comprimento total dos indivíduos. Em estudos pesqueiros, muitas vezes apenas parte do exemplar é obtida, seja devido ao processamento do pescado, danos durante a captura ou coleta incompleta em campo <span class="citation">(<a href="#ref-royce1942">ROYCE, 1942</a>)</span>. Nesses casos, torna-se útil estimar o comprimento total do peixe a partir do comprimento padrão.</p>
<p>Já fizemos a avaliação da correlação entre as variáveis de interesse. Agora faremos uma análise de regressão linear entre essas variáveis, para que possamos, usando o modelo ajustado da regressão, prever o comprimento total a partir do comprimento padrão.</p>
<div id="variáveis-independentes-e-dependentes" class="section level4" number="13.7.0.1">
<h4>
<span class="header-section-number">13.7.0.1</span> Variáveis independentes e dependentes<a class="anchor" aria-label="anchor" href="#vari%C3%A1veis-independentes-e-dependentes"><i class="fas fa-link"></i></a>
</h4>
<p>Quando se testa uma relação de causa e efeito, a variável que supostamente causa a relação é chamada de variável <strong>independente</strong>, e geralmente é representada no eixo x. Já a variável que representa o efeito é denominada <strong>variável dependente</strong>, e é representada no eixo y.</p>
<p>Em alguns experimentos, o pesquisador <strong>define os valores da variável independente</strong>. Por exemplo, se o interesse for avaliar o efeito da temperatura sobre a taxa de vocalização de anuros, os animais podem ser mantidos em câmaras com temperaturas controladas de 10°C, 15°C, 20°C <span class="citation">(<a href="#ref-mcdonald2014">MCDONALD, 2014</a>)</span>, e essa seria a variável independente. Uma outra possibilidade é quando, <strong>ambas as variáveis apresentam variação natural</strong>, mas a relação causal ocorre apenas em uma direção. Por exemplo, ao medir temperatura do ar e taxa de vocalização de sapos em diferentes noites, ambas variam naturalmente. Entretanto, caso exista relação causal, espera-se que a temperatura (<strong>independente</strong>) afete a vocalização (<strong>dependente</strong>), e não o contrário, já que a vocalização dos sapos não altera a temperatura do ambiente <span class="citation">(<a href="#ref-mcdonald2014">MCDONALD, 2014</a>)</span>.</p>
<p>Um último caso ocorre quando desejamos prever uma variável (<strong>dependente</strong>) a partir de uma segunda variável (<strong>independente</strong>). Em estudos biométricos como o em <em>Cichla ocellaris</em>, podemos investigar a relação entre comprimento padrão (CP_cm) e comprimento total (CT_cm). Nesse caso, podemos considerar comprimento padrão como variável independente, pois desejamos prever comprimento total a partir do comprimento padrão.</p>
<p>No R, isso é implementando usando a função <code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code></p>
<pre><code>lm(y ~ x, data = dados)</code></pre>
<p>onde:</p>
<p>o que está à esquerda de <code>~</code> é a variável dependente (resposta, y);<br>
o que está à direita de <code>~</code> é a variável independente (explicativa, preditora, x).</p>
</div>
<div id="exemplo-1" class="section level4" number="13.7.0.2">
<h4>
<span class="header-section-number">13.7.0.2</span> Exemplo<a class="anchor" aria-label="anchor" href="#exemplo-1"><i class="fas fa-link"></i></a>
</h4>
<p>No script a seguir, seguimos as seguintes etapas:</p>
<ol style="list-style-type: decimal">
<li>Explorar relações biométricas</li>
<li>Calcular correlações simples</li>
<li>Teste de significância</li>
<li>Ajuste da regressão linear</li>
<li>Verificação de pressupostos</li>
<li>Realização da ANOVA do modelo da regressão</li>
<li>Aplicação de correção robusta</li>
</ol>
<div class="sourceCode" id="cb221"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">df</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span><span class="va">univ</span><span class="op">$</span><span class="va">CP_cm</span>, <span class="va">univ</span><span class="op">$</span><span class="va">CT_cm</span>, <span class="va">univ</span><span class="op">$</span><span class="va">PT_g</span><span class="op">)</span></span>
<span><span class="co">#df</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">df</span><span class="op">[</span>,<span class="fl">1</span><span class="op">:</span><span class="fl">2</span><span class="op">]</span>,</span>
<span>     xlim <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0</span>, <span class="fl">40</span><span class="op">)</span>,</span>
<span>     ylim <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0</span>, <span class="fl">50</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="co">#abline(modelo, col = "red", lwd = 2)</span></span>
<span></span>
<span><span class="co"># Teste de Pearson</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/cor.html">cor</a></span><span class="op">(</span><span class="va">df</span>, method<span class="op">=</span><span class="st">"pearson"</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/cor.test.html">cor.test</a></span><span class="op">(</span><span class="va">univ</span><span class="op">$</span><span class="va">CP_cm</span>, <span class="va">univ</span><span class="op">$</span><span class="va">CT_cm</span>,</span>
<span>         method <span class="op">=</span> <span class="st">"pearson"</span><span class="op">)</span></span>
<span><span class="co"># Teste de Spearman</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/cor.html">cor</a></span><span class="op">(</span><span class="va">df</span><span class="op">[</span>,<span class="fl">1</span><span class="op">:</span><span class="fl">2</span><span class="op">]</span>, method<span class="op">=</span><span class="st">"spearman"</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/cor.test.html">cor.test</a></span><span class="op">(</span><span class="va">univ</span><span class="op">$</span><span class="va">CP_cm</span>, <span class="va">univ</span><span class="op">$</span><span class="va">CT_cm</span>,</span>
<span>         method<span class="op">=</span><span class="st">"spearman"</span><span class="op">)</span></span>
<span></span>
<span><span class="va">modelo</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">CT_cm</span> <span class="op">~</span> <span class="va">CP_cm</span>, data<span class="op">=</span><span class="va">univ</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">modelo</span><span class="op">)</span></span></code></pre></div>
<pre><code>##            univ.CP_cm univ.CT_cm univ.PT_g
## univ.CP_cm  1.0000000  0.9990120 0.9039503
## univ.CT_cm  0.9990120  1.0000000 0.9057485
## univ.PT_g   0.9039503  0.9057485 1.0000000
## 
##  Pearson's product-moment correlation
## 
## data:  univ$CP_cm and univ$CT_cm
## t = 467.22, df = 432, p-value &lt; 2.2e-16
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  0.9988068 0.9991819
## sample estimates:
##      cor 
## 0.999012 
## 
##            univ.CP_cm univ.CT_cm
## univ.CP_cm  1.0000000  0.9976789
## univ.CT_cm  0.9976789  1.0000000
## 
##  Spearman's rank correlation rho
## 
## data:  univ$CP_cm and univ$CT_cm
## S = 31624, p-value &lt; 2.2e-16
## alternative hypothesis: true rho is not equal to 0
## sample estimates:
##       rho 
## 0.9976789 
## 
## 
## Call:
## lm(formula = CT_cm ~ CP_cm, data = univ)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -2.3777 -0.1281 -0.0147  0.1260  3.0354 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 0.147883   0.037700   3.923 0.000102 ***
## CP_cm       1.206566   0.002582 467.221  &lt; 2e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 0.4216 on 432 degrees of freedom
## Multiple R-squared:  0.998,  Adjusted R-squared:  0.998 
## F-statistic: 2.183e+05 on 1 and 432 DF,  p-value: &lt; 2.2e-16</code></pre>
<div class="inline-figure"><img src="fundamentos_de_ecologia_numerica_files/figure-html/unnamed-chunk-135-1.png" alt="" width="672"></div>
<p>No caso do nosso exemplo, o modelo de regressão linear simples pode ser representado por:</p>
<p><span class="math display">\[
CT_{cm} = \beta_0 + \beta_1 CP_{cm} + \varepsilon
\]</span></p>
<p>onde:</p>
<ul>
<li>
<span class="math inline">\(CT_{cm}\)</span> = comprimento total (variável resposta ou dependente);</li>
<li>
<span class="math inline">\(CP_{cm}\)</span> = comprimento padrão (variável preditora ou independente);</li>
<li>
<span class="math inline">\(\beta_0\)</span> = intercepto do modelo;</li>
<li>
<span class="math inline">\(\beta_1\)</span> = coeficiente angular da regressão;</li>
<li>
<span class="math inline">\(\varepsilon\)</span> = erro aleatório associado ao modelo.</li>
</ul>
<p>Esse modelo busca prever o comprimento total dos indivíduos a partir do comprimento padrão.</p>
<p>No R, o modelo é ajustado utilizando a função:</p>
<pre><code>modelo &lt;- lm(CT_cm ~ CP_cm, data = univ)</code></pre>
<p>Interpretação:</p>
<p>A função <code><a href="https://rdrr.io/r/base/summary.html">summary()</a></code> fornece todas as informações necessárias para interpretar os resultados da regressão linear.</p>
<p>A fórmula utilizada dentro da função <code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code> indica que <code>CT_cm</code> é a variável resposta (dependente) e <code>CP_cm</code> é a variável explicativa (independente). A <strong>equação do modelo ajustado</strong> seria:</p>
<p><span class="math display">\[
CT_{cm} = 0.147 + 1.206 \times CP_{cm}
\]</span>
onde:</p>
<ul>
<li>0,147 é o intercepto (<span class="math inline">\(\beta_0\)</span>)<br>
</li>
<li>1,206 é o coeficiente angular (<span class="math inline">\(\beta_1\)</span>)</li>
</ul>
<p>O <strong>intercept</strong> (<span class="math inline">\(\beta_0 = 0.147\)</span>) representa o valor esperado de CT_cm quando CP_cm=0 (geralmente sem interpretação biológica, mas importante em Modelos Lineares Generaliados). O <strong>coeficiente angular</strong> (<span class="math inline">\(\beta_1\)</span> = 1,206) indica que, em média, para cada aumento de 1 cm em CP_cm, espera-se aumento aproximado de 1,206 cm em CT_cm. O <strong>erro padrão do coeficiente angular</strong>, que mede a precisão da estimativa de <span class="math inline">\(\beta_1\)</span>, foi de 0,00258.</p>
<p>Os resultados também mostram que O coeficiente de CP_cm é altamente significativo (t=467.22, p&lt;0.001), indicando que o comprimento padrão é um forte preditor do comprimento total. Embora o modelo apresente um erro médio de aproximadamente 0,42 cm na predição do comprimento total, como mostrado no <strong>erro padrão residual</strong> de 0.4216. Os <strong>coeficientes de determinação</strong> (múltiplos e ajustados) de 0.998, indicam que o cerca de 99,8% da variação no comprimento total.</p>
<p>Finalmente, <strong>o teste F</strong> de 2.183e+05 e seu <strong>valor de p</strong> &lt; 0.001, testam a hipótese de que o modelo não explica a variável resposta:</p>
<p><span class="math inline">\(H_0\)</span>: Hipótese nula: <span class="math inline">\(\beta_1 = 0\)</span>, ou seja, a variável explicativa não exerce efeito sobre a variável resposta (o modelo não possui poder preditivo).</p>
<p><span class="math inline">\(H_1\)</span>: Hipótese alternativa: <span class="math inline">\(\beta_1 \neq 0\)</span>, ou seja, a variável explicativa exerce efeito sobre a variável resposta (o modelo possui poder preditivo).</p>
<p>Como p&lt;0.001, rejeita-se <span class="math inline">\(H_0\)</span> e aceota-se <span class="math inline">\(H_1\)</span>, o modelo de regressão é estatisticamente significativo e tem poder preditivo para o comprimento total.</p>
<p>O QUE REPORTAR: A regressão linear simples revelou que o comprimento padrão foi um preditor significativo do comprimento total (<span class="math inline">\(\beta\)</span> = 1.207 <span class="math inline">\(\pm\)</span> 0.003, t<span class="math inline">\(_{(432)}\)</span> = 467.22, p &lt; 0.001). O modelo apresentou excelente ajuste aos dados (r<span class="math inline">\(^2\)</span> = 0.998; F<span class="math inline">\(_{(1,432)}\)</span> = 218300, p &lt; 0.001), explicando aproximadamente 99,8% da variação no comprimento total. A equação ajustada foi <span class="math inline">\(CT_{cm} = 0.148 + 1.207 \times CP_{cm}\)</span>.</p>
<p>Na sequência avaliamos homogeneidade de variâncias. Para o caso de heterogeneidade de variâncias devemos usar a <strong>correção robusta de White (HC3)</strong>. Antes disso realizamos uma ANOVA da regressão, para testar se o comprimento padrão explica uma parcela significativa da variação no comprimento total. A diferença entre <code><a href="https://rdrr.io/r/stats/anova.html">anova()</a></code> e <code><a href="https://rdrr.io/pkg/car/man/Anova.html">Anova()</a></code> só aparece em modelos com dois ou mais preditores. <code>Anova(modelo, white.adjust = TRUE)</code> calcula o mesmo teste, mas utilizando a correção robusta de White (HC3) para os erros padrão. Essa correção é recomendada quando há heterocedasticidade (variância não constante dos resíduos).</p>
<div class="sourceCode" id="cb224"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/graphics/par.html">par</a></span><span class="op">(</span>mfrow<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">2</span>,<span class="fl">2</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">modelo</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/par.html">par</a></span><span class="op">(</span>mfrow<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span>,<span class="fl">1</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/anova.html">anova</a></span><span class="op">(</span><span class="va">modelo</span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/bprice2652/car_repo">car</a></span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/car/man/Anova.html">Anova</a></span><span class="op">(</span><span class="va">modelo</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/car/man/Anova.html">Anova</a></span><span class="op">(</span><span class="va">modelo</span>, white.adjust<span class="op">=</span><span class="cn">TRUE</span><span class="op">)</span></span></code></pre></div>
<pre><code>## Coefficient covariances computed by hccm()</code></pre>
<pre><code>## Analysis of Variance Table
## 
## Response: CT_cm
##            Df Sum Sq Mean Sq F value    Pr(&gt;F)    
## CP_cm       1  38802   38802  218295 &lt; 2.2e-16 ***
## Residuals 432     77       0                      
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## Anova Table (Type II tests)
## 
## Response: CT_cm
##           Sum Sq  Df F value    Pr(&gt;F)    
## CP_cm      38802   1  218295 &lt; 2.2e-16 ***
## Residuals     77 432                      
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## Analysis of Deviance Table (Type II tests)
## 
## Response: CT_cm
##            Df     F    Pr(&gt;F)    
## CP_cm       1 75315 &lt; 2.2e-16 ***
## Residuals 432                    
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
<div class="inline-figure"><img src="fundamentos_de_ecologia_numerica_files/figure-html/unnamed-chunk-136-1.png" alt="" width="672"></div>
<p>Em um novo exemplo, podemos analisar comprimento total e peso corporal em peixes. Em estudos de relação peso-comprimento normalmente considera-se comprimento como variável independente e peso como variável dependente.</p>
<div class="sourceCode" id="cb227"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">df</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span><span class="va">univ</span><span class="op">$</span><span class="va">CP_cm</span>, <span class="va">univ</span><span class="op">$</span><span class="va">CT_cm</span>, <span class="va">univ</span><span class="op">$</span><span class="va">PT_g</span><span class="op">)</span></span>
<span><span class="co">#df</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">df</span><span class="op">[</span>,<span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">2</span>,<span class="fl">3</span><span class="op">)</span><span class="op">]</span><span class="op">)</span></span>
<span><span class="co">#abline(modelo, col = "red", lwd = 2)</span></span></code></pre></div>
<div class="inline-figure"><img src="fundamentos_de_ecologia_numerica_files/figure-html/unnamed-chunk-137-1.png" alt="" width="672"></div>
</div>
</div>
<div id="gráfico-de-dispersão-scatterplot" class="section level2" number="13.8">
<h2>
<span class="header-section-number">13.8</span> Gráfico de dispersão (<em>scatterplot</em>)<a class="anchor" aria-label="anchor" href="#gr%C3%A1fico-de-dispers%C3%A3o-scatterplot"><i class="fas fa-link"></i></a>
</h2>
<p>Um gráfico de dispersão mostra a relação entre duas variáveis quantitativas, representando cada observação como um ponto no plano cartesiano. Faremos isso usando o pacote <code>ggplot2</code>.</p>
<div id="ggplot" class="section level3" number="13.8.1">
<h3>
<span class="header-section-number">13.8.1</span> O que é ggplot2?<a class="anchor" aria-label="anchor" href="#ggplot"><i class="fas fa-link"></i></a>
</h3>
<p>O <code>ggplot2</code> é um pacote de visualização de dados para R, que permite definir visualmente o que se quer mostrar através de camadas adicionadas usando o símbolo <strong><code>+</code></strong>, usando os seguintes componentes principais:</p>
<ol style="list-style-type: lower-alpha">
<li><p>Dados (<code>data</code>): O ponto de partida para qualquer gráfico é um data frame — uma tabela com linhas (observações) e colunas (variáveis).</p></li>
<li><p>Mapeamento estético (<code>aesthetics/aes</code>): Define como variáveis do dataset mapeiam para propriedades visuais como posição (x, y), cor (color), tamanho (size) ou forma (shape), entre outros:</p></li>
</ol>
<ul>
<li>
<code>x</code>: eixo horizontal</li>
<li>
<code>y</code>: eixo vertical</li>
<li>
<code>color</code>: cor</li>
<li>
<code>size</code>: tamanho</li>
<li>
<code>shape</code>: forma</li>
<li>
<code>fill</code>: preenchimento</li>
</ul>
<ol start="3" style="list-style-type: lower-alpha">
<li>Representações geométricas (<code>geoms</code>): Cada elemento visual do gráfico é adicionado como uma camada. Por exemplo:</li>
</ol>
<ul>
<li>
<code><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point()</a></code> para gráficos de dispersão</li>
<li>
<code><a href="https://ggplot2.tidyverse.org/reference/geom_path.html">geom_line()</a></code> para linhas</li>
<li>
<code><a href="https://ggplot2.tidyverse.org/reference/geom_bar.html">geom_bar()</a></code> para gráficos de barras</li>
</ul>
<p>A estrutura geral de um gráfico em ggplot2 é:</p>
<pre><code>ggplot(data = dados,
       mapping = aes(x = var1,
                     y = var2)) +
    geom_tipo()
?ggplot</code></pre>
<p>Esse modelo modular torna possível compor gráficos simples ou complexos com clareza.</p>
<div class="sourceCode" id="cb229"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://ggplot2.tidyverse.org">ggplot2</a></span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/colnames.html">colnames</a></span><span class="op">(</span><span class="va">univ</span><span class="op">)</span></span>
<span><span class="va">dados</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/subset.html">subset</a></span><span class="op">(</span><span class="va">univ</span>,</span>
<span>                <span class="va">sexo</span> <span class="op">!=</span> <span class="st">"imaturo"</span> <span class="op">&amp;</span> <span class="va">Pgon_g</span><span class="op">&gt;</span><span class="fl">0.2</span> <span class="op">&amp;</span> <span class="va">Pgon_g</span><span class="op">&lt;</span><span class="fl">10</span><span class="op">)</span> <span class="co">#ou `filter` do dplyr</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/table.html">table</a></span><span class="op">(</span><span class="va">dados</span><span class="op">$</span><span class="va">sexo</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/unique.html">unique</a></span><span class="op">(</span><span class="va">dados</span><span class="op">$</span><span class="va">sexo</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">dados</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">CP_cm</span>,</span>
<span>                 y <span class="op">=</span> <span class="va">Pgon_g</span>,</span>
<span>                 color <span class="op">=</span> <span class="va">sexo</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_smooth.html">geom_smooth</a></span><span class="op">(</span>method <span class="op">=</span> <span class="st">"lm"</span>,</span>
<span>              se <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span></code></pre></div>
<pre><code>## `geom_smooth()` using formula = 'y ~ x'</code></pre>
<pre><code>##  [1] "CT_cm"    "PT_g"     "CP_cm"    "Ctubo_cm" "PC_g"     "p_PT"    
##  [7] "Pest_g"   "Cest_cm"  "gr_est"   "ir_est"   "Pint_g"   "Cint_cm" 
## [13] "gr_int"   "ir_int"   "Pgon_g"   "Cgon_cm"  "emg"      "ig"      
## [19] "mes"      "periodo"  "estação"  "sexo"     "sexo2"   
## 
## FEMEA MACHO 
##    21    39 
## [1] "MACHO" "FEMEA"</code></pre>
<div class="inline-figure"><img src="fundamentos_de_ecologia_numerica_files/figure-html/unnamed-chunk-138-1.png" alt="" width="672"></div>
<p>O gráfico acima ilustra uma regressão linear simples entre <code>CP_cm</code> e <code>Pgon_g</code>, com ajuste separado por <code>sexo</code>. As diferenças entre as retas e a dispersão dos pontos sugerem que o peso gonadal não depende apenas do comprimento corporal, mas também de outras características do indivíduo. Por isso, podemos testar como uma análise seguinte a <strong>regressão múltipla</strong>, incorporando simultaneamente <code>CP_cm</code>, <code>sexo</code> e outras possíveis covariáveis relevantes para estimar efeitos parciais e testar interações.</p>
<p>Assim, embora a regressão simples seja útil para descrever a associação bivariada, ela não controla simultaneamente múltiplas fontes de variação.</p>
</div>
</div>
<div id="apêndices-7" class="section level2 unnumbered">
<h2>Apêndices<a class="anchor" aria-label="anchor" href="#ap%C3%AAndices-7"><i class="fas fa-link"></i></a>
</h2>
</div>
<div id="sites-para-consulta-1" class="section level2 unnumbered">
<h2>Sites para consulta<a class="anchor" aria-label="anchor" href="#sites-para-consulta-1"><i class="fas fa-link"></i></a>
</h2>
<p><a href="https://stackoverflow.com/questions/31741742/how-to-identify-the-distribution-of-the-given-data-using-r" class="uri">https://stackoverflow.com/questions/31741742/how-to-identify-the-distribution-of-the-given-data-using-r</a></p>
<p><a href="https://stats.stackexchange.com/questions/132652/how-to-determine-which-distribution-fits-my-data-best" class="uri">https://stats.stackexchange.com/questions/132652/how-to-determine-which-distribution-fits-my-data-best</a></p>
<p><a href="https://www.r-bloggers.com/2015/11/correlation-and-linear-regression/" class="uri">https://www.r-bloggers.com/2015/11/correlation-and-linear-regression/</a></p>
</div>
<div id="script-limpo-4" class="section level2 unnumbered">
<h2>Script limpo<a class="anchor" aria-label="anchor" href="#script-limpo-4"><i class="fas fa-link"></i></a>
</h2>
<p>Aqui apresento o scrip na íntegra sem os textos ou outros comentários. Você pode copiar e colar no R para executa-lo. Lembre de remover os <span style="color:green"><code>#</code></span> ou <span style="color:green"><code>##</code></span> caso necessite executar essas linhas.</p>
</div>
<div id="referências-10" class="section level2 unnumbered">
<h2>Referências<a class="anchor" aria-label="anchor" href="#refer%C3%AAncias-10"><i class="fas fa-link"></i></a>
</h2>

</div>
</div>
<h3>Bibliografia Geral</h3>
<div id="refs" class="references csl-bib-body" entry-spacing="1">
<div id="ref-cleophas2016" class="csl-entry">
CLEOPHAS, T. J.; ZWINDERMAN, A. H. <strong>SPSS for Starters and 2nd Levelers</strong>. Cham: Springer International Publishing, 2016. Disponível em: &lt;<a href="https://link.springer.com/10.1007/978-3-319-20600-4">https://link.springer.com/10.1007/978-3-319-20600-4</a>&gt;
</div>
<div id="ref-coakes2001" class="csl-entry">
COAKES, S. J.; STEED, L. G. <strong>SPSS: Analysis Without Anguish: version 10.0 for Windows</strong>. Milton, Qld: John Wiley &amp; Sons Australia, Ltd, 2001.
</div>
<div id="ref-mcdonald2014" class="csl-entry">
MCDONALD, J. H. <strong>Handbook of Biolological Statistics</strong>. Third ed. Baltimore, Maryland, U.S.A.: Sparky House Publishing, 2014. Disponível em: &lt;<a href="https://www.biostathandbook.com/permissions.html;%20www.biostathandbook.com/HandbookBioStatThird.pdf">https://www.biostathandbook.com/permissions.html; www.biostathandbook.com/HandbookBioStatThird.pdf</a>&gt;
</div>
<div id="ref-royce1942" class="csl-entry">
ROYCE, W. F. Standard length versus total length. <strong>Transactions of the American Fisheries Society</strong>, [s. l.], v. 71, n. 1, p. 270–274, 1942. Disponível em: &lt;<a href="https://academic.oup.com/tafs/article/71/1/270/7898954">https://academic.oup.com/tafs/article/71/1/270/7898954</a>&gt;
</div>
</div>
  <div class="chapter-nav">
<div class="prev"><a href="testes.html"><span class="header-section-number">12</span> R Módulo 3.2 - Testes estatísticos</a></div>
<div class="next"><a href="regmul.html"><span class="header-section-number">14</span> Regressão múltipla</a></div>
</div></main><div class="col-md-3 col-lg-2 d-none d-md-block sidebar sidebar-chapter">
    <nav id="toc" data-toggle="toc" aria-label="On this page"><h2>On this page</h2>
      <ul class="nav navbar-nav">
<li>
<a class="nav-link" href="#correg"><span class="header-section-number">13</span> Correlação e Regressão</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#resumo-8">RESUMO</a></li>
<li><a class="nav-link" href="#apresenta%C3%A7%C3%A3o-8">Apresentação</a></li>
</ul>
</li>
<li>
<a class="nav-link" href="#correla%C3%A7%C3%A3o"><span class="header-section-number">13.1</span> Correlação</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#coeficiente-de-correla%C3%A7%C3%A3o-de-pearson-r"><span class="header-section-number">13.1.1</span> Coeficiente de correlação de Pearson (\(r\))</a></li>
<li><a class="nav-link" href="#coeficiente-de-determina%C3%A7%C3%A3o-r2"><span class="header-section-number">13.1.2</span> Coeficiente de determinação (\(r^2\))</a></li>
<li><a class="nav-link" href="#rela%C3%A7%C3%A3o-entre-r-e-r2"><span class="header-section-number">13.1.3</span> Relação entre \(r\) e \(R^2\)</a></li>
</ul>
</li>
<li><a class="nav-link" href="#sobre-os-dados-2"><span class="header-section-number">13.2</span> Sobre os dados</a></li>
<li><a class="nav-link" href="#organiza%C3%A7%C3%A3o-b%C3%A1sica-3"><span class="header-section-number">13.3</span> Organização básica</a></li>
<li><a class="nav-link" href="#importando-a-planilha-3"><span class="header-section-number">13.4</span> Importando a planilha</a></li>
<li><a class="nav-link" href="#correla%C3%A7%C3%A3o-simples-bivariada"><span class="header-section-number">13.5</span> Correlação simples (bivariada)</a></li>
<li><a class="nav-link" href="#correla%C3%A7%C3%A3o-parcial"><span class="header-section-number">13.6</span> Correlação parcial</a></li>
<li><a class="nav-link" href="#regress%C3%A3o-simples"><span class="header-section-number">13.7</span> Regressão simples</a></li>
<li>
<a class="nav-link" href="#gr%C3%A1fico-de-dispers%C3%A3o-scatterplot"><span class="header-section-number">13.8</span> Gráfico de dispersão (scatterplot)</a><ul class="nav navbar-nav"><li><a class="nav-link" href="#ggplot"><span class="header-section-number">13.8.1</span> O que é ggplot2?</a></li></ul>
</li>
<li><a class="nav-link" href="#ap%C3%AAndices-7">Apêndices</a></li>
<li><a class="nav-link" href="#sites-para-consulta-1">Sites para consulta</a></li>
<li><a class="nav-link" href="#script-limpo-4">Script limpo</a></li>
<li><a class="nav-link" href="#refer%C3%AAncias-10">Referências</a></li>
</ul>

      <div class="book-extra">
        <ul class="list-unstyled">
          
        </ul>
</div>
    </nav>
</div>

</div>
</div> <!-- .container -->

<footer class="bg-primary text-light mt-5"><div class="container"><div class="row">

  <div class="col-12 col-md-6 mt-3">
    <p>"<strong>Fundamentos de Ecologia Numérica</strong>: Disciplina de Ecologia Numérica do Curso de Ciências Biológicas do Campus V da UEPB" was written by Prof. Elvio S. F. Medeiros, Laboratório de Ecologia, Universidade Estadual da Paraíba, Campus V, João Pessoa, PB. It was last built on Last updated: 27/07/2026 18:26:38.</p>
  </div>

  <div class="col-12 col-md-6 mt-3">
    <p>This book was built by the <a class="text-light" href="https://bookdown.org">bookdown</a> R package.</p>
  </div>

</div></div>
</footer><!-- dynamically load mathjax for compatibility with self-contained --><script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script><script type="text/x-mathjax-config">const popovers = document.querySelectorAll('a.footnote-ref[data-toggle="popover"]');
for (let popover of popovers) {
  const div = document.createElement('div');
  div.setAttribute('style', 'position: absolute; top: 0, left:0; width:0, height:0, overflow: hidden; visibility: hidden;');
  div.innerHTML = popover.getAttribute('data-content');

  var has_math = div.querySelector("span.math");
  if (has_math) {
    document.body.appendChild(div);
    MathJax.Hub.Queue(["Typeset", MathJax.Hub, div]);
    MathJax.Hub.Queue(function() {
      popover.setAttribute('data-content', div.innerHTML);
      document.body.removeChild(div);
    })
  }
}
</script>
</body>
</html>
