<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title> 15 R Módulo 7 - Modelos lineares generalizados (GLMs) | Fundamentos de Ecologia Numérica</title>
<meta name="author" content="Prof. Elvio S. F. Medeiros">
<meta name="author" content="Laboratório de Ecologia">
<meta name="author" content="Universidade Estadual da Paraíba">
<meta name="author" content="Campus V, João Pessoa, PB">
<meta name="description" content="RESUMO Até este ponto, assumimos que a variância é constante e que os erros seguem uma distribuição normal. Entretanto, para muitos tipos de dados, uma ou ambas essas suposições não são válidas....">
<meta name="generator" content="bookdown 0.47 with bs4_book()">
<meta property="og:title" content=" 15 R Módulo 7 - Modelos lineares generalizados (GLMs) | Fundamentos de Ecologia Numérica">
<meta property="og:type" content="book">
<meta property="og:description" content="RESUMO Até este ponto, assumimos que a variância é constante e que os erros seguem uma distribuição normal. Entretanto, para muitos tipos de dados, uma ou ambas essas suposições não são válidas....">
<meta name="twitter:card" content="summary">
<meta name="twitter:title" content=" 15 R Módulo 7 - Modelos lineares generalizados (GLMs) | Fundamentos de Ecologia Numérica">
<meta name="twitter:description" content="RESUMO Até este ponto, assumimos que a variância é constante e que os erros seguem uma distribuição normal. Entretanto, para muitos tipos de dados, uma ou ambas essas suposições não são válidas....">
<!-- JS --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/fuse.js/6.4.6/fuse.js" integrity="sha512-zv6Ywkjyktsohkbp9bb45V6tEMoWhzFzXis+LrMehmJZZSys19Yxf1dopHx7WzIKxr5tK2dVcYmaCk2uqdjF4A==" crossorigin="anonymous"></script><script src="https://kit.fontawesome.com/6ecbd6c532.js" crossorigin="anonymous"></script><script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link href="libs/bootstrap-4.6.0/bootstrap.min.css" rel="stylesheet">
<script src="libs/bootstrap-4.6.0/bootstrap.bundle.min.js"></script><script src="libs/bs3compat-0.11.0/transition.js"></script><script src="libs/bs3compat-0.11.0/tabs.js"></script><script src="libs/bs3compat-0.11.0/bs3compat.js"></script><link href="libs/bs4_book-1.0.0/bs4_book.css" rel="stylesheet">
<script src="libs/bs4_book-1.0.0/bs4_book.js"></script><script src="libs/kePrint-0.0.1/kePrint.js"></script><link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet">
<link href="libs/bsTable-3.3.7/bootstrapTable.min.css" rel="stylesheet">
<script src="libs/bsTable-3.3.7/bootstrapTable.js"></script><script src="libs/htmlwidgets-1.6.4/htmlwidgets.js"></script><script src="libs/rglWebGL-binding-1.3.36/rglWebGL.js"></script><link href="libs/rglwidgetClass-1.3.36/rgl.css" rel="stylesheet">
<script src="libs/rglwidgetClass-1.3.36/rglClass.src.js"></script><script src="libs/rglwidgetClass-1.3.36/utils.src.js"></script><script src="libs/rglwidgetClass-1.3.36/buffer.src.js"></script><script src="libs/rglwidgetClass-1.3.36/subscenes.src.js"></script><script src="libs/rglwidgetClass-1.3.36/shaders.src.js"></script><script src="libs/rglwidgetClass-1.3.36/shadersrc.src.js"></script><script src="libs/rglwidgetClass-1.3.36/textures.src.js"></script><script src="libs/rglwidgetClass-1.3.36/projection.src.js"></script><script src="libs/rglwidgetClass-1.3.36/mouse.src.js"></script><script src="libs/rglwidgetClass-1.3.36/init.src.js"></script><script src="libs/rglwidgetClass-1.3.36/pieces.src.js"></script><script src="libs/rglwidgetClass-1.3.36/draw.src.js"></script><script src="libs/rglwidgetClass-1.3.36/controls.src.js"></script><script src="libs/rglwidgetClass-1.3.36/selection.src.js"></script><script src="libs/rglwidgetClass-1.3.36/rglTimer.src.js"></script><script src="libs/rglwidgetClass-1.3.36/pretty.src.js"></script><script src="libs/rglwidgetClass-1.3.36/axes.src.js"></script><script src="libs/rglwidgetClass-1.3.36/animation.src.js"></script><script src="libs/CanvasMatrix4-1.3.36/CanvasMatrix.src.js"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/autocomplete.js/0.38.0/autocomplete.jquery.min.js" integrity="sha512-GU9ayf+66Xx2TmpxqJpliWbT5PiGYxpaG8rfnBEk1LL8l1KGkRShhngwdXK1UgqhAzWpZHSiYPc09/NwDQIGyg==" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/mark.min.js" integrity="sha512-5CYOlHXGh6QpOFA/TeTylKLWfB3ftPsde7AnmhuitiTX4K5SqCLBeKro6sPS8ilsz1Q4NRx3v8Ko2IBiszzdww==" crossorigin="anonymous"></script><!-- CSS --><style type="text/css">
    
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  </style>
<style type="text/css">
    /* Used with Pandoc 2.11+ new --citeproc when CSL is used */
    div.csl-bib-body { }
    div.csl-entry {
      clear: both;
          margin-bottom: 1em;
        }
    .hanging div.csl-entry {
      margin-left:2em;
      text-indent:-2em;
    }
    div.csl-left-margin {
      min-width:2em;
      float:left;
    }
    div.csl-right-inline {
      margin-left:2em;
      padding-left:1em;
    }
    div.csl-indent {
      margin-left: 2em;
    }
  </style>
<link rel="stylesheet" href="style.css">
</head>
<body data-spy="scroll" data-target="#toc">

<div class="container-fluid">
<div class="row">
  <header class="col-sm-12 col-lg-3 sidebar sidebar-book"><a class="sr-only sr-only-focusable" href="#content">Skip to main content</a>

    <div class="d-flex align-items-start justify-content-between">
      <h1>
        <a href="index.html" title="Disciplina de Ecologia Numérica do Curso de Ciências Biológicas do Campus V da UEPB">Fundamentos de Ecologia Numérica</a>:
        <small class="text-muted">Disciplina de Ecologia Numérica do Curso de Ciências Biológicas do Campus V da UEPB</small>
      </h1>
      <button class="btn btn-outline-primary d-lg-none ml-2 mt-1" type="button" data-toggle="collapse" data-target="#main-nav" aria-expanded="true" aria-controls="main-nav"><i class="fas fa-bars"></i><span class="sr-only">Show table of contents</span></button>
    </div>

    <div id="main-nav" class="collapse-lg">
      <form role="search">
        <input id="search" class="form-control" type="search" placeholder="Search" aria-label="Search">
</form>

      <nav aria-label="Table of contents"><h2>Table of contents</h2>
        <ul class="book-toc list-unstyled">
<li><a class="" href="index.html">Fundamentos de Ecologia Numérica</a></li>
<li><a class="" href="motiv.html">Motivação</a></li>
<li><a class="" href="plano.html">Plano de estudo</a></li>
<li><a class="" href="org.html">Organização do livro</a></li>
<li><a class="" href="estudar.html">Como estudar por esse livro?</a></li>
<li><a class="" href="cita.html">Como citar esse livro</a></li>
<li><a class="" href="download.html">Download da versão impressa</a></li>
<li class="book-part">I. INTRODUÇÃO</li>
<li><a class="" href="ferram.html"><span class="header-section-number">1</span> Ferramentas</a></li>
<li><a class="" href="rrstu.html"><span class="header-section-number">2</span> Introdução ao R/RStudio</a></li>
<li class="book-part">II. TEORIA</li>
<li><a class="" href="amd.html"><span class="header-section-number">3</span> Teoria 1 - Introdução à Análise Multivariada de Dados (AMD)</a></li>
<li><a class="" href="tiposE.html"><span class="header-section-number">4</span> Teoria 2 - Tipos de dados usados em AMD</a></li>
<li><a class="" href="reltrnsT.html"><span class="header-section-number">5</span> Teoria 3 - Relativizações e transformações de dados</a></li>
<li class="book-part">III. BASES DE DADOS</li>
<li><a class="" href="bases.html"><span class="header-section-number">6</span> Bases de dados. Dados do PPBio Semiárido</a></li>
<li><a class="" href="basepeixes.html"><span class="header-section-number">7</span> Base de dados I - Peixes</a></li>
<li><a class="" href="basehab.html"><span class="header-section-number">8</span> Base de dados II - Habitat</a></li>
<li class="book-part">IV. ESTATÍSTICAS DESCRITIVAS</li>
<li><a class="" href="tiposR.html"><span class="header-section-number">9</span> R Módulo 1 - Sintaxe e Tipos de dados no R</a></li>
<li><a class="" href="xls.html"><span class="header-section-number">10</span> R Módulo 2 - Importando planilhas de dados</a></li>
<li><a class="" href="norm.html"><span class="header-section-number">11</span> R Módulo 3 - Estatísticas descritivas e normalidade</a></li>
<li><a class="" href="testes.html"><span class="header-section-number">12</span> R Módulo 4 - Testes estatísticos</a></li>
<li><a class="" href="correg.html"><span class="header-section-number">13</span> R Módulo 5 - Correlação e Regressão</a></li>
<li><a class="" href="regmul.html"><span class="header-section-number">14</span> R Módulo 6 - Regressão múltipla</a></li>
<li><a class="active" href="mlgs.html"><span class="header-section-number">15</span> R Módulo 7 - Modelos lineares generalizados (GLMs)</a></li>
<li><a class="" href="estrcom.html"><span class="header-section-number">16</span> R Módulo 8.1 - Estrutura da comunidade</a></li>
<li><a class="" href="partdiv.html"><span class="header-section-number">17</span> R Modulo 8.2 - Decomposição da diversidade</a></li>
<li><a class="" href="estrhab.html"><span class="header-section-number">18</span> R Módulo 9 - Estrutura do habitat</a></li>
<li class="book-part">V. ANÁLISES MULTIVARIADAS</li>
<li><a class="" href="reltrns.html"><span class="header-section-number">19</span> R Modulo 10.2 - Relativizações e transformações</a></li>
<li><a class="" href="outcentr.html"><span class="header-section-number">20</span> R Módulo 10.2 - Análise de outliers baseada no desvio padrão do centróide</a></li>
<li><a class="" href="upgma.html"><span class="header-section-number">21</span> R Módulo 11.1 - Análise de Classificação Hierárquica - SAHN</a></li>
<li><a class="" href="kmeans.html"><span class="header-section-number">22</span> R Módulo 11.2 - Análise de Classificação Não-hierárquica - K-Means</a></li>
<li><a class="" href="pca.html"><span class="header-section-number">23</span> R Módulo 12 - Análise de Componentes Principais - PCA</a></li>
<li><a class="" href="nmds.html"><span class="header-section-number">24</span> R Módulo 13.1 - Análise de Ordenação - NMDS</a></li>
<li><a class="" href="nmds2.html"><span class="header-section-number">25</span> R Modulo 13.2 - Análise de Ordenação - NMDS</a></li>
<li class="book-part">VI. INFORMAÇÕES GERAIS</li>
<li><a class="" href="nomes.html"><span class="header-section-number">26</span> Nomenclatura das matrizes em AMD</a></li>
<li><a class="" href="bibliografia-geral.html">Bibliografia Geral</a></li>
</ul>

        <div class="book-extra">
          
        </div>
      </nav>
</div>
  </header><main class="col-sm-12 col-md-9 col-lg-7" id="content"><div id="mlgs" class="section level1" number="15">
<h1>
<span class="header-section-number"> 15</span> R Módulo 7 - Modelos lineares generalizados (GLMs)<a class="anchor" aria-label="anchor" href="#mlgs"><i class="fas fa-link"></i></a>
</h1>
<div id="resumo-10" class="section level3 unnumbered">
<h3>RESUMO<a class="anchor" aria-label="anchor" href="#resumo-10"><i class="fas fa-link"></i></a>
</h3>
<p>Até este ponto, assumimos que a variância é constante e que os erros seguem uma distribuição normal. Entretanto, para muitos tipos de dados, uma ou ambas essas suposições não são válidas. Se quisermos que nossas análises sejam imparciais e que nossas interpretações sejam cientificamente corretas, precisamos de métodos capazes de lidar com essas situações. Em dados de contagem, por exemplo, nos quais a variável resposta assume valores inteiros e frequentemente há muitos zeros no conjunto de dados, a variância pode aumentar linearmente com a média. Em dados de proporção, nos quais registramos tanto o número de sucessos quanto o número de fracassos de um evento, a variância apresenta uma relação em forma de <em>U</em> invertido com a média. Já quando a variável resposta segue uma distribuição gama (como em dados de tempo até a morte ou tempo até a ocorrência de um evento), a variância aumenta mais rapidamente do que de forma linear em relação à média. Assim, na prática, os dados frequentemente apresentam outros tipos de padrões de relação entre média e variância (veja Crawley <span class="citation">(<a href="#ref-crawley2005">2005</a>)</span> e <span class="citation">(<a href="#ref-crawley2015">2015</a>)</span>), de onde esse capítulo é baseado). A maneira de tratar todos esses problemas dentro de um único arcabouço teórico foi desenvolvida por John Nelder <span class="citation">(<a href="#ref-nelder1972">NELDER; WEDDERBURN, 1972</a>)</span>, que denominou essa abordagem de <strong>Modelos Lineares Generalizados</strong> (<em>Generalized Linear Models</em>), ou simplesmente <strong>GLMs</strong> (originalmente chamados de <em>glims</em>).</p>
</div>
<div id="apresentação-10" class="section level3 unnumbered">
<h3>Apresentação<a class="anchor" aria-label="anchor" href="#apresenta%C3%A7%C3%A3o-10"><i class="fas fa-link"></i></a>
</h3>
</div>
<div id="por-que-precisamos-de-modelos-lineares-generalizados" class="section level3" number="15.0.1">
<h3>
<span class="header-section-number">15.0.1</span> Por que precisamos de Modelos Lineares Generalizados?<a class="anchor" aria-label="anchor" href="#por-que-precisamos-de-modelos-lineares-generalizados"><i class="fas fa-link"></i></a>
</h3>
<p>Os Modelos Lineares Generalizados (<em>Generalized Linear Models</em> – GLMs) representam uma extensão dos modelos lineares clássicos, permitindo analisar uma ampla variedade de tipos de dados encontrados em Biologia, Ecologia e Ciências Ambientais <span class="citation">(<a href="#ref-dunn2018">DUNN; SMYTH, 2018</a>; <a href="#ref-mccullagh1989">MCCULLAGH; NELDER, 1989</a>)</span>.</p>
<p>Até este ponto, foram apresentados métodos como o teste t, ANOVA, correlação de Pearson e regressão linear simples. Todos esses métodos pertencem à família dos modelos lineares e compartilham um conjunto de pressupostos que devem ser atendidos para que as inferências estatísticas sejam válidas.</p>
<p>Em uma regressão linear simples, por exemplo, assume-se que:</p>
<ul>
<li>a variável resposta é contínua;</li>
<li>os resíduos seguem uma distribuição Normal;</li>
<li>existe uma relação linear entre a variável resposta e os preditores;</li>
<li>a variância dos resíduos é constante (homocedasticidade).</li>
</ul>
<p>Quando essas premissas são atendidas, a regressão linear fornece estimativas confiáveis e de fácil interpretação. Entretanto, muitos conjuntos de dados biológicos não apresentam essas características.</p>
<p>Na Ecologia, por exemplo, é comum trabalhar com variáveis resposta como:</p>
<ul>
<li>número de espécies;</li>
<li>abundância de indivíduos;</li>
<li>presença ou ausência de uma espécie;</li>
<li>proporção de sobrevivência;</li>
<li>porcentagem de cobertura vegetal;</li>
<li>concentração de nutrientes;</li>
<li>biomassa de organismos.</li>
</ul>
<p>Essas variáveis frequentemente apresentam distribuições diferentes da Normal, além de relações entre média e variância incompatíveis com a regressão linear clássica.</p>
<p>No exemplo que viemos tratando, a relação peso x comprimento ou comprimento total x comprimento padrão, não podem assumir valores negativos (Figura <a href="mlgs.html#fig:4043glm">15.1</a>). Entretanto, um modelo linear pode produzir previsões biologicamente impossíveis, peso ou comprimento total negativos. Veja resultados prévios abaixo.</p>
<div class="figure">
<span style="display:block;" id="fig:4043glm"></span>
<img src="fundamentos_de_ecologia_numerica_files/figure-html/4043glm-1.png" alt="Observe que a reta ajustada produz previsões negativas para riachos muito estreitos, algo biologicamente impossível" width="550px"><p class="caption">
Figura 15.1: Observe que a reta ajustada produz previsões negativas para riachos muito estreitos, algo biologicamente impossível
</p>
</div>
<p>Da mesma forma, probabilidades e proporções estão naturalmente limitadas ao intervalo entre 0 e 1, mas uma regressão linear pode gerar valores menores que 0 ou maiores que 1.</p>
<p>Essas limitações motivaram o desenvolvimento dos Modelos Lineares Generalizados (GLMs), que mantêm a estrutura dos modelos lineares tradicionais, mas permitem utilizar diferentes distribuições de probabilidade e diferentes funções de ligação (link functions) de acordo com a natureza da variável resposta.</p>
<p>Assim, enquanto a regressão linear utiliza exclusivamente a distribuição Normal, os GLMs possibilitam modelar variáveis de contagem, proporções, probabilidades e outras distribuições frequentemente encontradas em estudos ecológicos.</p>
</div>
<div id="tipos-de-distribuição-em-glms" class="section level3" number="15.0.2">
<h3>
<span class="header-section-number">15.0.2</span> Tipos de distribuição em GLM’s<a class="anchor" aria-label="anchor" href="#tipos-de-distribui%C3%A7%C3%A3o-em-glms"><i class="fas fa-link"></i></a>
</h3>
<p>A principal suposição que fizemos até aqui para os modelo lineares (função <code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code>), é que a variância é constante (Figura <a href="mlgs.html#fig:4043glm2">15.2</a>, (a)). Nesse caso, a escolha da distribuição depende da natureza da variável resposta. Variáveis contínuas aproximadamente simétricas costumam ser modeladas por uma distribuição Normal, enquanto contagens, proporções e variáveis contínuas positivas requerem outras distribuições.</p>
<p>Em <strong>dados de contagem</strong>, nos quais a variável resposta assume valores inteiros e frequentemente há muitos zeros no conjunto de dados, a variância pode aumentar linearmente com a média (Figura <a href="mlgs.html#fig:4043glm2">15.2</a>, (b)). Em <strong>dados de proporção</strong>, nos quais se registra tanto o número de sucessos quanto o número de fracassos de um evento, a variância apresenta uma relação em forma de <em>U</em> invertido com a média (Figura <a href="mlgs.html#fig:4043glm2">15.2</a>, (c)). Quando a variável resposta segue uma distribuição gama (como em <strong>dados de tempo</strong> até a morte ou tempo até a ocorrência de um evento), a variância aumenta mais rapidamente do que de forma linear em relação à média (Figura <a href="mlgs.html#fig:4043glm2">15.2</a>, (d)).</p>
<div class="figure">
<span style="display:block;" id="fig:4043glm2"></span>
<img src="fundamentos_de_ecologia_numerica_files/figure-html/4043glm2-1.png" alt="Relação entre a média e a variância para diferentes distribuições de probabilidade utilizadas em Modelos Lineares Generalizados (GLMs). (a) Distribuição normal, com variância constante; (b) distribuição de Poisson, em que a variância é igual à média; (c) distribuição binomial, cuja variância apresenta uma relação em forma de U invertido com a média; e (d) distribuição gama, em que a variância aumenta proporcionalmente ao quadrado da média. Essas diferentes relações entre média e variância justificam o uso de famílias de distribuições específicas em GLMs, em substituição aos modelos lineares clássicos que assumem homocedasticidade." width="550px"><p class="caption">
Figura 15.2: Relação entre a média e a variância para diferentes distribuições de probabilidade utilizadas em Modelos Lineares Generalizados (GLMs). (a) Distribuição normal, com variância constante; (b) distribuição de Poisson, em que a variância é igual à média; (c) distribuição binomial, cuja variância apresenta uma relação em forma de U invertido com a média; e (d) distribuição gama, em que a variância aumenta proporcionalmente ao quadrado da média. Essas diferentes relações entre média e variância justificam o uso de famílias de distribuições específicas em GLMs, em substituição aos modelos lineares clássicos que assumem homocedasticidade.
</p>
</div>
<p>Aqui vemos a dispersão da variância em resposta a média para as famílias de distribuições mais comuns em GLM (Figura <a href="mlgs.html#fig:4043glm3">15.3</a>).</p>
<div class="figure">
<span style="display:block;" id="fig:4043glm3"></span>
<img src="fundamentos_de_ecologia_numerica_files/figure-html/4043glm3-1.png" alt="Relação da dispersão da variância em resposta a média para as famílias de distribuição mais comuns em GLM. Essas diferentes relações entre média e variância justificam o uso de famílias de distribuições específicas em GLMs, em substituição aos modelos lineares clássicos que assumem homocedasticidade." width="550px"><p class="caption">
Figura 15.3: Relação da dispersão da variância em resposta a média para as famílias de distribuição mais comuns em GLM. Essas diferentes relações entre média e variância justificam o uso de famílias de distribuições específicas em GLMs, em substituição aos modelos lineares clássicos que assumem homocedasticidade.
</p>
</div>
<p>Essas quatro relações fundamentam a escolha da família de distribuição em Modelos Lineares Generalizados (GLMs), pois cada tipo de variável resposta apresenta um padrão característico de relação entre a média e a variância.</p>
<p>As principais distribuições utilizadas em Modelos Lineares Generalizados são mostradas abaixo (Figura <a href="mlgs.html#fig:4043distglm">15.4</a>). As distribuições Normal, Gamma e Beta são contínuas, portanto possuem uma função densidade (<span class="math inline">\(f(x)\)</span>). Já as distribuições Poisson e Binomial são discretas. Elas possuem uma função de massa de probabilidade (<span class="math inline">\(P(X=x)\)</span>), definida apenas para valores inteiros. Além da forma da distribuição, cada família possui uma relação característica entre a média e a variância. Nos modelos lineares clássicos assume-se variância constante. Nos GLMs, entretanto, a variância pode aumentar linearmente com a média (Poisson), atingir um máximo (Binomial) ou crescer aproximadamente com o quadrado da média (Gamma) (Figura <a href="mlgs.html#fig:4043glm">15.1</a>). Essa flexibilidade permite modelar adequadamente diferentes tipos de dados biológicos.</p>
<div class="figure">
<span style="display:block;" id="fig:4043distglm"></span>
<img src="fundamentos_de_ecologia_numerica_files/figure-html/4043distglm-1.png" alt="Principais distribuições utilizadas em Modelos Lineares Generalizados." width="600px"><p class="caption">
Figura 15.4: Principais distribuições utilizadas em Modelos Lineares Generalizados.
</p>
</div>
<p>Muitos dos métodos estatísticos clássicos, como a <strong>regressão linear</strong> e o <strong>teste t de Student</strong>, assumem que a variância é constante (homocedasticidade). No entanto, em diversas aplicações essa suposição não é válida. É justamente por isso que os GLMs são tão úteis, pois permitem modelar adequadamente situações em que a variância depende da média da variável resposta <span class="citation">(<a href="#ref-crawley2005">CRAWLEY, 2005</a>, <a href="#ref-crawley2015">2015</a>; <a href="#ref-dunn2018">DUNN; SMYTH, 2018</a>; <a href="#ref-mccullagh1989">MCCULLAGH; NELDER, 1989</a>; <a href="#ref-nelder1972">NELDER; WEDDERBURN, 1972</a>; <a href="#ref-zuur2009">ZUUR et al., 2009</a>)</span>.</p>
<p>Mas qual distribuição escolher? Abaixo segue um esquema ((Figura <a href="mlgs.html#fig:esquemadistribs">15.5</a>) adaptado de <a href="https://bedeffinianrowedavies.com/">Davies</a> <span class="citation">(<a href="#ref-davies2021">DAVIES et al., 2021</a>, <a href="#ref-davies2022">2022</a>)</span>.</p>
<div class="figure">
<span style="display:block;" id="fig:esquemadistribs"></span>
<img src="imagens/distribuicoes.png" alt="Tipos de distribuição em relação a variável resposta em GLM's (Adaptado de Davies, B.F.R. em 2026. Fonte: &lt;https://bedeffinianrowedavies.com/&gt;)." width="500px"><p class="caption">
Figura 15.5: Tipos de distribuição em relação a variável resposta em GLM’s (Adaptado de Davies, B.F.R. em 2026. Fonte: <a href="https://bedeffinianrowedavies.com/" class="uri">https://bedeffinianrowedavies.com/</a>).
</p>
</div>
<div id="pressupostos-6" class="section level4" number="15.0.2.1">
<h4>
<span class="header-section-number">15.0.2.1</span> Pressupostos<a class="anchor" aria-label="anchor" href="#pressupostos-6"><i class="fas fa-link"></i></a>
</h4>
<p>Um Modelo Linear Generalizado possui três componentes fundamentais: <strong>a estrutura de erros</strong>, <strong>o preditor linear</strong> e <strong>a função de ligação</strong> (<em>link function</em>) <span class="citation">(<a href="#ref-crawley2015">CRAWLEY, 2015</a>)</span>:</p>
</div>
<div id="estrutura-de-erros" class="section level4" number="15.0.2.2">
<h4>
<span class="header-section-number">15.0.2.2</span> Estrutura de erros:<a class="anchor" aria-label="anchor" href="#estrutura-de-erros"><i class="fas fa-link"></i></a>
</h4>
<p>Até este ponto, trabalhamos com análises estatísticas que assumem <strong>erros normalmente distribuídos</strong>. Na prática, entretanto, muitos tipos de dados apresentam distribuições de erro que não seguem a distribuição normal <span class="citation">(<a href="#ref-crawley2005">CRAWLEY, 2005</a>, <a href="#ref-crawley2015">2015</a>)</span>. Alguns exemplos incluem:</p>
<ul>
<li>erros com forte assimetria;</li>
<li>erros com excesso ou deficiência de curtose;</li>
<li>erros limitados a um intervalo específico, como ocorre com dados de proporções;</li>
<li>erros que não podem produzir valores ajustados negativos, como em dados de contagem.</li>
</ul>
<p>As principais alternativas para lidar com essas situações consistem em <strong>transformar a variável resposta</strong> ou utilizar <strong>métodos não-paramétricos</strong> <span class="citation">(<a href="#ref-sokal1995">SOKAL; ROHLF, 1995</a>)</span>. Os <strong>Modelos Lineares Generalizados</strong> representam uma abordagem mais flexível, pois permitem especificar diferentes distribuições de probabilidade para os erros, de acordo com a natureza da variável resposta.</p>
<p>Entre as distribuições de erro mais utilizadas em GLMs destacam-se <span class="citation">(<a href="#ref-faraway2016">FARAWAY, 2016</a>)</span>:</p>
<ul>
<li>
<strong>Distribuição de Poisson</strong>, apropriada para dados de contagem;</li>
<li>
<strong>Distribuição Binomial</strong>, indicada para dados de proporções ou sucessos e fracassos;</li>
<li>
<strong>Distribuição Gama</strong>, adequada para variáveis contínuas, positivas, cuja variabilidade tende a aumentar proporcionalmente ao quadrado da média (ou que apresentam coeficiente de variação aproximadamente constante);</li>
<li>
<strong>Distribuição Exponencial</strong>, empregada em dados de tempo até a ocorrência de um evento, como em análises de sobrevivência.</li>
</ul>
<div class="inline-table"><table class="table table-sm">
<thead><tr class="header">
<th align="left">Tipo de variável resposta</th>
<th align="left">Distribuição recomendada</th>
</tr></thead>
<tbody>
<tr class="odd">
<td align="left">Contínua</td>
<td align="left">Normal (Gaussiana)</td>
</tr>
<tr class="even">
<td align="left">Contagem</td>
<td align="left">Poisson</td>
</tr>
<tr class="odd">
<td align="left">Presença/Ausência</td>
<td align="left">Binomial</td>
</tr>
<tr class="even">
<td align="left">Proporção</td>
<td align="left">Binomial ou Beta*</td>
</tr>
<tr class="odd">
<td align="left">Tempo ou valores positivos</td>
<td align="left">Gamma</td>
</tr>
</tbody>
</table></div>
<p>* A distribuição <strong>Binomial</strong> é utilizada quando a proporção é obtida a partir de um número conhecido de ensaios (por exemplo, número de sementes germinadas em 100 sementes). A distribuição <strong>Beta</strong> é indicada para proporções contínuas restritas ao intervalo (0,1), como a fração de cobertura vegetal ou a proporção de área ocupada por uma espécie.</p>
</div>
<div id="estrutura-do-modelo" class="section level4" number="15.0.2.3">
<h4>
<span class="header-section-number">15.0.2.3</span> Estrutura do modelo:<a class="anchor" aria-label="anchor" href="#estrutura-do-modelo"><i class="fas fa-link"></i></a>
</h4>
<p>A estrutura de um modelo relaciona cada valor observado da variável resposta (<strong>y</strong>) a um valor previsto (<strong>ŷ</strong>). Esse valor previsto é obtido por meio de uma transformação aplicada ao resultado do <strong>preditor linear</strong>.</p>
<p>O <strong>preditor linear</strong>, geralmente representado pela letra grega (<span class="math inline">\(\eta\)</span>) (<em>eta</em>), consiste em uma combinação linear dos efeitos de uma ou mais variáveis explicativas (<span class="math inline">\(x_j\)</span>):</p>
<p><span class="math display">\[\eta_i = \beta_0 + \sum_{j=1}^{p} x_{ij}\beta_j,\]</span></p>
<p>em que:</p>
<ul>
<li>
<span class="math inline">\(x_{ij}\)</span> representa o valor da <em>j</em>-ésima variável explicativa para a <em>i</em>-ésima observação;</li>
<li>
<span class="math inline">\(\beta_j\)</span> são os parâmetros do modelo, normalmente desconhecidos e estimados a partir dos dados;</li>
<li>
<span class="math inline">\(p\)</span> é o número de variáveis explicativas incluídas no modelo.</li>
</ul>
<p>O lado direito da equação é denominado <strong>estrutura linear</strong>. O número de termos do preditor linear depende da quantidade de parâmetros que precisam ser estimados.</p>
<p>Por exemplo:</p>
<p>Em uma <strong>regressão linear simples</strong>, o preditor linear possui dois parâmetros: o intercepto (<span class="math inline">\(\beta_0\)</span>) e o coeficiente angular (<span class="math inline">\(\beta_1\)</span>). Em uma <strong>ANOVA de um fator</strong> com quatro tratamentos, o preditor linear contém quatro termos, correspondentes às médias estimadas para cada nível do fator. Quando o modelo inclui <strong>covariáveis</strong>, cada uma delas acrescenta um novo termo ao preditor linear, representando sua inclinação (coeficiente de regressão). Em uma <strong>ANOVA fatorial</strong>, os termos de interação também adicionam parâmetros ao modelo. O número de parâmetros depende dos graus de liberdade envolvidos. Por exemplo, a interação entre um fator com dois níveis e outro com quatro níveis acrescenta três parâmetros, pois <span class="math inline">\(((2-1)(4-1)=3)\)</span>.</p>
<p>No caso dos GLMs, para avaliar o ajuste de um modelo, calcula-se inicialmente o valor do <strong>preditor linear</strong> (<span class="math inline">\(\eta\)</span>) para cada observação da variável resposta. Em seguida, esse valor é relacionado à variável resposta por meio da <strong>função de ligação</strong> (<em>link function</em>). A função de ligação transforma a média da variável resposta para uma escala em que a relação com os preditores seja linear. Após estimar o preditor linear, o modelo aplica a <strong>função inversa da ligação</strong> para retornar os valores previstos à escala original da variável resposta. Esses valores são conhecidos como <strong>valores ajustados</strong> (<em>fitted values</em>).</p>
<p>Por exemplo, quando a função de ligação é o <strong>logaritmo</strong> (<em>log link</em>), o valor ajustado é obtido aplicando a função exponencial ao preditor linear:</p>
<p><span class="math display">\[\hat{\mu}=e^{\eta}\]</span>
e quando a função de ligação é o <strong>recíproco</strong> (<em>reciprocal link</em>), o valor ajustado corresponde ao inverso do preditor linear:</p>
<p><span class="math display">\[\hat{\mu}=\frac{1}{\eta}\]</span></p>
<p>Assim, embora o ajuste do modelo seja realizado na escala do preditor linear, <strong>os resultados finais são expressos na escala original da variável resposta</strong>, facilitando sua interpretação.</p>
</div>
<div id="função-de-ligação" class="section level4" number="15.0.2.4">
<h4>
<span class="header-section-number">15.0.2.4</span> Função de ligação:<a class="anchor" aria-label="anchor" href="#fun%C3%A7%C3%A3o-de-liga%C3%A7%C3%A3o"><i class="fas fa-link"></i></a>
</h4>
<p>Segundo <span class="citation">CRAWLEY (<a href="#ref-crawley2015">2015</a>)</span>, um dos conceitos mais desafiadores dos GLMs é a compreensão da relação entre os valores da variável resposta, observados nos dados e previstos pelo modelo, e o <strong>preditor linear</strong>. A ideia fundamental é que a <strong>função de ligação</strong> (<em>link function</em>) estabelece a relação entre a <strong>média da variável resposta</strong> e o preditor linear.</p>
<p><span class="citation">CRAWLEY (<a href="#ref-crawley2015">2015</a>)</span> expressa essa relação em termos matemáticos como:</p>
<p><span class="math display">\[\eta = g(\mu),\]</span>
onde,</p>
<ul>
<li>
<span class="math inline">\(\eta\)</span> é o <strong>preditor linear</strong>;</li>
<li>
<span class="math inline">\(\mu = E(y)\)</span> é a média esperada da variável resposta;</li>
<li>
<span class="math inline">\(g(\cdot)\)</span> é a função de ligação.</li>
</ul>
<p>Embora a expressão seja simples, seu significado merece atenção. O preditor linear (<span class="math inline">\(\eta\)</span>) é obtido a partir da combinação linear das variáveis explicativas e de seus respectivos coeficientes. Portanto, ele <strong>não corresponde diretamente a um valor da variável resposta</strong>, exceto no caso particular da <strong>função de ligação identidade</strong>, utilizada implicitamente na regressão linear tradicional.</p>
<p>Em um GLM, a média da variável resposta é inicialmente transformada pela função de ligação, produzindo o preditor linear. Após o ajuste do modelo, a <strong>função inversa da ligação</strong> é aplicada ao preditor linear para obter os valores ajustados na escala original da variável resposta <span class="citation">(<a href="#ref-faraway2016">FARAWAY, 2016</a>)</span>:</p>
<p><span class="math display">\[\mu = g^{-1}(\eta)\]</span></p>
<p>Assim, o modelo é ajustado em uma escala linear, mas as previsões são apresentadas na escala original dos dados, o que facilita sua interpretação.</p>
</div>
</div>
<div id="escolha-da-função-de-ligação" class="section level3" number="15.0.3">
<h3>
<span class="header-section-number">15.0.3</span> Escolha da função de ligação<a class="anchor" aria-label="anchor" href="#escolha-da-fun%C3%A7%C3%A3o-de-liga%C3%A7%C3%A3o"><i class="fas fa-link"></i></a>
</h3>
<p>Uma das principais razões para utilizar diferentes funções de ligação é garantir que os valores ajustados permaneçam dentro de limites compatíveis com a natureza da variável resposta <span class="citation">(<a href="#ref-faraway2016">FARAWAY, 2016</a>)</span>.</p>
<p>Por exemplo:</p>
<p>Em <strong>dados de contagem</strong>, os valores previstos devem ser sempre <strong>maiores ou iguais a zero</strong>, pois contagens negativas não fazem sentido. Nesse caso, a <strong>função de ligação logarítmica</strong> (<em>log link</em>) é uma escolha apropriada, pois sua função inversa é a exponencial:</p>
<p><span class="math display">\[\mu = e^{\eta}\]</span></p>
<p>que produz apenas valores positivos.</p>
<p>Da mesma forma, quando a variável resposta representa uma <strong>proporção</strong> ou uma <strong>probabilidade</strong>, os valores ajustados devem estar obrigatoriamente entre 0 e 1. Para esses casos, utiliza-se geralmente a <strong>função de ligação logito</strong> (<em>logit link</em>), definida como:</p>
<p><span class="math display">\[\eta = \log\left(\frac{p}{1-p}\right)\]</span></p>
<p>em que <span class="math inline">\(p\)</span> representa a probabilidade de ocorrência do evento de interesse. A função inversa do logito garante que todas as probabilidades estimadas permaneçam no intervalo entre 0 e 1.</p>
<div id="comparação-entre-funções-de-ligação" class="section level4" number="15.0.3.1">
<h4>
<span class="header-section-number">15.0.3.1</span> Comparação entre funções de ligação<a class="anchor" aria-label="anchor" href="#compara%C3%A7%C3%A3o-entre-fun%C3%A7%C3%B5es-de-liga%C3%A7%C3%A3o"><i class="fas fa-link"></i></a>
</h4>
<blockquote>
<p>Uma das vantagens dos GLMs é que diferentes funções de ligação podem ser utilizadas para um mesmo conjunto de dados, permitindo comparar modelos que descrevem diferentes formas de relação entre o preditor linear e a variável resposta.</p>
<p>— M.J. Crawley em <span class="citation">(<a href="#ref-crawley2015">CRAWLEY, 2015</a>)</span>.</p>
</blockquote>
<p>Como todos esses modelos são ajustados utilizando a mesma estrutura de dados, é possível comparar seus desempenhos por meio da <strong>deviância residual</strong> (<em>residual deviance</em>). Em geral, a função de ligação mais adequada é aquela que produz a <strong>menor deviância residual</strong>, indicando que o modelo descreve os dados de forma mais eficiente.</p>
<p>Dessa forma, a escolha da função de ligação não altera apenas a forma matemática do modelo, mas também influencia diretamente a qualidade do ajuste e a interpretação dos efeitos das variáveis explicativas sobre a variável resposta.</p>
</div>
<div id="funções-canônicas-de-ligação" class="section level4" number="15.0.3.2">
<h4>
<span class="header-section-number">15.0.3.2</span> Funções canônicas de ligação<a class="anchor" aria-label="anchor" href="#fun%C3%A7%C3%B5es-can%C3%B4nicas-de-liga%C3%A7%C3%A3o"><i class="fas fa-link"></i></a>
</h4>
<p>As <strong>funções de ligação canônicas</strong> (<em>canonical link functions</em>) são as funções de ligação utilizadas no R por padrão quando uma determinada distribuição de erros é especificada no argumento <code>family</code> de um GLM. Em outras palavras, quando nenhuma função de ligação é explicitamente informada, o software adota automaticamente a função de ligação canônica associada à distribuição escolhida.</p>
<p>As principais combinações entre distribuições de erro e suas respectivas funções de ligação canônicas são apresentadas na Tabela abaixo <span class="citation">(<a href="#ref-faraway2016">FARAWAY, 2016</a>)</span>.</p>
<div class="inline-table"><table class="table table-sm">
<colgroup>
<col width="34%">
<col width="39%">
<col width="26%">
</colgroup>
<thead><tr class="header">
<th align="left">Distribuição de erros (<code>family</code>)</th>
<th align="left">Função de ligação canônica (<code>link</code>)</th>
<th align="left">Função inversa</th>
</tr></thead>
<tbody>
<tr class="odd">
<td align="left">Normal</td>
<td align="left">Identidade (<em>identity</em>)</td>
<td align="left"><span class="math inline">\(\mu = \eta\)</span></td>
</tr>
<tr class="even">
<td align="left">Poisson</td>
<td align="left">Logaritmo (<em>log</em>)</td>
<td align="left"><span class="math inline">\(\mu = e^{\eta}\)</span></td>
</tr>
<tr class="odd">
<td align="left">Binomial</td>
<td align="left">Logito (<em>logit</em>)</td>
<td align="left"><span class="math inline">\(\mu = \dfrac{e^{\eta}}{1+e^{\eta}}\)</span></td>
</tr>
<tr class="even">
<td align="left">Gama</td>
<td align="left">Recíproca (<em>reciprocal</em>)</td>
<td align="left"><span class="math inline">\(\mu = \dfrac{1}{\eta}\)</span></td>
</tr>
</tbody>
</table></div>
<p>Cada uma dessas funções foi desenvolvida para estabelecer uma relação adequada entre o <strong>preditor linear</strong> (<span class="math inline">\(\eta\)</span>) e a <strong>média da variável resposta</strong> (<span class="math inline">\(\mu\)</span>)), respeitando as características da distribuição dos dados. A escolha da função de ligação garante que os valores ajustados permaneçam dentro de limites plausíveis. Por exemplo, a função <strong>log</strong> assegura que as estimativas para dados de contagem sejam sempre positivas, enquanto a função <strong>logito</strong> produz probabilidades compreendidas entre 0 e 1.</p>
<p>Embora essas sejam as funções de ligação canônicas, elas <strong>não são as únicas opções disponíveis</strong>. Em muitos casos, é possível utilizar outras funções de ligação para uma mesma distribuição. Por exemplo, para a distribuição binomial também podem ser empregadas as funções <strong>probit</strong> e <strong><em>complementary log-log</em></strong> <strong>(cloglog)</strong>, e para a distribuição gama podem ser utilizadas as funções <strong>log</strong> e <strong>identidade</strong>. A função canônica, entretanto, costuma ser a escolha inicial por apresentar propriedades matemáticas convenientes e, frequentemente, proporcionar estimativas mais eficientes <span class="citation">(<a href="#ref-mccullagh1989">MCCULLAGH; NELDER, 1989</a>; <a href="#ref-zuur2009">ZUUR et al., 2009</a>)</span>.</p>
<p>No <strong>R</strong>, basta especificar a família da distribuição para que a função de ligação canônica seja utilizada automaticamente. Para uma regressão linear (distribuição normal e função identidade)(equivalente a <code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code>:</p>
<pre><code>glm(y ~ x, family = gaussian(link = "identity"))</code></pre>
<p>Caso seja desejada outra função de ligação, ela pode ser especificada por meio do argumento <code>link</code>. Para a distribuição <code>Gama</code> com ligação <code>log</code>:</p>
<pre><code>glm(y ~ x, family = Gamma(link = "log"))</code></pre>
<p>As quatro combinações canônicas apresentadas na tabela correspondem aos modelos mais utilizados na prática e constituem o ponto de partida para a maioria das análises.</p>
</div>
<div id="exemplo-1-distribuição-gaussiana" class="section level4" number="15.0.3.3">
<h4>
<span class="header-section-number">15.0.3.3</span> Exemplo 1: Distribuição Gaussiana<a class="anchor" aria-label="anchor" href="#exemplo-1-distribui%C3%A7%C3%A3o-gaussiana"><i class="fas fa-link"></i></a>
</h4>
<p>Vejamos um fluxo de trabalho prático:</p>
<ol style="list-style-type: decimal">
<li><p>Formular a pergunta científica e traduzi-la em um modelo estatístico.</p></li>
<li><p>Escolher a distribuição da variável resposta.</p></li>
<li><p>Ajustar o modelo .</p></li>
<li><p>Verificar os diagnósticos do modelo: Gráfico de resíduos <em>versus</em> valores ajustados (<em>Residuals vs. Fitted</em>) e no gráfico Q-Q (<em>Normal Q-Q</em>) antes de interpretar os resultados.</p></li>
<li><p>Interpretar o modelo por meio da visualização das predições: Gerar valores preditos, intervalos de confiança e os sobrepor aos dados observados, facilitando a interpretação dos resultados.</p></li>
</ol>
<p>Nesse primeiro exemplo, vamos usar a distribuição Gaussiana (apropriada para dados contínuos), utilizando <code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code> e <code>glm(..., family = gaussian)</code>, uma vez que <code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code> é, essencialmente, um GLM Gaussiano, e é equivalente a <code>glm(..., family = gaussian)</code>.</p>
</div>
</div>
<div id="organização-básica-6" class="section level2" number="15.1">
<h2>
<span class="header-section-number">15.1</span> Organização básica<a class="anchor" aria-label="anchor" href="#organiza%C3%A7%C3%A3o-b%C3%A1sica-6"><i class="fas fa-link"></i></a>
</h2>
<div id="pacotes-do-módulo-5" class="section level3" number="15.1.1">
<h3>
<span class="header-section-number">15.1.1</span> Pacotes do módulo<a class="anchor" aria-label="anchor" href="#pacotes-do-m%C3%B3dulo-5"><i class="fas fa-link"></i></a>
</h3>
<p>Instalando os pacotes necessários para esse módulo.</p>
<div class="sourceCode" id="cb277"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/utils/install.packages.html">install.packages</a></span><span class="op">(</span><span class="st">"openxlsx"</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/packageDescription.html">packageVersion</a></span><span class="op">(</span><span class="st">"rlang"</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/remove.packages.html">remove.packages</a></span><span class="op">(</span><span class="st">"rlang"</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/install.packages.html">install.packages</a></span><span class="op">(</span><span class="st">"rlang"</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/packageDescription.html">packageVersion</a></span><span class="op">(</span><span class="st">"rlang"</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/install.packages.html">install.packages</a></span><span class="op">(</span><span class="st">"devtools"</span><span class="op">)</span></span>
<span><span class="fu">devtools</span><span class="fu">::</span><span class="fu"><a href="https://devtools.r-lib.org/reference/install-deprecated.html">install_github</a></span><span class="op">(</span><span class="st">"dustinfife/flexplot"</span><span class="op">)</span></span></code></pre></div>
<div id="limpando-a-memória-4" class="section level4 unnumbered">
<h4>Limpando a memória<a class="anchor" aria-label="anchor" href="#limpando-a-mem%C3%B3ria-4"><i class="fas fa-link"></i></a>
</h4>
<div class="sourceCode" id="cb278"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/grDevices/dev.html">dev.off</a></span><span class="op">(</span><span class="op">)</span> <span class="co">#apaga os graficos, se houver algum</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/rm.html">rm</a></span><span class="op">(</span>list<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/ls.html">ls</a></span><span class="op">(</span>all<span class="op">=</span><span class="cn">TRUE</span><span class="op">)</span><span class="op">)</span> <span class="co">#limpa a memória</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/cat.html">cat</a></span><span class="op">(</span><span class="st">"\014"</span><span class="op">)</span> <span class="co">#limpa o console </span></span>
<span><span class="co">#options(scipen = 999) #sem notação científica</span></span></code></pre></div>
<div class="sourceCode" id="cb279"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://ycphs.github.io/openxlsx/index.html">openxlsx</a></span><span class="op">)</span></span>
<span><span class="va">univ</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/openxlsx/man/read.xlsx.html">read.xlsx</a></span><span class="op">(</span><span class="st">"D:/Elvio/OneDrive/Disciplinas/_EcoNumerica/5.Matrizes/tucuna.xlsx"</span>,</span>
<span>                  rowNames <span class="op">=</span> <span class="cn">T</span>, colNames <span class="op">=</span> <span class="cn">T</span>,</span>
<span>                  sheet <span class="op">=</span> <span class="st">"tucuna"</span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://tidyverse.tidyverse.org">tidyverse</a></span><span class="op">)</span></span>
<span></span>
<span><span class="va">lm1</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">CP_cm</span><span class="op">~</span><span class="va">sexo</span><span class="op">*</span><span class="va">periodo</span>, data <span class="op">=</span> <span class="va">univ</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/par.html">par</a></span><span class="op">(</span>mfrow <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">2</span>,<span class="fl">2</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">lm1</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/par.html">par</a></span><span class="op">(</span>mfrow <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span>,<span class="fl">1</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://patchwork.data-imaginist.com">patchwork</a></span><span class="op">)</span></span>
<span><span class="va">ModelOutputs</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span>Fitted<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/stats/fitted.values.html">fitted</a></span><span class="op">(</span><span class="va">lm1</span><span class="op">)</span>,</span>
<span>                         Residuals<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/stats/residuals.html">resid</a></span><span class="op">(</span><span class="va">lm1</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="va">p1</span><span class="op">&lt;-</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">ModelOutputs</span><span class="op">)</span><span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">Fitted</span>, y <span class="op">=</span> <span class="va">Residuals</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_classic</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>y <span class="op">=</span> <span class="st">"Resíduos"</span>, x <span class="op">=</span> <span class="st">"Valores ajustados"</span><span class="op">)</span></span>
<span><span class="va">p2</span><span class="op">&lt;-</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">ModelOutputs</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_qq.html">stat_qq</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>sample <span class="op">=</span> <span class="va">Residuals</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_qq.html">stat_qq_line</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>sample <span class="op">=</span> <span class="va">Residuals</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_classic</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>y <span class="op">=</span> <span class="st">"Quantis dos dados"</span>,x <span class="op">=</span> <span class="st">"Quantis teóricos"</span><span class="op">)</span></span>
<span><span class="va">p1</span><span class="op">+</span><span class="va">p2</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">lm1</span><span class="op">)</span></span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = CP_cm ~ sexo * periodo, data = univ)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -11.904  -3.421  -1.600   2.929  27.720 
## 
## Coefficients:
##                         Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)              14.9026     0.9833  15.156  &lt; 2e-16 ***
## sexoimaturo              -7.7226     1.2566  -6.145 1.83e-09 ***
## sexoMACHO                 2.7650     1.2277   2.252   0.0248 *  
## periodoseco               0.6427     1.2884   0.499   0.6182    
## sexoimaturo:periodoseco  -0.1022     1.5813  -0.065   0.9485    
## sexoMACHO:periodoseco     1.6934     1.6973   0.998   0.3190    
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 6.061 on 428 degrees of freedom
## Multiple R-squared:   0.41,  Adjusted R-squared:  0.4031 
## F-statistic: 59.49 on 5 and 428 DF,  p-value: &lt; 2.2e-16</code></pre>
<p><img src="fundamentos_de_ecologia_numerica_files/figure-html/unnamed-chunk-166-1.png" alt="" width="672"><img src="fundamentos_de_ecologia_numerica_files/figure-html/unnamed-chunk-166-2.png" alt="" width="672"></p>
<p>O modelo está usando os três sexos, mas nesse caso o R utiliza codificação por tratamento (<em>treatment contrasts</em>): um dos níveis é escolhido como categoria de referência, e apenas os demais aparecem como coeficientes.</p>
<p>No seu modelo apresentado, o nível <code>FÊMEA</code> foi escolhido como referência. Assim, no modelo, <code>FÊMEA</code> (referência) equivale ao intercepto. Temos 3 níveis, mas apenas 2 coeficientes, porque o terceiro está embutido no intercepto.</p>
<p>Nesse caso, o intercepto vale 14.90. Esse é o comprimento médio (CP_cm) das fêmeas, no período chuvoso (também referência, note que que ele não aparece no modelo). O coeficiente <code>sexoMACHO</code> (<em>Estimate</em> = 2.765 e p = 0.0248), significa que, no período chuvoso, machos possuem, em média, 14.90 + 2.77 = 17.67 cm. Enquanto fêmeas possuem 14.90 cm. Já o coeficiente <code>sexoimaturo</code> (<em>Estimate</em> = -7.723), significa que os imaturos são, em média, 14.90 - 7.72 = 7.18 cm menores que as fêmeas no período chuvoso.</p>
<p>Para mudar para que <code>MACHO</code> seja a referência, pode-se redefinir o fator <code>univ$sexo &lt;- relevel(univ$sexo, ref = "MACHO")</code>.</p>
<div class="sourceCode" id="cb281"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://mjskay.github.io/ggdist/">ggdist</a></span><span class="op">)</span></span>
<span><span class="va">p_box</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">univ</span><span class="op">)</span><span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_boxplot.html">geom_boxplot</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">sexo</span>,</span>
<span>                   y <span class="op">=</span> <span class="va">CP_cm</span>,</span>
<span>                   fill <span class="op">=</span> <span class="va">periodo</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_manual.html">scale_fill_manual</a></span><span class="op">(</span>values <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"darkcyan"</span>,<span class="st">"darkorange"</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>x <span class="op">=</span> <span class="st">"Sexo"</span>, y <span class="op">=</span> <span class="st">"Variável resposta (CP(cm))"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_classic</a></span><span class="op">(</span><span class="op">)</span></span>
<span></span>
<span><span class="va">p_cloud</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">univ</span>,</span>
<span>                <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">sexo</span>,</span>
<span>                    y <span class="op">=</span> <span class="va">CP_cm</span>,</span>
<span>                    fill <span class="op">=</span> <span class="va">periodo</span>, colour <span class="op">=</span> <span class="va">periodo</span><span class="op">)</span><span class="op">)</span><span class="op">+</span> </span>
<span>  <span class="fu"><a href="https://mjskay.github.io/ggdist/reference/stat_halfeye.html">stat_halfeye</a></span><span class="op">(</span>adjust <span class="op">=</span> <span class="fl">.5</span>,</span>
<span>               width <span class="op">=</span> <span class="fl">.6</span>, </span>
<span>               .width <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">.5</span>, <span class="fl">.95</span><span class="op">)</span>,</span>
<span>               alpha<span class="op">=</span><span class="fl">0.7</span>,</span>
<span>               position <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/position_dodge.html">position_dodge</a></span><span class="op">(</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_manual.html">scale_fill_manual</a></span><span class="op">(</span>values <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"darkcyan"</span>,<span class="st">"darkorange"</span><span class="op">)</span><span class="op">)</span><span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_manual.html">scale_colour_manual</a></span><span class="op">(</span>values <span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span> <span class="op">(</span><span class="st">"darkcyan"</span>,<span class="st">"darkorange"</span><span class="op">)</span><span class="op">)</span><span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>x <span class="op">=</span> <span class="st">"Sexo"</span>,y<span class="op">=</span><span class="st">"Variável resposta (CP(cm))"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_classic</a></span><span class="op">(</span><span class="op">)</span></span>
<span><span class="va">p_box</span><span class="op">+</span><span class="va">p_cloud</span></span>
<span></span>
<span><span class="va">NewData_1</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/expand.grid.html">expand.grid</a></span><span class="op">(</span>periodo <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"chuvoso"</span>,<span class="st">"seco"</span><span class="op">)</span>,</span>
<span>                       sexo <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"FEMEA"</span>,<span class="st">"imaturo"</span>,<span class="st">"MACHO"</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="va">Pred</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/stats/predict.html">predict</a></span><span class="op">(</span><span class="va">lm1</span>,<span class="va">NewData_1</span>,se.fit<span class="op">=</span><span class="cn">TRUE</span><span class="op">)</span></span>
<span></span>
<span><span class="va">NewData</span> <span class="op">&lt;-</span> <span class="va">NewData_1</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>response<span class="op">=</span><span class="va">Pred</span><span class="op">$</span><span class="va">fit</span>,</span>
<span>         se.fit<span class="op">=</span><span class="va">Pred</span><span class="op">$</span><span class="va">se.fit</span>,</span>
<span>         Upr<span class="op">=</span><span class="va">response</span><span class="op">+</span><span class="op">(</span><span class="va">se.fit</span><span class="op">*</span><span class="fl">1.96</span><span class="op">)</span>,</span>
<span>         Lwr<span class="op">=</span><span class="va">response</span><span class="op">-</span><span class="op">(</span><span class="va">se.fit</span><span class="op">*</span><span class="fl">1.96</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">NewData</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">sexo</span>,</span>
<span>                 y <span class="op">=</span> <span class="va">response</span>,</span>
<span>                 colour <span class="op">=</span> <span class="va">periodo</span><span class="op">)</span>,</span>
<span>             position <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/position_dodge.html">position_dodge</a></span><span class="op">(</span><span class="fl">0.8</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_linerange.html">geom_errorbar</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">sexo</span>,</span>
<span>                    ymax <span class="op">=</span> <span class="va">Upr</span>,</span>
<span>                    ymin <span class="op">=</span> <span class="va">Lwr</span>,</span>
<span>                    colour <span class="op">=</span> <span class="va">periodo</span><span class="op">)</span>,</span>
<span>                width <span class="op">=</span> <span class="fl">0.1</span>,</span>
<span>                position<span class="op">=</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/position_dodge.html">position_dodge</a></span><span class="op">(</span><span class="fl">0.8</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_manual.html">scale_colour_manual</a></span><span class="op">(</span>values<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"darkcyan"</span>,<span class="st">"darkorange"</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>x<span class="op">=</span><span class="st">"Sexo"</span>,y<span class="op">=</span><span class="st">"Variável resposta (CP(cm))"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_classic</a></span><span class="op">(</span><span class="op">)</span></span>
<span></span>
<span><span class="va">Plot1</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">univ</span>,</span>
<span>              <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">sexo</span>,</span>
<span>                  y <span class="op">=</span> <span class="va">CP_cm</span>,</span>
<span>                  fill <span class="op">=</span> <span class="va">periodo</span>,</span>
<span>                  colour <span class="op">=</span> <span class="va">periodo</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu">ggdist</span><span class="fu">::</span><span class="fu"><a href="https://mjskay.github.io/ggdist/reference/stat_halfeye.html">stat_halfeye</a></span><span class="op">(</span>adjust <span class="op">=</span> <span class="fl">.5</span>,</span>
<span>                       width <span class="op">=</span> <span class="fl">.6</span>, </span>
<span>                       .width <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">.5</span>, <span class="fl">.95</span><span class="op">)</span>,</span>
<span>                       alpha <span class="op">=</span> <span class="fl">0.7</span>,</span>
<span>                       position <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/position_dodge.html">position_dodge</a></span><span class="op">(</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_manual.html">scale_fill_manual</a></span><span class="op">(</span>values <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"darkcyan"</span>, <span class="st">"darkorange"</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_manual.html">scale_colour_manual</a></span><span class="op">(</span>values <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"darkcyan"</span>, <span class="st">"darkorange"</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>x <span class="op">=</span> <span class="st">"Sexo"</span>,y <span class="op">=</span> <span class="st">"Variável resposta (CP(cm))"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_classic</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/theme.html">theme</a></span><span class="op">(</span>legend.position <span class="op">=</span> <span class="st">"none"</span><span class="op">)</span></span>
<span></span>
<span><span class="va">Plot2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">NewData</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">sexo</span>, y <span class="op">=</span> <span class="va">response</span>, colour <span class="op">=</span> <span class="va">periodo</span><span class="op">)</span>,</span>
<span>             position <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/position_dodge.html">position_dodge</a></span><span class="op">(</span><span class="fl">0.8</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_linerange.html">geom_errorbar</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">sexo</span>, ymax <span class="op">=</span> <span class="va">Upr</span>,</span>
<span>                    ymin <span class="op">=</span> <span class="va">Lwr</span>, colour <span class="op">=</span> <span class="va">periodo</span><span class="op">)</span>,</span>
<span>                width <span class="op">=</span> <span class="fl">0.1</span>,</span>
<span>                position <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/position_dodge.html">position_dodge</a></span><span class="op">(</span><span class="fl">0.8</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_manual.html">scale_colour_manual</a></span><span class="op">(</span>values <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"darkcyan"</span>,<span class="st">"darkorange"</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>x<span class="op">=</span><span class="st">"Sexo"</span>,y<span class="op">=</span><span class="st">"Variável resposta modelada(CP(cm))"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_classic</a></span><span class="op">(</span><span class="op">)</span></span>
<span><span class="va">Plot1</span><span class="op">+</span><span class="va">Plot2</span></span></code></pre></div>
<p><img src="fundamentos_de_ecologia_numerica_files/figure-html/unnamed-chunk-167-1.png" alt="" width="672"><img src="fundamentos_de_ecologia_numerica_files/figure-html/unnamed-chunk-167-2.png" alt="" width="672"><img src="fundamentos_de_ecologia_numerica_files/figure-html/unnamed-chunk-167-3.png" alt="" width="672"></p>
<div class="sourceCode" id="cb282"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">Plot1</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">univ</span>,</span>
<span>              <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">sexo</span>,</span>
<span>                  y <span class="op">=</span> <span class="va">CP_cm</span>,</span>
<span>                  fill <span class="op">=</span> <span class="va">periodo</span>, colour <span class="op">=</span> <span class="va">periodo</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu">ggdist</span><span class="fu">::</span><span class="fu"><a href="https://mjskay.github.io/ggdist/reference/stat_halfeye.html">stat_halfeye</a></span><span class="op">(</span>adjust <span class="op">=</span> <span class="fl">.5</span>,</span>
<span>                       width <span class="op">=</span> <span class="fl">.6</span>, </span>
<span>                       .width <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">.5</span>, <span class="fl">.95</span><span class="op">)</span>,</span>
<span>                       alpha <span class="op">=</span> <span class="fl">0.7</span>,</span>
<span>                       position <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/position_dodge.html">position_dodge</a></span><span class="op">(</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_manual.html">scale_fill_manual</a></span><span class="op">(</span>values <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"darkcyan"</span>, <span class="st">"darkorange"</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_manual.html">scale_colour_manual</a></span><span class="op">(</span>values <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"darkcyan"</span>, <span class="st">"darkorange"</span><span class="op">)</span><span class="op">)</span><span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>x <span class="op">=</span> <span class="st">"sexo"</span>,y <span class="op">=</span> <span class="st">"Variável resposta (CP(cm))"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_classic</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_continuous.html">scale_y_continuous</a></span><span class="op">(</span>limits <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0</span>, <span class="fu"><a href="https://rdrr.io/r/base/Extremes.html">max</a></span><span class="op">(</span><span class="va">univ</span><span class="op">$</span><span class="va">CP_cm</span><span class="op">)</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/theme.html">theme</a></span><span class="op">(</span>legend.position <span class="op">=</span> <span class="st">"none"</span><span class="op">)</span></span>
<span></span>
<span><span class="va">Plot2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">NewData</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">sexo</span>, y <span class="op">=</span> <span class="va">response</span>, colour <span class="op">=</span> <span class="va">periodo</span><span class="op">)</span>,</span>
<span>             position <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/position_dodge.html">position_dodge</a></span><span class="op">(</span><span class="fl">0.8</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_linerange.html">geom_errorbar</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">sexo</span>, ymax <span class="op">=</span> <span class="va">Upr</span>,</span>
<span>                    ymin <span class="op">=</span> <span class="va">Lwr</span>, colour <span class="op">=</span> <span class="va">periodo</span><span class="op">)</span>,</span>
<span>                width <span class="op">=</span> <span class="fl">0.1</span>,</span>
<span>                position <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/position_dodge.html">position_dodge</a></span><span class="op">(</span><span class="fl">0.8</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_manual.html">scale_colour_manual</a></span><span class="op">(</span>values <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"darkcyan"</span>, <span class="st">"darkorange"</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>x <span class="op">=</span> <span class="st">"Sexo"</span>,y <span class="op">=</span> <span class="st">"Modelo da variável resposta (CT(cm))"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_continuous.html">scale_y_continuous</a></span><span class="op">(</span>limits <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0</span>, <span class="fu"><a href="https://rdrr.io/r/base/Extremes.html">max</a></span><span class="op">(</span><span class="va">univ</span><span class="op">$</span><span class="va">CP_cm</span><span class="op">)</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_classic</a></span><span class="op">(</span><span class="op">)</span></span>
<span><span class="va">Plot1</span><span class="op">+</span><span class="va">Plot2</span></span></code></pre></div>
<div class="inline-figure"><img src="fundamentos_de_ecologia_numerica_files/figure-html/unnamed-chunk-168-1.png" alt="" width="672"></div>
<div class="sourceCode" id="cb283"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">NewData</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">sexo</span>, y <span class="op">=</span> <span class="va">response</span>, colour <span class="op">=</span> <span class="va">periodo</span><span class="op">)</span>,</span>
<span>             position <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/position_dodge.html">position_dodge</a></span><span class="op">(</span><span class="fl">0.8</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_linerange.html">geom_errorbar</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">sexo</span>, ymax <span class="op">=</span> <span class="va">Upr</span>,</span>
<span>                    ymin <span class="op">=</span> <span class="va">Lwr</span>, colour <span class="op">=</span> <span class="va">periodo</span><span class="op">)</span>,</span>
<span>                width <span class="op">=</span> <span class="fl">0.1</span>,</span>
<span>                position <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/position_dodge.html">position_dodge</a></span><span class="op">(</span><span class="fl">0.8</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span>data <span class="op">=</span> <span class="va">univ</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">sexo</span>,</span>
<span>                                     y <span class="op">=</span> <span class="va">CP_cm</span>,</span>
<span>                                     colour <span class="op">=</span> <span class="va">periodo</span><span class="op">)</span>,</span>
<span>             position <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/position_jitterdodge.html">position_jitterdodge</a></span><span class="op">(</span>jitter.width <span class="op">=</span> <span class="fl">0.4</span>,</span>
<span>                                           dodge.width <span class="op">=</span> <span class="fl">0.8</span><span class="op">)</span>,</span>
<span>             alpha <span class="op">=</span> <span class="fl">0.3</span>,</span>
<span>             size <span class="op">=</span> <span class="fl">1.5</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_manual.html">scale_colour_manual</a></span><span class="op">(</span>values <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"darkcyan"</span>, <span class="st">"darkorange"</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>x <span class="op">=</span> <span class="st">"Sexo"</span>, y <span class="op">=</span> <span class="st">"Variável resposta (CP(cm))"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_classic</a></span><span class="op">(</span><span class="op">)</span></span></code></pre></div>
<div class="inline-figure"><img src="fundamentos_de_ecologia_numerica_files/figure-html/unnamed-chunk-169-1.png" alt="" width="672"></div>
<div class="sourceCode" id="cb284"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://ggplot2.tidyverse.org">ggplot2</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://dplyr.tidyverse.org">dplyr</a></span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/colnames.html">colnames</a></span><span class="op">(</span><span class="va">univ</span><span class="op">)</span></span>
<span><span class="va">dados</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/subset.html">subset</a></span><span class="op">(</span><span class="va">univ</span>,</span>
<span>                <span class="va">sexo</span> <span class="op">!=</span> <span class="st">"imaturo"</span> <span class="op">&amp;</span> <span class="va">Pgon_g</span><span class="op">&gt;</span><span class="fl">0.2</span> <span class="op">&amp;</span> <span class="va">Pgon_g</span><span class="op">&lt;</span><span class="fl">10</span><span class="op">)</span> <span class="co">#ou `filter` do dplyr</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/table.html">table</a></span><span class="op">(</span><span class="va">dados</span><span class="op">$</span><span class="va">sexo</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/unique.html">unique</a></span><span class="op">(</span><span class="va">dados</span><span class="op">$</span><span class="va">sexo</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">dados</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">CP_cm</span>,</span>
<span>                 y <span class="op">=</span> <span class="va">Pgon_g</span>,</span>
<span>                 color <span class="op">=</span> <span class="va">sexo</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_smooth.html">geom_smooth</a></span><span class="op">(</span>method <span class="op">=</span> <span class="st">"lm"</span>,</span>
<span>              se <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Dados observados</span></span>
<span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">dados</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">CP_cm</span>,</span>
<span>                 y <span class="op">=</span> <span class="va">Pgon_g</span>,</span>
<span>                 colour <span class="op">=</span> <span class="va">sexo</span><span class="op">)</span>,</span>
<span>             alpha <span class="op">=</span> <span class="fl">0.6</span>,</span>
<span>             size <span class="op">=</span> <span class="fl">2</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_manual.html">scale_colour_manual</a></span><span class="op">(</span>values <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"darkcyan"</span>,<span class="st">"darkorange"</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>x <span class="op">=</span> <span class="st">"Comprimento padrão (cm)"</span>,</span>
<span>       y <span class="op">=</span> <span class="st">"Peso da gônada (g)"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_classic</a></span><span class="op">(</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Ajuste do modelo</span></span>
<span><span class="va">lm2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">Pgon_g</span> <span class="op">~</span> <span class="va">sexo</span> <span class="op">*</span> <span class="va">CP_cm</span>, data <span class="op">=</span> <span class="va">dados</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Diagnóstico do modelo</span></span>
<span><span class="va">ModelOutputs</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span></span>
<span>  Fitted <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/fitted.values.html">fitted</a></span><span class="op">(</span><span class="va">lm2</span><span class="op">)</span>,</span>
<span>  Residuals <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/residuals.html">resid</a></span><span class="op">(</span><span class="va">lm2</span><span class="op">)</span></span>
<span><span class="op">)</span></span>
<span><span class="va">p3</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">ModelOutputs</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">Fitted</span>,</span>
<span>                 y <span class="op">=</span> <span class="va">Residuals</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_abline.html">geom_hline</a></span><span class="op">(</span>yintercept <span class="op">=</span> <span class="fl">0</span>,</span>
<span>             linetype <span class="op">=</span> <span class="fl">2</span>,</span>
<span>             colour <span class="op">=</span> <span class="st">"red"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>x <span class="op">=</span> <span class="st">"Valores ajustados"</span>,</span>
<span>       y <span class="op">=</span> <span class="st">"Resíduos"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_classic</a></span><span class="op">(</span><span class="op">)</span></span>
<span><span class="va">p4</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">ModelOutputs</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_qq.html">stat_qq</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>sample <span class="op">=</span> <span class="va">Residuals</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_qq.html">stat_qq_line</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>sample <span class="op">=</span> <span class="va">Residuals</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>x <span class="op">=</span> <span class="st">"Quartis teóricos"</span>,</span>
<span>       y <span class="op">=</span> <span class="st">"Quartis amostrais"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_classic</a></span><span class="op">(</span><span class="op">)</span></span>
<span><span class="va">p3</span> <span class="op">+</span> <span class="va">p4</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">lm2</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Conjunto de dados para predição</span></span>
<span><span class="va">NewData_</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/expand.grid.html">expand.grid</a></span><span class="op">(</span></span>
<span>  CP_cm <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/seq.html">seq</a></span><span class="op">(</span>from <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/Extremes.html">min</a></span><span class="op">(</span><span class="va">dados</span><span class="op">$</span><span class="va">CP_cm</span><span class="op">)</span>,</span>
<span>              to <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/Extremes.html">max</a></span><span class="op">(</span><span class="va">dados</span><span class="op">$</span><span class="va">CP_cm</span><span class="op">)</span>,</span>
<span>              length.out <span class="op">=</span> <span class="fl">1000</span><span class="op">)</span>,</span>
<span>  sexo <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"FEMEA"</span>,<span class="st">"MACHO"</span><span class="op">)</span></span>
<span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Limites observados para cada sexo</span></span>
<span><span class="co"># (evita extrapolar além dos dados)</span></span>
<span><span class="va">FEMEA_var</span> <span class="op">&lt;-</span> <span class="va">dados</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">sexo</span> <span class="op">==</span> <span class="st">"FEMEA"</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarise</a></span><span class="op">(</span>min <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/Extremes.html">min</a></span><span class="op">(</span><span class="va">CP_cm</span><span class="op">)</span>,</span>
<span>            max <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/Extremes.html">max</a></span><span class="op">(</span><span class="va">CP_cm</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="va">MACHO_var</span> <span class="op">&lt;-</span> <span class="va">dados</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">sexo</span> <span class="op">==</span> <span class="st">"MACHO"</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarise</a></span><span class="op">(</span>min <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/Extremes.html">min</a></span><span class="op">(</span><span class="va">CP_cm</span><span class="op">)</span>,</span>
<span>            max <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/Extremes.html">max</a></span><span class="op">(</span><span class="va">CP_cm</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="va">NewData_3</span> <span class="op">&lt;-</span> <span class="va">NewData_</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu">dplyr</span><span class="fu">::</span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span></span>
<span>    Range <span class="op">=</span> <span class="fu">dplyr</span><span class="fu">::</span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/case-and-replace-when.html">case_when</a></span><span class="op">(</span></span>
<span>      <span class="va">sexo</span> <span class="op">==</span> <span class="st">"FEMEA"</span> <span class="op">&amp;</span></span>
<span>        <span class="va">CP_cm</span> <span class="op">&gt;=</span> <span class="va">FEMEA_var</span><span class="op">$</span><span class="va">min</span> <span class="op">&amp;</span></span>
<span>        <span class="va">CP_cm</span> <span class="op">&lt;=</span> <span class="va">FEMEA_var</span><span class="op">$</span><span class="va">max</span> <span class="op">~</span> <span class="st">"Good"</span>,</span>
<span>      </span>
<span>      <span class="va">sexo</span> <span class="op">==</span> <span class="st">"MACHO"</span> <span class="op">&amp;</span></span>
<span>        <span class="va">CP_cm</span> <span class="op">&gt;=</span> <span class="va">MACHO_var</span><span class="op">$</span><span class="va">min</span> <span class="op">&amp;</span></span>
<span>        <span class="va">CP_cm</span> <span class="op">&lt;=</span> <span class="va">MACHO_var</span><span class="op">$</span><span class="va">max</span> <span class="op">~</span> <span class="st">"Good"</span></span>
<span>    <span class="op">)</span></span>
<span>  <span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu">dplyr</span><span class="fu">::</span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="op">!</span><span class="fu"><a href="https://rdrr.io/r/base/NA.html">is.na</a></span><span class="op">(</span><span class="va">Range</span><span class="op">)</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu">dplyr</span><span class="fu">::</span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="op">-</span><span class="va">Range</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Predições do modelo</span></span>
<span><span class="va">Pred_2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/predict.html">predict</a></span><span class="op">(</span><span class="va">lm2</span>, <span class="va">NewData_3</span>, se.fit <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span>
<span></span>
<span><span class="va">NewData_2</span> <span class="op">&lt;-</span> <span class="va">NewData_3</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>response <span class="op">=</span> <span class="va">Pred_2</span><span class="op">$</span><span class="va">fit</span>,</span>
<span>         se.fit <span class="op">=</span> <span class="va">Pred_2</span><span class="op">$</span><span class="va">se.fit</span>,</span>
<span>         Upr <span class="op">=</span> <span class="va">response</span> <span class="op">+</span> <span class="fl">1.96</span> <span class="op">*</span> <span class="va">se.fit</span>,</span>
<span>         Lwr <span class="op">=</span> <span class="va">response</span> <span class="op">-</span> <span class="fl">1.96</span> <span class="op">*</span> <span class="va">se.fit</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Apenas as curvas ajustadas</span></span>
<span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_ribbon.html">geom_ribbon</a></span><span class="op">(</span>data <span class="op">=</span> <span class="va">NewData_2</span>,</span>
<span>              <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">CP_cm</span>,</span>
<span>                  ymin <span class="op">=</span> <span class="va">Lwr</span>,</span>
<span>                  ymax <span class="op">=</span> <span class="va">Upr</span>,</span>
<span>                  fill <span class="op">=</span> <span class="va">sexo</span><span class="op">)</span>,</span>
<span>              alpha <span class="op">=</span> <span class="fl">0.30</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_path.html">geom_line</a></span><span class="op">(</span>data <span class="op">=</span> <span class="va">NewData_2</span>,</span>
<span>            <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">CP_cm</span>,</span>
<span>                y <span class="op">=</span> <span class="va">response</span>,</span>
<span>                colour <span class="op">=</span> <span class="va">sexo</span><span class="op">)</span>,</span>
<span>            linewidth <span class="op">=</span> <span class="fl">1.2</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_manual.html">scale_colour_manual</a></span><span class="op">(</span>values <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"darkcyan"</span>,<span class="st">"darkorange"</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_manual.html">scale_fill_manual</a></span><span class="op">(</span>values <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"darkcyan"</span>,<span class="st">"darkorange"</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>x <span class="op">=</span> <span class="st">"Comprimento padrão (cm)"</span>,</span>
<span>       y <span class="op">=</span> <span class="st">"Peso da gônada previsto (g)"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_classic</a></span><span class="op">(</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Dados observados e modelo ajustado</span></span>
<span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span>data <span class="op">=</span> <span class="va">dados</span>,</span>
<span>             <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">CP_cm</span>,</span>
<span>                 y <span class="op">=</span> <span class="va">Pgon_g</span>,</span>
<span>                 colour <span class="op">=</span> <span class="va">sexo</span><span class="op">)</span>,</span>
<span>             alpha <span class="op">=</span> <span class="fl">0.5</span>,</span>
<span>             size <span class="op">=</span> <span class="fl">2</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_ribbon.html">geom_ribbon</a></span><span class="op">(</span>data <span class="op">=</span> <span class="va">NewData_2</span>,</span>
<span>              <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">CP_cm</span>,</span>
<span>                  ymin <span class="op">=</span> <span class="va">Lwr</span>,</span>
<span>                  ymax <span class="op">=</span> <span class="va">Upr</span>,</span>
<span>                  fill <span class="op">=</span> <span class="va">sexo</span><span class="op">)</span>,</span>
<span>              alpha <span class="op">=</span> <span class="fl">0.25</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_path.html">geom_line</a></span><span class="op">(</span>data <span class="op">=</span> <span class="va">NewData_2</span>,</span>
<span>            <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">CP_cm</span>,</span>
<span>                y <span class="op">=</span> <span class="va">response</span>,</span>
<span>                colour <span class="op">=</span> <span class="va">sexo</span><span class="op">)</span>,</span>
<span>            linewidth <span class="op">=</span> <span class="fl">1.2</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_manual.html">scale_colour_manual</a></span><span class="op">(</span>values <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"darkcyan"</span>,<span class="st">"darkorange"</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_manual.html">scale_fill_manual</a></span><span class="op">(</span>values <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"darkcyan"</span>,<span class="st">"darkorange"</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>x <span class="op">=</span> <span class="st">"Comprimento padrão (cm)"</span>,</span>
<span>       y <span class="op">=</span> <span class="st">"Peso da gônada (g)"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_classic</a></span><span class="op">(</span><span class="op">)</span></span></code></pre></div>
<pre><code>##  [1] "CT_cm"    "PT_g"     "CP_cm"    "Ctubo_cm" "PC_g"     "p_PT"    
##  [7] "Pest_g"   "Cest_cm"  "gr_est"   "ir_est"   "Pint_g"   "Cint_cm" 
## [13] "gr_int"   "ir_int"   "Pgon_g"   "Cgon_cm"  "emg"      "ig"      
## [19] "mes"      "periodo"  "estação"  "sexo"     "sexo2"   
## 
## FEMEA MACHO 
##    21    39 
## [1] "MACHO" "FEMEA"
## 
## Call:
## lm(formula = Pgon_g ~ sexo * CP_cm, data = dados)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -2.7401 -0.3473 -0.2079  0.3214  5.6282 
## 
## Coefficients:
##                 Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)     -6.73940    1.69138  -3.985 0.000197 ***
## sexoMACHO        6.18466    2.24380   2.756 0.007875 ** 
## CP_cm            0.41581    0.06933   5.998 1.53e-07 ***
## sexoMACHO:CP_cm -0.36462    0.08640  -4.220 9.03e-05 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 1.296 on 56 degrees of freedom
## Multiple R-squared:  0.5956, Adjusted R-squared:  0.5739 
## F-statistic: 27.49 on 3 and 56 DF,  p-value: 4.621e-11</code></pre>
<p><img src="fundamentos_de_ecologia_numerica_files/figure-html/unnamed-chunk-170-1.png" alt="" width="672"><img src="fundamentos_de_ecologia_numerica_files/figure-html/unnamed-chunk-170-2.png" alt="" width="672"><img src="fundamentos_de_ecologia_numerica_files/figure-html/unnamed-chunk-170-3.png" alt="" width="672"><img src="fundamentos_de_ecologia_numerica_files/figure-html/unnamed-chunk-170-4.png" alt="" width="672"><img src="fundamentos_de_ecologia_numerica_files/figure-html/unnamed-chunk-170-5.png" alt="" width="672"></p>
<p>Como há uma interação significativa (sexo × CP_cm, p &lt; 0,001), esse gráfico é especialmente interessante porque mostra que as inclinações das retas são diferentes entre machos e fêmeas, e isso é justamente o que o termo de interação está testando. Em vez de interpretar apenas a tabela de coeficientes, o gráfico permite visualizar como a relação entre comprimento e peso da gônada muda entre os sexos. Isso segue exatamente a abordagem adotada no tutorial que você está utilizando.</p>
<p>Hoje é mais comum usar o pacote <code>emmeans</code> para interpretar modelos com interações. Além de <code>summary(lm2)</code>, podemos fazer:</p>
<div class="sourceCode" id="cb286"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://rvlenth.github.io/emmeans/">emmeans</a></span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rvlenth.github.io/emmeans/reference/emmeans.html">emmeans</a></span><span class="op">(</span><span class="va">lm2</span>, <span class="va">pairwise</span> <span class="op">~</span> <span class="va">sexo</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rvlenth.github.io/emmeans/reference/emtrends.html">emtrends</a></span><span class="op">(</span><span class="va">lm2</span>, <span class="va">pairwise</span> <span class="op">~</span> <span class="va">sexo</span>, var <span class="op">=</span> <span class="st">"CP_cm"</span><span class="op">)</span></span></code></pre></div>
<pre><code>## $emmeans
##  sexo  emmean    SE df lower.CL upper.CL
##  FEMEA  4.414 0.342 56    3.729     5.10
##  MACHO  0.818 0.221 56    0.375     1.26
## 
## Confidence level used: 0.95 
## 
## $contrasts
##  contrast      estimate    SE df t.ratio p.value
##  FEMEA - MACHO      3.6 0.407 56   8.828 &lt;0.0001
## 
## 
## $emtrends
##  sexo  CP_cm.trend     SE df lower.CL upper.CL
##  FEMEA      0.4158 0.0693 56   0.2769    0.555
##  MACHO      0.0512 0.0516 56  -0.0521    0.154
## 
## Confidence level used: 0.95 
## 
## $contrasts
##  contrast      estimate     SE df t.ratio p.value
##  FEMEA - MACHO    0.365 0.0864 56   4.220 &lt;0.0001</code></pre>
<p>O primeiro compara as médias ajustadas entre os sexos (quando apropriado) e o segundo testa formalmente se as inclinações das retas diferem entre machos e fêmeas, que é exatamente a hipótese representada pelo termo de interação sexo:CP_cm. Isso complementa a interpretação gráfica apresentada.</p>
<pre><code>plot(univ$CP_cm,
     univ$CT_cm,
     pch = 16,
     xlab = "Comprimento padrão (cm)",
     ylab = "Comprimento total (cm)")

modelo &lt;- glm(CT_cm ~ CP_cm,
              family = gaussian,
              data = univ)

summary(modelo)

modelo &lt;- lm(CT_cm ~ CP_cm,
             data = univ)

novo &lt;- data.frame(
  CP_cm = seq(min(univ$CP_cm),
              max(univ$CP_cm),
              length.out = 200)
)

pred &lt;- predict(modelo,
                newdata = novo,
                se.fit = TRUE)

novo$fit &lt;- pred$fit
novo$lwr &lt;- pred$fit - 1.96 * pred$se.fit
novo$upr &lt;- pred$fit + 1.96 * pred$se.fit

plot(univ$CP_cm,
     univ$CT_cm,
     pch = 16,
     xlab = "Comprimento padrão (cm)",
     ylab = "Comprimento total (cm)")

polygon(c(novo$CP_cm,
          rev(novo$CP_cm)),
        c(novo$lwr,
          rev(novo$upr)),
        col = "grey85",
        border = NA)

lines(novo$CP_cm,
      novo$fit,
      lwd = 2)

par(mfrow = c(2,2))
plot(modelo)
par(mfrow = c(1,1))

summary(modelo)

coef(glm(CT_cm ~ CP_cm,
         family = gaussian,
         data = univ))

coef(lm(CT_cm ~ CP_cm,
        data = univ))

##############

t.test(CP_cm ~ periodo,
       data = univ)

modelo &lt;- glm(CP_cm ~ periodo,
              family = gaussian,
              data = univ)

summary(modelo)

modelo &lt;- lm(CP_cm ~ periodo,
             data = univ)

summary(modelo)

boxplot(CP_cm ~ periodo,
        data = univ,
        col = "lightgray",
        xlab = "Sex",
        ylab = "Standard length (cm)")

stripchart(CP_cm ~ periodo,
           data = univ,
           vertical = TRUE,
           method = "jitter",
           pch = 16,
           xlab = "Sex",
           ylab = "Standard length (cm)")

aggregate(CP_cm ~ periodo,
          data = univ,
          mean)

predict(modelo)</code></pre>
</div>
<div id="exemplo-2-1" class="section level4" number="15.1.1.1">
<h4>
<span class="header-section-number">15.1.1.1</span> Exemplo 2<a class="anchor" aria-label="anchor" href="#exemplo-2-1"><i class="fas fa-link"></i></a>
</h4>
</div>
</div>
</div>
<div id="organização-básica-7" class="section level2" number="15.2">
<h2>
<span class="header-section-number">15.2</span> Organização básica<a class="anchor" aria-label="anchor" href="#organiza%C3%A7%C3%A3o-b%C3%A1sica-7"><i class="fas fa-link"></i></a>
</h2>
<div id="limpando-a-memória-5" class="section level4 unnumbered">
<h4>Limpando a memória<a class="anchor" aria-label="anchor" href="#limpando-a-mem%C3%B3ria-5"><i class="fas fa-link"></i></a>
</h4>
<div class="sourceCode" id="cb289"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/grDevices/dev.html">dev.off</a></span><span class="op">(</span><span class="op">)</span> <span class="co">#apaga os graficos, se houver algum</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/rm.html">rm</a></span><span class="op">(</span>list<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/ls.html">ls</a></span><span class="op">(</span>all<span class="op">=</span><span class="cn">TRUE</span><span class="op">)</span><span class="op">)</span> <span class="co">#limpa a memória</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/cat.html">cat</a></span><span class="op">(</span><span class="st">"\014"</span><span class="op">)</span> <span class="co">#limpa o console </span></span>
<span><span class="co">#options(scipen = 999) #sem notação científica</span></span></code></pre></div>
</div>
<div id="organizando-os-dados-2" class="section level3" number="15.2.1">
<h3>
<span class="header-section-number">15.2.1</span> Organizando os dados<a class="anchor" aria-label="anchor" href="#organizando-os-dados-2"><i class="fas fa-link"></i></a>
</h3>
<div class="sourceCode" id="cb290"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">anovas</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/utils/read.table.html">read.csv</a></span><span class="op">(</span><span class="st">"t_anovas.csv"</span>,</span>
<span>                   sep <span class="op">=</span> <span class="st">";"</span>, dec <span class="op">=</span> <span class="st">"."</span>,</span>
<span>                   row.names <span class="op">=</span> <span class="fl">1</span>,</span>
<span>                   header <span class="op">=</span> <span class="cn">TRUE</span>,</span>
<span>                   na.strings <span class="op">=</span> <span class="cn">NA</span><span class="op">)</span></span>
<span><span class="va">anovas</span> <span class="op">&lt;-</span> <span class="va">anovas</span><span class="op">[</span>, <span class="op">-</span><span class="fl">1</span><span class="op">]</span></span>
<span><span class="va">anovas</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/cbind.html">cbind</a></span><span class="op">(</span>Grupos <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/colnames.html">rownames</a></span><span class="op">(</span><span class="va">anovas</span><span class="op">)</span>, <span class="va">anovas</span><span class="op">)</span></span>
<span><span class="va">anovas</span></span>
<span><span class="va">grps</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/substr.html">substr</a></span><span class="op">(</span><span class="va">anovas</span><span class="op">[</span>, <span class="fl">1</span><span class="op">]</span>, <span class="fl">1</span>,<span class="fl">1</span><span class="op">)</span></span>
<span><span class="va">grps</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://dplyr.tidyverse.org">dplyr</a></span><span class="op">)</span></span>
<span><span class="va">testt</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span><span class="va">anovas</span>, Grupos <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="va">grps</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="va">testt</span></span>
<span></span>
<span><span class="co">###SALVANDO MATRIZ FINAL ANOVAS----</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/write.table.html">write.table</a></span><span class="op">(</span><span class="va">testt</span>, <span class="st">"t_test.csv"</span>,</span>
<span>            sep <span class="op">=</span> <span class="st">";"</span>, dec <span class="op">=</span> <span class="st">"."</span>, <span class="co">#"\t",</span></span>
<span>            row.names <span class="op">=</span> <span class="cn">TRUE</span>,</span>
<span>            quote <span class="op">=</span> <span class="cn">TRUE</span>,</span>
<span>            append <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span>
<span><span class="va">testt</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/utils/read.table.html">read.csv</a></span><span class="op">(</span><span class="st">"t_test.csv"</span>,</span>
<span>                   sep <span class="op">=</span> <span class="st">";"</span>, dec <span class="op">=</span> <span class="st">"."</span>,</span>
<span>                   row.names <span class="op">=</span> <span class="fl">1</span>,</span>
<span>                   header <span class="op">=</span> <span class="cn">TRUE</span>,</span>
<span>                   na.strings <span class="op">=</span> <span class="cn">NA</span><span class="op">)</span></span>
<span><span class="va">testt</span></span></code></pre></div>
<pre><code>##            Grupos     Srare        dens  S
## S-R-CI-1 S-R-CI-1  5.000000   1.7857143  5
## S-R-CI-2 S-R-CI-2 12.719603  86.3690476 13
## S-R-CI-3 S-R-CI-3 15.057283 257.4404762 21
## S-R-CI-4 S-R-CI-4 16.000000  57.9761905 16
## B-A-SA-1 B-A-SA-1  2.000000   0.2976190  2
## B-A-SA-2 B-A-SA-2  3.000000   0.8333333  3
## B-A-SA-3 B-A-SA-3  6.000000   0.8928571  6
## B-A-SA-4 B-A-SA-4  3.000000   2.3809524  3
## B-A-MU-2 B-A-MU-2  1.000000   0.1785714  1
## B-A-MU-3 B-A-MU-3  2.000000   0.2380952  2
## B-A-MU-4 B-A-MU-4  2.000000   0.7142857  2
## B-R-EP-2 B-R-EP-2  3.920860  82.7380952  4
## B-R-EP-3 B-R-EP-3  5.000000  26.4880952  5
## B-R-EP-4 B-R-EP-4  2.955224  79.7619048  3
## S-A-RE-1 S-A-RE-1 13.171426  95.5952381 14
## S-A-RE-2 S-A-RE-2  7.000000  64.3452381  7
## S-A-RE-3 S-A-RE-3 19.932602  80.8333333 20
## S-A-RE-4 S-A-RE-4 11.638514 103.6904762 12
## S-R-SE-1 S-R-SE-1  7.000000   1.8452381  7
## S-R-SE-2 S-R-SE-2  3.000000  75.4166667  3
## S-R-SE-3 S-R-SE-3  3.763162 249.4642857  4
## S-R-SE-4 S-R-SE-4  8.603085 406.6071429 11
##  [1] "S" "S" "S" "S" "B" "B" "B" "B" "B" "B" "B" "B" "B" "B" "S" "S" "S" "S" "S"
## [20] "S" "S" "S"
##          Grupos     Srare        dens  S
## S-R-CI-1      S  5.000000   1.7857143  5
## S-R-CI-2      S 12.719603  86.3690476 13
## S-R-CI-3      S 15.057283 257.4404762 21
## S-R-CI-4      S 16.000000  57.9761905 16
## B-A-SA-1      B  2.000000   0.2976190  2
## B-A-SA-2      B  3.000000   0.8333333  3
## B-A-SA-3      B  6.000000   0.8928571  6
## B-A-SA-4      B  3.000000   2.3809524  3
## B-A-MU-2      B  1.000000   0.1785714  1
## B-A-MU-3      B  2.000000   0.2380952  2
## B-A-MU-4      B  2.000000   0.7142857  2
## B-R-EP-2      B  3.920860  82.7380952  4
## B-R-EP-3      B  5.000000  26.4880952  5
## B-R-EP-4      B  2.955224  79.7619048  3
## S-A-RE-1      S 13.171426  95.5952381 14
## S-A-RE-2      S  7.000000  64.3452381  7
## S-A-RE-3      S 19.932602  80.8333333 20
## S-A-RE-4      S 11.638514 103.6904762 12
## S-R-SE-1      S  7.000000   1.8452381  7
## S-R-SE-2      S  3.000000  75.4166667  3
## S-R-SE-3      S  3.763162 249.4642857  4
## S-R-SE-4      S  8.603085 406.6071429 11
##          Grupos     Srare        dens  S
## S-R-CI-1      S  5.000000   1.7857143  5
## S-R-CI-2      S 12.719603  86.3690476 13
## S-R-CI-3      S 15.057283 257.4404762 21
## S-R-CI-4      S 16.000000  57.9761905 16
## B-A-SA-1      B  2.000000   0.2976190  2
## B-A-SA-2      B  3.000000   0.8333333  3
## B-A-SA-3      B  6.000000   0.8928571  6
## B-A-SA-4      B  3.000000   2.3809524  3
## B-A-MU-2      B  1.000000   0.1785714  1
## B-A-MU-3      B  2.000000   0.2380952  2
## B-A-MU-4      B  2.000000   0.7142857  2
## B-R-EP-2      B  3.920860  82.7380952  4
## B-R-EP-3      B  5.000000  26.4880952  5
## B-R-EP-4      B  2.955224  79.7619048  3
## S-A-RE-1      S 13.171426  95.5952381 14
## S-A-RE-2      S  7.000000  64.3452381  7
## S-A-RE-3      S 19.932602  80.8333333 20
## S-A-RE-4      S 11.638514 103.6904762 12
## S-R-SE-1      S  7.000000   1.8452381  7
## S-R-SE-2      S  3.000000  75.4166667  3
## S-R-SE-3      S  3.763162 249.4642857  4
## S-R-SE-4      S  8.603085 406.6071429 11</code></pre>
</div>
<div id="anova-vs-glm" class="section level3" number="15.2.2">
<h3>
<span class="header-section-number">15.2.2</span> ANOVA vs GLM<a class="anchor" aria-label="anchor" href="#anova-vs-glm"><i class="fas fa-link"></i></a>
</h3>
<p>Suponha que você queira comparar a riqueza (Srare) entre grupos (Grupos):</p>
<div class="sourceCode" id="cb292"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">dados</span> <span class="op">&lt;-</span> <span class="va">anovas</span></span>
<span><span class="va">modelo_aov</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/aov.html">aov</a></span><span class="op">(</span><span class="va">Srare</span> <span class="op">~</span> <span class="va">Grupos</span>, data <span class="op">=</span> <span class="va">dados</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">modelo_aov</span><span class="op">)</span></span></code></pre></div>
<pre><code>##             Df Sum Sq Mean Sq
## Grupos      21  612.4   29.16</code></pre>
<p>ou</p>
<div class="sourceCode" id="cb294"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">modelo_lm</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">Srare</span> <span class="op">~</span> <span class="va">Grupos</span>, data <span class="op">=</span> <span class="va">dados</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/anova.html">anova</a></span><span class="op">(</span><span class="va">modelo_lm</span><span class="op">)</span></span></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Response: Srare
##           Df Sum Sq Mean Sq F value Pr(&gt;F)
## Grupos    21 612.37  29.161     NaN    NaN
## Residuals  0   0.00     NaN</code></pre>
<ol start="2" style="list-style-type: decimal">
<li>O mesmo modelo usando GLM</li>
</ol>
<div class="sourceCode" id="cb296"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">modelo_glm</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/glm.html">glm</a></span><span class="op">(</span><span class="va">Srare</span> <span class="op">~</span> <span class="va">Grupos</span>,</span>
<span>                  data <span class="op">=</span> <span class="va">dados</span>,</span>
<span>                  family <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/family.html">gaussian</a></span><span class="op">(</span>link <span class="op">=</span> <span class="st">"identity"</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/anova.html">anova</a></span><span class="op">(</span><span class="va">modelo_glm</span>, test <span class="op">=</span> <span class="st">"F"</span><span class="op">)</span></span></code></pre></div>
<pre><code>## Analysis of Deviance Table
## 
## Model: gaussian, link: identity
## 
## Response: Srare
## 
## Terms added sequentially (first to last)
## 
## 
##        Df Deviance Resid. Df Resid. Dev
## NULL                      21     612.37
## Grupos 21   612.37         0       0.00</code></pre>
<p>ou</p>
<div class="sourceCode" id="cb298"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">modelo_glm</span><span class="op">)</span></span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = Srare ~ Grupos, family = gaussian(link = "identity"), 
##     data = dados)
## 
## Coefficients:
##                Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept)       1.000        NaN     NaN      NaN
## GruposB-A-MU-3    1.000        NaN     NaN      NaN
## GruposB-A-MU-4    1.000        NaN     NaN      NaN
## GruposB-A-SA-1    1.000        NaN     NaN      NaN
## GruposB-A-SA-2    2.000        NaN     NaN      NaN
## GruposB-A-SA-3    5.000        NaN     NaN      NaN
## GruposB-A-SA-4    2.000        NaN     NaN      NaN
## GruposB-R-EP-2    2.921        NaN     NaN      NaN
## GruposB-R-EP-3    4.000        NaN     NaN      NaN
## GruposB-R-EP-4    1.955        NaN     NaN      NaN
## GruposS-A-RE-1   12.171        NaN     NaN      NaN
## GruposS-A-RE-2    6.000        NaN     NaN      NaN
## GruposS-A-RE-3   18.933        NaN     NaN      NaN
## GruposS-A-RE-4   10.639        NaN     NaN      NaN
## GruposS-R-CI-1    4.000        NaN     NaN      NaN
## GruposS-R-CI-2   11.720        NaN     NaN      NaN
## GruposS-R-CI-3   14.057        NaN     NaN      NaN
## GruposS-R-CI-4   15.000        NaN     NaN      NaN
## GruposS-R-SE-1    6.000        NaN     NaN      NaN
## GruposS-R-SE-2    2.000        NaN     NaN      NaN
## GruposS-R-SE-3    2.763        NaN     NaN      NaN
## GruposS-R-SE-4    7.603        NaN     NaN      NaN
## 
## (Dispersion parameter for gaussian family taken to be NaN)
## 
##     Null deviance: 6.1237e+02  on 21  degrees of freedom
## Residual deviance: 1.5560e-27  on  0  degrees of freedom
## AIC: -1317.6
## 
## Number of Fisher Scoring iterations: 1</code></pre>
<p>Esse modelo é matematicamente equivalente à ANOVA.</p>
<div class="sourceCode" id="cb300"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/options.html">options</a></span><span class="op">(</span>scipen <span class="op">=</span> <span class="fl">999</span><span class="op">)</span></span>
<span></span>
<span><span class="co">#packageVersion("rlang")</span></span>
<span><span class="co">#remove.packages("rlang")</span></span>
<span><span class="co">#install.packages("rlang")</span></span>
<span><span class="co">#packageVersion("rlang")</span></span>
<span><span class="co">#install.packages("devtools")</span></span>
<span><span class="co">#devtools::install_github("dustinfife/flexplot")</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va">flexplot</span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://ggplot2.tidyverse.org">ggplot2</a></span><span class="op">)</span></span>
<span></span>
<span><span class="co"># A Numeric v. Numeric example (simple regression)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/flexplot/man/flexplot.html">flexplot</a></span><span class="op">(</span><span class="va">Srare</span> <span class="op">~</span> <span class="fl">1</span>, data <span class="op">=</span> <span class="va">dados</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/flexplot/man/flexplot.html">flexplot</a></span><span class="op">(</span><span class="va">S</span> <span class="op">~</span> <span class="fl">1</span>, data <span class="op">=</span> <span class="va">dados</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/flexplot/man/flexplot.html">flexplot</a></span><span class="op">(</span><span class="va">Srare</span> <span class="op">~</span> <span class="va">S</span>, data <span class="op">=</span> <span class="va">dados</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/flexplot/man/flexplot.html">flexplot</a></span><span class="op">(</span><span class="va">Srare</span> <span class="op">~</span> <span class="va">S</span>,</span>
<span>         data <span class="op">=</span> <span class="va">dados</span>,</span>
<span>         method <span class="op">=</span> <span class="st">"lm"</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">Srare</span> <span class="op">~</span> <span class="va">S</span>, data <span class="op">=</span> <span class="va">dados</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/flexplot/man/flexplot.html">flexplot</a></span><span class="op">(</span><span class="va">Srare</span> <span class="op">~</span> <span class="va">S</span>,</span>
<span>         data <span class="op">=</span> <span class="va">dados</span>,</span>
<span>         method <span class="op">=</span> <span class="st">"lm"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/lims.html">xlim</a></span><span class="op">(</span><span class="fl">0</span>, <span class="fl">25</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_smooth.html">geom_smooth</a></span><span class="op">(</span>method <span class="op">=</span> <span class="st">"lm"</span>, fullrange <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span>
<span></span>
<span><span class="va">model</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">Srare</span> <span class="op">~</span> <span class="va">S</span>,</span>
<span>            data <span class="op">=</span> <span class="va">dados</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">model</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/flexplot/man/estimates.html">estimates</a></span><span class="op">(</span><span class="va">model</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># note that the "significance" of the correlation is the</span></span>
<span><span class="co"># same thing as the p-value for the slope of the lm</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/cor.test.html">cor.test</a></span><span class="op">(</span><span class="va">dados</span><span class="op">$</span><span class="va">Srare</span>,</span>
<span>         <span class="va">dados</span><span class="op">$</span><span class="va">S</span><span class="op">)</span></span>
<span></span>
<span></span>
<span><span class="co"># A Categorical v. Numeric example (previous name t-test)</span></span>
<span></span>
<span><span class="va">dados</span> <span class="op">&lt;-</span> <span class="va">testt</span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/flexplot/man/flexplot.html">flexplot</a></span><span class="op">(</span><span class="va">Srare</span> <span class="op">~</span> <span class="fl">1</span>,</span>
<span>         data <span class="op">=</span> <span class="va">dados</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/flexplot/man/flexplot.html">flexplot</a></span><span class="op">(</span><span class="va">Grupos</span> <span class="op">~</span> <span class="fl">1</span>,</span>
<span>         data <span class="op">=</span> <span class="va">dados</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/flexplot/man/flexplot.html">flexplot</a></span><span class="op">(</span><span class="va">Srare</span> <span class="op">~</span> <span class="va">Grupos</span>,</span>
<span>         data <span class="op">=</span> <span class="va">dados</span><span class="op">)</span></span>
<span></span>
<span><span class="va">modelt</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">Srare</span> <span class="op">~</span> <span class="va">Grupos</span>,</span>
<span>             data <span class="op">=</span> <span class="va">dados</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">modelt</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/flexplot/man/estimates.html">estimates</a></span><span class="op">(</span><span class="va">modelt</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># proof that the GLM method results in the same thing as a t-test</span></span>
<span></span>
<span><span class="va">t</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/t.test.html">t.test</a></span><span class="op">(</span><span class="va">Srare</span> <span class="op">~</span> <span class="va">Grupos</span>,</span>
<span>            data <span class="op">=</span> <span class="va">dados</span>,</span>
<span>            var.equal <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span>
<span><span class="va">t</span></span>
<span></span>
<span><span class="co">#install.packages("effectsize")</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://easystats.github.io/effectsize/">effectsize</a></span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://easystats.github.io/effectsize/reference/cohens_d.html">cohens_d</a></span><span class="op">(</span><span class="va">Srare</span> <span class="op">~</span> <span class="va">Grupos</span>,</span>
<span>         data <span class="op">=</span> <span class="va">dados</span><span class="op">)</span></span>
<span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://personality-project.org/r/psych/">psych</a></span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/psych/man/cohen.d.html">cohen.d</a></span><span class="op">(</span><span class="va">Srare</span> <span class="op">~</span> <span class="va">Grupos</span>,</span>
<span>         data <span class="op">=</span> <span class="va">dados</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Uma forma de calcular d a partir do valor de t e dos graus de liberdade</span></span>
<span></span>
<span><span class="fu"><a href="https://easystats.github.io/effectsize/reference/t_to_r.html">t_to_d</a></span><span class="op">(</span><span class="va">t</span><span class="op">$</span><span class="va">statistic</span>, <span class="va">t</span><span class="op">$</span><span class="va">parameter</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Uma forma de calcular o tamanho de efeito r a partir do valor de t e dos graus de liberdade</span></span>
<span></span>
<span><span class="fu"><a href="https://easystats.github.io/effectsize/reference/t_to_r.html">t_to_r</a></span><span class="op">(</span><span class="va">t</span><span class="op">$</span><span class="va">statistic</span>, <span class="va">t</span><span class="op">$</span><span class="va">parameter</span><span class="op">)</span></span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Srare ~ S, data = dados)
## 
## Coefficients:
## (Intercept)            S  
##      0.4760       0.8737  
## 
## 
## Call:
## lm(formula = Srare ~ S, data = dados)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -3.7667 -0.2195 -0.0736  0.4080  1.9823 
## 
## Coefficients:
##             Estimate Std. Error t value           Pr(&gt;|t|)    
## (Intercept)   0.4760     0.3835   1.241              0.229    
## S             0.8737     0.0403  21.682 0.0000000000000023 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 1.118 on 20 degrees of freedom
## Multiple R-squared:  0.9592, Adjusted R-squared:  0.9572 
## F-statistic: 470.1 on 1 and 20 DF,  p-value: 0.0000000000000023
## 
## Model R squared:
## 0.959 (0.93, 0.99)
## 
## Semi-Partial R squared:
##     S 
## 0.959 
## Correlation:
##  0.979 
## 
## 
## Estimates for Numeric Variables = 
##     variables estimate lower upper std.estimate std.lower std.upper
## 1 (Intercept)     0.48 -0.28  1.23         0.00      0.00      0.00
## 2           S     0.87  0.79  0.95         0.98      0.89      1.07
## 
##  Pearson's product-moment correlation
## 
## data:  dados$Srare and dados$S
## t = 21.682, df = 20, p-value = 0.0000000000000023
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  0.9500773 0.9915604
## sample estimates:
##       cor 
## 0.9793833 
## 
## 
## Call:
## lm(formula = Srare ~ Grupos, data = dados)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -7.240 -1.975 -0.110  2.337  9.692 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)    3.088      1.291   2.392 0.026707 *  
## GruposS        7.153      1.748   4.092 0.000567 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 4.082 on 20 degrees of freedom
## Multiple R-squared:  0.4557, Adjusted R-squared:  0.4285 
## F-statistic: 16.75 on 1 and 20 DF,  p-value: 0.0005671
## 
## Model R squared:
## 0.456 (0.18, 0.73)
## 
## Semi-Partial R squared:
## Grupos 
##  0.456 
## 
## Estimates for Factors:
##   variables levels estimate lower upper
## 1    Grupos      B     3.09  0.39  5.78
## 2                S    10.24  7.78  12.7
## 
## 
## Mean Differences:
##   variables comparison difference lower upper cohens.d
## 1    Grupos        S-B       7.15     2 12.31     1.75
## 
##  Two Sample t-test
## 
## data:  Srare by Grupos
## t = -4.0922, df = 20, p-value = 0.0005671
## alternative hypothesis: true difference in means between group B and group S is not equal to 0
## 95 percent confidence interval:
##  -10.798979  -3.506749
## sample estimates:
## mean in group B mean in group S 
##        3.087608       10.240473 
## 
## Cohen's d |         95% CI
## --------------------------
## -1.75     | [-2.73, -0.74]
## 
## - Estimated using pooled SD.Call: cohen.d(x = Srare ~ Grupos, data = dados)
## Cohen d statistic of difference between two means
##       lower effect upper
## Srare  0.81   1.84  2.83
## 
## Multivariate (Mahalanobis) distance between groups
## [1] 1.8
## r equivalent of difference between two means
## Srare 
##  0.68 
## d     |         95% CI
## ----------------------
## -1.83 | [-2.86, -0.77]
## r     |         95% CI
## ----------------------
## -0.68 | [-0.82, -0.36]</code></pre>
<p><img src="fundamentos_de_ecologia_numerica_files/figure-html/unnamed-chunk-178-1.png" alt="" width="672"><img src="fundamentos_de_ecologia_numerica_files/figure-html/unnamed-chunk-178-2.png" alt="" width="672"><img src="fundamentos_de_ecologia_numerica_files/figure-html/unnamed-chunk-178-3.png" alt="" width="672"><img src="fundamentos_de_ecologia_numerica_files/figure-html/unnamed-chunk-178-4.png" alt="" width="672"><img src="fundamentos_de_ecologia_numerica_files/figure-html/unnamed-chunk-178-5.png" alt="" width="672"><img src="fundamentos_de_ecologia_numerica_files/figure-html/unnamed-chunk-178-6.png" alt="" width="672"><img src="fundamentos_de_ecologia_numerica_files/figure-html/unnamed-chunk-178-7.png" alt="" width="672"><img src="fundamentos_de_ecologia_numerica_files/figure-html/unnamed-chunk-178-8.png" alt="" width="672"></p>
</div>
</div>
<div id="material-de-apoio-8" class="section level2" number="15.3">
<h2>
<span class="header-section-number">15.3</span> Material de apoio<a class="anchor" aria-label="anchor" href="#material-de-apoio-8"><i class="fas fa-link"></i></a>
</h2>
</div>
<div id="teste-seus-conhecimentos-7" class="section level2" number="15.4">
<h2>
<span class="header-section-number">15.4</span> TESTE SEUS CONHECIMENTOS<a class="anchor" aria-label="anchor" href="#teste-seus-conhecimentos-7"><i class="fas fa-link"></i></a>
</h2>
<div class="infobox note">
<div class="center">
<p><strong>NOTA</strong></p>
</div>
<p>Baixe esse arquivo de atividade sobre correlação e regressão R (<a href="listas/.docx">LISTA DE EXERCÍCIOS</a>) e responda às questões. Se achar necessário, insira “chunks” de scripts do R, prints de tela ou cópias de gráficos, resultados ou mensagens de erro.</p>
</div>
<div class="infobox note">
<div class="center">
<p><strong>NOTA</strong></p>
</div>
<p>Baixe esse arquivo de exercício e resolva as questões no R (<a href="exerc/.R">Exercício 5</a>).</p>
</div>
</div>
<div id="apêndices-9" class="section level2 unnumbered">
<h2>Apêndices<a class="anchor" aria-label="anchor" href="#ap%C3%AAndices-9"><i class="fas fa-link"></i></a>
</h2>
</div>
<div id="sites-para-consulta-3" class="section level2 unnumbered">
<h2>Sites para consulta<a class="anchor" aria-label="anchor" href="#sites-para-consulta-3"><i class="fas fa-link"></i></a>
</h2>
<p><a href="https://stackoverflow.com/questions/31741742/how-to-identify-the-distribution-of-the-given-data-using-r" class="uri">https://stackoverflow.com/questions/31741742/how-to-identify-the-distribution-of-the-given-data-using-r</a><br><a href="https://stats.stackexchange.com/questions/132652/how-to-determine-which-distribution-fits-my-data-best" class="uri">https://stats.stackexchange.com/questions/132652/how-to-determine-which-distribution-fits-my-data-best</a><br><a href="https://www.r-bloggers.com/2015/11/correlation-and-linear-regression/" class="uri">https://www.r-bloggers.com/2015/11/correlation-and-linear-regression/</a><br><a href="https://bedeffinianrowedavies.com/statisticstutorials/introductionglms" class="uri">https://bedeffinianrowedavies.com/statisticstutorials/introductionglms</a></p>
</div>
<div id="script-limpo-6" class="section level2 unnumbered">
<h2>Script limpo<a class="anchor" aria-label="anchor" href="#script-limpo-6"><i class="fas fa-link"></i></a>
</h2>
<p>Aqui apresento o scrip na íntegra sem os textos ou outros comentários. Você pode copiar e colar no R para executa-lo. Lembre de remover os <span style="color:green"><code>#</code></span> ou <span style="color:green"><code>##</code></span> caso necessite executar essas linhas.</p>
</div>
<div id="referências-12" class="section level2 unnumbered">
<h2>Referências<a class="anchor" aria-label="anchor" href="#refer%C3%AAncias-12"><i class="fas fa-link"></i></a>
</h2>

</div>
</div>
<h3>Bibliografia Geral</h3>
<div id="refs" class="references csl-bib-body" entry-spacing="1">
<div id="ref-crawley2005" class="csl-entry">
CRAWLEY, M. J. <strong>Statistics: An Introduction using R</strong>. 1. ed. [s.l.] : Wiley, 2005. Disponível em: &lt;<a href="https://onlinelibrary.wiley.com/doi/book/10.1002/9781119941750">https://onlinelibrary.wiley.com/doi/book/10.1002/9781119941750</a>&gt;
</div>
<div id="ref-crawley2015" class="csl-entry">
CRAWLEY, M. J. <strong>Statistics: An Introduction Using R</strong>. 2. ed ed. Chichester: Wiley, 2015.
</div>
<div id="ref-davies2022" class="csl-entry">
DAVIES, B. F. R.; HOLMES, L.; BICKNELL, A.; ATTRILL, M. J.; SHEEHAN, E. V. A decade implementing ecosystem approach to fisheries management improves diversity of taxa and traits within a marine protected area in the UK. <strong>Diversity and Distributions</strong>, [s. l.], v. 28, n. 1, p. 173–188, 2022. Disponível em: &lt;<a href="https://onlinelibrary.wiley.com/doi/10.1111/ddi.13451">https://onlinelibrary.wiley.com/doi/10.1111/ddi.13451</a>&gt;
</div>
<div id="ref-davies2021" class="csl-entry">
DAVIES, B. F. R.; HOLMES, L.; REES, A.; ATTRILL, M. J.; CARTWRIGHT, A. Y.; SHEEHAN, E. V. Ecosystem Approach to Fisheries Management works -How switching from mobile to static fishing gear improves populations of fished and non<span>-</span>fished species inside a marine<span>-</span>protected area. <strong>Journal of Applied Ecology</strong>, [s. l.], v. 58, n. 11, p. 2463–2478, 2021. Disponível em: &lt;<a href="https://bedeffinianrowedavies.com/">https://bedeffinianrowedavies.com/</a>&gt;
</div>
<div id="ref-dunn2018" class="csl-entry">
DUNN, P. K.; SMYTH, G. K. <strong>Generalized Linear Models With Examples in R</strong>. New York, NY: Springer New York, 2018. Disponível em: &lt;<a href="http://link.springer.com/10.1007/978-1-4419-0118-7">http://link.springer.com/10.1007/978-1-4419-0118-7</a>&gt;
</div>
<div id="ref-faraway2016" class="csl-entry">
FARAWAY, J. J. <strong>Extending the Linear Model with R: Generalized Linear, Mixed Effects and Nonparametric Regression Models, Second Edition</strong>. 2nd ed ed. Boca Raton: CRC Press, 2016.
</div>
<div id="ref-mccullagh1989" class="csl-entry">
MCCULLAGH, P.; NELDER, J. A. <strong><a href="https://doi.org/10.1201/9780203753736">Generalized Linear Models</a></strong>. 2. ed. London, UK: Chapman; Hall, 1989.
</div>
<div id="ref-nelder1972" class="csl-entry">
NELDER, J. A.; WEDDERBURN, R. W. M. Generalized Linear Models. <strong>Journal of the Royal Statistical Society. Series A (General)</strong>, [s. l.], v. 135, n. 3, p. 370, 1972. Disponível em: &lt;<a href="https://www.jstor.org/stable/10.2307/2344614?origin=crossref">https://www.jstor.org/stable/10.2307/2344614?origin=crossref</a>&gt;
</div>
<div id="ref-sokal1995" class="csl-entry">
SOKAL, R. R.; ROHLF, F. J. <strong>Biometry: The Principles and Practice of Statistics in Biological Research</strong>. 3. ed. New York: W.H. Freeman; Company, 1995. Type: Book.
</div>
<div id="ref-zuur2009" class="csl-entry">
ZUUR, A. F.; IENO, E. N.; WALKER, N.; SAVELIEV, A. A.; SMITH, G. M. <strong>Mixed Effects Models and Extensions in Ecology with R</strong>. New York, NY: Springer New York, 2009. Disponível em: &lt;<a href="https://link.springer.com/10.1007/978-0-387-87458-6">https://link.springer.com/10.1007/978-0-387-87458-6</a>&gt;
</div>
</div>
  <div class="chapter-nav">
<div class="prev"><a href="regmul.html"><span class="header-section-number">14</span> R Módulo 6 - Regressão múltipla</a></div>
<div class="next"><a href="estrcom.html"><span class="header-section-number">16</span> R Módulo 8.1 - Estrutura da comunidade</a></div>
</div></main><div class="col-md-3 col-lg-2 d-none d-md-block sidebar sidebar-chapter">
    <nav id="toc" data-toggle="toc" aria-label="On this page"><h2>On this page</h2>
      <ul class="nav navbar-nav">
<li>
<a class="nav-link" href="#mlgs"><span class="header-section-number">15</span> R Módulo 7 - Modelos lineares generalizados (GLMs)</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#resumo-10">RESUMO</a></li>
<li><a class="nav-link" href="#apresenta%C3%A7%C3%A3o-10">Apresentação</a></li>
<li><a class="nav-link" href="#por-que-precisamos-de-modelos-lineares-generalizados"><span class="header-section-number">15.0.1</span> Por que precisamos de Modelos Lineares Generalizados?</a></li>
<li><a class="nav-link" href="#tipos-de-distribui%C3%A7%C3%A3o-em-glms"><span class="header-section-number">15.0.2</span> Tipos de distribuição em GLM’s</a></li>
<li><a class="nav-link" href="#escolha-da-fun%C3%A7%C3%A3o-de-liga%C3%A7%C3%A3o"><span class="header-section-number">15.0.3</span> Escolha da função de ligação</a></li>
</ul>
</li>
<li>
<a class="nav-link" href="#organiza%C3%A7%C3%A3o-b%C3%A1sica-6"><span class="header-section-number">15.1</span> Organização básica</a><ul class="nav navbar-nav"><li><a class="nav-link" href="#pacotes-do-m%C3%B3dulo-5"><span class="header-section-number">15.1.1</span> Pacotes do módulo</a></li></ul>
</li>
<li>
<a class="nav-link" href="#organiza%C3%A7%C3%A3o-b%C3%A1sica-7"><span class="header-section-number">15.2</span> Organização básica</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#organizando-os-dados-2"><span class="header-section-number">15.2.1</span> Organizando os dados</a></li>
<li><a class="nav-link" href="#anova-vs-glm"><span class="header-section-number">15.2.2</span> ANOVA vs GLM</a></li>
</ul>
</li>
<li><a class="nav-link" href="#material-de-apoio-8"><span class="header-section-number">15.3</span> Material de apoio</a></li>
<li><a class="nav-link" href="#teste-seus-conhecimentos-7"><span class="header-section-number">15.4</span> TESTE SEUS CONHECIMENTOS</a></li>
<li><a class="nav-link" href="#ap%C3%AAndices-9">Apêndices</a></li>
<li><a class="nav-link" href="#sites-para-consulta-3">Sites para consulta</a></li>
<li><a class="nav-link" href="#script-limpo-6">Script limpo</a></li>
<li><a class="nav-link" href="#refer%C3%AAncias-12">Referências</a></li>
</ul>

      <div class="book-extra">
        <ul class="list-unstyled">
          
        </ul>
</div>
    </nav>
</div>

</div>
</div> <!-- .container -->

<footer class="bg-primary text-light mt-5"><div class="container"><div class="row">

  <div class="col-12 col-md-6 mt-3">
    <p>"<strong>Fundamentos de Ecologia Numérica</strong>: Disciplina de Ecologia Numérica do Curso de Ciências Biológicas do Campus V da UEPB" was written by Prof. Elvio S. F. Medeiros, Laboratório de Ecologia, Universidade Estadual da Paraíba, Campus V, João Pessoa, PB. It was last built on Last updated: 08/08/2026 11:03:05.</p>
  </div>

  <div class="col-12 col-md-6 mt-3">
    <p>This book was built by the <a class="text-light" href="https://bookdown.org">bookdown</a> R package.</p>
  </div>

</div></div>
</footer><!-- dynamically load mathjax for compatibility with self-contained --><script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script><script type="text/x-mathjax-config">const popovers = document.querySelectorAll('a.footnote-ref[data-toggle="popover"]');
for (let popover of popovers) {
  const div = document.createElement('div');
  div.setAttribute('style', 'position: absolute; top: 0, left:0; width:0, height:0, overflow: hidden; visibility: hidden;');
  div.innerHTML = popover.getAttribute('data-content');

  var has_math = div.querySelector("span.math");
  if (has_math) {
    document.body.appendChild(div);
    MathJax.Hub.Queue(["Typeset", MathJax.Hub, div]);
    MathJax.Hub.Queue(function() {
      popover.setAttribute('data-content', div.innerHTML);
      document.body.removeChild(div);
    })
  }
}
</script>
</body>
</html>
