<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <title> 21 R Módulo 6 - Análise de outliers baseada no desvio padrão do centróide | Fundamentos de Ecologia Numérica</title>

    <meta name="author" content="Prof. Elvio S. F. Medeiros" />
    <meta name="author" content="Laboratório de Ecologia" />
    <meta name="author" content="Universidade Estadual da Paraíba" />
    <meta name="author" content="Campus V, João Pessoa, PB" />
  
   <meta name="description" content="…. The output format for this example is bookdown::gitbook." />
   <meta name="generator" content="placeholder" />
  <meta property="og:title" content=" 21 R Módulo 6 - Análise de outliers baseada no desvio padrão do centróide | Fundamentos de Ecologia Numérica" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="…. The output format for this example is bookdown::gitbook." />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content=" 21 R Módulo 6 - Análise de outliers baseada no desvio padrão do centróide | Fundamentos de Ecologia Numérica" />
  
  <meta name="twitter:description" content="…. The output format for this example is bookdown::gitbook." />
  
  <!-- JS -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/fuse.js/6.4.6/fuse.js" integrity="sha512-zv6Ywkjyktsohkbp9bb45V6tEMoWhzFzXis+LrMehmJZZSys19Yxf1dopHx7WzIKxr5tK2dVcYmaCk2uqdjF4A==" crossorigin="anonymous"></script>
  <script src="https://kit.fontawesome.com/6ecbd6c532.js" crossorigin="anonymous"></script>
    <script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <link href="libs/bootstrap-4.6.0/bootstrap.min.css" rel="stylesheet" />
    <script src="libs/bootstrap-4.6.0/bootstrap.bundle.min.js"></script>
    <script src="libs/bs3compat-0.10.0/transition.js"></script>
    <script src="libs/bs3compat-0.10.0/tabs.js"></script>
    <script src="libs/bs3compat-0.10.0/bs3compat.js"></script>
    <link href="libs/bs4_book-1.0.0/bs4_book.css" rel="stylesheet" />
    <script src="libs/bs4_book-1.0.0/bs4_book.js"></script>
    <script src="libs/kePrint-0.0.1/kePrint.js"></script>
    <link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />
    <link href="libs/bsTable-3.3.7/bootstrapTable.min.css" rel="stylesheet" />
    <script src="libs/bsTable-3.3.7/bootstrapTable.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/autocomplete.js/0.38.0/autocomplete.jquery.min.js" integrity="sha512-GU9ayf+66Xx2TmpxqJpliWbT5PiGYxpaG8rfnBEk1LL8l1KGkRShhngwdXK1UgqhAzWpZHSiYPc09/NwDQIGyg==" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/mark.min.js" integrity="sha512-5CYOlHXGh6QpOFA/TeTylKLWfB3ftPsde7AnmhuitiTX4K5SqCLBeKro6sPS8ilsz1Q4NRx3v8Ko2IBiszzdww==" crossorigin="anonymous"></script>

  <!-- CSS -->
  <style type="text/css">
    
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  </style>
    <style type="text/css">
    /* Used with Pandoc 2.11+ new --citeproc when CSL is used */
    div.csl-bib-body { }
    div.csl-entry {
      clear: both;
          margin-bottom: 1em;
        }
    .hanging div.csl-entry {
      margin-left:2em;
      text-indent:-2em;
    }
    div.csl-left-margin {
      min-width:2em;
      float:left;
    }
    div.csl-right-inline {
      margin-left:2em;
      padding-left:1em;
    }
    div.csl-indent {
      margin-left: 2em;
    }
  </style>
      <link rel="stylesheet" href="style.css" />
  
</head>

<body data-spy="scroll" data-target="#toc">

<div class="container-fluid">
<div class="row">
  <header class="col-sm-12 col-lg-3 sidebar sidebar-book">
    <a class="sr-only sr-only-focusable" href="#content">Skip to main content</a>

    <div class="d-flex align-items-start justify-content-between">
      <h1>
        <a href="index.html" title="Disciplina de Ecologia Numérica do Curso de Ciências Biológicas do Campus V da UEPB">Fundamentos de Ecologia Numérica</a>:
        <small class="text-muted">Disciplina de Ecologia Numérica do Curso de Ciências Biológicas do Campus V da UEPB</small>
      </h1>
      <button class="btn btn-outline-primary d-lg-none ml-2 mt-1" type="button" data-toggle="collapse" data-target="#main-nav" aria-expanded="true" aria-controls="main-nav"><i class="fas fa-bars"></i><span class="sr-only">Show table of contents</span></button>
    </div>

    <div id="main-nav" class="collapse-lg">
      <form role="search">
        <input id="search" class="form-control" type="search" placeholder="Search" aria-label="Search">
      </form>

      <nav aria-label="Table of contents">
        <h2>Table of contents</h2>
        <div id="book-toc"></div>

        <div class="book-extra">
          <p><a id="book-repo" href="#">View book source <i class="fab fa-github"></i></a></li></p>
        </div>
      </nav>
    </div>
  </header>

  <main class="col-sm-12 col-md-9 col-lg-7" id="content">
<div id="outcentr" class="section level1" number="21">
<h1><span class="header-section-number"> 21</span> R Módulo 6 - Análise de outliers baseada no desvio padrão do centróide</h1>
<div id="apresentação-15" class="section level3 unnumbered">
<h3>Apresentação</h3>
<p>A análise de outliers baseada no desvio padrão do centróide em análise multivariada é uma técnica utilizada para identificar valores discrepantes em uma matriz de dados com várias variáveis. Essa técnica consiste em calcular o centróide dos dados (ou seja, a média de cada variável), e então calcular o desvio padrão de cada observação em relação ao centróide. Os valores que estão a uma distância maior que um certo número de desvios padrão do centróide são considerados outliers. Essa técnica é útil para identificar observações que podem estar afetando a análise de dados multivariados, como análise de componentes principais, e que podem precisar ser tratadas de forma especial. No entanto, é importante lembrar que a identificação de outliers é uma questão subjetiva e depende do contexto da análise e do objetivo do estudo.</p>
</div>
<div id="sobre-os-dados-do-ppbio-3" class="section level2" number="21.1">
<h2><span class="header-section-number">21.1</span> Sobre os dados do PPBio</h2>
<p>Usaremos para esse tutorial dados coletados no Programa de Pesquisa em Biodiversidade - PPBio (Veja <a href="https://ppbio.inpa.gov.br/Sobre">Programa de Pesquisa em Biodiversidade – PPBio</a>). Nesta base de dados estão armazenadas informações sobre diversos grupos taxonômicos dstribuidos em diversas unidades amostrais (UA’s ou sítios), como peixes, macroinverbrebrados bentônicos, quironomídeos e zooplâncotn, além de dados do habitat, como variáveis físicas e químicas, morfologia do habitat, composição do substrato, estrutura de habitat marginal, entre outros (Figura <a href="outcentr.html#fig:6ppbio">21.1</a>).</p>
<div class="figure"><span style="display:block;" id="fig:6ppbio"></span>
<img src="imagens/ppbio.png" alt="Parte da planilha de dados brutos do PPBio." width="476" />
<p class="caption">
Figura 21.1: Parte da planilha de dados brutos do PPBio.
</p>
</div>
<p>Essa é a <strong>matriz bruta de dados</strong>, porque os valores ainda não foram ajustados para os valores de Captura Por Unidade de Esforço (CPUE), nem foram relativizados ou transformados (Tabela <a href="outcentr.html#tab:6arqs">21.1</a>). As matrizes disponíveis para análises, com suas descrições e tipos de dados recomendados são mostradas na Tabela <a href="outcentr.html#tab:6arqs">21.1</a>.</p>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:6arqs">Tabela 21.1: </span><span id="tab:6arqs">Tabela 21.2: </span>Exemplos de matrizes disponíveis para análises (PPBio Semiárido), com suas descrições e tipos de dados recomendados.
</caption>
<thead>
<tr>
<th style="text-align:left;">
Arquivo (.xlsx)
</th>
<th style="text-align:left;">
Tipo de matriz
</th>
<th style="text-align:left;">
Descrição
</th>
<th style="text-align:left;">
Tipo de dados
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;width: 2cm; ">
ppbio06c
</td>
<td style="text-align:left;width: 2cm; ">
Matriz comunitária
</td>
<td style="text-align:left;width: 2cm; ">
O arquivo ppbio06 traz os dados brutos que serão usados nas análises. A matriz de dados brutos contendo 26 localidades em estações do ano diferentes (objetos) x 35 espécies (atributos), antes de qualquer modificação.
</td>
<td style="text-align:left;width: 2cm; ">
Contagens de indivíduos com alta amplitude de variação, sugerido uso de matriz relativizada.
</td>
</tr>
<tr>
<td style="text-align:left;width: 2cm; ">
ppbio06h
</td>
<td style="text-align:left;width: 2cm; ">
Matriz ambiental
</td>
<td style="text-align:left;width: 2cm; ">
O arquivo ppbio06h traz os dados brutos que serão usados nas análises. A matriz de dados brutos contendo 26 localidades em estações diferentes (objetos) x 35 variáveis ambienteis (atributos) medidas em diferentes escalas espaciais, antes de qualquer modificação.
</td>
<td style="text-align:left;width: 2cm; ">
Unidades de medição diferentes (cm, m, °C, mg/L, etc.), com uma alta amplitude de variação, sugerido uso de matriz transformada e/ou reescalada.
</td>
</tr>
<tr>
<td style="text-align:left;width: 2cm; ">
ppbio06
</td>
<td style="text-align:left;width: 2cm; ">
Matriz comunitária
</td>
<td style="text-align:left;width: 2cm; ">
O arquivo ppbio06 traz os dados brutos que serão usados nessa análise. A matriz de dados brutos contendo 26 locais/ocasiões (objetos) x 35 espécies (atributos), antes de qualquer modificação.
</td>
<td style="text-align:left;width: 2cm; ">
Contagens de indivíduos com alta amplitude de variação, sugerido uso de matriz relativizada.
</td>
</tr>
<tr>
<td style="text-align:left;width: 2cm; ">
ppbio06cpue
</td>
<td style="text-align:left;width: 2cm; ">
Matriz comunitária
</td>
<td style="text-align:left;width: 2cm; ">
O arquivo ppbio06cpue traz os valores depois de terem sidos ajustados pela Captura Por Unidade de Esforço (CPUE), onde o número de indivíduos de cada espécie em uma determinada UA é dividido pelo esforço de captura daquela UA. Isso significa que os dados foram relativizados pela CPUE. A matriz de dados brutos contendo 26 localidades em estações do ano diferentes (objetos) x 35 espécies (atributos), antes de qualquer modificação.
</td>
<td style="text-align:left;width: 2cm; ">
Densidades de indivíduos (no. de indivíduos por Unidade de Esforço de Captura) com alta amplitude de variação, sugerido uso de matriz relativizada.
</td>
</tr>
</tbody>
</table>
<p>A planilha <code>ppbio</code> contém o delineamento amostral de um dos estudos do Projeto PPBio (Figura <a href="outcentr.html#fig:6rm1">21.2</a>. Nas linhas são apresentadas as abreviações dos nomes das unidades amostrais (UA’s) e nas colunas são apresentados os nomes abreviados das espécies - temos portando uma matriz comunitária (<a href="outcentr.html#tab:6arqs">21.1</a>. No corpo da planilha temos os valores para o tipo de dados amostrado. Quantitativo, semi-quatitativo ou qualitativo.<br />
Qual desses tipos de dados você acha que é apresentado na planilha?</p>
<div class="figure"><span style="display:block;" id="fig:6rm1"></span>
<img src="imagens/rm1.fig3.png" alt="Associação entre a planilha de dados brutos do PPBio e o delineamento amostral do estudo." width="556" />
<p class="caption">
Figura 21.2: Associação entre a planilha de dados brutos do PPBio e o delineamento amostral do estudo.
</p>
</div>
<p>Várias das espécies nessa matriz tem grande importância ecológica, como é o caso de <em>Astyanax bimaculatus</em> <a href="#fn14" class="footnote-ref" id="fnref14"><sup>14</sup></a> (Figura <a href="outcentr.html#fig:6asbim">21.3</a>), que é muito comum em rios intermitentes e serve de alimento para predadores maiores como a espécie <em>Hoplias malabaricus</em> <a href="#fn15" class="footnote-ref" id="fnref15"><sup>15</sup></a> (Figura <a href="outcentr.html#fig:6hmala">21.4</a>).</p>
<div class="figure"><span style="display:block;" id="fig:6asbim"></span>
<img src="imagens/spp/Asbim_u4.jpg" alt="*Astyanax bimaculatus*, a espécie mais comum da matriz de dados ppbio. Peru, by Eakins, R. Fonte: &lt;https://www.fishbase.se/summary/Astianax-bimaculatus.html&gt;" width="320" />
<p class="caption">
Figura 21.3: <em>Astyanax bimaculatus</em>, a espécie mais comum da matriz de dados ppbio. Peru, by Eakins, R. Fonte: <a href="https://www.fishbase.se/summary/Astianax-bimaculatus.html" class="uri">https://www.fishbase.se/summary/Astianax-bimaculatus.html</a>
</p>
</div>
<div class="figure"><span style="display:block;" id="fig:6hmala"></span>
<img src="imagens/spp/Homal_u6.jpg" alt="*Hoplias malabaricus*, espécie que cresce para se tornar um importante predador. Brazil, by Roselet, F.F.G. Fonte: &lt;https://www.fishbase.se/summary/Hoplias-malabaricus.html&gt;" width="320" />
<p class="caption">
Figura 21.4: <em>Hoplias malabaricus</em>, espécie que cresce para se tornar um importante predador. Brazil, by Roselet, F.F.G. Fonte: <a href="https://www.fishbase.se/summary/Hoplias-malabaricus.html" class="uri">https://www.fishbase.se/summary/Hoplias-malabaricus.html</a>
</p>
</div>
</div>
<div id="organização-básica-11" class="section level2" number="21.2">
<h2><span class="header-section-number">21.2</span> Organização básica</h2>
<div class="sourceCode" id="cb490"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb490-1"><a href="outcentr.html#cb490-1" tabindex="-1"></a><span class="fu">dev.off</span>() <span class="co">#apaga os graficos, se houver algum</span></span>
<span id="cb490-2"><a href="outcentr.html#cb490-2" tabindex="-1"></a><span class="fu">rm</span>(<span class="at">list=</span><span class="fu">ls</span>(<span class="at">all=</span><span class="cn">TRUE</span>)) <span class="co">#limpa a memória</span></span>
<span id="cb490-3"><a href="outcentr.html#cb490-3" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">&quot;</span><span class="sc">\014</span><span class="st">&quot;</span>) <span class="co">#limpa o console</span></span></code></pre></div>
<p>Instalando os pacotes necessários para esse módulo</p>
<div class="sourceCode" id="cb491"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb491-1"><a href="outcentr.html#cb491-1" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">&quot;openxlsx&quot;</span>) <span class="co">#importa arquivos do excel</span></span>
<span id="cb491-2"><a href="outcentr.html#cb491-2" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">&quot;moments&quot;</span>) <span class="co">#calcula assimetria e curtose dos dados</span></span>
<span id="cb491-3"><a href="outcentr.html#cb491-3" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">&quot;matrixStats&quot;</span>) <span class="co">#fornece funções rápidas para a estatística de matrizes</span></span>
<span id="cb491-4"><a href="outcentr.html#cb491-4" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">&quot;gt&quot;</span>) <span class="co">#ferramenta para criação de tabelas bonitas e personalizáveis</span></span></code></pre></div>
<p>Agora vamos <strong>definir o diretório de trabalho</strong>. Esse código é usado para obter e definir o diretório de trabalho atual no R. O comando <code>getwd()</code> retorna o caminho do diretório onde o R está lendo e salvando arquivos. O comando <code>setwd()</code> muda esse diretório de trabalho para o caminho especificado entre aspas. No seu caso, você deve ajustar o caminho para o seu próprio diretório de trabalho. <strong>Lembre de usar a barra “/” entre os diretórios. E não a contra-barra “\”.</strong></p>
<p>Definindo o diretório de trabalho e installando os pacotes necessários:</p>
<div class="sourceCode" id="cb492"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb492-1"><a href="outcentr.html#cb492-1" tabindex="-1"></a><span class="fu">getwd</span>()</span>
<span id="cb492-2"><a href="outcentr.html#cb492-2" tabindex="-1"></a><span class="fu">setwd</span>(<span class="st">&quot;C:/Seu/Diretório/De/Trabalho&quot;</span>)</span></code></pre></div>
<div id="importando-a-planilha-8" class="section level3" number="21.2.1">
<h3><span class="header-section-number">21.2.1</span> Importando a planilha</h3>
<p>Note que o símbolo <span style="color:green"><code>#</code></span> em programação R significa que o texto que vem depois dele é um comentário e não será executado pelo programa. Isso é útil para explicar o código ou deixar anotações.<br />
- Ajuste a primeira linha do código abaixo para refletir <span style="color:blue">“C:/Seu/Diretório/De/Trabalho/Planilha.xlsx”</span>.<br />
- Ajuste o parâmetro <code>sheet = "Sheet1"</code> para refletir a aba correta do arquivo .xlsx a ser importado.</p>
<p>Alternativamente você pode ir na barra de tarefas e escolhes as opções:<br />
SESSION -&gt; SET WORKING DIRECTORY -&gt; CHOOSE DIRECTORY</p>
<div class="sourceCode" id="cb493"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb493-1"><a href="outcentr.html#cb493-1" tabindex="-1"></a><span class="fu">library</span>(openxlsx)</span>
<span id="cb493-2"><a href="outcentr.html#cb493-2" tabindex="-1"></a>m_bruta <span class="ot">&lt;-</span> <span class="fu">read.xlsx</span>(<span class="st">&quot;D:/Elvio/OneDrive/Disciplinas/_EcoNumerica/5.Matrizes/ppbio06c-peixes.xlsx&quot;</span>,</span>
<span id="cb493-3"><a href="outcentr.html#cb493-3" tabindex="-1"></a>                   <span class="at">rowNames =</span> T, <span class="at">colNames =</span> T,</span>
<span id="cb493-4"><a href="outcentr.html#cb493-4" tabindex="-1"></a>                   <span class="at">sheet =</span> <span class="st">&quot;Sheet1&quot;</span>)</span>
<span id="cb493-5"><a href="outcentr.html#cb493-5" tabindex="-1"></a><span class="fu">str</span>(m_bruta)</span>
<span id="cb493-6"><a href="outcentr.html#cb493-6" tabindex="-1"></a>m_bruta_ma <span class="ot">&lt;-</span> <span class="fu">as.matrix</span>(m_bruta) <span class="co">#lê m_bruta como uma matriz</span></span>
<span id="cb493-7"><a href="outcentr.html#cb493-7" tabindex="-1"></a><span class="fu">str</span>(m_bruta_ma)</span>
<span id="cb493-8"><a href="outcentr.html#cb493-8" tabindex="-1"></a><span class="co">#m_bruta</span></span>
<span id="cb493-9"><a href="outcentr.html#cb493-9" tabindex="-1"></a>m_bruta_ma[<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>,<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>] <span class="co">#[1:5,1:5] mostra apenas as linhas e colunas de 1 a 5.</span></span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    26 obs. of  35 variables:
##  $ ap-davis : num  0 0 0 0 0 0 0 0 0 0 ...
##  $ as-bimac : num  1 99 194 19 23 142 5 46 206 16 ...
##  $ as-fasci : num  0 0 55 0 1 3 1 0 64 0 ...
##  $ ch-bimac : num  0 0 0 0 13 3 0 178 0 0 ...
##  $ ci-ocela : num  0 0 0 0 0 0 40 0 0 13 ...
##  $ ci-orien : num  0 0 5 0 0 69 9 0 25 24 ...
##  $ co-macro : num  0 0 0 0 0 0 0 0 0 0 ...
##  $ co-heter : num  0 0 1 0 0 0 0 0 0 0 ...
##  $ cr-menez : num  0 0 14 0 0 4 0 0 8 0 ...
##  $ cu-lepid : num  0 0 0 0 0 0 0 0 0 0 ...
##  $ cy-gilbe : num  0 0 0 0 0 0 0 0 0 0 ...
##  $ ge-brasi : num  0 0 3 0 0 0 0 0 1 0 ...
##  $ he-margi : num  0 0 0 0 0 1 0 0 0 0 ...
##  $ ho-malab : num  0 0 1 5 0 17 10 2 31 4 ...
##  $ hy-pusar : num  0 0 9 2 0 43 2 0 11 0 ...
##  $ le-melan : num  0 0 0 0 0 0 0 0 0 0 ...
##  $ le-piau  : num  0 0 3 0 0 1 3 0 2 1 ...
##  $ le-taeni : num  0 0 0 0 0 0 0 0 0 0 ...
##  $ mo-costa : num  0 0 0 0 0 0 0 0 0 0 ...
##  $ mo-lepid : num  0 1 39 0 0 1 0 0 0 0 ...
##  $ or-nilot : num  0 2 36 0 0 77 0 0 138 0 ...
##  $ pa-manag : num  0 0 0 0 0 0 0 0 0 0 ...
##  $ pimel-sp : num  0 0 6 0 0 0 0 0 0 0 ...
##  $ po-retic : num  0 0 0 0 0 20 0 0 5 0 ...
##  $ po-vivip : num  0 0 47 15 0 221 32 0 326 10 ...
##  $ pr-brevi : num  9 0 5 0 1 15 5 2 164 0 ...
##  $ ps-rhomb : num  0 0 0 0 0 0 0 0 1 0 ...
##  $ ps-genise: num  0 0 0 0 0 0 0 0 1 0 ...
##  $ se-heter : num  0 0 40 14 4 60 0 0 38 0 ...
##  $ se-piaba : num  0 0 68 0 0 0 0 0 0 0 ...
##  $ se-spilo : num  0 0 0 0 0 0 0 0 1 0 ...
##  $ st-noton : num  0 0 1 0 0 25 0 0 115 0 ...
##  $ sy-marmo : num  0 0 0 0 0 0 1 0 0 0 ...
##  $ te-chalc : num  0 0 0 0 0 0 0 0 0 0 ...
##  $ tr-signa : num  0 0 18 0 0 15 0 0 7 0 ...
##  num [1:26, 1:35] 0 0 0 0 0 0 0 0 0 0 ...
##  - attr(*, &quot;dimnames&quot;)=List of 2
##   ..$ : chr [1:26] &quot;S-A-ZA1&quot; &quot;S-R-CC1&quot; &quot;S-R-CT1&quot; &quot;S-R-CP1&quot; ...
##   ..$ : chr [1:35] &quot;ap-davis&quot; &quot;as-bimac&quot; &quot;as-fasci&quot; &quot;ch-bimac&quot; ...
##         ap-davis as-bimac as-fasci ch-bimac ci-ocela
## S-A-ZA1        0        1        0        0        0
## S-R-CC1        0       99        0        0        0
## S-R-CT1        0      194       55        0        0
## S-R-CP1        0       19        0        0        0
## S-A-TA1        0       23        1       13        0</code></pre>
</div>
</div>
<div id="reset-point-1" class="section level2" number="21.3">
<h2><span class="header-section-number">21.3</span> Reset point</h2>
<div class="greeting message" style="color: green;">
<p><span style="color:red">ATENÇÃO</span> Aqui substitui-se uma nova matriz de dados, relativizada e/ou transformada, pela matriz de trabalho inicial.</p>
</div>
<div class="sourceCode" id="cb495"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb495-1"><a href="outcentr.html#cb495-1" tabindex="-1"></a><span class="co">#m_bruta &lt;- (m_bruta)   # &lt;1&gt;</span></span></code></pre></div>
<ol style="list-style-type: decimal">
<li>Aqui usaremos as matrizes relativizadas/transformadas/particionadas, etc</li>
</ol>
<p>Podemos exibir a planilha depois de ter sido importada para o ambiente R/RStudio usando as funções <code>View()</code>, <code>print()</code> ou <code>head()</code>. Note que essas funções são case-sensitive. A função <code>ignore.case()</code> é uma função do pacote stringr que modifica um padrão para que ele não considere o caso das letras nas correspondências. Por exemplo, se você quiser encontrar todas as ocorrências da letra “a” em um vetor de caracteres, independente de ser “A” ou “a”, você pode usar essa função.</p>
<div class="sourceCode" id="cb496"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb496-1"><a href="outcentr.html#cb496-1" tabindex="-1"></a><span class="co">#View(m_bruta)</span></span>
<span id="cb496-2"><a href="outcentr.html#cb496-2" tabindex="-1"></a><span class="fu">print</span>(m_bruta)</span>
<span id="cb496-3"><a href="outcentr.html#cb496-3" tabindex="-1"></a><span class="fu">head</span>(m_bruta)</span></code></pre></div>
<p>A função <code>head()</code> no RStudio é uma forma de ver as primeiras (n=6) linhas de um objeto, como um vetor, uma matriz, um data frame ou uma lista. Ela é útil para ter uma ideia do conteúdo e da estrutura do objeto.</p>
<p>Também podemos explorar as características da planilha usando as funções <code>str()</code>, <code>mode()</code>, <code>class()</code> e <code>length()</code>. O número de observações ou tamanho do vetor depende do tipo de dados, se eles são uma <code>matrix</code> ou um <code>data.frame</code>.</p>
<div class="sourceCode" id="cb497"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb497-1"><a href="outcentr.html#cb497-1" tabindex="-1"></a><span class="fu">str</span>(m_bruta)</span>
<span id="cb497-2"><a href="outcentr.html#cb497-2" tabindex="-1"></a><span class="fu">mode</span>(m_bruta)</span>
<span id="cb497-3"><a href="outcentr.html#cb497-3" tabindex="-1"></a><span class="fu">class</span>(m_bruta)</span>
<span id="cb497-4"><a href="outcentr.html#cb497-4" tabindex="-1"></a><span class="co">#?str</span></span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    26 obs. of  35 variables:
##  $ ap-davis : num  0 0 0 0 0 0 0 0 0 0 ...
##  $ as-bimac : num  1 99 194 19 23 142 5 46 206 16 ...
##  $ as-fasci : num  0 0 55 0 1 3 1 0 64 0 ...
##  $ ch-bimac : num  0 0 0 0 13 3 0 178 0 0 ...
##  $ ci-ocela : num  0 0 0 0 0 0 40 0 0 13 ...
##  $ ci-orien : num  0 0 5 0 0 69 9 0 25 24 ...
##  $ co-macro : num  0 0 0 0 0 0 0 0 0 0 ...
##  $ co-heter : num  0 0 1 0 0 0 0 0 0 0 ...
##  $ cr-menez : num  0 0 14 0 0 4 0 0 8 0 ...
##  $ cu-lepid : num  0 0 0 0 0 0 0 0 0 0 ...
##  $ cy-gilbe : num  0 0 0 0 0 0 0 0 0 0 ...
##  $ ge-brasi : num  0 0 3 0 0 0 0 0 1 0 ...
##  $ he-margi : num  0 0 0 0 0 1 0 0 0 0 ...
##  $ ho-malab : num  0 0 1 5 0 17 10 2 31 4 ...
##  $ hy-pusar : num  0 0 9 2 0 43 2 0 11 0 ...
##  $ le-melan : num  0 0 0 0 0 0 0 0 0 0 ...
##  $ le-piau  : num  0 0 3 0 0 1 3 0 2 1 ...
##  $ le-taeni : num  0 0 0 0 0 0 0 0 0 0 ...
##  $ mo-costa : num  0 0 0 0 0 0 0 0 0 0 ...
##  $ mo-lepid : num  0 1 39 0 0 1 0 0 0 0 ...
##  $ or-nilot : num  0 2 36 0 0 77 0 0 138 0 ...
##  $ pa-manag : num  0 0 0 0 0 0 0 0 0 0 ...
##  $ pimel-sp : num  0 0 6 0 0 0 0 0 0 0 ...
##  $ po-retic : num  0 0 0 0 0 20 0 0 5 0 ...
##  $ po-vivip : num  0 0 47 15 0 221 32 0 326 10 ...
##  $ pr-brevi : num  9 0 5 0 1 15 5 2 164 0 ...
##  $ ps-rhomb : num  0 0 0 0 0 0 0 0 1 0 ...
##  $ ps-genise: num  0 0 0 0 0 0 0 0 1 0 ...
##  $ se-heter : num  0 0 40 14 4 60 0 0 38 0 ...
##  $ se-piaba : num  0 0 68 0 0 0 0 0 0 0 ...
##  $ se-spilo : num  0 0 0 0 0 0 0 0 1 0 ...
##  $ st-noton : num  0 0 1 0 0 25 0 0 115 0 ...
##  $ sy-marmo : num  0 0 0 0 0 0 1 0 0 0 ...
##  $ te-chalc : num  0 0 0 0 0 0 0 0 0 0 ...
##  $ tr-signa : num  0 0 18 0 0 15 0 0 7 0 ...
## [1] &quot;list&quot;
## [1] &quot;data.frame&quot;</code></pre>
<p>O símbolo <code>?</code> é usado para acessar a documentação de uma função ou um pacote no R. Como mostrado acima você pode saber mais sobre a função <code>str()</code>, usando o comando <code>?str</code>. Isso vai abrir uma página no menu de ajuda com a descrição, os argumentos, os valores de retorno e os exemplos da função <code>str()</code>. Você também pode usar o símbolo <code>?</code> para obter informações sobre um pacote inteiro. Por exemplo, se você quiser saber mais sobre o pacote <code>openxlsx</code>, você pode digitar <code>?openxlsx</code>. Isso vai abrir uma página com a visão geral, a instalação, os recursos e as referências do pacote solicitado.</p>
<p>Podemos agora calcular o número e a proporção de zeros na matriz usando as funções <code>sum()</code> e <code>length()</code> (Você pode pesquisar o que faz a função <code>length()</code> usando o comando <code>?length</code>).</p>
<div id="tamanho-da-matriz-1" class="section level3" number="21.3.1">
<h3><span class="header-section-number">21.3.1</span> Tamanho da matriz</h3>
<div class="sourceCode" id="cb499"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb499-1"><a href="outcentr.html#cb499-1" tabindex="-1"></a><span class="fu">range</span>(m_bruta) <span class="co">#menor e maior valores</span></span>
<span id="cb499-2"><a href="outcentr.html#cb499-2" tabindex="-1"></a><span class="fu">length</span>(m_bruta) <span class="co">#no. de colunas</span></span>
<span id="cb499-3"><a href="outcentr.html#cb499-3" tabindex="-1"></a><span class="fu">ncol</span>(m_bruta) <span class="co">#no. de N colunas</span></span>
<span id="cb499-4"><a href="outcentr.html#cb499-4" tabindex="-1"></a><span class="fu">nrow</span>(m_bruta) <span class="co">#no. de M linhas</span></span>
<span id="cb499-5"><a href="outcentr.html#cb499-5" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">lengths</span>(m_bruta)) <span class="co">#soma os nos. de colunas</span></span>
<span id="cb499-6"><a href="outcentr.html#cb499-6" tabindex="-1"></a><span class="fu">length</span>(<span class="fu">as.matrix</span>(m_bruta)) <span class="co">#tamanho da matriz m x n</span></span>
<span id="cb499-7"><a href="outcentr.html#cb499-7" tabindex="-1"></a><span class="fu">sum</span>(m_bruta <span class="sc">==</span> <span class="dv">0</span>) <span class="co"># número de observações igual a zero</span></span>
<span id="cb499-8"><a href="outcentr.html#cb499-8" tabindex="-1"></a><span class="fu">sum</span>(m_bruta <span class="sc">&gt;</span> <span class="dv">0</span>) <span class="co"># número de observações maiores que zero</span></span>
<span id="cb499-9"><a href="outcentr.html#cb499-9" tabindex="-1"></a>zeros <span class="ot">&lt;-</span> (<span class="fu">sum</span>(m_bruta <span class="sc">==</span> <span class="dv">0</span>)<span class="sc">/</span><span class="fu">length</span>(<span class="fu">as.matrix</span>(m_bruta)))<span class="sc">*</span><span class="dv">100</span> <span class="co"># proporção de zeros na matriz</span></span>
<span id="cb499-10"><a href="outcentr.html#cb499-10" tabindex="-1"></a>zeros</span></code></pre></div>
<pre><code>## [1]   0 511
## [1] 35
## [1] 35
## [1] 26
## [1] 910
## [1] 910
## [1] 716
## [1] 194
## [1] 78.68132</code></pre>
<p>A matriz de dados apresenta um total de 910 valores que variam entre 0, 511 (menor e maior valores). A matriz m x n tem 26 linhas e 35 colunas. Existem 716 observações iguais a zero e 194 observações maiores que zero, representando um percentual de 78.7% dos valores sendo zeros.</p>
<p>Essas informações podem ser resumidas na Tabela <a href="outcentr.html#tab:6tbl-tam">21.3</a> que será gerada abaixo.</p>
<div class="sourceCode" id="cb501"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb501-1"><a href="outcentr.html#cb501-1" tabindex="-1"></a>tamanho <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb501-2"><a href="outcentr.html#cb501-2" tabindex="-1"></a>  <span class="at">Comando =</span> <span class="fu">c</span>(<span class="st">&quot;range&quot;</span>, <span class="st">&quot;lenght&quot;</span>, <span class="st">&quot;m cols&quot;</span>, <span class="st">&quot;n linhas&quot;</span>, <span class="st">&quot;Tamanho&quot;</span>, <span class="st">&quot;Tamanho&quot;</span>,</span>
<span id="cb501-3"><a href="outcentr.html#cb501-3" tabindex="-1"></a>             <span class="st">&quot;Zeros&quot;</span>, <span class="st">&quot;Nao zeros&quot;</span>, <span class="st">&quot;% Zeros&quot;</span>),</span>
<span id="cb501-4"><a href="outcentr.html#cb501-4" tabindex="-1"></a>  <span class="at">Resultado =</span> <span class="fu">c</span>(<span class="fu">paste</span>(<span class="fu">range</span>(m_bruta), <span class="at">collapse =</span> <span class="st">&quot; - &quot;</span>), <span class="fu">length</span>(m_bruta), <span class="fu">ncol</span>(m_bruta),</span>
<span id="cb501-5"><a href="outcentr.html#cb501-5" tabindex="-1"></a>                <span class="fu">nrow</span>(m_bruta), <span class="fu">sum</span>(<span class="fu">lengths</span>(m_bruta)), <span class="fu">length</span>(<span class="fu">as.matrix</span>(m_bruta)), <span class="fu">sum</span>(m_bruta <span class="sc">==</span> <span class="dv">0</span>),</span>
<span id="cb501-6"><a href="outcentr.html#cb501-6" tabindex="-1"></a>                <span class="fu">sum</span>(m_bruta <span class="sc">&gt;</span> <span class="dv">0</span>), <span class="fu">round</span>(zeros, <span class="dv">1</span>))</span>
<span id="cb501-7"><a href="outcentr.html#cb501-7" tabindex="-1"></a>)</span>
<span id="cb501-8"><a href="outcentr.html#cb501-8" tabindex="-1"></a>tamanho</span></code></pre></div>
<pre><code>##     Comando Resultado
## 1     range   0 - 511
## 2    lenght        35
## 3    m cols        35
## 4  n linhas        26
## 5   Tamanho       910
## 6   Tamanho       910
## 7     Zeros       716
## 8 Nao zeros       194
## 9   % Zeros      78.7</code></pre>
<table>
<caption><span id="tab:6tbl-tam">Tabela 21.3: </span>Resumo das informações sobre o tamanho da matriz</caption>
<thead>
<tr class="header">
<th align="left">Comando</th>
<th align="left">Resultado</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">range</td>
<td align="left">0 - 511</td>
</tr>
<tr class="even">
<td align="left">lenght</td>
<td align="left">35</td>
</tr>
<tr class="odd">
<td align="left">m cols</td>
<td align="left">35</td>
</tr>
<tr class="even">
<td align="left">n linhas</td>
<td align="left">26</td>
</tr>
<tr class="odd">
<td align="left">Tamanho</td>
<td align="left">910</td>
</tr>
<tr class="even">
<td align="left">Tamanho</td>
<td align="left">910</td>
</tr>
<tr class="odd">
<td align="left">Zeros</td>
<td align="left">716</td>
</tr>
<tr class="even">
<td align="left">Nao zeros</td>
<td align="left">194</td>
</tr>
<tr class="odd">
<td align="left">% Zeros</td>
<td align="left">78.7</td>
</tr>
</tbody>
</table>
<p>Ou seja, temos uma matriz de tamanho <code>m x n</code> igual a 26 objetos por 35 atributos, onde 78.68% dos valores da matriz são iguais a zero!</p>
</div>
</div>
<div id="cálculo-de-matriz-de-distâncias-euclidiana-euclid" class="section level2" number="21.4">
<h2><span class="header-section-number">21.4</span> Cálculo de matriz de distâncias Euclidiana (<code>euclid</code>)</h2>
<p>Agora vamos calcular a matriz de <strong>distâncias euclidianas</strong> <span class="citation">(<a href="#ref-borcard2018">BORCARD; GILLET; LEGENDRE, 2018</a>; <a href="#ref-legendre1998">LEGENDRE; LEGENDRE, 1998</a>)</span> entre as UA´s usando a função <code>dist()</code> (pesquise o que faz essa função usando o comando <code>?dist</code>).</p>
<div class="sourceCode" id="cb503"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb503-1"><a href="outcentr.html#cb503-1" tabindex="-1"></a>euclid <span class="ot">&lt;-</span> <span class="fu">dist</span>(m_bruta, <span class="at">method =</span> <span class="st">&quot;euclidian&quot;</span>, <span class="at">diag =</span> <span class="cn">TRUE</span>, <span class="at">upper =</span> <span class="cn">FALSE</span>)</span>
<span id="cb503-2"><a href="outcentr.html#cb503-2" tabindex="-1"></a><span class="co">#?dist</span></span></code></pre></div>
<!--- #15.358=Standard deviation e 93.898=Grand mean, eram os  valores originais do PC-ORD para os  dados OakRaw (transformados e relativisados)--->
<p>Pronto, calculamos a matriz de distâncias (Euclidiana). Agora podemos visualizar a matriz.</p>
<div class="sourceCode" id="cb504"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb504-1"><a href="outcentr.html#cb504-1" tabindex="-1"></a><span class="co">#euclid</span></span>
<span id="cb504-2"><a href="outcentr.html#cb504-2" tabindex="-1"></a><span class="fu">str</span>(euclid)</span>
<span id="cb504-3"><a href="outcentr.html#cb504-3" tabindex="-1"></a><span class="fu">mode</span>(euclid)</span>
<span id="cb504-4"><a href="outcentr.html#cb504-4" tabindex="-1"></a><span class="fu">class</span>(euclid)</span>
<span id="cb504-5"><a href="outcentr.html#cb504-5" tabindex="-1"></a><span class="fu">length</span>(<span class="fu">as.matrix</span>(euclid))</span>
<span id="cb504-6"><a href="outcentr.html#cb504-6" tabindex="-1"></a><span class="fu">as.matrix</span>(euclid)[<span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>, <span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>] <span class="co">#mostra as 5 primeiras linhas e colunas da matriz</span></span></code></pre></div>
<pre><code>##  &#39;dist&#39; num [1:325] 98.4 228.5 29.2 27.1 294.1 ...
##  - attr(*, &quot;Size&quot;)= int 26
##  - attr(*, &quot;Labels&quot;)= chr [1:26] &quot;S-A-ZA1&quot; &quot;S-R-CC1&quot; &quot;S-R-CT1&quot; &quot;S-R-CP1&quot; ...
##  - attr(*, &quot;Diag&quot;)= logi TRUE
##  - attr(*, &quot;Upper&quot;)= logi FALSE
##  - attr(*, &quot;method&quot;)= chr &quot;euclidean&quot;
##  - attr(*, &quot;call&quot;)= language dist(x = m_bruta, method = &quot;euclidian&quot;, diag = TRUE, upper = FALSE)
## [1] &quot;numeric&quot;
## [1] &quot;dist&quot;
## [1] 676
##           S-A-ZA1   S-R-CC1  S-R-CT1   S-R-CP1   S-A-TA1  S-R-CT2
## S-A-ZA1   0.00000  98.43780 228.5235  29.24038  27.09243 294.0629
## S-R-CC1  98.43780   0.00000 154.2433  82.79493  77.25283 261.3905
## S-R-CT1 228.52352 154.24331   0.0000 208.52338 209.69263 224.9133
## S-R-CP1  29.24038  82.79493 208.5234   0.00000  23.25941 271.4922
## S-A-TA1  27.09243  77.25283 209.6926  23.25941   0.00000 283.7869
## S-R-CT2 294.06292 261.39051 224.9133 271.49217 283.78689   0.0000</code></pre>
<p>Note que a matriz <code>euclid</code> está como uma classe <code>dist</code>. Uma matriz do tipo <code>dist</code> no R é um objeto que armazena as distâncias entre as linhas de uma matriz ou um data frame. Ela é criada pela função <code>dist()</code>, que calcula as distâncias usando diferentes medidas, como “euclidean”, “manhattan”, “canberra”, “binary” ou “minkowski” <span class="citation">(<a href="#ref-horton2015">HORTON; KLEINMAN, 2015</a>)</span> (Figura <a href="outcentr.html#tab:6tbl-dists">21.4</a>).</p>
<p>Visualizando a matriz de distâncias, observamos que ela:</p>
<ul>
<li><p>é uma matriz quadrada que contém as distâncias entre cada par de elementos do conjuto de dados,</p></li>
<li><p>terá a dimensão m x m (m=linhas, n=colunas) e,</p></li>
<li><p>e cada elemento da matriz será a distância entre cada par de observações ou objetos.</p></li>
</ul>
<p>A <strong>matriz de distâncias é simétrica</strong>, pois a distância entre i e j é igual à distância entre j e i. A matriz de distâncias também tem <strong>diagonal zero</strong>, pois a distância entre uma observação e ela mesma é zero.</p>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:6tbl-dists">Tabela 21.4: </span><span id="tab:6tbl-dists">Tabela 21.5: </span>Medidas de distância disponíves na função <code>dist()</code> para calcular a distância entre dois pontos ou objetos em um espaço multidimensionl.
</caption>
<thead>
<tr>
<th style="text-align:center;">
Distância
</th>
<th style="text-align:left;">
Descrição
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;width: 4cm; ">
Euclidiana
</td>
<td style="text-align:left;width: 4cm; ">
Mede a distância entre dois pontos no espaço, seguindo o teorema de Pitágoras. É uma medida de distância direta entre dois pontos.
</td>
</tr>
<tr>
<td style="text-align:center;width: 4cm; ">
Manhattan
</td>
<td style="text-align:left;width: 4cm; ">
Também conhecida como distância da cidade, mede a distância como se estivesse dirigindo em uma cidade. A distância é a soma das diferenças absolutas de cada coordenada.
</td>
</tr>
<tr>
<td style="text-align:center;width: 4cm; ">
Canberra
</td>
<td style="text-align:left;width: 4cm; ">
Leva em consideração a proporção de diferenças em relação ao tamanho total das variáveis.
</td>
</tr>
<tr>
<td style="text-align:center;width: 4cm; ">
Binária
</td>
<td style="text-align:left;width: 4cm; ">
Mede a semelhança entre dois objetos. É 0 quando dois valores são iguais e 1 caso contrário.
</td>
</tr>
<tr>
<td style="text-align:center;width: 4cm; ">
Minkowski
</td>
<td style="text-align:left;width: 4cm; ">
É uma generalização da distância euclidiana e da distância de Manhattan. A distância é controlada por um parâmetro P, que determina a ordem da distância.
</td>
</tr>
</tbody>
</table>
<p>A matriz <code>euclid</code> está como uma classe <code>dist</code>, mas podemos transformá-la em uma classe <code>matrix</code> usando a função <code>as.matrix()</code>.</p>
<div class="sourceCode" id="cb506"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb506-1"><a href="outcentr.html#cb506-1" tabindex="-1"></a>euclid_ma <span class="ot">&lt;-</span> (<span class="fu">as.matrix</span>(euclid))</span>
<span id="cb506-2"><a href="outcentr.html#cb506-2" tabindex="-1"></a><span class="co">#View(euclid_ma)</span></span>
<span id="cb506-3"><a href="outcentr.html#cb506-3" tabindex="-1"></a><span class="fu">str</span>(euclid_ma)</span>
<span id="cb506-4"><a href="outcentr.html#cb506-4" tabindex="-1"></a><span class="fu">mode</span>(euclid_ma)</span>
<span id="cb506-5"><a href="outcentr.html#cb506-5" tabindex="-1"></a><span class="fu">class</span>(euclid_ma)</span>
<span id="cb506-6"><a href="outcentr.html#cb506-6" tabindex="-1"></a>euclid_ma[<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>, <span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>] <span class="co">#mostra as 5 primeiras linhas e colunas da matriz</span></span></code></pre></div>
<pre><code>##  num [1:26, 1:26] 0 98.4 228.5 29.2 27.1 ...
##  - attr(*, &quot;dimnames&quot;)=List of 2
##   ..$ : chr [1:26] &quot;S-A-ZA1&quot; &quot;S-R-CC1&quot; &quot;S-R-CT1&quot; &quot;S-R-CP1&quot; ...
##   ..$ : chr [1:26] &quot;S-A-ZA1&quot; &quot;S-R-CC1&quot; &quot;S-R-CT1&quot; &quot;S-R-CP1&quot; ...
## [1] &quot;numeric&quot;
## [1] &quot;matrix&quot; &quot;array&quot; 
##           S-A-ZA1   S-R-CC1  S-R-CT1   S-R-CP1   S-A-TA1
## S-A-ZA1   0.00000  98.43780 228.5235  29.24038  27.09243
## S-R-CC1  98.43780   0.00000 154.2433  82.79493  77.25283
## S-R-CT1 228.52352 154.24331   0.0000 208.52338 209.69263
## S-R-CP1  29.24038  82.79493 208.5234   0.00000  23.25941
## S-A-TA1  27.09243  77.25283 209.6926  23.25941   0.00000</code></pre>
<!--- Definir qual o jeito correto: Fazer os calculos ma matriz do tipo 'dist' ou na matriz do tipo 'as.matrix'--->
</div>
<div id="calculando-o-centróide-da-matriz-de-distâncias-euclid" class="section level2" number="21.5">
<h2><span class="header-section-number">21.5</span> Calculando o centróide da matriz de distâncias <code>euclid</code></h2>
<p>Primeiro algumas informações básicas da matriz</p>
<div class="sourceCode" id="cb508"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb508-1"><a href="outcentr.html#cb508-1" tabindex="-1"></a><span class="fu">range</span>(m_bruta)</span>
<span id="cb508-2"><a href="outcentr.html#cb508-2" tabindex="-1"></a><span class="fu">range</span>(euclid)</span>
<span id="cb508-3"><a href="outcentr.html#cb508-3" tabindex="-1"></a><span class="fu">min</span>(euclid)</span>
<span id="cb508-4"><a href="outcentr.html#cb508-4" tabindex="-1"></a><span class="fu">max</span>(euclid)</span>
<span id="cb508-5"><a href="outcentr.html#cb508-5" tabindex="-1"></a><span class="fu">mean</span>(euclid) <span class="co">#CENTROIDE!! OU Grand mean</span></span>
<span id="cb508-6"><a href="outcentr.html#cb508-6" tabindex="-1"></a><span class="fu">sd</span>(euclid)  <span class="co">#Standard deviation</span></span>
<span id="cb508-7"><a href="outcentr.html#cb508-7" tabindex="-1"></a>centroide <span class="ot">&lt;-</span> <span class="fu">mean</span>(euclid)</span>
<span id="cb508-8"><a href="outcentr.html#cb508-8" tabindex="-1"></a>centroide</span></code></pre></div>
<pre><code>## [1]   0 511
## [1]  16.27882 707.32666
## [1] 16.27882
## [1] 707.3267
## [1] 285.9043
## [1] 172.9708
## [1] 285.9043</code></pre>
<p>A função <code>mean()</code> calcula a média de todos os valores da matriz de distâncias, ou seja, a média multivariada, que é o centróide. Nesse caso o <strong>centroide assume o valor de 285.9</strong>.</p>
<p>Usamos agora a fórmula <code>m*(m-1)/2</code>, onde <code>m</code> é o no. de objetos sendo comparados, para calcular quantas distâcias temos na nossa matriz.</p>
<div class="sourceCode" id="cb510"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb510-1"><a href="outcentr.html#cb510-1" tabindex="-1"></a><span class="fu">length</span>(euclid)</span>
<span id="cb510-2"><a href="outcentr.html#cb510-2" tabindex="-1"></a>m <span class="ot">&lt;-</span> <span class="fu">nrow</span>(m_bruta)</span>
<span id="cb510-3"><a href="outcentr.html#cb510-3" tabindex="-1"></a>m</span>
<span id="cb510-4"><a href="outcentr.html#cb510-4" tabindex="-1"></a>m<span class="sc">*</span>(m<span class="dv">-1</span>)<span class="sc">/</span><span class="dv">2</span></span>
<span id="cb510-5"><a href="outcentr.html#cb510-5" tabindex="-1"></a><span class="fu">summary</span>(euclid)</span></code></pre></div>
<pre><code>## [1] 325
## [1] 26
## [1] 325
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   16.28  142.70  242.82  285.90  423.64  707.33</code></pre>
<p>Temos então que m é <strong>26 objetos</strong> (ou linhas), e portanto, a matriz de distâncias tem <strong>325 valores</strong>.</p>
<p>Fazemos agora um breve sumário do que foi calculado até agora com base na matriz de distâncias <code>euclid</code>.</p>
<div class="sourceCode" id="cb512"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb512-1"><a href="outcentr.html#cb512-1" tabindex="-1"></a>Sumario1 <span class="ot">&lt;-</span> <span class="fu">cbind</span>(<span class="fu">min</span>(euclid),</span>
<span id="cb512-2"><a href="outcentr.html#cb512-2" tabindex="-1"></a>                  <span class="fu">max</span>(euclid),</span>
<span id="cb512-3"><a href="outcentr.html#cb512-3" tabindex="-1"></a>                  <span class="fu">sd</span>(euclid),</span>
<span id="cb512-4"><a href="outcentr.html#cb512-4" tabindex="-1"></a>                  <span class="fu">mean</span>(euclid),</span>
<span id="cb512-5"><a href="outcentr.html#cb512-5" tabindex="-1"></a>                  <span class="fu">length</span>(euclid))</span>
<span id="cb512-6"><a href="outcentr.html#cb512-6" tabindex="-1"></a><span class="fu">colnames</span>(Sumario1) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;Minimo&quot;</span>, <span class="st">&quot;Maximo&quot;</span>, <span class="st">&quot;Desv.Padr&quot;</span>, <span class="st">&quot;Media&quot;</span>, <span class="st">&quot;m(m-1)/2&quot;</span>)</span>
<span id="cb512-7"><a href="outcentr.html#cb512-7" tabindex="-1"></a><span class="fu">rownames</span>(Sumario1) <span class="ot">&lt;-</span> (<span class="st">&quot;Valores&quot;</span>)</span>
<span id="cb512-8"><a href="outcentr.html#cb512-8" tabindex="-1"></a>Sumario1</span></code></pre></div>
<pre><code>##           Minimo   Maximo Desv.Padr    Media m(m-1)/2
## Valores 16.27882 707.3267  172.9708 285.9043      325</code></pre>
</div>
<div id="distribuição-de-frequências-da-matriz-de-distâncias-euclid" class="section level2" number="21.6">
<h2><span class="header-section-number">21.6</span> Distribuição de frequências da matriz de distâncias <code>euclid</code></h2>
<p>O código abaixo vai plotar um histograma e um boxplot da distribuição de dados armazenada em <code>euclid</code>. Também é adicionada uma curva normal teórica ao histograma utilizando a média e o desvio padrão dos dados (Figura <a href="outcentr.html#fig:6euclid">21.5</a>). Atente que o comando <code>par(mfrow=c(2,1))</code> define o layout dos gráficos, especificando que serão plotados 2 gráficos em uma coluna. As funções <code>floor(min(euclid)), ceiling(max(euclid))</code> definem os limites dos graficos pelo valores mínimo e máximo do objeto (<code>euclid</code>).</p>
<div class="sourceCode" id="cb514"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb514-1"><a href="outcentr.html#cb514-1" tabindex="-1"></a><span class="fu">range</span>(euclid)</span></code></pre></div>
<pre><code>## [1]  16.27882 707.32666</code></pre>
<div class="sourceCode" id="cb516"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb516-1"><a href="outcentr.html#cb516-1" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">1</span>))</span>
<span id="cb516-2"><a href="outcentr.html#cb516-2" tabindex="-1"></a><span class="fu">hist</span>(euclid,</span>
<span id="cb516-3"><a href="outcentr.html#cb516-3" tabindex="-1"></a>     <span class="at">breaks =</span> <span class="dv">15</span>, <span class="co">#determina o no. de colunas do histograma</span></span>
<span id="cb516-4"><a href="outcentr.html#cb516-4" tabindex="-1"></a>     <span class="at">xlim =</span> <span class="fu">range</span>(<span class="fu">floor</span>(<span class="fu">min</span>(euclid)), <span class="fu">ceiling</span>(<span class="fu">max</span>(euclid))), </span>
<span id="cb516-5"><a href="outcentr.html#cb516-5" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">&quot;Distr. de Frequências&quot;</span>,</span>
<span id="cb516-6"><a href="outcentr.html#cb516-6" tabindex="-1"></a>     <span class="at">freq =</span> <span class="cn">FALSE</span>)</span>
<span id="cb516-7"><a href="outcentr.html#cb516-7" tabindex="-1"></a><span class="fu">curve</span>(<span class="fu">dnorm</span>(x, <span class="at">mean=</span><span class="fu">mean</span>(euclid), <span class="at">sd=</span><span class="fu">sd</span>(euclid)), <span class="at">add=</span><span class="cn">TRUE</span>)</span>
<span id="cb516-8"><a href="outcentr.html#cb516-8" tabindex="-1"></a><span class="fu">boxplot.default</span>(euclid, <span class="at">horizontal =</span> <span class="cn">TRUE</span>, <span class="at">frame =</span> <span class="cn">FALSE</span>,</span>
<span id="cb516-9"><a href="outcentr.html#cb516-9" tabindex="-1"></a>                <span class="at">xlab=</span><span class="st">&quot;Distr. de Frequências&quot;</span>,</span>
<span id="cb516-10"><a href="outcentr.html#cb516-10" tabindex="-1"></a>                <span class="at">ylim=</span><span class="fu">c</span>(<span class="fu">floor</span>(<span class="fu">min</span>(euclid)), <span class="fu">ceiling</span>(<span class="fu">max</span>(euclid)))) <span class="co">#Limites do eixo Y</span></span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:6euclid"></span>
<img src="fundamentos_de_ecologia_numerica_files/figure-html/6euclid-1.png" alt="Distribuições de frequências da matriz de distâncias `euclid`" width="672" />
<p class="caption">
Figura 21.5: Distribuições de frequências da matriz de distâncias <code>euclid</code>
</p>
</div>
<p>O comando abaixo apaga os gráficos, use-o apenas se necessário.</p>
<div class="sourceCode" id="cb517"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb517-1"><a href="outcentr.html#cb517-1" tabindex="-1"></a><span class="fu">dev.off</span>()</span></code></pre></div>
</div>
<div id="procurando-outliers" class="section level2" number="21.7">
<h2><span class="header-section-number">21.7</span> Procurando outliers</h2>
<div id="listas-de-distâncias" class="section level3" number="21.7.1">
<h3><span class="header-section-number">21.7.1</span> Listas de distâncias</h3>
<p>Vamos agora criar uma lista com as distâncias em desvio padrão entre cada objeto e o <strong>centróide</strong>, baseada na matriz de distâncias <code>euclid_ma</code> (ou outra matriz de distâncias criada a partir de uma matriz relativizada/transformada ou bruta, dependendo do arquivo escolhido). As distâncias médias do centroide, expressas em desvios padrão, também podem ser chamadas de <strong>z-scores</strong>.</p>
<p>Para esse cálculo é necessário que a matriz de distâncias (do tipo <code>dist</code>) seja do tipo <code>matrix</code>. Por isso usamos o comando <code>as.matrix</code> e removemos a diagonal da nova matriz <code>euclid_ma</code>. Códigos a seguir.</p>
<div id="removendo-os-zeros-da-matriz-de-distâncias" class="section level4" number="21.7.1.1">
<h4><span class="header-section-number">21.7.1.1</span> Removendo os zeros da matriz de distâncias</h4>
<div class="sourceCode" id="cb518"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb518-1"><a href="outcentr.html#cb518-1" tabindex="-1"></a><span class="fu">library</span>(matrixStats)</span></code></pre></div>
<pre><code>## Warning: pacote &#39;matrixStats&#39; foi compilado no R versão 4.5.3</code></pre>
<pre><code>## 
## Anexando pacote: &#39;matrixStats&#39;</code></pre>
<pre><code>## O seguinte objeto é mascarado por &#39;package:dplyr&#39;:
## 
##     count</code></pre>
<div class="sourceCode" id="cb522"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb522-1"><a href="outcentr.html#cb522-1" tabindex="-1"></a><span class="fu">library</span>(moments)</span>
<span id="cb522-2"><a href="outcentr.html#cb522-2" tabindex="-1"></a>euclid_ma <span class="ot">&lt;-</span> <span class="fu">as.matrix</span>(euclid)</span>
<span id="cb522-3"><a href="outcentr.html#cb522-3" tabindex="-1"></a>euclid_ma</span>
<span id="cb522-4"><a href="outcentr.html#cb522-4" tabindex="-1"></a><span class="fu">range</span>(euclid_ma) <span class="co">#valor errado</span></span>
<span id="cb522-5"><a href="outcentr.html#cb522-5" tabindex="-1"></a><span class="fu">mean</span>(euclid_ma) <span class="co">#valor errado</span></span>
<span id="cb522-6"><a href="outcentr.html#cb522-6" tabindex="-1"></a><span class="fu">sd</span>(euclid_ma) <span class="co">#valor errado</span></span>
<span id="cb522-7"><a href="outcentr.html#cb522-7" tabindex="-1"></a><span class="fu">is.na</span>(euclid_ma) <span class="ot">&lt;-</span> euclid_ma<span class="sc">==</span><span class="dv">0</span> <span class="co">#atribui n.a. aos valores = 0</span></span>
<span id="cb522-8"><a href="outcentr.html#cb522-8" tabindex="-1"></a><span class="fu">mean</span>(euclid_ma, <span class="at">na.rm=</span>T)  <span class="co">#valor correto, omite valores n.a. do calculo</span></span>
<span id="cb522-9"><a href="outcentr.html#cb522-9" tabindex="-1"></a><span class="fu">mean</span>(euclid_ma, <span class="at">na.rm=</span>T) <span class="co">#valor correto, omite valores n.a. do calculo</span></span>
<span id="cb522-10"><a href="outcentr.html#cb522-10" tabindex="-1"></a><span class="fu">sd</span>(euclid_ma, <span class="at">na.rm=</span>T) <span class="co">#valor correto, omite valores n.a. do calculo</span></span>
<span id="cb522-11"><a href="outcentr.html#cb522-11" tabindex="-1"></a><span class="co">#colMeans(euclid_ma, na.rm=T) #omite valores n.a. do calculo</span></span>
<span id="cb522-12"><a href="outcentr.html#cb522-12" tabindex="-1"></a><span class="co">#rowMeans(euclid_ma, na.rm=T) #omite valores n.a. do calculo</span></span></code></pre></div>
<pre><code>##           S-A-ZA1   S-R-CC1  S-R-CT1   S-R-CP1   S-A-TA1  S-R-CT2   S-R-CP2
## S-A-ZA1   0.00000  98.43780 228.5235  29.24038  27.09243 294.0629  53.40412
## S-R-CC1  98.43780   0.00000 154.2433  82.79493  77.25283 261.3905 108.10180
## S-R-CT1 228.52352 154.24331   0.0000 208.52338 209.69263 224.9133 224.09150
## S-R-CP1  29.24038  82.79493 208.5234   0.00000  23.25941 271.4922  49.22398
## S-A-TA1  27.09243  77.25283 209.6926  23.25941   0.00000 283.7869  57.82733
## S-R-CT2 294.06292 261.39051 224.9133 271.49217 283.78689   0.0000 268.95167
## S-R-CP2  53.40412 108.10180 224.0915  49.22398  57.82733 268.9517   0.00000
## S-A-TA2 183.74439 185.75791 261.8301 181.24845 166.66133 326.3327 190.15257
## S-R-CT3 460.42155 428.64437 366.6429 443.90877 453.59674 238.3799 438.54532
## S-R-CP3  34.17601  88.06816 215.2557  31.32092  33.13608 275.0436  40.37326
## S-A-TA3 333.86674 274.45765 269.9444 321.82604 309.19735 360.8213 334.61769
## S-R-CT4 187.51533 213.67265 273.0769 189.67604 191.60898 298.0084 190.90835
## S-R-CP4  81.58431 127.98437 226.6208  69.86415  85.24084 238.5351  57.30620
## S-A-TA4 478.64601 402.05970 359.7819 464.33932 453.15560 450.2344 478.08995
## B-A-MU1 190.62529 209.01196 287.5257 191.40272 190.90312 344.8086 197.56012
## B-R-ET1  36.13862 102.02941 228.2740  43.89761  42.52058 291.0859  63.79655
## B-A-GU1  16.27882  97.90301 227.0507  30.36445  28.40775 293.4110  55.07268
## B-R-PC2  91.52595  98.07650 204.8560  86.04650  84.49260 282.9558 103.56158
## B-A-MU2 119.74974  68.23489 165.6351 106.08958 103.04368 262.9848 125.71396
## B-A-GU2 110.95495 147.95607 249.2348 114.19282 113.77610 305.9902 122.87799
## B-R-PC3 151.57506 133.59266 183.3085 135.95588 140.16776 259.3260 157.58490
## B-A-MU3 534.53718 441.89592 367.2261 516.37293 513.70809 451.3635 530.43944
## B-A-GU3 353.04249 363.59180 396.0858 353.76829 353.56612 414.4539 356.90195
## B-R-PC4  89.73294 127.93748 229.5801  87.46999  89.97778 295.9341 103.55675
## B-A-MU4 641.28309 612.29405 595.5023 631.36598 633.67026 590.7597 633.81385
## B-A-GU4 230.36059 244.38903 302.0546 230.92640 230.49512 341.1700 236.11438
##          S-A-TA2  S-R-CT3   S-R-CP3  S-A-TA3  S-R-CT4   S-R-CP4  S-A-TA4
## S-A-ZA1 183.7444 460.4215  34.17601 333.8667 187.5153  81.58431 478.6460
## S-R-CC1 185.7579 428.6444  88.06816 274.4576 213.6726 127.98437 402.0597
## S-R-CT1 261.8301 366.6429 215.25566 269.9444 273.0769 226.62083 359.7819
## S-R-CP1 181.2484 443.9088  31.32092 321.8260 189.6760  69.86415 464.3393
## S-A-TA1 166.6613 453.5967  33.13608 309.1973 191.6090  85.24084 453.1556
## S-R-CT2 326.3327 238.3799 275.04363 360.8213 298.0084 238.53511 450.2344
## S-R-CP2 190.1526 438.5453  40.37326 334.6177 190.9084  57.30620 478.0899
## S-A-TA2   0.0000 478.9008 182.86060 198.3053 264.0038 200.93282 360.8130
## S-R-CT3 478.9008   0.0000 449.24826 478.0994 419.5474 411.12529 530.0566
## S-R-CP3 182.8606 449.2483   0.00000 324.5351 190.8612  74.14850 467.2216
## S-A-TA3 198.3053 478.0994 324.53505   0.0000 384.4750 344.01599 164.3624
## S-R-CT4 264.0038 419.5474 190.86121 384.4750   0.0000 195.29977 515.1932
## S-R-CP4 200.9328 411.1253  74.14850 344.0160 195.2998   0.00000 486.2016
## S-A-TA4 360.8130 530.0566 467.22157 164.3624 515.1932 486.20160   0.0000
## B-A-MU1 262.6481 494.5402 192.39023 377.5142 265.3413 207.01208 506.2549
## B-R-ET1 186.4457 461.2114  47.45524 334.1841 190.2735  88.34025 478.2384
## B-A-GU1 183.8777 462.0985  35.22783 333.2807 189.3278  82.22530 477.9676
## B-R-PC2 195.6246 447.5008  90.57041 315.9209 190.5282 122.53571 451.2815
## B-A-MU2 197.8686 427.9603 110.62549 282.7313 222.6971 140.52046 407.6175
## B-A-GU2 214.5623 466.3872 115.52922 352.2528 207.3089 137.12403 491.9075
## B-R-PC3 223.6672 423.6402 147.47542 315.7942 220.0114 170.50220 440.0898
## B-A-MU3 522.9532 505.9802 520.09038 399.2405 563.5140 534.39873 336.9926
## B-A-GU3 397.2719 518.7784 354.25273 483.3363 352.7846 362.13671 590.8849
## B-R-PC4 202.8398 461.7597  94.17006 341.0029 182.5541 119.84991 481.9544
## B-A-MU4 651.0146 647.9599 634.01104 643.0435 659.8833 626.19965 674.7548
## B-A-GU4 292.6124 476.7599 231.75849 398.4708 265.0623 244.09834 521.8716
##          B-A-MU1   B-R-ET1   B-A-GU1   B-R-PC2   B-A-MU2   B-A-GU2  B-R-PC3
## S-A-ZA1 190.6253  36.13862  16.27882  91.52595 119.74974 110.95495 151.5751
## S-R-CC1 209.0120 102.02941  97.90301  98.07650  68.23489 147.95607 133.5927
## S-R-CT1 287.5257 228.27396 227.05066 204.85605 165.63514 249.23483 183.3085
## S-R-CP1 191.4027  43.89761  30.36445  86.04650 106.08958 114.19282 135.9559
## S-A-TA1 190.9031  42.52058  28.40775  84.49260 103.04368 113.77610 140.1678
## S-R-CT2 344.8086 291.08590 293.41097 282.95583 262.98479 305.99020 259.3260
## S-R-CP2 197.5601  63.79655  55.07268 103.56158 125.71396 122.87799 157.5849
## S-A-TA2 262.6481 186.44570 183.87768 195.62464 197.86864 214.56235 223.6672
## S-R-CT3 494.5402 461.21145 462.09847 447.50084 427.96028 466.38718 423.6402
## S-R-CP3 192.3902  47.45524  35.22783  90.57041 110.62549 115.52922 147.4754
## S-A-TA3 377.5142 334.18408 333.28066 315.92088 282.73132 352.25275 315.7942
## S-R-CT4 265.3413 190.27349 189.32776 190.52821 222.69710 207.30895 220.0114
## S-R-CP4 207.0121  88.34025  82.22530 122.53571 140.52046 137.12403 170.5022
## S-A-TA4 506.2549 478.23843 477.96757 451.28151 407.61747 491.90751 440.0898
## B-A-MU1   0.0000 193.24078 183.63823 201.66556 151.28781 198.33557 225.3242
## B-R-ET1 193.2408   0.00000  36.53765  97.11334 119.98333 112.60107 151.2977
## B-A-GU1 183.6382  36.53765   0.00000  91.72786 115.33863  98.15294 149.6529
## B-R-PC2 201.6656  97.11334  91.72786   0.00000 114.92171 141.58390 114.7606
## B-A-MU2 151.2878 119.98333 115.33863 114.92171   0.00000 153.39817 143.1049
## B-A-GU2 198.3356 112.60107  98.15294 141.58390 153.39817   0.00000 173.1011
## B-R-PC3 225.3242 151.29772 149.65293 114.76062 143.10486 173.10113   0.0000
## B-A-MU3 505.4424 530.61097 531.72831 497.81221 422.87823 539.86572 476.5574
## B-A-GU3 381.5508 348.29729 342.49380 360.00556 364.76705 257.95736 337.1735
## B-R-PC4 205.1536  95.01579  89.16838 122.22520 142.70249 139.05035 150.8211
## B-A-MU4 498.8387 627.17462 635.41089 625.57414 550.83754 632.75193 618.9628
## B-A-GU4 289.1885 227.41592 219.20538 242.81886 251.58299 129.34837 239.0000
##          B-A-MU3  B-A-GU3   B-R-PC4  B-A-MU4  B-A-GU4
## S-A-ZA1 534.5372 353.0425  89.73294 641.2831 230.3606
## S-R-CC1 441.8959 363.5918 127.93748 612.2940 244.3890
## S-R-CT1 367.2261 396.0858 229.58005 595.5023 302.0546
## S-R-CP1 516.3729 353.7683  87.46999 631.3660 230.9264
## S-A-TA1 513.7081 353.5661  89.97778 633.6703 230.4951
## S-R-CT2 451.3635 414.4539 295.93411 590.7597 341.1700
## S-R-CP2 530.4394 356.9019 103.55675 633.8139 236.1144
## S-A-TA2 522.9532 397.2719 202.83984 651.0146 292.6124
## S-R-CT3 505.9802 518.7784 461.75968 647.9599 476.7599
## S-R-CP3 520.0904 354.2527  94.17006 634.0110 231.7585
## S-A-TA3 399.2405 483.3363 341.00293 643.0435 398.4708
## S-R-CT4 563.5140 352.7846 182.55410 659.8833 265.0623
## S-R-CP4 534.3987 362.1367 119.84991 626.1996 244.0983
## S-A-TA4 336.9926 590.8849 481.95435 674.7548 521.8716
## B-A-MU1 505.4424 381.5508 205.15360 498.8387 289.1885
## B-R-ET1 530.6110 348.2973  95.01579 627.1746 227.4159
## B-A-GU1 531.7283 342.4938  89.16838 635.4109 219.2054
## B-R-PC2 497.8122 360.0056 122.22520 625.5741 242.8189
## B-A-MU2 422.8782 364.7670 142.70249 550.8375 251.5830
## B-A-GU2 539.8657 257.9574 139.05035 632.7519 129.3484
## B-R-PC3 476.5574 337.1735 150.82109 618.9628 239.0000
## B-A-MU3   0.0000 624.8288 534.66812 519.9981 566.2808
## B-A-GU3 624.8288   0.0000 357.35557 707.3267 134.3763
## B-R-PC4 534.6681 357.3556   0.00000 641.2628 241.6402
## B-A-MU4 519.9981 707.3267 641.26282   0.0000 669.3982
## B-A-GU4 566.2808 134.3763 241.64023 669.3982   0.0000
## [1]   0.0000 707.3267
## [1] 274.908
## [1] 178.1842
## [1] 285.9043
## [1] 285.9043
## [1] 172.8375</code></pre>
</div>
<div id="criando-uma-lista" class="section level4" number="21.7.1.2">
<h4><span class="header-section-number">21.7.1.2</span> Criando uma Lista</h4>
<div class="sourceCode" id="cb524"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb524-1"><a href="outcentr.html#cb524-1" tabindex="-1"></a>centroide_ma <span class="ot">&lt;-</span> <span class="fu">mean</span>(euclid_ma, <span class="at">na.rm=</span>T)</span>
<span id="cb524-2"><a href="outcentr.html#cb524-2" tabindex="-1"></a>av.dist <span class="ot">&lt;-</span> (<span class="fu">as.matrix</span>(<span class="fu">colMeans</span>(euclid_ma, <span class="at">na.rm=</span>T)))</span>
<span id="cb524-3"><a href="outcentr.html#cb524-3" tabindex="-1"></a>av.desvpad <span class="ot">&lt;-</span> (<span class="fu">as.matrix</span>(<span class="fu">colSds</span>(euclid_ma, <span class="at">na.rm=</span>T)))</span>
<span id="cb524-4"><a href="outcentr.html#cb524-4" tabindex="-1"></a>dp.centroide_ma <span class="ot">&lt;-</span> (av.dist<span class="sc">-</span>centroide_ma)<span class="sc">/</span>(<span class="fu">colSds</span>(av.dist)) <span class="co">#ou z-scores</span></span>
<span id="cb524-5"><a href="outcentr.html#cb524-5" tabindex="-1"></a>list <span class="ot">&lt;-</span> <span class="fu">as.matrix</span>(<span class="fu">cbind</span>(av.dist, av.desvpad, dp.centroide_ma))</span>
<span id="cb524-6"><a href="outcentr.html#cb524-6" tabindex="-1"></a>list</span></code></pre></div>
<pre><code>##             [,1]      [,2]        [,3]
## S-A-ZA1 202.2608 175.36143 -0.74136373
## S-R-CC1 205.9912 142.40233 -0.70830031
## S-R-CT1 266.3790  93.46194 -0.17306037
## S-R-CP1 195.7828 170.97514 -0.79878039
## S-A-TA1 195.8495 170.39163 -0.79818963
## S-R-CT2 317.0479  82.87727  0.27603716
## S-R-CP2 207.1435 167.09006 -0.69808647
## S-A-TA2 268.5172 124.64348 -0.15410841
## S-R-CT3 455.6678  68.84928  1.50467759
## S-R-CP3 199.1922 170.79087 -0.76856181
## S-A-TA3 347.0119  92.95522  0.54161944
## S-R-CT4 280.9253 131.44373 -0.04413038
## S-R-CP4 217.3521 157.62618 -0.60760370
## S-A-TA4 458.7988  93.50892  1.53242940
## B-A-MU1 278.0482 116.17286 -0.06963167
## B-R-ET1 205.3272 169.74682 -0.71418525
## B-A-GU1 200.2219 174.32564 -0.75943496
## B-R-PC2 215.0274 152.54520 -0.62820821
## B-A-MU2 210.8910 128.79692 -0.66487097
## B-A-GU2 229.0481 151.90782 -0.50393825
## B-R-PC3 235.2979 130.07777 -0.44854354
## B-A-MU3 499.5754  64.70789  1.89384716
## B-A-GU3 394.6795 116.02951  0.96411611
## B-R-PC4 225.0953 158.58714 -0.53897264
## B-A-MU4 624.1237  45.46670  2.99776610
## B-A-GU4 298.2560 130.86907  0.10947773</code></pre>
<p>Ordenamos as distâncias da maior para a menor.</p>
<div class="sourceCode" id="cb526"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb526-1"><a href="outcentr.html#cb526-1" tabindex="-1"></a><span class="fu">colnames</span>(list, <span class="at">do.NULL =</span> <span class="cn">FALSE</span>)</span>
<span id="cb526-2"><a href="outcentr.html#cb526-2" tabindex="-1"></a><span class="fu">colnames</span>(list) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;Av.Dist&quot;</span>, <span class="st">&quot;Av.StDev&quot;</span>, <span class="st">&quot;DP.Centroide&quot;</span>)</span>
<span id="cb526-3"><a href="outcentr.html#cb526-3" tabindex="-1"></a>list2 <span class="ot">&lt;-</span> list[<span class="fu">order</span>(list[,<span class="dv">1</span>], <span class="at">decreasing =</span> <span class="cn">TRUE</span>),] <span class="co">#[,1] ou o nome da coluna</span></span>
<span id="cb526-4"><a href="outcentr.html#cb526-4" tabindex="-1"></a>list2</span></code></pre></div>
<pre><code>## [1] &quot;col1&quot; &quot;col2&quot; &quot;col3&quot;
##          Av.Dist  Av.StDev DP.Centroide
## B-A-MU4 624.1237  45.46670   2.99776610
## B-A-MU3 499.5754  64.70789   1.89384716
## S-A-TA4 458.7988  93.50892   1.53242940
## S-R-CT3 455.6678  68.84928   1.50467759
## B-A-GU3 394.6795 116.02951   0.96411611
## S-A-TA3 347.0119  92.95522   0.54161944
## S-R-CT2 317.0479  82.87727   0.27603716
## B-A-GU4 298.2560 130.86907   0.10947773
## S-R-CT4 280.9253 131.44373  -0.04413038
## B-A-MU1 278.0482 116.17286  -0.06963167
## S-A-TA2 268.5172 124.64348  -0.15410841
## S-R-CT1 266.3790  93.46194  -0.17306037
## B-R-PC3 235.2979 130.07777  -0.44854354
## B-A-GU2 229.0481 151.90782  -0.50393825
## B-R-PC4 225.0953 158.58714  -0.53897264
## S-R-CP4 217.3521 157.62618  -0.60760370
## B-R-PC2 215.0274 152.54520  -0.62820821
## B-A-MU2 210.8910 128.79692  -0.66487097
## S-R-CP2 207.1435 167.09006  -0.69808647
## S-R-CC1 205.9912 142.40233  -0.70830031
## B-R-ET1 205.3272 169.74682  -0.71418525
## S-A-ZA1 202.2608 175.36143  -0.74136373
## B-A-GU1 200.2219 174.32564  -0.75943496
## S-R-CP3 199.1922 170.79087  -0.76856181
## S-A-TA1 195.8495 170.39163  -0.79818963
## S-R-CP1 195.7828 170.97514  -0.79878039</code></pre>
</div>
</div>
<div id="distribuição-de-frequências-das-distâncias-médias-para-o-centróide-av.dist" class="section level3" number="21.7.2">
<h3><span class="header-section-number">21.7.2</span> Distribuição de frequências das distâncias médias para o centróide <code>av.dist</code></h3>
<p>Observe o valor maximo e minimo gerados pela função <code>range()</code> e substitua nas linhas de código assinaladas com <code>#</code>. Aqui o menor valor foi 195.7828431 e o maior valor foi 624.1236964. Use valores maiores para facilitar a visualização no gráfico (Figura <a href="outcentr.html#fig:6avdist">21.6</a>).</p>
<div class="sourceCode" id="cb528"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb528-1"><a href="outcentr.html#cb528-1" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">3</span>,<span class="dv">1</span>))</span>
<span id="cb528-2"><a href="outcentr.html#cb528-2" tabindex="-1"></a><span class="fu">hist</span>(list2[, <span class="st">&quot;Av.Dist&quot;</span>],</span>
<span id="cb528-3"><a href="outcentr.html#cb528-3" tabindex="-1"></a>     <span class="at">breaks =</span> <span class="dv">15</span>, <span class="co">#determina o no. de colunas do histograma</span></span>
<span id="cb528-4"><a href="outcentr.html#cb528-4" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">&quot;Distr. de Frequências das Distâncias (em dp) para o centroide&quot;</span>,</span>
<span id="cb528-5"><a href="outcentr.html#cb528-5" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">&quot;Distribuição de Frequência da distância média para o centroide&quot;</span>,</span>
<span id="cb528-6"><a href="outcentr.html#cb528-6" tabindex="-1"></a>     <span class="at">xlim =</span> <span class="fu">range</span>(<span class="fu">floor</span>(<span class="fu">min</span>(av.dist)), <span class="fu">ceiling</span>(<span class="fu">max</span>(av.dist))), <span class="co">#substitua aqui o menor e maior valor do `range()`</span></span>
<span id="cb528-7"><a href="outcentr.html#cb528-7" tabindex="-1"></a>     <span class="at">freq =</span> T)</span>
<span id="cb528-8"><a href="outcentr.html#cb528-8" tabindex="-1"></a><span class="fu">hist</span>(list2[, <span class="st">&quot;Av.Dist&quot;</span>],</span>
<span id="cb528-9"><a href="outcentr.html#cb528-9" tabindex="-1"></a>     <span class="at">breaks =</span> <span class="dv">15</span>, <span class="co">#determina o no. de colunas do histograma</span></span>
<span id="cb528-10"><a href="outcentr.html#cb528-10" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">&quot;Distr. de Frequências das Distâncias (em dp) para o centroide&quot;</span>,</span>
<span id="cb528-11"><a href="outcentr.html#cb528-11" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">&quot;Curva de normalidade ajustada para a Distribuição de Frequência&quot;</span>,</span>
<span id="cb528-12"><a href="outcentr.html#cb528-12" tabindex="-1"></a>     <span class="at">xlim =</span> <span class="fu">range</span>(<span class="fu">floor</span>(<span class="fu">min</span>(av.dist)), <span class="fu">ceiling</span>(<span class="fu">max</span>(av.dist))), <span class="co">#substitua aqui o menor e maior valor do `range()`</span></span>
<span id="cb528-13"><a href="outcentr.html#cb528-13" tabindex="-1"></a>     <span class="at">freq =</span> F)</span>
<span id="cb528-14"><a href="outcentr.html#cb528-14" tabindex="-1"></a><span class="fu">curve</span>(<span class="fu">dnorm</span>(x, <span class="at">mean=</span><span class="fu">mean</span>(list2[, <span class="st">&quot;Av.Dist&quot;</span>]), <span class="at">sd=</span><span class="fu">sd</span>(list2[, <span class="st">&quot;Av.Dist&quot;</span>])), <span class="at">add=</span><span class="cn">TRUE</span>)</span>
<span id="cb528-15"><a href="outcentr.html#cb528-15" tabindex="-1"></a><span class="fu">boxplot.default</span>(list2[, <span class="st">&quot;Av.Dist&quot;</span>], <span class="at">horizontal =</span> <span class="cn">TRUE</span>, <span class="at">frame =</span> <span class="cn">FALSE</span>,</span>
<span id="cb528-16"><a href="outcentr.html#cb528-16" tabindex="-1"></a>                <span class="at">xlab=</span><span class="st">&quot;Distr. de Frequências&quot;</span>,</span>
<span id="cb528-17"><a href="outcentr.html#cb528-17" tabindex="-1"></a>                <span class="at">ylim=</span><span class="fu">c</span>(<span class="fu">floor</span>(<span class="fu">min</span>(av.dist)), <span class="fu">ceiling</span>(<span class="fu">max</span>(av.dist)))) <span class="co">#substitua aqui o menor e maior valor do `range()`</span></span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:6avdist"></span>
<img src="fundamentos_de_ecologia_numerica_files/figure-html/6avdist-1.png" alt="Distribuição de frequências das distâncias médias para o centroide." width="672" />
<p class="caption">
Figura 21.6: Distribuição de frequências das distâncias médias para o centroide.
</p>
</div>
<div class="sourceCode" id="cb529"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb529-1"><a href="outcentr.html#cb529-1" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">1</span>))</span></code></pre></div>
<div id="distribuição-de-frequências-dos-desvios-padões-das-distâncias-médias-para-o-centróide-dp.centroide" class="section level4" number="21.7.2.1">
<h4><span class="header-section-number">21.7.2.1</span> Distribuição de frequências dos desvios padões das distâncias médias para o centróide <code>DP.Centroide</code></h4>
<p>Observe o valor máximo e mínimo gerados pela função <code>range()</code> e substitua nas linhas de código assinaladas com <code>#</code>. Aqui o menor valor foi -0.7987804 e o maior valor foi 2.9977661. Use valores maiores para facilitar a visualização no gráfico (Figura <a href="outcentr.html#fig:4centro">21.7</a>).</p>
<div class="sourceCode" id="cb530"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb530-1"><a href="outcentr.html#cb530-1" tabindex="-1"></a><span class="fu">range</span>(dp.centroide_ma)</span>
<span id="cb530-2"><a href="outcentr.html#cb530-2" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">3</span>,<span class="dv">1</span>))</span>
<span id="cb530-3"><a href="outcentr.html#cb530-3" tabindex="-1"></a><span class="fu">hist</span>(list2[, <span class="st">&quot;DP.Centroide&quot;</span>],</span>
<span id="cb530-4"><a href="outcentr.html#cb530-4" tabindex="-1"></a>     <span class="at">breaks =</span> <span class="dv">15</span>, <span class="co">#determina o no. de colunas do histograma</span></span>
<span id="cb530-5"><a href="outcentr.html#cb530-5" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">&quot;Distr. de Frequências das Distâncias dos desvios padões para o centroide&quot;</span>,</span>
<span id="cb530-6"><a href="outcentr.html#cb530-6" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">&quot;Distribuição de Frequência dos desvio padões das distâncias médias para o centroide&quot;</span>,</span>
<span id="cb530-7"><a href="outcentr.html#cb530-7" tabindex="-1"></a>     <span class="at">xlim =</span> <span class="fu">range</span>(<span class="fu">floor</span>(<span class="fu">min</span>(dp.centroide_ma)), <span class="fu">ceiling</span>(<span class="fu">max</span>(dp.centroide_ma))), <span class="co">#substitua aqui o menor e maior valor do `range()`</span></span>
<span id="cb530-8"><a href="outcentr.html#cb530-8" tabindex="-1"></a>     <span class="at">freq =</span> T)</span>
<span id="cb530-9"><a href="outcentr.html#cb530-9" tabindex="-1"></a><span class="fu">hist</span>(list2[, <span class="st">&quot;DP.Centroide&quot;</span>],</span>
<span id="cb530-10"><a href="outcentr.html#cb530-10" tabindex="-1"></a>     <span class="at">breaks =</span> <span class="dv">15</span>, <span class="co">#determina o no. de colunas do histograma</span></span>
<span id="cb530-11"><a href="outcentr.html#cb530-11" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">&quot;Distr. de Frequências das Distâncias dos desvios padrões das distâncias médias para o centroide&quot;</span>,</span>
<span id="cb530-12"><a href="outcentr.html#cb530-12" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">&quot;Curva de normalidade ajustada para a Distribuição de Frequência&quot;</span>,</span>
<span id="cb530-13"><a href="outcentr.html#cb530-13" tabindex="-1"></a>     <span class="at">xlim =</span> <span class="fu">range</span>(<span class="fu">floor</span>(<span class="fu">min</span>(dp.centroide_ma)), <span class="fu">ceiling</span>(<span class="fu">max</span>(dp.centroide_ma))), <span class="co">#substitua aqui o menor e maior valor do `range()`</span></span>
<span id="cb530-14"><a href="outcentr.html#cb530-14" tabindex="-1"></a>     <span class="at">freq =</span> F)</span>
<span id="cb530-15"><a href="outcentr.html#cb530-15" tabindex="-1"></a><span class="fu">curve</span>(<span class="fu">dnorm</span>(x, <span class="at">mean=</span><span class="fu">mean</span>(list2[, <span class="st">&quot;DP.Centroide&quot;</span>]), <span class="at">sd=</span><span class="fu">sd</span>(list2[, <span class="st">&quot;DP.Centroide&quot;</span>])), <span class="at">add=</span><span class="cn">TRUE</span>)</span>
<span id="cb530-16"><a href="outcentr.html#cb530-16" tabindex="-1"></a><span class="fu">boxplot.default</span>(list2[, <span class="st">&quot;DP.Centroide&quot;</span>], <span class="at">horizontal =</span> <span class="cn">TRUE</span>, <span class="at">frame =</span> <span class="cn">FALSE</span>,</span>
<span id="cb530-17"><a href="outcentr.html#cb530-17" tabindex="-1"></a>                <span class="at">xlab=</span><span class="st">&quot;Distr. de Frequências&quot;</span>,</span>
<span id="cb530-18"><a href="outcentr.html#cb530-18" tabindex="-1"></a>                <span class="at">ylim=</span><span class="fu">c</span>(<span class="fu">floor</span>(<span class="fu">min</span>(dp.centroide_ma)), <span class="fu">ceiling</span>(<span class="fu">max</span>(dp.centroide_ma)))) <span class="co">#substitua aqui o menor e maior valor do `range()`</span></span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:4centro"></span>
<img src="fundamentos_de_ecologia_numerica_files/figure-html/4centro-1.png" alt="Distribuição de frequências dos desvios padões das distâncias médias para o centroide." width="672" />
<p class="caption">
Figura 21.7: Distribuição de frequências dos desvios padões das distâncias médias para o centroide.
</p>
</div>
<div class="sourceCode" id="cb531"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb531-1"><a href="outcentr.html#cb531-1" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">1</span>))</span></code></pre></div>
<pre><code>## [1] -0.7987804  2.9977661</code></pre>
<p>Se necessário apague os gráficos</p>
<div class="sourceCode" id="cb533"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb533-1"><a href="outcentr.html#cb533-1" tabindex="-1"></a><span class="fu">dev.off</span>()</span></code></pre></div>
</div>
</div>
</div>
<div id="lista-final-de-outliers" class="section level2" number="21.8">
<h2><span class="header-section-number">21.8</span> Lista final de outliers</h2>
<p>Agora fazemos a lista final de distâncias com os outliers baseados em um ‘cutoff’.</p>
<div class="sourceCode" id="cb534"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb534-1"><a href="outcentr.html#cb534-1" tabindex="-1"></a>cutoff <span class="ot">&lt;-</span> <span class="fl">2.0</span></span></code></pre></div>
<p>Note que o ‘cutoff’ foi estabelecido no código acima no <code>vetor</code> ‘cutoff &lt;-’. Ou seja, o ‘cutoff’ definindo quem serão considerados outliers, foi estabelecido como sendo valores de <strong>+2.0</strong> e <strong>-2.0</strong> desvios padrões da média multivariada ou centroide. Valores acima ou abaixo do ‘cutoff’ definido recebem o nome “OUT”, na coluna “Outliers”. Criada com o código abaixo.</p>
<div class="sourceCode" id="cb535"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb535-1"><a href="outcentr.html#cb535-1" tabindex="-1"></a><span class="fu">library</span>(gt)</span>
<span id="cb535-2"><a href="outcentr.html#cb535-2" tabindex="-1"></a><span class="fu">format</span>(cutoff, <span class="at">nsmall =</span> <span class="dv">1</span>)</span>
<span id="cb535-3"><a href="outcentr.html#cb535-3" tabindex="-1"></a>listf <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(list2)</span>
<span id="cb535-4"><a href="outcentr.html#cb535-4" tabindex="-1"></a>listf<span class="sc">$</span>Outliers <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(listf<span class="sc">$</span>DP.Centroide<span class="sc">&gt;-</span>cutoff <span class="co">#CUTOFF MENOR QUE -&#39;cutoff</span></span>
<span id="cb535-5"><a href="outcentr.html#cb535-5" tabindex="-1"></a>                         <span class="sc">&amp;</span> listf<span class="sc">$</span>DP.Centroide<span class="sc">&lt;</span>cutoff,  <span class="co">#CUTOFF MAIOR QUE &#39;cutoff&#39;</span></span>
<span id="cb535-6"><a href="outcentr.html#cb535-6" tabindex="-1"></a>                         <span class="st">&quot;&quot;</span>, <span class="st">&quot;OUT&quot;</span>) </span>
<span id="cb535-7"><a href="outcentr.html#cb535-7" tabindex="-1"></a>listf</span>
<span id="cb535-8"><a href="outcentr.html#cb535-8" tabindex="-1"></a><span class="fu">gt</span>(<span class="fu">cbind</span>(<span class="at">Sitios=</span><span class="fu">rownames</span>(listf),listf))</span></code></pre></div>
<pre><code>## [1] &quot;2.0&quot;
##          Av.Dist  Av.StDev DP.Centroide Outliers
## B-A-MU4 624.1237  45.46670   2.99776610      OUT
## B-A-MU3 499.5754  64.70789   1.89384716         
## S-A-TA4 458.7988  93.50892   1.53242940         
## S-R-CT3 455.6678  68.84928   1.50467759         
## B-A-GU3 394.6795 116.02951   0.96411611         
## S-A-TA3 347.0119  92.95522   0.54161944         
## S-R-CT2 317.0479  82.87727   0.27603716         
## B-A-GU4 298.2560 130.86907   0.10947773         
## S-R-CT4 280.9253 131.44373  -0.04413038         
## B-A-MU1 278.0482 116.17286  -0.06963167         
## S-A-TA2 268.5172 124.64348  -0.15410841         
## S-R-CT1 266.3790  93.46194  -0.17306037         
## B-R-PC3 235.2979 130.07777  -0.44854354         
## B-A-GU2 229.0481 151.90782  -0.50393825         
## B-R-PC4 225.0953 158.58714  -0.53897264         
## S-R-CP4 217.3521 157.62618  -0.60760370         
## B-R-PC2 215.0274 152.54520  -0.62820821         
## B-A-MU2 210.8910 128.79692  -0.66487097         
## S-R-CP2 207.1435 167.09006  -0.69808647         
## S-R-CC1 205.9912 142.40233  -0.70830031         
## B-R-ET1 205.3272 169.74682  -0.71418525         
## S-A-ZA1 202.2608 175.36143  -0.74136373         
## B-A-GU1 200.2219 174.32564  -0.75943496         
## S-R-CP3 199.1922 170.79087  -0.76856181         
## S-A-TA1 195.8495 170.39163  -0.79818963         
## S-R-CP1 195.7828 170.97514  -0.79878039</code></pre>
<div id="opvzmirkwc" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>#opvzmirkwc table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#opvzmirkwc thead, #opvzmirkwc tbody, #opvzmirkwc tfoot, #opvzmirkwc tr, #opvzmirkwc td, #opvzmirkwc th {
  border-style: none;
}

#opvzmirkwc p {
  margin: 0;
  padding: 0;
}

#opvzmirkwc .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#opvzmirkwc .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#opvzmirkwc .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#opvzmirkwc .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#opvzmirkwc .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#opvzmirkwc .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#opvzmirkwc .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#opvzmirkwc .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#opvzmirkwc .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#opvzmirkwc .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#opvzmirkwc .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#opvzmirkwc .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#opvzmirkwc .gt_spanner_row {
  border-bottom-style: hidden;
}

#opvzmirkwc .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#opvzmirkwc .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#opvzmirkwc .gt_from_md > :first-child {
  margin-top: 0;
}

#opvzmirkwc .gt_from_md > :last-child {
  margin-bottom: 0;
}

#opvzmirkwc .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#opvzmirkwc .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#opvzmirkwc .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#opvzmirkwc .gt_row_group_first td {
  border-top-width: 2px;
}

#opvzmirkwc .gt_row_group_first th {
  border-top-width: 2px;
}

#opvzmirkwc .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#opvzmirkwc .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#opvzmirkwc .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#opvzmirkwc .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#opvzmirkwc .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#opvzmirkwc .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#opvzmirkwc .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#opvzmirkwc .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#opvzmirkwc .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#opvzmirkwc .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#opvzmirkwc .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#opvzmirkwc .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#opvzmirkwc .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#opvzmirkwc .gt_left {
  text-align: left;
}

#opvzmirkwc .gt_center {
  text-align: center;
}

#opvzmirkwc .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#opvzmirkwc .gt_font_normal {
  font-weight: normal;
}

#opvzmirkwc .gt_font_bold {
  font-weight: bold;
}

#opvzmirkwc .gt_font_italic {
  font-style: italic;
}

#opvzmirkwc .gt_super {
  font-size: 65%;
}

#opvzmirkwc .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#opvzmirkwc .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#opvzmirkwc .gt_indent_1 {
  text-indent: 5px;
}

#opvzmirkwc .gt_indent_2 {
  text-indent: 10px;
}

#opvzmirkwc .gt_indent_3 {
  text-indent: 15px;
}

#opvzmirkwc .gt_indent_4 {
  text-indent: 20px;
}

#opvzmirkwc .gt_indent_5 {
  text-indent: 25px;
}

#opvzmirkwc .katex-display {
  display: inline-flex !important;
  margin-bottom: 0.75em !important;
}

#opvzmirkwc div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {
  height: 0px !important;
}
</style>
<table class="gt_table" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
  <thead>
    <tr class="gt_col_headings">
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" scope="col" id="Sitios">Sitios</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="Av.Dist">Av.Dist</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="Av.StDev">Av.StDev</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="DP.Centroide">DP.Centroide</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" scope="col" id="Outliers">Outliers</th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td headers="Sitios" class="gt_row gt_left">B-A-MU4</td>
<td headers="Av.Dist" class="gt_row gt_right">624.1237</td>
<td headers="Av.StDev" class="gt_row gt_right">45.46670</td>
<td headers="DP.Centroide" class="gt_row gt_right">2.99776610</td>
<td headers="Outliers" class="gt_row gt_left">OUT</td></tr>
    <tr><td headers="Sitios" class="gt_row gt_left">B-A-MU3</td>
<td headers="Av.Dist" class="gt_row gt_right">499.5754</td>
<td headers="Av.StDev" class="gt_row gt_right">64.70789</td>
<td headers="DP.Centroide" class="gt_row gt_right">1.89384716</td>
<td headers="Outliers" class="gt_row gt_left"></td></tr>
    <tr><td headers="Sitios" class="gt_row gt_left">S-A-TA4</td>
<td headers="Av.Dist" class="gt_row gt_right">458.7988</td>
<td headers="Av.StDev" class="gt_row gt_right">93.50892</td>
<td headers="DP.Centroide" class="gt_row gt_right">1.53242940</td>
<td headers="Outliers" class="gt_row gt_left"></td></tr>
    <tr><td headers="Sitios" class="gt_row gt_left">S-R-CT3</td>
<td headers="Av.Dist" class="gt_row gt_right">455.6678</td>
<td headers="Av.StDev" class="gt_row gt_right">68.84928</td>
<td headers="DP.Centroide" class="gt_row gt_right">1.50467759</td>
<td headers="Outliers" class="gt_row gt_left"></td></tr>
    <tr><td headers="Sitios" class="gt_row gt_left">B-A-GU3</td>
<td headers="Av.Dist" class="gt_row gt_right">394.6795</td>
<td headers="Av.StDev" class="gt_row gt_right">116.02951</td>
<td headers="DP.Centroide" class="gt_row gt_right">0.96411611</td>
<td headers="Outliers" class="gt_row gt_left"></td></tr>
    <tr><td headers="Sitios" class="gt_row gt_left">S-A-TA3</td>
<td headers="Av.Dist" class="gt_row gt_right">347.0119</td>
<td headers="Av.StDev" class="gt_row gt_right">92.95522</td>
<td headers="DP.Centroide" class="gt_row gt_right">0.54161944</td>
<td headers="Outliers" class="gt_row gt_left"></td></tr>
    <tr><td headers="Sitios" class="gt_row gt_left">S-R-CT2</td>
<td headers="Av.Dist" class="gt_row gt_right">317.0479</td>
<td headers="Av.StDev" class="gt_row gt_right">82.87727</td>
<td headers="DP.Centroide" class="gt_row gt_right">0.27603716</td>
<td headers="Outliers" class="gt_row gt_left"></td></tr>
    <tr><td headers="Sitios" class="gt_row gt_left">B-A-GU4</td>
<td headers="Av.Dist" class="gt_row gt_right">298.2560</td>
<td headers="Av.StDev" class="gt_row gt_right">130.86907</td>
<td headers="DP.Centroide" class="gt_row gt_right">0.10947773</td>
<td headers="Outliers" class="gt_row gt_left"></td></tr>
    <tr><td headers="Sitios" class="gt_row gt_left">S-R-CT4</td>
<td headers="Av.Dist" class="gt_row gt_right">280.9253</td>
<td headers="Av.StDev" class="gt_row gt_right">131.44373</td>
<td headers="DP.Centroide" class="gt_row gt_right">-0.04413038</td>
<td headers="Outliers" class="gt_row gt_left"></td></tr>
    <tr><td headers="Sitios" class="gt_row gt_left">B-A-MU1</td>
<td headers="Av.Dist" class="gt_row gt_right">278.0482</td>
<td headers="Av.StDev" class="gt_row gt_right">116.17286</td>
<td headers="DP.Centroide" class="gt_row gt_right">-0.06963167</td>
<td headers="Outliers" class="gt_row gt_left"></td></tr>
    <tr><td headers="Sitios" class="gt_row gt_left">S-A-TA2</td>
<td headers="Av.Dist" class="gt_row gt_right">268.5172</td>
<td headers="Av.StDev" class="gt_row gt_right">124.64348</td>
<td headers="DP.Centroide" class="gt_row gt_right">-0.15410841</td>
<td headers="Outliers" class="gt_row gt_left"></td></tr>
    <tr><td headers="Sitios" class="gt_row gt_left">S-R-CT1</td>
<td headers="Av.Dist" class="gt_row gt_right">266.3790</td>
<td headers="Av.StDev" class="gt_row gt_right">93.46194</td>
<td headers="DP.Centroide" class="gt_row gt_right">-0.17306037</td>
<td headers="Outliers" class="gt_row gt_left"></td></tr>
    <tr><td headers="Sitios" class="gt_row gt_left">B-R-PC3</td>
<td headers="Av.Dist" class="gt_row gt_right">235.2979</td>
<td headers="Av.StDev" class="gt_row gt_right">130.07777</td>
<td headers="DP.Centroide" class="gt_row gt_right">-0.44854354</td>
<td headers="Outliers" class="gt_row gt_left"></td></tr>
    <tr><td headers="Sitios" class="gt_row gt_left">B-A-GU2</td>
<td headers="Av.Dist" class="gt_row gt_right">229.0481</td>
<td headers="Av.StDev" class="gt_row gt_right">151.90782</td>
<td headers="DP.Centroide" class="gt_row gt_right">-0.50393825</td>
<td headers="Outliers" class="gt_row gt_left"></td></tr>
    <tr><td headers="Sitios" class="gt_row gt_left">B-R-PC4</td>
<td headers="Av.Dist" class="gt_row gt_right">225.0953</td>
<td headers="Av.StDev" class="gt_row gt_right">158.58714</td>
<td headers="DP.Centroide" class="gt_row gt_right">-0.53897264</td>
<td headers="Outliers" class="gt_row gt_left"></td></tr>
    <tr><td headers="Sitios" class="gt_row gt_left">S-R-CP4</td>
<td headers="Av.Dist" class="gt_row gt_right">217.3521</td>
<td headers="Av.StDev" class="gt_row gt_right">157.62618</td>
<td headers="DP.Centroide" class="gt_row gt_right">-0.60760370</td>
<td headers="Outliers" class="gt_row gt_left"></td></tr>
    <tr><td headers="Sitios" class="gt_row gt_left">B-R-PC2</td>
<td headers="Av.Dist" class="gt_row gt_right">215.0274</td>
<td headers="Av.StDev" class="gt_row gt_right">152.54520</td>
<td headers="DP.Centroide" class="gt_row gt_right">-0.62820821</td>
<td headers="Outliers" class="gt_row gt_left"></td></tr>
    <tr><td headers="Sitios" class="gt_row gt_left">B-A-MU2</td>
<td headers="Av.Dist" class="gt_row gt_right">210.8910</td>
<td headers="Av.StDev" class="gt_row gt_right">128.79692</td>
<td headers="DP.Centroide" class="gt_row gt_right">-0.66487097</td>
<td headers="Outliers" class="gt_row gt_left"></td></tr>
    <tr><td headers="Sitios" class="gt_row gt_left">S-R-CP2</td>
<td headers="Av.Dist" class="gt_row gt_right">207.1435</td>
<td headers="Av.StDev" class="gt_row gt_right">167.09006</td>
<td headers="DP.Centroide" class="gt_row gt_right">-0.69808647</td>
<td headers="Outliers" class="gt_row gt_left"></td></tr>
    <tr><td headers="Sitios" class="gt_row gt_left">S-R-CC1</td>
<td headers="Av.Dist" class="gt_row gt_right">205.9912</td>
<td headers="Av.StDev" class="gt_row gt_right">142.40233</td>
<td headers="DP.Centroide" class="gt_row gt_right">-0.70830031</td>
<td headers="Outliers" class="gt_row gt_left"></td></tr>
    <tr><td headers="Sitios" class="gt_row gt_left">B-R-ET1</td>
<td headers="Av.Dist" class="gt_row gt_right">205.3272</td>
<td headers="Av.StDev" class="gt_row gt_right">169.74682</td>
<td headers="DP.Centroide" class="gt_row gt_right">-0.71418525</td>
<td headers="Outliers" class="gt_row gt_left"></td></tr>
    <tr><td headers="Sitios" class="gt_row gt_left">S-A-ZA1</td>
<td headers="Av.Dist" class="gt_row gt_right">202.2608</td>
<td headers="Av.StDev" class="gt_row gt_right">175.36143</td>
<td headers="DP.Centroide" class="gt_row gt_right">-0.74136373</td>
<td headers="Outliers" class="gt_row gt_left"></td></tr>
    <tr><td headers="Sitios" class="gt_row gt_left">B-A-GU1</td>
<td headers="Av.Dist" class="gt_row gt_right">200.2219</td>
<td headers="Av.StDev" class="gt_row gt_right">174.32564</td>
<td headers="DP.Centroide" class="gt_row gt_right">-0.75943496</td>
<td headers="Outliers" class="gt_row gt_left"></td></tr>
    <tr><td headers="Sitios" class="gt_row gt_left">S-R-CP3</td>
<td headers="Av.Dist" class="gt_row gt_right">199.1922</td>
<td headers="Av.StDev" class="gt_row gt_right">170.79087</td>
<td headers="DP.Centroide" class="gt_row gt_right">-0.76856181</td>
<td headers="Outliers" class="gt_row gt_left"></td></tr>
    <tr><td headers="Sitios" class="gt_row gt_left">S-A-TA1</td>
<td headers="Av.Dist" class="gt_row gt_right">195.8495</td>
<td headers="Av.StDev" class="gt_row gt_right">170.39163</td>
<td headers="DP.Centroide" class="gt_row gt_right">-0.79818963</td>
<td headers="Outliers" class="gt_row gt_left"></td></tr>
    <tr><td headers="Sitios" class="gt_row gt_left">S-R-CP1</td>
<td headers="Av.Dist" class="gt_row gt_right">195.7828</td>
<td headers="Av.StDev" class="gt_row gt_right">170.97514</td>
<td headers="DP.Centroide" class="gt_row gt_right">-0.79878039</td>
<td headers="Outliers" class="gt_row gt_left"></td></tr>
  </tbody>
  
</table>
</div>
</div>
<div id="particionando-a-matriz" class="section level2" number="21.9">
<h2><span class="header-section-number">21.9</span> Particionando a matriz</h2>
<p>Talvez seja necessário particionar a matriz bruta para remover os outliers. Isso pode ser feito com os códigos abaixo. Atente para o <code>vetor</code> <strong><code>part</code></strong>. Ele define quais objetos ou UA’s serão particionados.</p>
<div class="sourceCode" id="cb537"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb537-1"><a href="outcentr.html#cb537-1" tabindex="-1"></a>part <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;B-A-MU4&quot;</span>, <span class="st">&quot;B-A-MU3&quot;</span>, <span class="st">&quot;S-A-TA4&quot;</span>, <span class="st">&quot;S-R-CT3&quot;</span>)</span>
<span id="cb537-2"><a href="outcentr.html#cb537-2" tabindex="-1"></a>part</span></code></pre></div>
<pre><code>## [1] &quot;B-A-MU4&quot; &quot;B-A-MU3&quot; &quot;S-A-TA4&quot; &quot;S-R-CT3&quot;</code></pre>
<div class="sourceCode" id="cb539"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb539-1"><a href="outcentr.html#cb539-1" tabindex="-1"></a>m_bruta_part <span class="ot">&lt;-</span> m_bruta[<span class="sc">!</span>(<span class="fu">row.names</span>(m_bruta) <span class="sc">%in%</span> <span class="fu">c</span>(part)),]</span>
<span id="cb539-2"><a href="outcentr.html#cb539-2" tabindex="-1"></a><span class="co">#m_bruta_part</span></span></code></pre></div>
<p>Criamos uma nova matriz particionada <code>m_bruta_part</code> sem <strong>B-A-MU4, B-A-MU3, S-A-TA4, S-R-CT3</strong>, que apresentavam valores acima do cutoff para outliers.</p>
<div class="greeting message" style="color: green;">
<p><span style="color:red">ATENÇÃO</span><br />
Quando deletamos linhas ou colunas da matriz de dados comunitária, precisamos ver se isso não gerou linhas ou colunas vazias. Observe por exemplo a espécie <em>Apareiodon davisi</em> <a href="#fn16" class="footnote-ref" id="fnref16"><sup>16</sup></a> (Figura <a href="outcentr.html#fig:6apdavis">21.8</a>). Por exemplo, se uma determinada espécie só ocorre em uma UA, e aquela UA foi removida, essa espécie não consta mais em nenhuma UA e por isso a sua soma vai ser igual a zero. Isso aconteceu com a espécie <em>Pseudancistrus genisetiger</em> <a href="#fn17" class="footnote-ref" id="fnref17"><sup>17</sup></a> (Figura <a href="outcentr.html#fig:6pgen">21.9</a>). Essa espécie precisará ser removida.</p>
</div>
<div class="figure"><span style="display:block;" id="fig:6apdavis"></span>
<img src="imagens/spp/Apdav_u0.jpg" alt="*Apareiodon davisi*, importante espécie bentopelágica das bacias dos rios Jaguaribe e Paraíba. Brazil, by Ramos, T.P.A. Fonte: &lt;https://www.fishbase.se/summary/Astianax-bimaculatus.html&gt;" width="320" />
<p class="caption">
Figura 21.8: <em>Apareiodon davisi</em>, importante espécie bentopelágica das bacias dos rios Jaguaribe e Paraíba. Brazil, by Ramos, T.P.A. Fonte: <a href="https://www.fishbase.se/summary/Astianax-bimaculatus.html" class="uri">https://www.fishbase.se/summary/Astianax-bimaculatus.html</a>
</p>
</div>
<div class="figure"><span style="display:block;" id="fig:6pgen"></span>
<img src="imagens/spp/genis.jpg" alt="*Pseudancistrus genisetiger*, uma espécie endêmica das bacias hidrográfcas do nordeste. By eplanetcatfish.com. Fonte: &lt;https://www.planetcatfish.com&gt; (Provável identificação errada do espécime da foto)](eplanetcatfish.jpg)" width="800" />
<p class="caption">
Figura 21.9: <em>Pseudancistrus genisetiger</em>, uma espécie endêmica das bacias hidrográfcas do nordeste. By eplanetcatfish.com. Fonte: <a href="https://www.planetcatfish.com" class="uri">https://www.planetcatfish.com</a> (Provável identificação errada do espécime da foto)](eplanetcatfish.jpg)
</p>
</div>
<p>Use o a função <code>View(m_bruta_part)</code> e procure linhas ou colunas na matriz <code>m_bruta_part</code> onde todos os valores são zero. Quais espécies você encontrou que deixaram de ocorrer na comunidade depois que as UA’s outliers foram removidas?.</p>
<p>Complicado? Os códigos abaixo resolvem isso, e mostram algumas propriedades da nova matriz <code>m_bruta_part2</code> depois de particionada pela segunda vez para remover linhas/colunas “zeradas”.</p>
<div class="sourceCode" id="cb540"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb540-1"><a href="outcentr.html#cb540-1" tabindex="-1"></a>sum <span class="ot">&lt;-</span> <span class="fu">colSums</span>(m_bruta_part)</span>
<span id="cb540-2"><a href="outcentr.html#cb540-2" tabindex="-1"></a>sum</span>
<span id="cb540-3"><a href="outcentr.html#cb540-3" tabindex="-1"></a>zero_sum_cols <span class="ot">&lt;-</span> <span class="fu">names</span>(<span class="fu">which</span>(<span class="fu">colSums</span>(m_bruta_part) <span class="sc">==</span> <span class="dv">0</span>))</span>
<span id="cb540-4"><a href="outcentr.html#cb540-4" tabindex="-1"></a>zero_sum_cols <span class="co">#nomes das espécies zeradas</span></span>
<span id="cb540-5"><a href="outcentr.html#cb540-5" tabindex="-1"></a>m_bruta_part2 <span class="ot">&lt;-</span> m_bruta_part[(<span class="fu">colSums</span>(m_bruta_part) <span class="sc">!=</span> <span class="dv">0</span>)] <span class="co">#em != a exclamação inverte o sentido</span></span>
<span id="cb540-6"><a href="outcentr.html#cb540-6" tabindex="-1"></a>zero_sum_cols2 <span class="ot">&lt;-</span> <span class="fu">names</span>(<span class="fu">which</span>(<span class="fu">colSums</span>(m_bruta_part2) <span class="sc">==</span> <span class="dv">0</span>))</span>
<span id="cb540-7"><a href="outcentr.html#cb540-7" tabindex="-1"></a>zero_sum_cols2 <span class="co">#nomes das espécies zeradas</span></span>
<span id="cb540-8"><a href="outcentr.html#cb540-8" tabindex="-1"></a>sum<span class="ot">&lt;-</span><span class="fu">colSums</span>(m_bruta_part2)</span>
<span id="cb540-9"><a href="outcentr.html#cb540-9" tabindex="-1"></a>sum</span>
<span id="cb540-10"><a href="outcentr.html#cb540-10" tabindex="-1"></a><span class="co">#m_bruta_part2</span></span>
<span id="cb540-11"><a href="outcentr.html#cb540-11" tabindex="-1"></a><span class="co">#m_bruta_part2 &lt;- as.matrix(m_bruta_part2)</span></span>
<span id="cb540-12"><a href="outcentr.html#cb540-12" tabindex="-1"></a><span class="fu">str</span>(m_bruta_part2)</span>
<span id="cb540-13"><a href="outcentr.html#cb540-13" tabindex="-1"></a><span class="fu">length</span>(<span class="fu">as.matrix</span>(m_bruta_part2))</span></code></pre></div>
<pre><code>##  ap-davis  as-bimac  as-fasci  ch-bimac  ci-ocela  ci-orien  co-macro  co-heter 
##        27      1040        94       432        70       118         2         1 
##  cr-menez  cu-lepid  cy-gilbe  ge-brasi  he-margi  ho-malab  hy-pusar  le-melan 
##        19        21       131       364         2        69        60         2 
##   le-piau  le-taeni  mo-costa  mo-lepid  or-nilot  pa-manag  pimel-sp  po-retic 
##        11         1         1        41       697       554         6        64 
##  po-vivip  pr-brevi  ps-rhomb ps-genise  se-heter  se-piaba  se-spilo  st-noton 
##       441       111         0         0       258        68         0        90 
##  sy-marmo  te-chalc  tr-signa 
##         1       134       201 
## [1] &quot;ps-rhomb&quot;  &quot;ps-genise&quot; &quot;se-spilo&quot; 
## character(0)
## ap-davis as-bimac as-fasci ch-bimac ci-ocela ci-orien co-macro co-heter 
##       27     1040       94      432       70      118        2        1 
## cr-menez cu-lepid cy-gilbe ge-brasi he-margi ho-malab hy-pusar le-melan 
##       19       21      131      364        2       69       60        2 
##  le-piau le-taeni mo-costa mo-lepid or-nilot pa-manag pimel-sp po-retic 
##       11        1        1       41      697      554        6       64 
## po-vivip pr-brevi se-heter se-piaba st-noton sy-marmo te-chalc tr-signa 
##      441      111      258       68       90        1      134      201 
## &#39;data.frame&#39;:    22 obs. of  32 variables:
##  $ ap-davis: num  0 0 0 0 0 0 0 0 0 0 ...
##  $ as-bimac: num  1 99 194 19 23 142 5 46 16 234 ...
##  $ as-fasci: num  0 0 55 0 1 3 1 0 0 7 ...
##  $ ch-bimac: num  0 0 0 0 13 3 0 178 0 238 ...
##  $ ci-ocela: num  0 0 0 0 0 0 40 0 13 0 ...
##  $ ci-orien: num  0 0 5 0 0 69 9 0 24 0 ...
##  $ co-macro: num  0 0 0 0 0 0 0 0 0 2 ...
##  $ co-heter: num  0 0 1 0 0 0 0 0 0 0 ...
##  $ cr-menez: num  0 0 14 0 0 4 0 0 0 0 ...
##  $ cu-lepid: num  0 0 0 0 0 0 0 0 0 0 ...
##  $ cy-gilbe: num  0 0 0 0 0 0 0 0 0 0 ...
##  $ ge-brasi: num  0 0 3 0 0 0 0 0 0 0 ...
##  $ he-margi: num  0 0 0 0 0 1 0 0 0 0 ...
##  $ ho-malab: num  0 0 1 5 0 17 10 2 4 20 ...
##  $ hy-pusar: num  0 0 9 2 0 43 2 0 0 0 ...
##  $ le-melan: num  0 0 0 0 0 0 0 0 0 0 ...
##  $ le-piau : num  0 0 3 0 0 1 3 0 1 0 ...
##  $ le-taeni: num  0 0 0 0 0 0 0 0 0 0 ...
##  $ mo-costa: num  0 0 0 0 0 0 0 0 0 0 ...
##  $ mo-lepid: num  0 1 39 0 0 1 0 0 0 0 ...
##  $ or-nilot: num  0 2 36 0 0 77 0 0 0 0 ...
##  $ pa-manag: num  0 0 0 0 0 0 0 0 0 0 ...
##  $ pimel-sp: num  0 0 6 0 0 0 0 0 0 0 ...
##  $ po-retic: num  0 0 0 0 0 20 0 0 0 0 ...
##  $ po-vivip: num  0 0 47 15 0 221 32 0 10 0 ...
##  $ pr-brevi: num  9 0 5 0 1 15 5 2 0 0 ...
##  $ se-heter: num  0 0 40 14 4 60 0 0 0 0 ...
##  $ se-piaba: num  0 0 68 0 0 0 0 0 0 0 ...
##  $ st-noton: num  0 0 1 0 0 25 0 0 0 0 ...
##  $ sy-marmo: num  0 0 0 0 0 0 1 0 0 0 ...
##  $ te-chalc: num  0 0 0 0 0 0 0 0 0 0 ...
##  $ tr-signa: num  0 0 18 0 0 15 0 0 0 0 ...
## [1] 704</code></pre>
</div>
<div id="exportando-a-matrix-final-de-trabalho" class="section level2" number="21.10">
<h2><span class="header-section-number">21.10</span> Exportando a matrix final de trabalho</h2>
<p>Agora vamos exportar a matrix de trabalho, nesse casso a matrix <code>m_bruta_part2</code>, como um arquivo de valores separados por vírgula (<code>m_bruta_part2csv.csv</code>). Na verdade, separado por <code>";"</code>, como definido na funçao <code>sep = ";"</code>. O arquivo será exportado para o diretório de trabalho. Na mesma sequência de códigos, importamos <code>m_bruta_part2csv.csv</code> como nossa matriz de trabalho <code>m_trab</code>.</p>
<div class="sourceCode" id="cb542"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb542-1"><a href="outcentr.html#cb542-1" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Sites =</span> <span class="fu">rownames</span>(m_bruta), m_bruta,</span>
<span id="cb542-2"><a href="outcentr.html#cb542-2" tabindex="-1"></a>                 <span class="at">row.names =</span> <span class="cn">NULL</span>,</span>
<span id="cb542-3"><a href="outcentr.html#cb542-3" tabindex="-1"></a>                 <span class="at">check.names =</span> <span class="cn">FALSE</span>) <span class="co">#add titulo a primeira coluna</span></span>
<span id="cb542-4"><a href="outcentr.html#cb542-4" tabindex="-1"></a></span>
<span id="cb542-5"><a href="outcentr.html#cb542-5" tabindex="-1"></a><span class="fu">write.table</span>(m_bruta_part2, <span class="st">&quot;m_trabcsv.csv&quot;</span>,</span>
<span id="cb542-6"><a href="outcentr.html#cb542-6" tabindex="-1"></a>            <span class="at">sep =</span> <span class="st">&quot;;&quot;</span>, <span class="at">dec =</span> <span class="st">&quot;.&quot;</span>, <span class="co">#&quot;\t&quot;,</span></span>
<span id="cb542-7"><a href="outcentr.html#cb542-7" tabindex="-1"></a>            <span class="at">row.names =</span> <span class="cn">TRUE</span>,</span>
<span id="cb542-8"><a href="outcentr.html#cb542-8" tabindex="-1"></a>            <span class="at">quote =</span> <span class="cn">TRUE</span>,</span>
<span id="cb542-9"><a href="outcentr.html#cb542-9" tabindex="-1"></a>            <span class="at">append =</span> <span class="cn">FALSE</span>)</span>
<span id="cb542-10"><a href="outcentr.html#cb542-10" tabindex="-1"></a></span>
<span id="cb542-11"><a href="outcentr.html#cb542-11" tabindex="-1"></a>m_trab <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&quot;m_trabcsv.csv&quot;</span>,</span>
<span id="cb542-12"><a href="outcentr.html#cb542-12" tabindex="-1"></a>                   <span class="at">sep =</span> <span class="st">&quot;;&quot;</span>, <span class="at">dec =</span> <span class="st">&quot;.&quot;</span>,</span>
<span id="cb542-13"><a href="outcentr.html#cb542-13" tabindex="-1"></a>                   <span class="at">row.names =</span> <span class="dv">1</span>,</span>
<span id="cb542-14"><a href="outcentr.html#cb542-14" tabindex="-1"></a>                   <span class="at">header =</span> <span class="cn">TRUE</span>, </span>
<span id="cb542-15"><a href="outcentr.html#cb542-15" tabindex="-1"></a>                   <span class="at">na.strings =</span> <span class="cn">NA</span>,</span>
<span id="cb542-16"><a href="outcentr.html#cb542-16" tabindex="-1"></a>                   <span class="at">check.names =</span> <span class="cn">FALSE</span>, <span class="co">#impede que o R mude os nomes das colunas</span></span>
<span id="cb542-17"><a href="outcentr.html#cb542-17" tabindex="-1"></a>                   <span class="at">col.names =</span> <span class="fu">gsub</span>(<span class="st">&quot;(^|_)([a-z])&quot;</span>, <span class="st">&quot;</span><span class="sc">\\</span><span class="st">1</span><span class="sc">\\</span><span class="st">U</span><span class="sc">\\</span><span class="st">2&quot;</span>,</span>
<span id="cb542-18"><a href="outcentr.html#cb542-18" tabindex="-1"></a>                                    <span class="fu">names</span>(m_trab), <span class="at">perl =</span> <span class="cn">TRUE</span>))</span></code></pre></div>
<ul>
<li>Inicial Maiuscula:col.names = gsub(“(^|_)([a-z])“,”\1\U\2”, names(m_trab), perl = TRUE))<br />
</li>
<li>Substituição: col.names = gsub(“-”, “.”, names(m_trab)))<br />
</li>
<li>A função <code>header=</code> especifica se o arquivo de entrada contém uma linha de cabeçalho com os nomes das colunas, <code>row.names</code> especifica qual coluna no arquivo de entrada deve ser usada como os nomes das linhas, e se <code>NULL</code>, os nomes das linhas são gerados como números</li>
</ul>
<p>Agora é com você…Refaça toda a análise com a matriz bruta particionada <code>m_bruta_part2</code></p>
</div>
<div id="apêndices-14" class="section level2 unnumbered">
<h2>Apêndices</h2>
<div id="outras-formas-de-fazer-a-partição" class="section level3 unnumbered">
<h3>Outras formas de fazer a partição</h3>
<p>m_bruta_part2 &lt;- m_bruta_part<span class="math display">\[colSums(abs(m_bruta_part), na.rm = F) \&gt; 0\]</span>
m_bruta_part2 &lt;- subset(m_bruta_part, colSums != 0) m_bruta_part2 &lt;-
m_bruta_part<span class="math display">\[, colSums(m_bruta_part != 0) \&gt; 0\]</span></p>
</div>
<div id="código" class="section level3 unnumbered">
<h3>Código</h3>
<p>range(euclidma) par(mfrow=c(2,1)) hist(euclidma, breaks = 15, #determina
o no. de colunas do histograma xlim = range(floor(min(euclidma)),
ceiling(max(euclidma))), xlab = “Distr. de Frequências”, freq = FALSE)
curve(dnorm(x, mean=mean(euclidma), sd=sd(euclidma)), add=TRUE)
boxplot.default(euclidma, horizontal = TRUE, frame = FALSE, xlab=“Distr.
de Frequências”, ylim=c(floor(min(euclidma)), ceiling(max(euclidma))))</p>
</div>
</div>
<div id="script-limpo-11" class="section level2 unnumbered">
<h2>Script limpo</h2>
<p>Aqui apresento o scrip na íntegra sem os textos ou outros comentários. Você pode copiar e colar no R para executa-lo. Lembre de remover os <span style="color:green"><code>#</code></span> ou <span style="color:green"><code>##</code></span> caso necessite executar essas linhas.</p>
<div class="sourceCode" id="cb543"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb543-1"><a href="outcentr.html#cb543-1" tabindex="-1"></a><span class="do">## dev.off() #apaga os graficos, se houver algum</span></span>
<span id="cb543-2"><a href="outcentr.html#cb543-2" tabindex="-1"></a><span class="do">## rm(list=ls(all=TRUE)) #limpa a memória</span></span>
<span id="cb543-3"><a href="outcentr.html#cb543-3" tabindex="-1"></a><span class="do">## cat(&quot;\014&quot;) #limpa o console</span></span>
<span id="cb543-4"><a href="outcentr.html#cb543-4" tabindex="-1"></a><span class="do">## install.packages(&quot;openxlsx&quot;) #importa arquivos do excel</span></span>
<span id="cb543-5"><a href="outcentr.html#cb543-5" tabindex="-1"></a><span class="do">## install.packages(&quot;moments&quot;) #calcula assimetria e curtose dos dados</span></span>
<span id="cb543-6"><a href="outcentr.html#cb543-6" tabindex="-1"></a><span class="do">## install.packages(&quot;matrixStats&quot;) #fornece funções rápidas para a estatística de matrizes</span></span>
<span id="cb543-7"><a href="outcentr.html#cb543-7" tabindex="-1"></a><span class="do">## install.packages(&quot;gt&quot;) #ferramenta para criação de tabelas bonitas e personalizáveis</span></span>
<span id="cb543-8"><a href="outcentr.html#cb543-8" tabindex="-1"></a><span class="do">## getwd()</span></span>
<span id="cb543-9"><a href="outcentr.html#cb543-9" tabindex="-1"></a><span class="do">## setwd(&quot;C:/Seu/Diretório/De/Trabalho&quot;)</span></span>
<span id="cb543-10"><a href="outcentr.html#cb543-10" tabindex="-1"></a><span class="fu">library</span>(openxlsx)</span>
<span id="cb543-11"><a href="outcentr.html#cb543-11" tabindex="-1"></a>m_bruta <span class="ot">&lt;-</span> <span class="fu">read.xlsx</span>(<span class="st">&quot;D:/Elvio/OneDrive/Disciplinas/_EcoNumerica/5.Matrizes/peixes06.xlsx&quot;</span>,</span>
<span id="cb543-12"><a href="outcentr.html#cb543-12" tabindex="-1"></a>                   <span class="at">rowNames =</span> T, <span class="at">colNames =</span> T,</span>
<span id="cb543-13"><a href="outcentr.html#cb543-13" tabindex="-1"></a>                   <span class="at">sheet =</span> <span class="st">&quot;Sheet1&quot;</span>)</span>
<span id="cb543-14"><a href="outcentr.html#cb543-14" tabindex="-1"></a><span class="fu">str</span>(m_bruta)</span>
<span id="cb543-15"><a href="outcentr.html#cb543-15" tabindex="-1"></a>m_bruta_ma <span class="ot">&lt;-</span> <span class="fu">as.matrix</span>(m_bruta) <span class="co">#lê m_bruta como uma matriz</span></span>
<span id="cb543-16"><a href="outcentr.html#cb543-16" tabindex="-1"></a><span class="fu">str</span>(m_bruta_ma)</span>
<span id="cb543-17"><a href="outcentr.html#cb543-17" tabindex="-1"></a><span class="co">#m_bruta</span></span>
<span id="cb543-18"><a href="outcentr.html#cb543-18" tabindex="-1"></a>m_bruta_ma[<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>,<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>] <span class="co">#[1:5,1:5] mostra apenas as linhas e colunas de 1 a 5.</span></span>
<span id="cb543-19"><a href="outcentr.html#cb543-19" tabindex="-1"></a><span class="co">#m_bruta &lt;- (m_bruta)   # &lt;1&gt;</span></span>
<span id="cb543-20"><a href="outcentr.html#cb543-20" tabindex="-1"></a><span class="co">#View(m_bruta)</span></span>
<span id="cb543-21"><a href="outcentr.html#cb543-21" tabindex="-1"></a><span class="fu">print</span>(m_bruta)</span>
<span id="cb543-22"><a href="outcentr.html#cb543-22" tabindex="-1"></a><span class="fu">head</span>(m_bruta)</span>
<span id="cb543-23"><a href="outcentr.html#cb543-23" tabindex="-1"></a><span class="fu">str</span>(m_bruta)</span>
<span id="cb543-24"><a href="outcentr.html#cb543-24" tabindex="-1"></a><span class="fu">mode</span>(m_bruta)</span>
<span id="cb543-25"><a href="outcentr.html#cb543-25" tabindex="-1"></a><span class="fu">class</span>(m_bruta)</span>
<span id="cb543-26"><a href="outcentr.html#cb543-26" tabindex="-1"></a><span class="co">#?str</span></span>
<span id="cb543-27"><a href="outcentr.html#cb543-27" tabindex="-1"></a><span class="fu">range</span>(m_bruta) <span class="co">#menor e maior valores</span></span>
<span id="cb543-28"><a href="outcentr.html#cb543-28" tabindex="-1"></a><span class="fu">length</span>(m_bruta) <span class="co">#no. de colunas</span></span>
<span id="cb543-29"><a href="outcentr.html#cb543-29" tabindex="-1"></a><span class="fu">ncol</span>(m_bruta) <span class="co">#no. de N colunas</span></span>
<span id="cb543-30"><a href="outcentr.html#cb543-30" tabindex="-1"></a><span class="fu">nrow</span>(m_bruta) <span class="co">#no. de M linhas</span></span>
<span id="cb543-31"><a href="outcentr.html#cb543-31" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">lengths</span>(m_bruta)) <span class="co">#soma os nos. de colunas</span></span>
<span id="cb543-32"><a href="outcentr.html#cb543-32" tabindex="-1"></a><span class="fu">length</span>(<span class="fu">as.matrix</span>(m_bruta)) <span class="co">#tamanho da matriz m x n</span></span>
<span id="cb543-33"><a href="outcentr.html#cb543-33" tabindex="-1"></a><span class="fu">sum</span>(m_bruta <span class="sc">==</span> <span class="dv">0</span>) <span class="co"># número de observações igual a zero</span></span>
<span id="cb543-34"><a href="outcentr.html#cb543-34" tabindex="-1"></a><span class="fu">sum</span>(m_bruta <span class="sc">&gt;</span> <span class="dv">0</span>) <span class="co"># número de observações maiores que zero</span></span>
<span id="cb543-35"><a href="outcentr.html#cb543-35" tabindex="-1"></a>zeros <span class="ot">&lt;-</span> (<span class="fu">sum</span>(m_bruta <span class="sc">==</span> <span class="dv">0</span>)<span class="sc">/</span><span class="fu">length</span>(<span class="fu">as.matrix</span>(m_bruta)))<span class="sc">*</span><span class="dv">100</span> <span class="co"># proporção de zeros na matriz</span></span>
<span id="cb543-36"><a href="outcentr.html#cb543-36" tabindex="-1"></a>zeros</span>
<span id="cb543-37"><a href="outcentr.html#cb543-37" tabindex="-1"></a>tamanho <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb543-38"><a href="outcentr.html#cb543-38" tabindex="-1"></a>  Função <span class="ot">=</span> <span class="fu">c</span>(<span class="st">&quot;range&quot;</span>, <span class="st">&quot;lenght&quot;</span>, <span class="st">&quot;m cols&quot;</span>, <span class="st">&quot;n linhas&quot;</span>, <span class="st">&quot;Tamanho&quot;</span>, <span class="st">&quot;Tamanho&quot;</span>,</span>
<span id="cb543-39"><a href="outcentr.html#cb543-39" tabindex="-1"></a>             <span class="st">&quot;Zeros&quot;</span>, <span class="st">&quot;Nao zeros&quot;</span>, <span class="st">&quot;% Zeros&quot;</span>),</span>
<span id="cb543-40"><a href="outcentr.html#cb543-40" tabindex="-1"></a>  <span class="at">Resultado =</span> <span class="fu">c</span>(<span class="fu">paste</span>(<span class="fu">range</span>(m_bruta), <span class="at">collapse =</span> <span class="st">&quot; - &quot;</span>), <span class="fu">length</span>(m_bruta), <span class="fu">ncol</span>(m_bruta),</span>
<span id="cb543-41"><a href="outcentr.html#cb543-41" tabindex="-1"></a>                <span class="fu">nrow</span>(m_bruta), <span class="fu">sum</span>(<span class="fu">lengths</span>(m_bruta)), <span class="fu">length</span>(<span class="fu">as.matrix</span>(m_bruta)), <span class="fu">sum</span>(m_bruta <span class="sc">==</span> <span class="dv">0</span>),</span>
<span id="cb543-42"><a href="outcentr.html#cb543-42" tabindex="-1"></a>                <span class="fu">sum</span>(m_bruta <span class="sc">&gt;</span> <span class="dv">0</span>), <span class="fu">round</span>(zeros, <span class="dv">1</span>))</span>
<span id="cb543-43"><a href="outcentr.html#cb543-43" tabindex="-1"></a>)</span>
<span id="cb543-44"><a href="outcentr.html#cb543-44" tabindex="-1"></a>tamanho</span>
<span id="cb543-45"><a href="outcentr.html#cb543-45" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(tamanho, <span class="at">format =</span> <span class="st">&quot;markdown&quot;</span>, <span class="at">caption =</span> <span class="st">&quot;Resumo das informações sobre o tamanho da matriz&quot;</span>)</span>
<span id="cb543-46"><a href="outcentr.html#cb543-46" tabindex="-1"></a>euclid <span class="ot">&lt;-</span> <span class="fu">dist</span>(m_bruta, <span class="at">method =</span> <span class="st">&quot;euclidian&quot;</span>, <span class="at">diag =</span> <span class="cn">TRUE</span>, <span class="at">upper =</span> <span class="cn">FALSE</span>)</span>
<span id="cb543-47"><a href="outcentr.html#cb543-47" tabindex="-1"></a><span class="co">#?dist</span></span>
<span id="cb543-48"><a href="outcentr.html#cb543-48" tabindex="-1"></a><span class="co">#euclid</span></span>
<span id="cb543-49"><a href="outcentr.html#cb543-49" tabindex="-1"></a><span class="fu">str</span>(euclid)</span>
<span id="cb543-50"><a href="outcentr.html#cb543-50" tabindex="-1"></a><span class="fu">mode</span>(euclid)</span>
<span id="cb543-51"><a href="outcentr.html#cb543-51" tabindex="-1"></a><span class="fu">class</span>(euclid)</span>
<span id="cb543-52"><a href="outcentr.html#cb543-52" tabindex="-1"></a><span class="fu">length</span>(<span class="fu">as.matrix</span>(euclid))</span>
<span id="cb543-53"><a href="outcentr.html#cb543-53" tabindex="-1"></a><span class="fu">as.matrix</span>(euclid)[<span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>, <span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>] <span class="co">#mostra as 5 primeiras linhas e colunas da matriz</span></span>
<span id="cb543-54"><a href="outcentr.html#cb543-54" tabindex="-1"></a>euclid_ma <span class="ot">&lt;-</span> (<span class="fu">as.matrix</span>(euclid))</span>
<span id="cb543-55"><a href="outcentr.html#cb543-55" tabindex="-1"></a><span class="co">#View(euclid_ma)</span></span>
<span id="cb543-56"><a href="outcentr.html#cb543-56" tabindex="-1"></a><span class="fu">str</span>(euclid_ma)</span>
<span id="cb543-57"><a href="outcentr.html#cb543-57" tabindex="-1"></a><span class="fu">mode</span>(euclid_ma)</span>
<span id="cb543-58"><a href="outcentr.html#cb543-58" tabindex="-1"></a><span class="fu">class</span>(euclid_ma)</span>
<span id="cb543-59"><a href="outcentr.html#cb543-59" tabindex="-1"></a>euclid_ma[<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>, <span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>] <span class="co">#mostra as 5 primeiras linhas e colunas da matriz</span></span>
<span id="cb543-60"><a href="outcentr.html#cb543-60" tabindex="-1"></a><span class="fu">range</span>(m_bruta)</span>
<span id="cb543-61"><a href="outcentr.html#cb543-61" tabindex="-1"></a><span class="fu">range</span>(euclid)</span>
<span id="cb543-62"><a href="outcentr.html#cb543-62" tabindex="-1"></a><span class="fu">min</span>(euclid)</span>
<span id="cb543-63"><a href="outcentr.html#cb543-63" tabindex="-1"></a><span class="fu">max</span>(euclid)</span>
<span id="cb543-64"><a href="outcentr.html#cb543-64" tabindex="-1"></a><span class="fu">mean</span>(euclid) <span class="co">#CENTROIDE!! OU Grand mean</span></span>
<span id="cb543-65"><a href="outcentr.html#cb543-65" tabindex="-1"></a><span class="fu">sd</span>(euclid)  <span class="co">#Standard deviation</span></span>
<span id="cb543-66"><a href="outcentr.html#cb543-66" tabindex="-1"></a>centroide <span class="ot">&lt;-</span> <span class="fu">mean</span>(euclid)</span>
<span id="cb543-67"><a href="outcentr.html#cb543-67" tabindex="-1"></a>centroide</span>
<span id="cb543-68"><a href="outcentr.html#cb543-68" tabindex="-1"></a><span class="fu">length</span>(euclid)</span>
<span id="cb543-69"><a href="outcentr.html#cb543-69" tabindex="-1"></a>m <span class="ot">&lt;-</span> <span class="fu">nrow</span>(m_bruta)</span>
<span id="cb543-70"><a href="outcentr.html#cb543-70" tabindex="-1"></a>m</span>
<span id="cb543-71"><a href="outcentr.html#cb543-71" tabindex="-1"></a>m<span class="sc">*</span>(m<span class="dv">-1</span>)<span class="sc">/</span><span class="dv">2</span></span>
<span id="cb543-72"><a href="outcentr.html#cb543-72" tabindex="-1"></a><span class="fu">summary</span>(euclid)</span>
<span id="cb543-73"><a href="outcentr.html#cb543-73" tabindex="-1"></a>Sumario1 <span class="ot">&lt;-</span> <span class="fu">cbind</span>(<span class="fu">min</span>(euclid),</span>
<span id="cb543-74"><a href="outcentr.html#cb543-74" tabindex="-1"></a>                  <span class="fu">max</span>(euclid),</span>
<span id="cb543-75"><a href="outcentr.html#cb543-75" tabindex="-1"></a>                  <span class="fu">sd</span>(euclid),</span>
<span id="cb543-76"><a href="outcentr.html#cb543-76" tabindex="-1"></a>                  <span class="fu">mean</span>(euclid),</span>
<span id="cb543-77"><a href="outcentr.html#cb543-77" tabindex="-1"></a>                  <span class="fu">length</span>(euclid))</span>
<span id="cb543-78"><a href="outcentr.html#cb543-78" tabindex="-1"></a><span class="fu">colnames</span>(Sumario1) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;Minimo&quot;</span>, <span class="st">&quot;Maximo&quot;</span>, <span class="st">&quot;Desv.Padr&quot;</span>, <span class="st">&quot;Media&quot;</span>, <span class="st">&quot;m(m-1)/2&quot;</span>)</span>
<span id="cb543-79"><a href="outcentr.html#cb543-79" tabindex="-1"></a><span class="fu">rownames</span>(Sumario1) <span class="ot">&lt;-</span> (<span class="st">&quot;Valores&quot;</span>)</span>
<span id="cb543-80"><a href="outcentr.html#cb543-80" tabindex="-1"></a>Sumario1</span>
<span id="cb543-81"><a href="outcentr.html#cb543-81" tabindex="-1"></a><span class="fu">range</span>(euclid)</span>
<span id="cb543-82"><a href="outcentr.html#cb543-82" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">1</span>))</span>
<span id="cb543-83"><a href="outcentr.html#cb543-83" tabindex="-1"></a><span class="fu">hist</span>(euclid,</span>
<span id="cb543-84"><a href="outcentr.html#cb543-84" tabindex="-1"></a>     <span class="at">breaks =</span> <span class="dv">15</span>, <span class="co">#determina o no. de colunas do histograma</span></span>
<span id="cb543-85"><a href="outcentr.html#cb543-85" tabindex="-1"></a>     <span class="at">xlim =</span> <span class="fu">range</span>(<span class="fu">floor</span>(<span class="fu">min</span>(euclid)), <span class="fu">ceiling</span>(<span class="fu">max</span>(euclid))), </span>
<span id="cb543-86"><a href="outcentr.html#cb543-86" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">&quot;Distr. de Frequências&quot;</span>,</span>
<span id="cb543-87"><a href="outcentr.html#cb543-87" tabindex="-1"></a>     <span class="at">freq =</span> <span class="cn">FALSE</span>)</span>
<span id="cb543-88"><a href="outcentr.html#cb543-88" tabindex="-1"></a><span class="fu">curve</span>(<span class="fu">dnorm</span>(x, <span class="at">mean=</span><span class="fu">mean</span>(euclid), <span class="at">sd=</span><span class="fu">sd</span>(euclid)), <span class="at">add=</span><span class="cn">TRUE</span>)</span>
<span id="cb543-89"><a href="outcentr.html#cb543-89" tabindex="-1"></a><span class="fu">boxplot.default</span>(euclid, <span class="at">horizontal =</span> <span class="cn">TRUE</span>, <span class="at">frame =</span> <span class="cn">FALSE</span>,</span>
<span id="cb543-90"><a href="outcentr.html#cb543-90" tabindex="-1"></a>                <span class="at">xlab=</span><span class="st">&quot;Distr. de Frequências&quot;</span>,</span>
<span id="cb543-91"><a href="outcentr.html#cb543-91" tabindex="-1"></a>                <span class="at">ylim=</span><span class="fu">c</span>(<span class="fu">floor</span>(<span class="fu">min</span>(euclid)), <span class="fu">ceiling</span>(<span class="fu">max</span>(euclid)))) <span class="co">#Limites do eixo Y</span></span>
<span id="cb543-92"><a href="outcentr.html#cb543-92" tabindex="-1"></a><span class="do">## dev.off()</span></span>
<span id="cb543-93"><a href="outcentr.html#cb543-93" tabindex="-1"></a><span class="fu">library</span>(matrixStats)</span>
<span id="cb543-94"><a href="outcentr.html#cb543-94" tabindex="-1"></a><span class="fu">library</span>(moments)</span>
<span id="cb543-95"><a href="outcentr.html#cb543-95" tabindex="-1"></a>euclid_ma <span class="ot">&lt;-</span> <span class="fu">as.matrix</span>(euclid)</span>
<span id="cb543-96"><a href="outcentr.html#cb543-96" tabindex="-1"></a>euclid_ma</span>
<span id="cb543-97"><a href="outcentr.html#cb543-97" tabindex="-1"></a><span class="fu">range</span>(euclid_ma) <span class="co">#valor errado</span></span>
<span id="cb543-98"><a href="outcentr.html#cb543-98" tabindex="-1"></a><span class="fu">mean</span>(euclid_ma) <span class="co">#valor errado</span></span>
<span id="cb543-99"><a href="outcentr.html#cb543-99" tabindex="-1"></a><span class="fu">sd</span>(euclid_ma) <span class="co">#valor errado</span></span>
<span id="cb543-100"><a href="outcentr.html#cb543-100" tabindex="-1"></a><span class="fu">is.na</span>(euclid_ma) <span class="ot">&lt;-</span> euclid_ma<span class="sc">==</span><span class="dv">0</span> <span class="co">#atribui n.a. aos valores = 0</span></span>
<span id="cb543-101"><a href="outcentr.html#cb543-101" tabindex="-1"></a><span class="fu">mean</span>(euclid_ma, <span class="at">na.rm=</span>T)  <span class="co">#valor correto, omite valores n.a. do calculo</span></span>
<span id="cb543-102"><a href="outcentr.html#cb543-102" tabindex="-1"></a><span class="fu">mean</span>(euclid_ma, <span class="at">na.rm=</span>T) <span class="co">#valor correto, omite valores n.a. do calculo</span></span>
<span id="cb543-103"><a href="outcentr.html#cb543-103" tabindex="-1"></a><span class="fu">sd</span>(euclid_ma, <span class="at">na.rm=</span>T) <span class="co">#valor correto, omite valores n.a. do calculo</span></span>
<span id="cb543-104"><a href="outcentr.html#cb543-104" tabindex="-1"></a><span class="co">#colMeans(euclid_ma, na.rm=T) #omite valores n.a. do calculo</span></span>
<span id="cb543-105"><a href="outcentr.html#cb543-105" tabindex="-1"></a><span class="co">#rowMeans(euclid_ma, na.rm=T) #omite valores n.a. do calculo</span></span>
<span id="cb543-106"><a href="outcentr.html#cb543-106" tabindex="-1"></a>centroide_ma <span class="ot">&lt;-</span> <span class="fu">mean</span>(euclid_ma, <span class="at">na.rm=</span>T)</span>
<span id="cb543-107"><a href="outcentr.html#cb543-107" tabindex="-1"></a>av.dist <span class="ot">&lt;-</span> (<span class="fu">as.matrix</span>(<span class="fu">colMeans</span>(euclid_ma, <span class="at">na.rm=</span>T)))</span>
<span id="cb543-108"><a href="outcentr.html#cb543-108" tabindex="-1"></a>av.desvpad <span class="ot">&lt;-</span> (<span class="fu">as.matrix</span>(<span class="fu">colSds</span>(euclid_ma, <span class="at">na.rm=</span>T)))</span>
<span id="cb543-109"><a href="outcentr.html#cb543-109" tabindex="-1"></a>dp.centroide_ma <span class="ot">&lt;-</span> (av.dist<span class="sc">-</span>centroide_ma)<span class="sc">/</span>(<span class="fu">colSds</span>(av.dist)) <span class="co">#ou z-scores</span></span>
<span id="cb543-110"><a href="outcentr.html#cb543-110" tabindex="-1"></a>list <span class="ot">&lt;-</span> <span class="fu">as.matrix</span>(<span class="fu">cbind</span>(av.dist, av.desvpad, dp.centroide_ma))</span>
<span id="cb543-111"><a href="outcentr.html#cb543-111" tabindex="-1"></a>list</span>
<span id="cb543-112"><a href="outcentr.html#cb543-112" tabindex="-1"></a><span class="fu">colnames</span>(list, <span class="at">do.NULL =</span> <span class="cn">FALSE</span>)</span>
<span id="cb543-113"><a href="outcentr.html#cb543-113" tabindex="-1"></a><span class="fu">colnames</span>(list) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;Av.Dist&quot;</span>, <span class="st">&quot;Av.StDev&quot;</span>, <span class="st">&quot;DP.Centroide&quot;</span>)</span>
<span id="cb543-114"><a href="outcentr.html#cb543-114" tabindex="-1"></a>list2 <span class="ot">&lt;-</span> list[<span class="fu">order</span>(list[,<span class="dv">1</span>], <span class="at">decreasing =</span> <span class="cn">TRUE</span>),] <span class="co">#[,1] ou o nome da coluna</span></span>
<span id="cb543-115"><a href="outcentr.html#cb543-115" tabindex="-1"></a>list2</span>
<span id="cb543-116"><a href="outcentr.html#cb543-116" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">3</span>,<span class="dv">1</span>))</span>
<span id="cb543-117"><a href="outcentr.html#cb543-117" tabindex="-1"></a><span class="fu">hist</span>(list2[, <span class="st">&quot;Av.Dist&quot;</span>],</span>
<span id="cb543-118"><a href="outcentr.html#cb543-118" tabindex="-1"></a>     <span class="at">breaks =</span> <span class="dv">15</span>, <span class="co">#determina o no. de colunas do histograma</span></span>
<span id="cb543-119"><a href="outcentr.html#cb543-119" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">&quot;Distr. de Frequências das Distâncias (em dp) para o centroide&quot;</span>,</span>
<span id="cb543-120"><a href="outcentr.html#cb543-120" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">&quot;Distribuição de Frequência da distância média para o centroide&quot;</span>,</span>
<span id="cb543-121"><a href="outcentr.html#cb543-121" tabindex="-1"></a>     <span class="at">xlim =</span> <span class="fu">range</span>(<span class="fu">floor</span>(<span class="fu">min</span>(av.dist)), <span class="fu">ceiling</span>(<span class="fu">max</span>(av.dist))), <span class="co">#substitua aqui o menor e maior valor do `range()`</span></span>
<span id="cb543-122"><a href="outcentr.html#cb543-122" tabindex="-1"></a>     <span class="at">freq =</span> T)</span>
<span id="cb543-123"><a href="outcentr.html#cb543-123" tabindex="-1"></a><span class="fu">hist</span>(list2[, <span class="st">&quot;Av.Dist&quot;</span>],</span>
<span id="cb543-124"><a href="outcentr.html#cb543-124" tabindex="-1"></a>     <span class="at">breaks =</span> <span class="dv">15</span>, <span class="co">#determina o no. de colunas do histograma</span></span>
<span id="cb543-125"><a href="outcentr.html#cb543-125" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">&quot;Distr. de Frequências das Distâncias (em dp) para o centroide&quot;</span>,</span>
<span id="cb543-126"><a href="outcentr.html#cb543-126" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">&quot;Curva de normalidade ajustada para a Distribuição de Frequência&quot;</span>,</span>
<span id="cb543-127"><a href="outcentr.html#cb543-127" tabindex="-1"></a>     <span class="at">xlim =</span> <span class="fu">range</span>(<span class="fu">floor</span>(<span class="fu">min</span>(av.dist)), <span class="fu">ceiling</span>(<span class="fu">max</span>(av.dist))), <span class="co">#substitua aqui o menor e maior valor do `range()`</span></span>
<span id="cb543-128"><a href="outcentr.html#cb543-128" tabindex="-1"></a>     <span class="at">freq =</span> F)</span>
<span id="cb543-129"><a href="outcentr.html#cb543-129" tabindex="-1"></a><span class="fu">curve</span>(<span class="fu">dnorm</span>(x, <span class="at">mean=</span><span class="fu">mean</span>(list2[, <span class="st">&quot;Av.Dist&quot;</span>]), <span class="at">sd=</span><span class="fu">sd</span>(list2[, <span class="st">&quot;Av.Dist&quot;</span>])), <span class="at">add=</span><span class="cn">TRUE</span>)</span>
<span id="cb543-130"><a href="outcentr.html#cb543-130" tabindex="-1"></a><span class="fu">boxplot.default</span>(list2[, <span class="st">&quot;Av.Dist&quot;</span>], <span class="at">horizontal =</span> <span class="cn">TRUE</span>, <span class="at">frame =</span> <span class="cn">FALSE</span>,</span>
<span id="cb543-131"><a href="outcentr.html#cb543-131" tabindex="-1"></a>                <span class="at">xlab=</span><span class="st">&quot;Distr. de Frequências&quot;</span>,</span>
<span id="cb543-132"><a href="outcentr.html#cb543-132" tabindex="-1"></a>                <span class="at">ylim=</span><span class="fu">c</span>(<span class="fu">floor</span>(<span class="fu">min</span>(av.dist)), <span class="fu">ceiling</span>(<span class="fu">max</span>(av.dist)))) <span class="co">#substitua aqui o menor e maior valor do `range()`</span></span>
<span id="cb543-133"><a href="outcentr.html#cb543-133" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">1</span>))</span>
<span id="cb543-134"><a href="outcentr.html#cb543-134" tabindex="-1"></a><span class="fu">range</span>(dp.centroide_ma)</span>
<span id="cb543-135"><a href="outcentr.html#cb543-135" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">3</span>,<span class="dv">1</span>))</span>
<span id="cb543-136"><a href="outcentr.html#cb543-136" tabindex="-1"></a><span class="fu">hist</span>(list2[, <span class="st">&quot;DP.Centroide&quot;</span>],</span>
<span id="cb543-137"><a href="outcentr.html#cb543-137" tabindex="-1"></a>     <span class="at">breaks =</span> <span class="dv">15</span>, <span class="co">#determina o no. de colunas do histograma</span></span>
<span id="cb543-138"><a href="outcentr.html#cb543-138" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">&quot;Distr. de Frequências das Distâncias dos desvios padões para o centroide&quot;</span>,</span>
<span id="cb543-139"><a href="outcentr.html#cb543-139" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">&quot;Distribuição de Frequência dos desvio padões das distâncias médias para o centroide&quot;</span>,</span>
<span id="cb543-140"><a href="outcentr.html#cb543-140" tabindex="-1"></a>     <span class="at">xlim =</span> <span class="fu">range</span>(<span class="fu">floor</span>(<span class="fu">min</span>(dp.centroide_ma)), <span class="fu">ceiling</span>(<span class="fu">max</span>(dp.centroide_ma))), <span class="co">#substitua aqui o menor e maior valor do `range()`</span></span>
<span id="cb543-141"><a href="outcentr.html#cb543-141" tabindex="-1"></a>     <span class="at">freq =</span> T)</span>
<span id="cb543-142"><a href="outcentr.html#cb543-142" tabindex="-1"></a><span class="fu">hist</span>(list2[, <span class="st">&quot;DP.Centroide&quot;</span>],</span>
<span id="cb543-143"><a href="outcentr.html#cb543-143" tabindex="-1"></a>     <span class="at">breaks =</span> <span class="dv">15</span>, <span class="co">#determina o no. de colunas do histograma</span></span>
<span id="cb543-144"><a href="outcentr.html#cb543-144" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">&quot;Distr. de Frequências das Distâncias dos desvios padrões das distâncias médias para o centroide&quot;</span>,</span>
<span id="cb543-145"><a href="outcentr.html#cb543-145" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">&quot;Curva de normalidade ajustada para a Distribuição de Frequência&quot;</span>,</span>
<span id="cb543-146"><a href="outcentr.html#cb543-146" tabindex="-1"></a>     <span class="at">xlim =</span> <span class="fu">range</span>(<span class="fu">floor</span>(<span class="fu">min</span>(dp.centroide_ma)), <span class="fu">ceiling</span>(<span class="fu">max</span>(dp.centroide_ma))), <span class="co">#substitua aqui o menor e maior valor do `range()`</span></span>
<span id="cb543-147"><a href="outcentr.html#cb543-147" tabindex="-1"></a>     <span class="at">freq =</span> F)</span>
<span id="cb543-148"><a href="outcentr.html#cb543-148" tabindex="-1"></a><span class="fu">curve</span>(<span class="fu">dnorm</span>(x, <span class="at">mean=</span><span class="fu">mean</span>(list2[, <span class="st">&quot;DP.Centroide&quot;</span>]), <span class="at">sd=</span><span class="fu">sd</span>(list2[, <span class="st">&quot;DP.Centroide&quot;</span>])), <span class="at">add=</span><span class="cn">TRUE</span>)</span>
<span id="cb543-149"><a href="outcentr.html#cb543-149" tabindex="-1"></a><span class="fu">boxplot.default</span>(list2[, <span class="st">&quot;DP.Centroide&quot;</span>], <span class="at">horizontal =</span> <span class="cn">TRUE</span>, <span class="at">frame =</span> <span class="cn">FALSE</span>,</span>
<span id="cb543-150"><a href="outcentr.html#cb543-150" tabindex="-1"></a>                <span class="at">xlab=</span><span class="st">&quot;Distr. de Frequências&quot;</span>,</span>
<span id="cb543-151"><a href="outcentr.html#cb543-151" tabindex="-1"></a>                <span class="at">ylim=</span><span class="fu">c</span>(<span class="fu">floor</span>(<span class="fu">min</span>(dp.centroide_ma)), <span class="fu">ceiling</span>(<span class="fu">max</span>(dp.centroide_ma)))) <span class="co">#substitua aqui o menor e maior valor do `range()`</span></span>
<span id="cb543-152"><a href="outcentr.html#cb543-152" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">1</span>))</span>
<span id="cb543-153"><a href="outcentr.html#cb543-153" tabindex="-1"></a><span class="do">## dev.off()</span></span>
<span id="cb543-154"><a href="outcentr.html#cb543-154" tabindex="-1"></a>cutoff <span class="ot">&lt;-</span> <span class="fl">2.0</span></span>
<span id="cb543-155"><a href="outcentr.html#cb543-155" tabindex="-1"></a><span class="fu">library</span>(gt)</span>
<span id="cb543-156"><a href="outcentr.html#cb543-156" tabindex="-1"></a><span class="fu">format</span>(cutoff, <span class="at">nsmall =</span> <span class="dv">1</span>)</span>
<span id="cb543-157"><a href="outcentr.html#cb543-157" tabindex="-1"></a>listf <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(list2)</span>
<span id="cb543-158"><a href="outcentr.html#cb543-158" tabindex="-1"></a>listf<span class="sc">$</span>Outliers <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(listf<span class="sc">$</span>DP.Centroide<span class="sc">&gt;-</span>cutoff <span class="co">#CUTOFF MENOR QUE -&#39;cutoff</span></span>
<span id="cb543-159"><a href="outcentr.html#cb543-159" tabindex="-1"></a>                         <span class="sc">&amp;</span> listf<span class="sc">$</span>DP.Centroide<span class="sc">&lt;</span>cutoff,  <span class="co">#CUTOFF MAIOR QUE &#39;cutoff&#39;</span></span>
<span id="cb543-160"><a href="outcentr.html#cb543-160" tabindex="-1"></a>                         <span class="st">&quot;&quot;</span>, <span class="st">&quot;OUT&quot;</span>) </span>
<span id="cb543-161"><a href="outcentr.html#cb543-161" tabindex="-1"></a>listf</span>
<span id="cb543-162"><a href="outcentr.html#cb543-162" tabindex="-1"></a><span class="fu">gt</span>(<span class="fu">cbind</span>(<span class="at">Sitios=</span><span class="fu">rownames</span>(listf),listf))</span>
<span id="cb543-163"><a href="outcentr.html#cb543-163" tabindex="-1"></a>part <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;B-A-MU4&quot;</span>, <span class="st">&quot;B-A-MU3&quot;</span>, <span class="st">&quot;S-A-TA4&quot;</span>, <span class="st">&quot;S-R-CT3&quot;</span>)</span>
<span id="cb543-164"><a href="outcentr.html#cb543-164" tabindex="-1"></a>part</span>
<span id="cb543-165"><a href="outcentr.html#cb543-165" tabindex="-1"></a>m_bruta_part <span class="ot">&lt;-</span> m_bruta[<span class="sc">!</span>(<span class="fu">row.names</span>(m_bruta) <span class="sc">%in%</span> <span class="fu">c</span>(part)),]</span>
<span id="cb543-166"><a href="outcentr.html#cb543-166" tabindex="-1"></a><span class="co">#m_bruta_part</span></span>
<span id="cb543-167"><a href="outcentr.html#cb543-167" tabindex="-1"></a>sum <span class="ot">&lt;-</span> <span class="fu">colSums</span>(m_bruta_part)</span>
<span id="cb543-168"><a href="outcentr.html#cb543-168" tabindex="-1"></a>sum</span>
<span id="cb543-169"><a href="outcentr.html#cb543-169" tabindex="-1"></a>zero_sum_cols <span class="ot">&lt;-</span> <span class="fu">names</span>(<span class="fu">which</span>(<span class="fu">colSums</span>(m_bruta_part) <span class="sc">==</span> <span class="dv">0</span>))</span>
<span id="cb543-170"><a href="outcentr.html#cb543-170" tabindex="-1"></a>zero_sum_cols <span class="co">#nomes das espécies zeradas</span></span>
<span id="cb543-171"><a href="outcentr.html#cb543-171" tabindex="-1"></a>m_bruta_part2 <span class="ot">&lt;-</span> m_bruta_part[(<span class="fu">colSums</span>(m_bruta_part) <span class="sc">!=</span> <span class="dv">0</span>)] <span class="co">#em != a exclamação inverte o sentido</span></span>
<span id="cb543-172"><a href="outcentr.html#cb543-172" tabindex="-1"></a>zero_sum_cols2 <span class="ot">&lt;-</span> <span class="fu">names</span>(<span class="fu">which</span>(<span class="fu">colSums</span>(m_bruta_part2) <span class="sc">==</span> <span class="dv">0</span>))</span>
<span id="cb543-173"><a href="outcentr.html#cb543-173" tabindex="-1"></a>zero_sum_cols2 <span class="co">#nomes das espécies zeradas</span></span>
<span id="cb543-174"><a href="outcentr.html#cb543-174" tabindex="-1"></a>sum<span class="ot">&lt;-</span><span class="fu">colSums</span>(m_bruta_part2)</span>
<span id="cb543-175"><a href="outcentr.html#cb543-175" tabindex="-1"></a>sum</span>
<span id="cb543-176"><a href="outcentr.html#cb543-176" tabindex="-1"></a><span class="co">#m_bruta_part2</span></span>
<span id="cb543-177"><a href="outcentr.html#cb543-177" tabindex="-1"></a><span class="co">#m_bruta_part2 &lt;- as.matrix(m_bruta_part2)</span></span>
<span id="cb543-178"><a href="outcentr.html#cb543-178" tabindex="-1"></a><span class="fu">str</span>(m_bruta_part2)</span>
<span id="cb543-179"><a href="outcentr.html#cb543-179" tabindex="-1"></a><span class="fu">length</span>(<span class="fu">as.matrix</span>(m_bruta_part2))</span>
<span id="cb543-180"><a href="outcentr.html#cb543-180" tabindex="-1"></a><span class="do">## df &lt;- data.frame(Sites = rownames(m_bruta), m_bruta,</span></span>
<span id="cb543-181"><a href="outcentr.html#cb543-181" tabindex="-1"></a><span class="do">##                  row.names = NULL,</span></span>
<span id="cb543-182"><a href="outcentr.html#cb543-182" tabindex="-1"></a><span class="do">##                  check.names = FALSE) #add titulo a primeira coluna</span></span>
<span id="cb543-183"><a href="outcentr.html#cb543-183" tabindex="-1"></a><span class="do">## </span></span>
<span id="cb543-184"><a href="outcentr.html#cb543-184" tabindex="-1"></a><span class="do">## write.table(m_bruta_part2, &quot;m_trabcsv.csv&quot;,</span></span>
<span id="cb543-185"><a href="outcentr.html#cb543-185" tabindex="-1"></a><span class="do">##             sep = &quot;;&quot;, dec = &quot;.&quot;, #&quot;\t&quot;,</span></span>
<span id="cb543-186"><a href="outcentr.html#cb543-186" tabindex="-1"></a><span class="do">##             row.names = TRUE,</span></span>
<span id="cb543-187"><a href="outcentr.html#cb543-187" tabindex="-1"></a><span class="do">##             quote = TRUE,</span></span>
<span id="cb543-188"><a href="outcentr.html#cb543-188" tabindex="-1"></a><span class="do">##             append = FALSE)</span></span>
<span id="cb543-189"><a href="outcentr.html#cb543-189" tabindex="-1"></a><span class="do">## </span></span>
<span id="cb543-190"><a href="outcentr.html#cb543-190" tabindex="-1"></a><span class="do">## m_trab &lt;- read.csv(&quot;m_trabcsv.csv&quot;,</span></span>
<span id="cb543-191"><a href="outcentr.html#cb543-191" tabindex="-1"></a><span class="do">##                    sep = &quot;;&quot;, dec = &quot;.&quot;,</span></span>
<span id="cb543-192"><a href="outcentr.html#cb543-192" tabindex="-1"></a><span class="do">##                    row.names = 1,</span></span>
<span id="cb543-193"><a href="outcentr.html#cb543-193" tabindex="-1"></a><span class="do">##                    header = TRUE,</span></span>
<span id="cb543-194"><a href="outcentr.html#cb543-194" tabindex="-1"></a><span class="do">##                    na.strings = NA,</span></span>
<span id="cb543-195"><a href="outcentr.html#cb543-195" tabindex="-1"></a><span class="do">##                    check.names = FALSE, #impede que o R mude os nomes das colunas</span></span>
<span id="cb543-196"><a href="outcentr.html#cb543-196" tabindex="-1"></a><span class="do">##                    col.names = gsub(&quot;(^|_)([a-z])&quot;, &quot;\\1\\U\\2&quot;,</span></span>
<span id="cb543-197"><a href="outcentr.html#cb543-197" tabindex="-1"></a><span class="do">##                                     names(m_trab), perl = TRUE))</span></span></code></pre></div>
</div>
<div id="referências-17" class="section level2 unnumbered">
<h2>Referências</h2>

</div>
</div>
<h3>Bibliografia Geral</h3>
<div id="refs" class="references csl-bib-body" entry-spacing="1">
<div id="ref-borcard2018" class="csl-entry">
BORCARD, D.; GILLET, F.; LEGENDRE, P. <strong>Numerical Ecology with R</strong>. Cham: Springer International Publishing, 2018. Disponível em: &lt;<a href="http://link.springer.com/10.1007/978-3-319-71404-2">http://link.springer.com/10.1007/978-3-319-71404-2</a>&gt;
</div>
<div id="ref-horton2015" class="csl-entry">
HORTON, N. J.; KLEINMAN, K. <strong>Using R and RStudio for Data Management, Statistical Analysis, and Graphics</strong>. 0. ed. [s.l.] : Chapman; Hall/CRC, 2015. Disponível em: &lt;<a href="https://www.taylorfrancis.com/books/9781482237375">https://www.taylorfrancis.com/books/9781482237375</a>&gt;
</div>
<div id="ref-legendre1998" class="csl-entry">
LEGENDRE, P.; LEGENDRE, L. <strong>Numerical Ecology</strong>. 2nd English ed ed. Amsterdam, The Netherlands ; New York ; Oxford.
</div>
</div>
<div class="footnotes">
<hr />
<ol start="14">
<li id="fn14"><p>A etimologia do gênero <em>Astyanax</em> vem da mitologia Grega. Heitor personagem da “Ilíada”, tinha um filho chamado Astíanax.<a href="outcentr.html#fnref14" class="footnote-back">↩︎</a></p></li>
<li id="fn15"><p>Do Grego, <em>hoplon</em>, arma ou armadura, em referência aos dentes caniniformes muito desenvolvidos, e forte estrutura óssea na cabeça.<a href="outcentr.html#fnref15" class="footnote-back">↩︎</a></p></li>
<li id="fn16"><p>A etimologia do nome <em>Apareiodon</em> vem do Grego, <em>a</em>, sem, <em>pareia</em>, lateral ou bochecha, e <em>odous</em> dentição, em referencia a ausência de tentes laterais no aparato bucal dessa espécie.<a href="outcentr.html#fnref16" class="footnote-back">↩︎</a></p></li>
<li id="fn17"><p>A etimologia do nome <em>Pseudancistrus</em> vem do Grego, <em>pseudes</em>, falso, e <em>agkistron</em>, gancho, em referência a falsos ganchos presentes na cabeça em algumas espécies do gênero.<a href="outcentr.html#fnref17" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
  </main>

  <div class="col-md-3 col-lg-2 d-none d-md-block sidebar sidebar-chapter">
    <nav id="toc" data-toggle="toc" aria-label="On this page">
      <h2>On this page</h2>
      <div id="book-on-this-page"></div>

      <div class="book-extra">
        <ul class="list-unstyled">
          <li><a id="book-source" href="#">View source <i class="fab fa-github"></i></a></li>
          <li><a id="book-edit" href="#">Edit this page <i class="fab fa-github"></i></a></li>
        </ul>
      </div>
    </nav>
  </div>

</div>
</div> <!-- .container -->

<footer class="bg-primary text-light mt-5">
  <div class="container"><div class="row">

  <div class="col-12 col-md-6 mt-3">
    <p>"<strong>Fundamentos de Ecologia Numérica</strong>: Disciplina de Ecologia Numérica do Curso de Ciências Biológicas do Campus V da UEPB" was written by Prof. Elvio S. F. Medeiros, Laboratório de Ecologia, Universidade Estadual da Paraíba, Campus V, João Pessoa, PB. It was last built on Last updated: 24/07/2026 16:50:19.</p>
  </div>

  <div class="col-12 col-md-6 mt-3">
    <p>This book was built by the <a class="text-light" href="https://bookdown.org">bookdown</a> R package.</p>
  </div>

</div></div>
</footer>


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
<script type="text/x-mathjax-config">const popovers = document.querySelectorAll('a.footnote-ref[data-toggle="popover"]');
for (let popover of popovers) {
  const div = document.createElement('div');
  div.setAttribute('style', 'position: absolute; top: 0, left:0; width:0, height:0, overflow: hidden; visibility: hidden;');
  div.innerHTML = popover.getAttribute('data-content');

  var has_math = div.querySelector("span.math");
  if (has_math) {
    document.body.appendChild(div);
    MathJax.Hub.Queue(["Typeset", MathJax.Hub, div]);
    MathJax.Hub.Queue(function() {
      popover.setAttribute('data-content', div.innerHTML);
      document.body.removeChild(div);
    })
  }
}
</script>
</body>

</html>
