<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <title> 20 R Modulo 5 - Relativizações e transformações | Fundamentos de Ecologia Numérica</title>

    <meta name="author" content="Prof. Elvio S. F. Medeiros" />
    <meta name="author" content="Laboratório de Ecologia" />
    <meta name="author" content="Universidade Estadual da Paraíba" />
    <meta name="author" content="Campus V, João Pessoa, PB" />
  
   <meta name="description" content="…. The output format for this example is bookdown::gitbook." />
   <meta name="generator" content="placeholder" />
  <meta property="og:title" content=" 20 R Modulo 5 - Relativizações e transformações | Fundamentos de Ecologia Numérica" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="…. The output format for this example is bookdown::gitbook." />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content=" 20 R Modulo 5 - Relativizações e transformações | Fundamentos de Ecologia Numérica" />
  
  <meta name="twitter:description" content="…. The output format for this example is bookdown::gitbook." />
  
  <!-- JS -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/fuse.js/6.4.6/fuse.js" integrity="sha512-zv6Ywkjyktsohkbp9bb45V6tEMoWhzFzXis+LrMehmJZZSys19Yxf1dopHx7WzIKxr5tK2dVcYmaCk2uqdjF4A==" crossorigin="anonymous"></script>
  <script src="https://kit.fontawesome.com/6ecbd6c532.js" crossorigin="anonymous"></script>
    <script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <link href="libs/bootstrap-4.6.0/bootstrap.min.css" rel="stylesheet" />
    <script src="libs/bootstrap-4.6.0/bootstrap.bundle.min.js"></script>
    <script src="libs/bs3compat-0.10.0/transition.js"></script>
    <script src="libs/bs3compat-0.10.0/tabs.js"></script>
    <script src="libs/bs3compat-0.10.0/bs3compat.js"></script>
    <link href="libs/bs4_book-1.0.0/bs4_book.css" rel="stylesheet" />
    <script src="libs/bs4_book-1.0.0/bs4_book.js"></script>
    <script src="libs/kePrint-0.0.1/kePrint.js"></script>
    <link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />
    <link href="libs/bsTable-3.3.7/bootstrapTable.min.css" rel="stylesheet" />
    <script src="libs/bsTable-3.3.7/bootstrapTable.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/autocomplete.js/0.38.0/autocomplete.jquery.min.js" integrity="sha512-GU9ayf+66Xx2TmpxqJpliWbT5PiGYxpaG8rfnBEk1LL8l1KGkRShhngwdXK1UgqhAzWpZHSiYPc09/NwDQIGyg==" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/mark.min.js" integrity="sha512-5CYOlHXGh6QpOFA/TeTylKLWfB3ftPsde7AnmhuitiTX4K5SqCLBeKro6sPS8ilsz1Q4NRx3v8Ko2IBiszzdww==" crossorigin="anonymous"></script>

  <!-- CSS -->
  <style type="text/css">
    
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  </style>
    <style type="text/css">
    /* Used with Pandoc 2.11+ new --citeproc when CSL is used */
    div.csl-bib-body { }
    div.csl-entry {
      clear: both;
          margin-bottom: 1em;
        }
    .hanging div.csl-entry {
      margin-left:2em;
      text-indent:-2em;
    }
    div.csl-left-margin {
      min-width:2em;
      float:left;
    }
    div.csl-right-inline {
      margin-left:2em;
      padding-left:1em;
    }
    div.csl-indent {
      margin-left: 2em;
    }
  </style>
      <link rel="stylesheet" href="style.css" />
  
</head>

<body data-spy="scroll" data-target="#toc">

<div class="container-fluid">
<div class="row">
  <header class="col-sm-12 col-lg-3 sidebar sidebar-book">
    <a class="sr-only sr-only-focusable" href="#content">Skip to main content</a>

    <div class="d-flex align-items-start justify-content-between">
      <h1>
        <a href="index.html" title="Disciplina de Ecologia Numérica do Curso de Ciências Biológicas do Campus V da UEPB">Fundamentos de Ecologia Numérica</a>:
        <small class="text-muted">Disciplina de Ecologia Numérica do Curso de Ciências Biológicas do Campus V da UEPB</small>
      </h1>
      <button class="btn btn-outline-primary d-lg-none ml-2 mt-1" type="button" data-toggle="collapse" data-target="#main-nav" aria-expanded="true" aria-controls="main-nav"><i class="fas fa-bars"></i><span class="sr-only">Show table of contents</span></button>
    </div>

    <div id="main-nav" class="collapse-lg">
      <form role="search">
        <input id="search" class="form-control" type="search" placeholder="Search" aria-label="Search">
      </form>

      <nav aria-label="Table of contents">
        <h2>Table of contents</h2>
        <div id="book-toc"></div>

        <div class="book-extra">
          <p><a id="book-repo" href="#">View book source <i class="fab fa-github"></i></a></li></p>
        </div>
      </nav>
    </div>
  </header>

  <main class="col-sm-12 col-md-9 col-lg-7" id="content">
<div id="reltrns" class="section level1" number="20">
<h1><span class="header-section-number"> 20</span> R Modulo 5 - Relativizações e transformações</h1>
<div id="resumo-14" class="section level3 unnumbered">
<h3>RESUMO</h3>
<p>Transformações e relativizações de dados são técnicas essenciais na análise de dados em Ecologia Numérica, permitindo comparar diferentes variáveis que estão em escalas diferentes ou que possuem unidades distintas.</p>
</div>
<div id="apresentação-14" class="section level3 unnumbered">
<h3>Apresentação</h3>
<p>O R é uma ferramenta poderosa para realização dessas operações, com diversos pacotes disponíveis para essa finalidade. Neste tutorial, iremos explorar algumas das principais funções do pacote vegan, que permite realizar transformações e relativizações de dados de forma simples e eficiente. Além disso, também utilizaremos outras bibliotecas importantes para reorganização e visualozação de dados. O tutorial irá abordar desde as operações básicas, como filtragem e seleção de dados, até as transformações mais complexas, como a normalização de dados e a relativização por medidas de biomassa ou área. Com exemplos práticos e ilustrações gráficas, o objetivo é permitir que os usuários do R possam aplicar essas técnicas em suas próprias análises e estudos de Ecologia Numérica. Ao final do tutorial, espera-se que o usuário esteja apto a realizar transformações e relativizações de dados em suas próprias análises, aumentando a qualidade e a precisão dos resultados obtidos.</p>
</div>
<div id="organização-básica-10" class="section level2" number="20.1">
<h2><span class="header-section-number">20.1</span> Organização básica</h2>
<div class="sourceCode" id="cb446"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb446-1"><a href="reltrns.html#cb446-1" tabindex="-1"></a><span class="fu">dev.off</span>() <span class="co">#apaga os graficos, se houver algum</span></span>
<span id="cb446-2"><a href="reltrns.html#cb446-2" tabindex="-1"></a><span class="fu">rm</span>(<span class="at">list=</span><span class="fu">ls</span>(<span class="at">all=</span><span class="cn">TRUE</span>)) <span class="co">#limpa a memória</span></span>
<span id="cb446-3"><a href="reltrns.html#cb446-3" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">&quot;</span><span class="sc">\014</span><span class="st">&quot;</span>) <span class="co">#limpa o console </span></span></code></pre></div>
<p>Instalando os pacotes necessários para esse módulo</p>
<div class="sourceCode" id="cb447"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb447-1"><a href="reltrns.html#cb447-1" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">&quot;openxlsx&quot;</span>) <span class="co">#importa arquivos do excel</span></span>
<span id="cb447-2"><a href="reltrns.html#cb447-2" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">&quot;moments&quot;</span>) <span class="co">#calcula assimetria e curtose dos dados</span></span>
<span id="cb447-3"><a href="reltrns.html#cb447-3" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">&quot;vegan&quot;</span>) <span class="co">#estatisticas para ecologia de comunidades</span></span></code></pre></div>
<p>Agora vamos <strong>definir o diretório de trabalho</strong>. Esse código é usado para obter e definir o diretório de trabalho atual no R. O comando <code>getwd()</code> retorna o caminho do diretório onde o R está lendo e salvando arquivos. O comando <code>setwd()</code> muda esse diretório de trabalho para o caminho especificado entre aspas. No seu caso, você deve ajustar o caminho para o seu próprio diretório de trabalho. <strong>Lembre de usar a barra “/” entre os diretórios. E não a contra-barra “\”.</strong></p>
<p>Definindo o diretório de trabalho e installando os pacotes necessários:</p>
<div class="sourceCode" id="cb448"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb448-1"><a href="reltrns.html#cb448-1" tabindex="-1"></a><span class="fu">getwd</span>()</span>
<span id="cb448-2"><a href="reltrns.html#cb448-2" tabindex="-1"></a><span class="fu">setwd</span>(<span class="st">&quot;C:/Seu/Diretório/De/Trabalho&quot;</span>)</span></code></pre></div>
<div id="importando-a-planilha-7" class="section level3" number="20.1.1">
<h3><span class="header-section-number">20.1.1</span> Importando a planilha</h3>
<p>Note que o símbolo <span style="color:green"><code>#</code></span> em programação R significa que o texto que vem depois dele é um comentário e não será executado pelo programa. Isso é útil para explicar o código ou deixar anotações.<br />
- Ajuste a primeira linha do código abaixo para refletir <span style="color:blue">“C:/Seu/Diretório/De/Trabalho/Planilha.xlsx”</span>.<br />
- Ajuste o parâmetro <code>sheet = "Sheet1"</code> para refletir a aba correta do arquivo .xlsx a ser importado.</p>
<div class="sourceCode" id="cb449"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb449-1"><a href="reltrns.html#cb449-1" tabindex="-1"></a><span class="fu">library</span>(openxlsx)</span>
<span id="cb449-2"><a href="reltrns.html#cb449-2" tabindex="-1"></a><span class="co">#dir &lt;- getwd() #criamos um vetor com o diretório  de trbalho </span></span>
<span id="cb449-3"><a href="reltrns.html#cb449-3" tabindex="-1"></a><span class="co">#shell.exec(dir) #abre o diretorio de trabalho no Windows Explorer</span></span>
<span id="cb449-4"><a href="reltrns.html#cb449-4" tabindex="-1"></a>m_bruta <span class="ot">&lt;-</span> <span class="fu">read.xlsx</span>(<span class="st">&quot;D:/Elvio/OneDrive/Disciplinas/_EcoNumerica/5.Matrizes/ppbio06c-peixes.xlsx&quot;</span>,</span>
<span id="cb449-5"><a href="reltrns.html#cb449-5" tabindex="-1"></a>                   <span class="at">rowNames =</span> T, <span class="at">colNames =</span> T,</span>
<span id="cb449-6"><a href="reltrns.html#cb449-6" tabindex="-1"></a>                   <span class="at">sheet =</span> <span class="st">&quot;Sheet1&quot;</span>)</span>
<span id="cb449-7"><a href="reltrns.html#cb449-7" tabindex="-1"></a><span class="fu">str</span>(m_bruta)</span>
<span id="cb449-8"><a href="reltrns.html#cb449-8" tabindex="-1"></a><span class="co">#View(m_bruta)</span></span>
<span id="cb449-9"><a href="reltrns.html#cb449-9" tabindex="-1"></a>m_bruta[<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>,<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>] <span class="co">#[1:5,1:5] mostra apenas as linhas e colunas de 1 a 5.</span></span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    26 obs. of  35 variables:
##  $ ap-davis : num  0 0 0 0 0 0 0 0 0 0 ...
##  $ as-bimac : num  1 99 194 19 23 142 5 46 206 16 ...
##  $ as-fasci : num  0 0 55 0 1 3 1 0 64 0 ...
##  $ ch-bimac : num  0 0 0 0 13 3 0 178 0 0 ...
##  $ ci-ocela : num  0 0 0 0 0 0 40 0 0 13 ...
##  $ ci-orien : num  0 0 5 0 0 69 9 0 25 24 ...
##  $ co-macro : num  0 0 0 0 0 0 0 0 0 0 ...
##  $ co-heter : num  0 0 1 0 0 0 0 0 0 0 ...
##  $ cr-menez : num  0 0 14 0 0 4 0 0 8 0 ...
##  $ cu-lepid : num  0 0 0 0 0 0 0 0 0 0 ...
##  $ cy-gilbe : num  0 0 0 0 0 0 0 0 0 0 ...
##  $ ge-brasi : num  0 0 3 0 0 0 0 0 1 0 ...
##  $ he-margi : num  0 0 0 0 0 1 0 0 0 0 ...
##  $ ho-malab : num  0 0 1 5 0 17 10 2 31 4 ...
##  $ hy-pusar : num  0 0 9 2 0 43 2 0 11 0 ...
##  $ le-melan : num  0 0 0 0 0 0 0 0 0 0 ...
##  $ le-piau  : num  0 0 3 0 0 1 3 0 2 1 ...
##  $ le-taeni : num  0 0 0 0 0 0 0 0 0 0 ...
##  $ mo-costa : num  0 0 0 0 0 0 0 0 0 0 ...
##  $ mo-lepid : num  0 1 39 0 0 1 0 0 0 0 ...
##  $ or-nilot : num  0 2 36 0 0 77 0 0 138 0 ...
##  $ pa-manag : num  0 0 0 0 0 0 0 0 0 0 ...
##  $ pimel-sp : num  0 0 6 0 0 0 0 0 0 0 ...
##  $ po-retic : num  0 0 0 0 0 20 0 0 5 0 ...
##  $ po-vivip : num  0 0 47 15 0 221 32 0 326 10 ...
##  $ pr-brevi : num  9 0 5 0 1 15 5 2 164 0 ...
##  $ ps-rhomb : num  0 0 0 0 0 0 0 0 1 0 ...
##  $ ps-genise: num  0 0 0 0 0 0 0 0 1 0 ...
##  $ se-heter : num  0 0 40 14 4 60 0 0 38 0 ...
##  $ se-piaba : num  0 0 68 0 0 0 0 0 0 0 ...
##  $ se-spilo : num  0 0 0 0 0 0 0 0 1 0 ...
##  $ st-noton : num  0 0 1 0 0 25 0 0 115 0 ...
##  $ sy-marmo : num  0 0 0 0 0 0 1 0 0 0 ...
##  $ te-chalc : num  0 0 0 0 0 0 0 0 0 0 ...
##  $ tr-signa : num  0 0 18 0 0 15 0 0 7 0 ...
##         ap-davis as-bimac as-fasci ch-bimac ci-ocela
## S-A-ZA1        0        1        0        0        0
## S-R-CC1        0       99        0        0        0
## S-R-CT1        0      194       55        0        0
## S-R-CP1        0       19        0        0        0
## S-A-TA1        0       23        1       13        0</code></pre>
<p>Exibindo os dados importados (esses comando são “case-sensitive” <code>ignore.case(object)</code>).</p>
<div class="sourceCode" id="cb451"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb451-1"><a href="reltrns.html#cb451-1" tabindex="-1"></a><span class="co">#View(m_bruta)</span></span>
<span id="cb451-2"><a href="reltrns.html#cb451-2" tabindex="-1"></a><span class="fu">print</span>(m_bruta[<span class="dv">1</span><span class="sc">:</span><span class="dv">8</span>,<span class="dv">1</span><span class="sc">:</span><span class="dv">8</span>])</span>
<span id="cb451-3"><a href="reltrns.html#cb451-3" tabindex="-1"></a>m_bruta[<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>,<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>]</span>
<span id="cb451-4"><a href="reltrns.html#cb451-4" tabindex="-1"></a><span class="fu">str</span>(m_bruta)</span>
<span id="cb451-5"><a href="reltrns.html#cb451-5" tabindex="-1"></a><span class="fu">mode</span>(m_bruta)</span>
<span id="cb451-6"><a href="reltrns.html#cb451-6" tabindex="-1"></a><span class="fu">class</span>(m_bruta)</span></code></pre></div>
<p>Podemos exibir a planilha depois de ter sido importada para o ambiente R/RStudio usando as funções <code>View()</code>, <code>print()</code> ou <code>head()</code>. Note que essas funções são case-sensitive. A função <code>ignore.case()</code> é uma função do pacote <code>stringr</code> que modifica um padrão para que ele não considere o caso das letras nas correspondências. Por exemplo, se você quiser encontrar todas as ocorrências da letra “a” em um vetor de caracteres, independente de ser “A” ou “a”, você pode usar essa função.</p>
<div class="sourceCode" id="cb452"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb452-1"><a href="reltrns.html#cb452-1" tabindex="-1"></a><span class="co">#View(m_bruta)</span></span>
<span id="cb452-2"><a href="reltrns.html#cb452-2" tabindex="-1"></a><span class="fu">print</span>(m_bruta)</span>
<span id="cb452-3"><a href="reltrns.html#cb452-3" tabindex="-1"></a><span class="fu">head</span>(m_bruta)</span></code></pre></div>
<p>A função <code>head()</code> no RStudio é uma forma de ver as primeiras <code>(n=6)</code> linhas de um objeto, como um vetor, uma matriz, um data frame ou uma lista. Ela é útil para ter uma ideia do conteúdo e da estrutura do objeto.</p>
<p>Também podemos explorar as características da planilha usando as funções <code>str()</code>, <code>mode()</code>, <code>class()</code> e <code>length()</code>. O número de observações ou tamanho do vetor depende do tipo de dados, se eles são uma matrix ou um data.frame.</p>
<div id="abreviações-1" class="section level4 unnumbered">
<h4>Abreviações</h4>
<p>No interesse de sistematizar o código R das várias matrizes que são comumente usadas em uma AMD, a tabela <a href="reltrns.html#tab:5tblm-2">20.1</a>, a seguir, resume seus tipos e abreviações.</p>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:5tblm-2">Tabela 20.1: </span>Nomenclatura das matrizes em AMD em relação aos atributos das colunas
</caption>
<thead>
<tr>
<th style="text-align:left;">
Nome
</th>
<th style="text-align:center;">
Atributos (colunas)
</th>
<th style="text-align:center;">
Abreviação no R
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;width: 2cm; ">
Matriz comunitaria
</td>
<td style="text-align:center;width: 2cm; ">
Os atributos são táxons ou OTU’s (Unidades Taxonômicas Operacionais) (ex. espécies, gêneros, morfotipos)
</td>
<td style="text-align:center;width: 2cm; ">
m_com
</td>
</tr>
<tr>
<td style="text-align:left;width: 2cm; ">
Matriz ambiental
</td>
<td style="text-align:center;width: 2cm; ">
Os atributos são dados ambientais e variáveis físicas e químicas (ex. pH, condutividade, temperatura)
</td>
<td style="text-align:center;width: 2cm; ">
m_amb
</td>
</tr>
<tr>
<td style="text-align:left;width: 2cm; ">
Matriz de habitat
</td>
<td style="text-align:center;width: 2cm; ">
Os atributos são elementos da estrutura do habitat (ex. macróficas, algas, pedras, lama, etc)
</td>
<td style="text-align:center;width: 2cm; ">
m_hab
</td>
</tr>
<tr>
<td style="text-align:left;width: 2cm; ">
Matriz bruta
</td>
<td style="text-align:center;width: 2cm; ">
Os atributos ainda não receberam nenhum tipo de tratamento estatísco (valores brutos, como coletados)
</td>
<td style="text-align:center;width: 2cm; ">
m_bruta
</td>
</tr>
<tr>
<td style="text-align:left;width: 2cm; ">
Matriz transposta
</td>
<td style="text-align:center;width: 2cm; ">
Os atributos foram transpostos para as linhas
</td>
<td style="text-align:center;width: 2cm; ">
m_t
</td>
</tr>
<tr>
<td style="text-align:left;width: 2cm; ">
Matriz relativizada
</td>
<td style="text-align:center;width: 2cm; ">
Os atributos foram relativizados por um critério de tamanho ou de variação (ex. dividir os valores de cada coluna pela soma)
</td>
<td style="text-align:center;width: 2cm; ">
m_rel, m_relcol, m_rellin
</td>
</tr>
<tr>
<td style="text-align:left;width: 2cm; ">
Matriz transformada
</td>
<td style="text-align:center;width: 2cm; ">
Foi aplicado um operador matemático a todos os atributos (ex. raiz quadrada, log)
</td>
<td style="text-align:center;width: 2cm; ">
m_trns, m_log10, m_asrq
</td>
</tr>
<tr>
<td style="text-align:left;width: 2cm; ">
Matriz de distâncias
</td>
<td style="text-align:center;width: 2cm; ">
Matriz de m x m similaridades ou de distâncias (ex. Euclidiana, Manhattan, Bray-Curtis, etc)
</td>
<td style="text-align:center;width: 2cm; ">
m_dists, m_euclid, m_bray
</td>
</tr>
<tr>
<td style="text-align:left;width: 2cm; ">
Matriz de trabalho
</td>
<td style="text-align:center;width: 2cm; ">
Qualquer matriz que seja o foco da análise atual (ex. comunitária, relativizada, etc)
</td>
<td style="text-align:center;width: 2cm; ">
m_trab
</td>
</tr>
<tr>
<td style="text-align:left;width: 2cm; ">
Matriz particionada
</td>
<td style="text-align:center;width: 2cm; ">
Foram removidas linhas ou colunas (ex. linhas que são outliers e espécies zeradas)
</td>
<td style="text-align:center;width: 2cm; ">
m_part
</td>
</tr>
<tr>
<td style="text-align:left;width: 2cm; ">
Base de dados
</td>
<td style="text-align:center;width: 2cm; ">
Arquivo do Excel planilhado a partir de dados de campo ou de laboratório. Será manejada e particionada no R, para criar a Matriz bruta
</td>
<td style="text-align:center;width: 2cm; ">
ppbio06.xlsx, zoorebio.xlsx, bentos06.xlsx
</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<div id="tamanho-da-matriz" class="section level2" number="20.2">
<h2><span class="header-section-number">20.2</span> Tamanho da matriz</h2>
<p>Podemos agora calcular o número e a proporção de zeros na matriz usando as funções <code>sum()</code> e <code>length()</code> (Você pode pesquisar o que faz a função <code>length()</code> usando o comando <code>?length</code>).</p>
<div class="sourceCode" id="cb453"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb453-1"><a href="reltrns.html#cb453-1" tabindex="-1"></a><span class="fu">range</span>(m_bruta) <span class="co">#menor e maior valores</span></span>
<span id="cb453-2"><a href="reltrns.html#cb453-2" tabindex="-1"></a><span class="fu">length</span>(m_bruta) <span class="co">#no. de colunas</span></span>
<span id="cb453-3"><a href="reltrns.html#cb453-3" tabindex="-1"></a><span class="fu">ncol</span>(m_bruta) <span class="co">#no. de N colunas</span></span>
<span id="cb453-4"><a href="reltrns.html#cb453-4" tabindex="-1"></a><span class="fu">nrow</span>(m_bruta) <span class="co">#no. de M linhas</span></span>
<span id="cb453-5"><a href="reltrns.html#cb453-5" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">lengths</span>(m_bruta)) <span class="co">#soma os nos. de colunas</span></span>
<span id="cb453-6"><a href="reltrns.html#cb453-6" tabindex="-1"></a><span class="fu">length</span>(<span class="fu">as.matrix</span>(m_bruta)) <span class="co">#tamanho da matriz m x n</span></span>
<span id="cb453-7"><a href="reltrns.html#cb453-7" tabindex="-1"></a><span class="fu">sum</span>(m_bruta <span class="sc">==</span> <span class="dv">0</span>) <span class="co"># número de observações igual a zero</span></span>
<span id="cb453-8"><a href="reltrns.html#cb453-8" tabindex="-1"></a><span class="fu">sum</span>(m_bruta <span class="sc">&gt;</span> <span class="dv">0</span>) <span class="co"># número de observações maiores que zero</span></span>
<span id="cb453-9"><a href="reltrns.html#cb453-9" tabindex="-1"></a>zeros <span class="ot">&lt;-</span> (<span class="fu">sum</span>(m_bruta <span class="sc">==</span> <span class="dv">0</span>)<span class="sc">/</span><span class="fu">length</span>(<span class="fu">as.matrix</span>(m_bruta)))<span class="sc">*</span><span class="dv">100</span> <span class="co"># proporção de zeros na matriz</span></span>
<span id="cb453-10"><a href="reltrns.html#cb453-10" tabindex="-1"></a>zeros</span></code></pre></div>
<pre><code>## [1]   0 511
## [1] 35
## [1] 35
## [1] 26
## [1] 910
## [1] 910
## [1] 716
## [1] 194
## [1] 78.68132</code></pre>
<p>Tabela que resume as informações geradas (<a href="reltrns.html#tab:tbl5-tam">20.2</a>).</p>
<div class="sourceCode" id="cb455"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb455-1"><a href="reltrns.html#cb455-1" tabindex="-1"></a>tamanho <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb455-2"><a href="reltrns.html#cb455-2" tabindex="-1"></a>  <span class="at">Comando =</span> <span class="fu">c</span>(<span class="st">&quot;range&quot;</span>, <span class="st">&quot;lenght&quot;</span>, <span class="st">&quot;m cols&quot;</span>, <span class="st">&quot;n linhas&quot;</span>, <span class="st">&quot;Tamanho&quot;</span>, <span class="st">&quot;Tamanho&quot;</span>,</span>
<span id="cb455-3"><a href="reltrns.html#cb455-3" tabindex="-1"></a>             <span class="st">&quot;Zeros&quot;</span>, <span class="st">&quot;Nao zeros&quot;</span>, <span class="st">&quot;% Zeros&quot;</span>),</span>
<span id="cb455-4"><a href="reltrns.html#cb455-4" tabindex="-1"></a>  <span class="at">Resultado =</span> <span class="fu">c</span>(<span class="fu">paste</span>(<span class="fu">range</span>(m_bruta), <span class="at">collapse =</span> <span class="st">&quot; - &quot;</span>), <span class="fu">length</span>(m_bruta), <span class="fu">ncol</span>(m_bruta),</span>
<span id="cb455-5"><a href="reltrns.html#cb455-5" tabindex="-1"></a>                <span class="fu">nrow</span>(m_bruta), <span class="fu">sum</span>(<span class="fu">lengths</span>(m_bruta)), <span class="fu">length</span>(<span class="fu">as.matrix</span>(m_bruta)), <span class="fu">sum</span>(m_bruta <span class="sc">==</span> <span class="dv">0</span>),</span>
<span id="cb455-6"><a href="reltrns.html#cb455-6" tabindex="-1"></a>                <span class="fu">sum</span>(m_bruta <span class="sc">&gt;</span> <span class="dv">0</span>), <span class="fu">round</span>(zeros, <span class="dv">1</span>)))</span>
<span id="cb455-7"><a href="reltrns.html#cb455-7" tabindex="-1"></a>tamanho</span></code></pre></div>
<pre><code>##     Comando Resultado
## 1     range   0 - 511
## 2    lenght        35
## 3    m cols        35
## 4  n linhas        26
## 5   Tamanho       910
## 6   Tamanho       910
## 7     Zeros       716
## 8 Nao zeros       194
## 9   % Zeros      78.7</code></pre>
<table>
<caption>
<span id="tab:tbl5-tam">Tabela 20.2: </span>Resumo das informações geradas.
</caption>
<thead>
<tr>
<th style="text-align:left;">
Comando
</th>
<th style="text-align:left;">
Resultado
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
range
</td>
<td style="text-align:left;">
0 - 511
</td>
</tr>
<tr>
<td style="text-align:left;">
lenght
</td>
<td style="text-align:left;">
35
</td>
</tr>
<tr>
<td style="text-align:left;">
m cols
</td>
<td style="text-align:left;">
35
</td>
</tr>
<tr>
<td style="text-align:left;">
n linhas
</td>
<td style="text-align:left;">
26
</td>
</tr>
<tr>
<td style="text-align:left;">
Tamanho
</td>
<td style="text-align:left;">
910
</td>
</tr>
<tr>
<td style="text-align:left;">
Tamanho
</td>
<td style="text-align:left;">
910
</td>
</tr>
<tr>
<td style="text-align:left;">
Zeros
</td>
<td style="text-align:left;">
716
</td>
</tr>
<tr>
<td style="text-align:left;">
Nao zeros
</td>
<td style="text-align:left;">
194
</td>
</tr>
<tr>
<td style="text-align:left;">
% Zeros
</td>
<td style="text-align:left;">
78.7
</td>
</tr>
</tbody>
</table>
<p>Ou seja, temos uma matriz de tamanho <code>m x n</code> igual a 26 objetos por 35 atributos, onde 78.68% dos valores da matriz são iguais a zero!</p>
</div>
<div id="id_501reinicio1" class="section level2" number="20.3">
<h2><span class="header-section-number">20.3</span> REINÍCIO 1</h2>
<div class="sourceCode" id="cb457"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb457-1"><a href="reltrns.html#cb457-1" tabindex="-1"></a>m_trab <span class="ot">&lt;-</span> m_bruta</span></code></pre></div>
<p>Aqui cria-se um novo objeto do R (<code>m_trab</code>, ou a matriz de trabalho, para esse momento) que substitui a matriz de dados original, por uma nova matriz que pode ser a matriz relativizada, transformada, transposta, etc. Dessa forma, mantemos a matriz de dados original caso precisemos dela novamente (Veja a Tabela Tabela @ref(tab:5tblm_2)).</p>
</div>
<div id="cálculo-da-matriz-de-distâncias" class="section level2" number="20.4">
<h2><span class="header-section-number">20.4</span> Cálculo da matriz de distâncias</h2>
<p>Agora vamos calcular a matriz de distâncias euclidiana <span class="citation">(<a href="#ref-borcard2018">BORCARD; GILLET; LEGENDRE, 2018</a>; <a href="#ref-legendre1998">LEGENDRE; LEGENDRE, 1998</a>)</span> entre as UA´s usando a função <code>dist()</code> (pesquise o que faz essa função usando o comando <code>?dist</code>).</p>
<div class="sourceCode" id="cb458"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb458-1"><a href="reltrns.html#cb458-1" tabindex="-1"></a>m_dists <span class="ot">&lt;-</span> <span class="fu">dist</span>(m_trab, <span class="at">method =</span> <span class="st">&quot;euclidian&quot;</span>, <span class="at">diag =</span> <span class="cn">TRUE</span>, <span class="at">upper =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<p>Pronto, calculamos a matriz de distâncias (euclidiana). Agora podemos visualizar a matriz.</p>
<div class="sourceCode" id="cb459"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb459-1"><a href="reltrns.html#cb459-1" tabindex="-1"></a><span class="co">#m_dists</span></span>
<span id="cb459-2"><a href="reltrns.html#cb459-2" tabindex="-1"></a><span class="fu">str</span>(m_dists)</span>
<span id="cb459-3"><a href="reltrns.html#cb459-3" tabindex="-1"></a><span class="fu">mode</span>(m_dists)</span>
<span id="cb459-4"><a href="reltrns.html#cb459-4" tabindex="-1"></a><span class="fu">class</span>(m_dists)</span>
<span id="cb459-5"><a href="reltrns.html#cb459-5" tabindex="-1"></a><span class="fu">length</span>(<span class="fu">as.matrix</span>(m_dists))</span>
<span id="cb459-6"><a href="reltrns.html#cb459-6" tabindex="-1"></a><span class="fu">as.matrix</span>(m_dists)[<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>, <span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>]</span></code></pre></div>
<pre><code>##  &#39;dist&#39; num [1:325] 98.4 228.5 29.2 27.1 294.1 ...
##  - attr(*, &quot;Size&quot;)= int 26
##  - attr(*, &quot;Labels&quot;)= chr [1:26] &quot;S-A-ZA1&quot; &quot;S-R-CC1&quot; &quot;S-R-CT1&quot; &quot;S-R-CP1&quot; ...
##  - attr(*, &quot;Diag&quot;)= logi TRUE
##  - attr(*, &quot;Upper&quot;)= logi FALSE
##  - attr(*, &quot;method&quot;)= chr &quot;euclidean&quot;
##  - attr(*, &quot;call&quot;)= language dist(x = m_trab, method = &quot;euclidian&quot;, diag = TRUE, upper = FALSE)
## [1] &quot;numeric&quot;
## [1] &quot;dist&quot;
## [1] 676
##           S-A-ZA1   S-R-CC1  S-R-CT1   S-R-CP1   S-A-TA1  S-R-CT2   S-R-CP2
## S-A-ZA1   0.00000  98.43780 228.5235  29.24038  27.09243 294.0629  53.40412
## S-R-CC1  98.43780   0.00000 154.2433  82.79493  77.25283 261.3905 108.10180
## S-R-CT1 228.52352 154.24331   0.0000 208.52338 209.69263 224.9133 224.09150
## S-R-CP1  29.24038  82.79493 208.5234   0.00000  23.25941 271.4922  49.22398
## S-A-TA1  27.09243  77.25283 209.6926  23.25941   0.00000 283.7869  57.82733
## S-R-CT2 294.06292 261.39051 224.9133 271.49217 283.78689   0.0000 268.95167
## S-R-CP2  53.40412 108.10180 224.0915  49.22398  57.82733 268.9517   0.00000
## S-A-TA2 183.74439 185.75791 261.8301 181.24845 166.66133 326.3327 190.15257
## S-R-CT3 460.42155 428.64437 366.6429 443.90877 453.59674 238.3799 438.54532
## S-R-CP3  34.17601  88.06816 215.2557  31.32092  33.13608 275.0436  40.37326
##          S-A-TA2  S-R-CT3   S-R-CP3
## S-A-ZA1 183.7444 460.4215  34.17601
## S-R-CC1 185.7579 428.6444  88.06816
## S-R-CT1 261.8301 366.6429 215.25566
## S-R-CP1 181.2484 443.9088  31.32092
## S-A-TA1 166.6613 453.5967  33.13608
## S-R-CT2 326.3327 238.3799 275.04363
## S-R-CP2 190.1526 438.5453  40.37326
## S-A-TA2   0.0000 478.9008 182.86060
## S-R-CT3 478.9008   0.0000 449.24826
## S-R-CP3 182.8606 449.2483   0.00000</code></pre>
<p>Uma matriz do tipo <code>dist</code> no R é um objeto que armazena as distâncias entre as linhas de uma matriz ou um data frame. Ela é criada pela função <code>dist()</code>, que calcula as distâncias usando diferentes medidas, como “euclidean”, “manhattan”, “canberra”, “binary” ou “minkowski” <span class="citation">(<a href="#ref-horton2015">HORTON; KLEINMAN, 2015</a>)</span>.</p>
<div class="sourceCode" id="cb461"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb461-1"><a href="reltrns.html#cb461-1" tabindex="-1"></a><span class="fu">range</span>(m_trab)</span>
<span id="cb461-2"><a href="reltrns.html#cb461-2" tabindex="-1"></a><span class="fu">range</span>(m_dists)</span>
<span id="cb461-3"><a href="reltrns.html#cb461-3" tabindex="-1"></a><span class="fu">min</span>(m_dists)</span>
<span id="cb461-4"><a href="reltrns.html#cb461-4" tabindex="-1"></a><span class="fu">max</span>(m_dists)</span>
<span id="cb461-5"><a href="reltrns.html#cb461-5" tabindex="-1"></a><span class="fu">mean</span>(m_dists) <span class="co">#CENTROIDE!! ou Grand mean</span></span>
<span id="cb461-6"><a href="reltrns.html#cb461-6" tabindex="-1"></a><span class="fu">sd</span>(m_dists)  <span class="co">#standard deviation</span></span>
<span id="cb461-7"><a href="reltrns.html#cb461-7" tabindex="-1"></a>centroide <span class="ot">&lt;-</span> <span class="fu">mean</span>(m_dists)</span>
<span id="cb461-8"><a href="reltrns.html#cb461-8" tabindex="-1"></a>centroide</span></code></pre></div>
<pre><code>## [1]   0 511
## [1]  16.27882 707.32666
## [1] 16.27882
## [1] 707.3267
## [1] 285.9043
## [1] 172.9708
## [1] 285.9043</code></pre>
<p>A função <code>mean()</code> calcula a média de todos os valores da matriz de distâncias, ou seja, a média multivariada, que é o centróide. Nesse caso o <strong>centroide assume o valor de 285.9</strong>. Usamos agora a fórmula <code>n*(n-1)/2</code>, onde <code>n</code> é o no. de objetos sendo comparados, para calcular quantas distâcias temos na nossa matriz.</p>
<div class="sourceCode" id="cb463"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb463-1"><a href="reltrns.html#cb463-1" tabindex="-1"></a><span class="fu">length</span>(m_dists)</span>
<span id="cb463-2"><a href="reltrns.html#cb463-2" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="fu">nrow</span>(<span class="fu">as.matrix</span>(m_dists))</span>
<span id="cb463-3"><a href="reltrns.html#cb463-3" tabindex="-1"></a>n</span>
<span id="cb463-4"><a href="reltrns.html#cb463-4" tabindex="-1"></a>n<span class="sc">*</span>(n<span class="dv">-1</span>)<span class="sc">/</span><span class="dv">2</span></span>
<span id="cb463-5"><a href="reltrns.html#cb463-5" tabindex="-1"></a><span class="fu">summary</span>(m_dists)</span></code></pre></div>
<pre><code>## [1] 325
## [1] 26
## [1] 325
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   16.28  142.70  242.82  285.90  423.64  707.33</code></pre>
<p>Temos então que n é 26 objetos (ou linhas), e portanto, a matriz de distâncias tem 325 valores. Fazemos agora um breve sumário do que foi calculado até agora com base na matriz de distâncias.</p>
<div class="sourceCode" id="cb465"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb465-1"><a href="reltrns.html#cb465-1" tabindex="-1"></a>Sumario1 <span class="ot">&lt;-</span> <span class="fu">cbind</span>(<span class="fu">min</span>(m_dists),</span>
<span id="cb465-2"><a href="reltrns.html#cb465-2" tabindex="-1"></a>                  <span class="fu">max</span>(m_dists),</span>
<span id="cb465-3"><a href="reltrns.html#cb465-3" tabindex="-1"></a>                  <span class="fu">sd</span>(m_dists),</span>
<span id="cb465-4"><a href="reltrns.html#cb465-4" tabindex="-1"></a>                  <span class="fu">mean</span>(m_dists),</span>
<span id="cb465-5"><a href="reltrns.html#cb465-5" tabindex="-1"></a>                  <span class="fu">length</span>(m_dists))</span>
<span id="cb465-6"><a href="reltrns.html#cb465-6" tabindex="-1"></a><span class="fu">colnames</span>(Sumario1) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;Minimo&quot;</span>, <span class="st">&quot;Maximo&quot;</span>, <span class="st">&quot;Desv.Padr&quot;</span>, <span class="st">&quot;Media&quot;</span>, <span class="st">&quot;m(m-1)/2&quot;</span>)</span>
<span id="cb465-7"><a href="reltrns.html#cb465-7" tabindex="-1"></a><span class="fu">rownames</span>(Sumario1) <span class="ot">&lt;-</span> (<span class="st">&quot;Valores&quot;</span>)</span>
<span id="cb465-8"><a href="reltrns.html#cb465-8" tabindex="-1"></a>Sumario1</span></code></pre></div>
<pre><code>##           Minimo   Maximo Desv.Padr    Media m(m-1)/2
## Valores 16.27882 707.3267  172.9708 285.9043      325</code></pre>
<p>A matriz <code>m_dists</code> está como uma classe <code>dist</code>, mas podemos transformá-la em uma classe <code>matrix</code> usando a função <code>as.matrix()</code>.</p>
<div class="sourceCode" id="cb467"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb467-1"><a href="reltrns.html#cb467-1" tabindex="-1"></a>dist <span class="ot">&lt;-</span> (<span class="fu">as.matrix</span>(m_dists))</span>
<span id="cb467-2"><a href="reltrns.html#cb467-2" tabindex="-1"></a><span class="co">#View(dist)</span></span>
<span id="cb467-3"><a href="reltrns.html#cb467-3" tabindex="-1"></a><span class="fu">str</span>(dist)</span>
<span id="cb467-4"><a href="reltrns.html#cb467-4" tabindex="-1"></a><span class="fu">mode</span>(dist)</span>
<span id="cb467-5"><a href="reltrns.html#cb467-5" tabindex="-1"></a><span class="fu">class</span>(dist)</span>
<span id="cb467-6"><a href="reltrns.html#cb467-6" tabindex="-1"></a><span class="co">#head(dist)</span></span>
<span id="cb467-7"><a href="reltrns.html#cb467-7" tabindex="-1"></a>dist[<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>, <span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>] <span class="co">#mostra as 5 primeiras linhas e colunas da matriz</span></span></code></pre></div>
<pre><code>##  num [1:26, 1:26] 0 98.4 228.5 29.2 27.1 ...
##  - attr(*, &quot;dimnames&quot;)=List of 2
##   ..$ : chr [1:26] &quot;S-A-ZA1&quot; &quot;S-R-CC1&quot; &quot;S-R-CT1&quot; &quot;S-R-CP1&quot; ...
##   ..$ : chr [1:26] &quot;S-A-ZA1&quot; &quot;S-R-CC1&quot; &quot;S-R-CT1&quot; &quot;S-R-CP1&quot; ...
## [1] &quot;numeric&quot;
## [1] &quot;matrix&quot; &quot;array&quot; 
##           S-A-ZA1   S-R-CC1  S-R-CT1   S-R-CP1   S-A-TA1
## S-A-ZA1   0.00000  98.43780 228.5235  29.24038  27.09243
## S-R-CC1  98.43780   0.00000 154.2433  82.79493  77.25283
## S-R-CT1 228.52352 154.24331   0.0000 208.52338 209.69263
## S-R-CP1  29.24038  82.79493 208.5234   0.00000  23.25941
## S-A-TA1  27.09243  77.25283 209.6926  23.25941   0.00000</code></pre>
<p>Visualizando a matriz de distâncias, observamos que ela é uma matriz quadrada que contém as distâncias entre cada par de elementos do conjuto de dados. A matriz de distâncias terá dimensão <code>n x n</code>, e cada elemento da matriz será a distância entre cada par de observações ou objetos. A matriz de distâncias é simétrica, pois a distância entre <em>i</em> e <em>j</em> é igual à distância entre <em>j</em> e <em>i</em>. A matriz de distâncias também tem diagonal zero, pois a distância entre uma observação e ela mesma é zero.</p>
</div>
<div id="distribuição-de-frequência-da-matriz-de-distâncias" class="section level2" number="20.5">
<h2><span class="header-section-number">20.5</span> Distribuição de frequência da matriz de distâncias</h2>
<p>Por fim, vamos produzir uma distribuição de frequência da matriz de distâncias, mas antes vamos explorar alguns parâmetros básicos da matriz de distâncias, como o intervalo, a média e o desvio padrão. Para isso, usamos as funções <code>range()</code>, <code>mean()</code> e <code>sd()</code> do R.</p>
<div id="calculando-alguns-parâmetros-básicos" class="section level3" number="20.5.1">
<h3><span class="header-section-number">20.5.1</span> Calculando alguns parâmetros básicos</h3>
<div class="sourceCode" id="cb469"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb469-1"><a href="reltrns.html#cb469-1" tabindex="-1"></a><span class="fu">range</span>(m_dists) <span class="co"># intervalo dos valores da matriz</span></span>
<span id="cb469-2"><a href="reltrns.html#cb469-2" tabindex="-1"></a><span class="fu">mean</span>(m_dists) <span class="co"># média dos valores da matriz</span></span>
<span id="cb469-3"><a href="reltrns.html#cb469-3" tabindex="-1"></a><span class="fu">sd</span>(m_dists) <span class="co"># desvio padrão dos valores da matriz</span></span></code></pre></div>
<pre><code>## [1]  16.27882 707.32666
## [1] 285.9043
## [1] 172.9708</code></pre>
<p>Esses comandos mostram que o <code>menor, maior</code> valores na matriz de distância foram 16.28, 707.33, enquanto que a média foi de 285.9 com um desvio padrão de 172.97.</p>
<div class="infobox note">
<div class="center">
<p><strong>IMPORTANTE</strong></p>
</div>
<p>Lembre que no R e RStudio, a vírgula é usada como separador de decimal e o ponto é apenas indicador de milhar. Por exemplo, 2.500,50 lê-se dois mil e quinhentos e 50 décimos.</p>
</div>
<p>Também podemos calcular a assimetria e a curtose da matriz de distâncias, que são medidas que indicam o grau de desvio da normalidade da distribuição. Para isso, precisamos carregar o pacote <code>moments</code>, que contém as funções <code>skewness()</code> (assimetria) e <code>kurtosis()</code> (curtose).</p>
</div>
<div id="calculando-a-assimetria-e-a-curtose" class="section level3" number="20.5.2">
<h3><span class="header-section-number">20.5.2</span> Calculando a assimetria e a curtose</h3>
<div class="sourceCode" id="cb471"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb471-1"><a href="reltrns.html#cb471-1" tabindex="-1"></a><span class="fu">library</span>(moments)</span>
<span id="cb471-2"><a href="reltrns.html#cb471-2" tabindex="-1"></a>sk <span class="ot">&lt;-</span> <span class="fu">skewness</span>(<span class="fu">as.matrix</span>(m_dists)) <span class="co">#calcula a assimetria da matriz</span></span>
<span id="cb471-3"><a href="reltrns.html#cb471-3" tabindex="-1"></a>ku <span class="ot">&lt;-</span> <span class="fu">kurtosis</span>(<span class="fu">as.matrix</span>(m_dists)) <span class="co">#calcula a curtose da matriz</span></span>
<span id="cb471-4"><a href="reltrns.html#cb471-4" tabindex="-1"></a>sku <span class="ot">&lt;-</span> <span class="fu">cbind</span>(sk,ku) <span class="co"># junta os dois valores em um vetor</span></span>
<span id="cb471-5"><a href="reltrns.html#cb471-5" tabindex="-1"></a><span class="fu">colnames</span>(sku) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;assimetria&quot;</span>, <span class="st">&quot;curtose&quot;</span>) <span class="co"># nomeia as colunas do vetor</span></span>
<span id="cb471-6"><a href="reltrns.html#cb471-6" tabindex="-1"></a>sku[<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>, ] <span class="co"># mostra as primeiras 10 linhas desse vetor</span></span>
<span id="cb471-7"><a href="reltrns.html#cb471-7" tabindex="-1"></a><span class="fu">summary</span>(sku) <span class="co"># mostra um resumo estatístico do vetor</span></span></code></pre></div>
<pre><code>##          assimetria   curtose
## S-A-ZA1  1.03617037  3.101029
## S-R-CC1  1.21511849  3.852134
## S-R-CT1  0.91278496  6.263889
## S-R-CP1  1.06839482  3.177206
## S-A-TA1  1.07960546  3.220821
## S-R-CT2  0.05290597  6.265832
## S-R-CP2  1.08571040  3.241712
## S-A-TA2  1.25111833  4.838956
## S-R-CT3 -2.35918827 10.736848
## S-R-CP3  1.06511174  3.178170
##    assimetria         curtose      
##  Min.   :-3.9660   Min.   : 2.946  
##  1st Qu.: 0.1891   1st Qu.: 3.226  
##  Median : 1.0531   Median : 3.793  
##  Mean   : 0.3625   Mean   : 5.248  
##  3rd Qu.: 1.1593   3rd Qu.: 5.659  
##  Max.   : 1.2826   Max.   :18.799</code></pre>
</div>
</div>
<div id="distribuição-de-frequências-da-matriz-de-distâncias" class="section level2" number="20.6">
<h2><span class="header-section-number">20.6</span> Distribuição de frequências da matriz de distâncias</h2>
<p>Agora que temos uma ideia dos parâmetros básicos da matriz de distâncias, vamos entender sua distribuição de frequência usando um histograma e um boxplot. O histograma mostra a frequência relativa de cada intervalo de valores da matriz, enquanto o boxplot mostra a mediana, os quartis e os valores extremos da matriz.</p>
<p>Para fazer os gráficos, usamos as funções <code>hist()</code> e <code>boxplot.default()</code> do R. Também usamos a função <code>curve()</code> para sobrepor uma curva de normalidade ao histograma, e a função par para ajustar os parâmetros gráficos.</p>
<p>Nas linhas <code>xlim = (), # limites dos eixos</code> do código abaixo, os limites dos eixos do gráfico a ser criado foram definidos entre 0 e 707.3266572. No seu caso, você deve ajustar os valores de <code>xlim</code> para que eles sejam os limites dos valores da sua matriz, definidos pela linha <code>range(dist)</code> <em>(primeira linha do código abaixo)</em>.</p>
<p>Em resumo, o código abaixo plota um histograma e um boxplot da distribuição de dados armazenada na matriz de distâncias. Também é adicionada uma curva normal teórica ao histograma utilizando a média e o desvio padrão dos dados (Figura <a href="reltrns.html#fig:5dists">20.1</a>. As funções <code>floor(min(m_dists))</code> e <code>ceiling(max(m_dists))</code> definem os limites dos graficos pelo valores mínimo e máximo do objeto.</p>
<div class="sourceCode" id="cb473"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb473-1"><a href="reltrns.html#cb473-1" tabindex="-1"></a><span class="fu">range</span>(m_dists)</span>
<span id="cb473-2"><a href="reltrns.html#cb473-2" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">1</span>)) <span class="co"># esse comando faz os gráficos aparecerem um acima do outro</span></span>
<span id="cb473-3"><a href="reltrns.html#cb473-3" tabindex="-1"></a><span class="fu">hist</span>(m_dists,</span>
<span id="cb473-4"><a href="reltrns.html#cb473-4" tabindex="-1"></a>     <span class="at">breaks =</span> <span class="dv">20</span>, <span class="co"># determina o número de colunas do histograma</span></span>
<span id="cb473-5"><a href="reltrns.html#cb473-5" tabindex="-1"></a>     <span class="at">xlim =</span> <span class="fu">range</span>(<span class="fu">floor</span>(<span class="fu">min</span>(m_dists)), <span class="fu">ceiling</span>(<span class="fu">max</span>(m_dists))), <span class="co"># limites dos eixos</span></span>
<span id="cb473-6"><a href="reltrns.html#cb473-6" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">&quot;Distr. de Frequências&quot;</span>,</span>
<span id="cb473-7"><a href="reltrns.html#cb473-7" tabindex="-1"></a>     <span class="at">freq =</span> <span class="cn">FALSE</span>, <span class="co"># mostra as frequências relativas em vez das absolutas</span></span>
<span id="cb473-8"><a href="reltrns.html#cb473-8" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">&quot;Histograma e boxplot da matriz de distâncias&quot;</span>)</span>
<span id="cb473-9"><a href="reltrns.html#cb473-9" tabindex="-1"></a><span class="fu">curve</span>(<span class="fu">dnorm</span>(x, <span class="at">mean=</span><span class="fu">mean</span>(m_dists), <span class="at">sd=</span><span class="fu">sd</span>(m_dists)), <span class="at">add=</span><span class="cn">TRUE</span>) <span class="co"># sobrepõe a curva de normalidade</span></span>
<span id="cb473-10"><a href="reltrns.html#cb473-10" tabindex="-1"></a><span class="fu">boxplot.default</span>(m_dists, <span class="at">horizontal =</span> <span class="cn">TRUE</span>, <span class="at">frame =</span> <span class="cn">FALSE</span>,</span>
<span id="cb473-11"><a href="reltrns.html#cb473-11" tabindex="-1"></a>                <span class="at">xlab=</span><span class="st">&quot;Distr. de Frequências&quot;</span>,</span>
<span id="cb473-12"><a href="reltrns.html#cb473-12" tabindex="-1"></a>                <span class="at">ylim=</span><span class="fu">c</span>(<span class="fu">floor</span>(<span class="fu">min</span>(m_dists)), <span class="fu">ceiling</span>(<span class="fu">max</span>(m_dists)))) <span class="co"># limites dos eixos</span></span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:5dists"></span>
<img src="fundamentos_de_ecologia_numerica_files/figure-html/5dists-1.png" alt="Distribuições de frequências da matriz de distâncias" width="672" />
<p class="caption">
Figura 20.1: Distribuições de frequências da matriz de distâncias
</p>
</div>
<pre><code>## [1]  16.27882 707.32666</code></pre>
<div class="greeting message" style="color: green;">
<p><span style="color:red">IMPORTANTE</span> [Atenção:] Se você recebeu a mensagem de erro <span style="color:red">“Error in plot.new() : figure margins too large”</span>, aumente o tamanho da janela do gráfico e execute o bloco de comandos novamente.</p>
</div>
<p>O comando abaixo apaga os gráficos.</p>
<div class="sourceCode" id="cb475"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb475-1"><a href="reltrns.html#cb475-1" tabindex="-1"></a><span class="fu">dev.off</span>()</span></code></pre></div>
</div>
<div id="relativizando-e-transformando-a-base-de-dados" class="section level2" number="20.7">
<h2><span class="header-section-number">20.7</span> Relativizando e transformando a base de dados</h2>
<p>Na sequencia de códigos a seguir o R realiza relativizações e transformações em dados biológicos <span class="citation">(<a href="#ref-sokal1995">SOKAL; ROHLF, 1995</a>)</span>. Vamos ver passo a passo o que cada seção do código faz. Os códigos para as demais principais relativizações estão nos <a href="reltrns.html#relativiza%C3%A7%C3%B5es">Apêndices</a></p>
<div class="sourceCode" id="cb476"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb476-1"><a href="reltrns.html#cb476-1" tabindex="-1"></a><span class="fu">library</span>(vegan)</span></code></pre></div>
<p>Essa linha carrega o pacote <code>vegan</code> no ambiente R, permitindo o uso de suas funções. O pacote <code>vegan</code> é um pacote do R para análise de ecologia numérica e comunidades biológicas. Ele fornece uma ampla variedade de funções para análise de dados ecológicos, como análise de diversidade, ordenação de espécies, análise de similaridade, entre outras.</p>
<p>A função <code>decostand()</code> é usada para relativizar os dados armazenados na matriz de trabalho (<code>m_trab</code>). O parâmetro <code>method</code> especifica o método de relativização, neste caso <em>“total”</em> (relativização pelo total de cada coluna). Outros métodos disponíveis são <em>max, normalize, range e rankm</em> (@ref(tab:(5tbl-rel)). O parâmetro <code>MARGIN</code> especifica em qual dimensão os cálculos devem ser feitos <em>(1 para linhas, 2 para colunas)</em>. Neste caso, <code>MARGIN=2</code> (colunas). A variável <code>m_relcol</code> armazena o resultado da relativização. Sokal e Rohlf <span class="citation">(<a href="#ref-sokal2009">SOKAL; ROHLF, 2009</a>)</span> tratam dos diversos tipos de relativizações e transformações em dados ecológicos.</p>
<div id="relativização-pelo-total" class="section level3" number="20.7.1">
<h3><span class="header-section-number">20.7.1</span> Relativização pelo total</h3>
<div class="sourceCode" id="cb477"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb477-1"><a href="reltrns.html#cb477-1" tabindex="-1"></a>m_relcol <span class="ot">&lt;-</span> <span class="fu">decostand</span>(m_trab,</span>
<span id="cb477-2"><a href="reltrns.html#cb477-2" tabindex="-1"></a>                         <span class="at">method=</span><span class="st">&quot;total&quot;</span>,</span>
<span id="cb477-3"><a href="reltrns.html#cb477-3" tabindex="-1"></a>                         <span class="at">MARGIN =</span> <span class="dv">2</span>)</span>
<span id="cb477-4"><a href="reltrns.html#cb477-4" tabindex="-1"></a><span class="co">#View(m_relcol)</span></span>
<span id="cb477-5"><a href="reltrns.html#cb477-5" tabindex="-1"></a>m_relcol</span></code></pre></div>
<pre><code>##          ap-davis     as-bimac    as-fasci    ch-bimac   ci-ocela   ci-orien
## S-A-ZA1 0.0000000 0.0004191115 0.000000000 0.000000000 0.00000000 0.00000000
## S-R-CC1 0.0000000 0.0414920369 0.000000000 0.000000000 0.00000000 0.00000000
## S-R-CT1 0.0000000 0.0813076278 0.348101266 0.000000000 0.00000000 0.03496503
## S-R-CP1 0.0000000 0.0079631182 0.000000000 0.000000000 0.00000000 0.00000000
## S-A-TA1 0.0000000 0.0096395641 0.006329114 0.018439716 0.00000000 0.00000000
## S-R-CT2 0.0000000 0.0595138307 0.018987342 0.004255319 0.00000000 0.48251748
## S-R-CP2 0.0000000 0.0020955574 0.006329114 0.000000000 0.57142857 0.06293706
## S-A-TA2 0.0000000 0.0192791282 0.000000000 0.252482270 0.00000000 0.00000000
## S-R-CT3 0.0000000 0.0863369656 0.405063291 0.000000000 0.00000000 0.17482517
## S-R-CP3 0.0000000 0.0067057837 0.000000000 0.000000000 0.18571429 0.16783217
## S-A-TA3 0.0000000 0.0980720872 0.044303797 0.337588652 0.00000000 0.00000000
## S-R-CT4 0.0000000 0.0000000000 0.006329114 0.000000000 0.00000000 0.03496503
## S-R-CP4 0.0000000 0.0000000000 0.000000000 0.000000000 0.15714286 0.04195804
## S-A-TA4 0.0000000 0.1651299246 0.000000000 0.387234043 0.00000000 0.00000000
## B-A-MU1 0.0000000 0.0050293378 0.000000000 0.000000000 0.00000000 0.00000000
## B-R-ET1 0.0000000 0.0012573345 0.000000000 0.000000000 0.00000000 0.00000000
## B-A-GU1 0.0000000 0.0008382230 0.012658228 0.000000000 0.00000000 0.00000000
## B-R-PC2 0.1851852 0.0184409053 0.000000000 0.000000000 0.02857143 0.00000000
## B-A-MU2 0.0000000 0.0414920369 0.000000000 0.000000000 0.00000000 0.00000000
## B-A-GU2 0.0000000 0.0000000000 0.000000000 0.000000000 0.00000000 0.00000000
## B-R-PC3 0.8148148 0.0314333613 0.044303797 0.000000000 0.05714286 0.00000000
## B-A-MU3 0.0000000 0.2141659681 0.000000000 0.000000000 0.00000000 0.00000000
## B-A-GU3 0.0000000 0.0025146689 0.000000000 0.000000000 0.00000000 0.00000000
## B-R-PC4 0.0000000 0.0029337804 0.107594937 0.000000000 0.00000000 0.00000000
## B-A-MU4 0.0000000 0.0984911987 0.000000000 0.000000000 0.00000000 0.00000000
## B-A-GU4 0.0000000 0.0054484493 0.000000000 0.000000000 0.00000000 0.00000000
##         co-macro co-heter   cr-menez cu-lepid  cy-gilbe     ge-brasi he-margi
## S-A-ZA1        0        0 0.00000000        0 0.0000000 0.0000000000      0.0
## S-R-CC1        0        0 0.00000000        0 0.0000000 0.0000000000      0.0
## S-R-CT1        0        1 0.50000000        0 0.0000000 0.0029411765      0.0
## S-R-CP1        0        0 0.00000000        0 0.0000000 0.0000000000      0.0
## S-A-TA1        0        0 0.00000000        0 0.0000000 0.0000000000      0.0
## S-R-CT2        0        0 0.14285714        0 0.0000000 0.0000000000      0.5
## S-R-CP2        0        0 0.00000000        0 0.0000000 0.0000000000      0.0
## S-A-TA2        0        0 0.00000000        0 0.0000000 0.0000000000      0.0
## S-R-CT3        0        0 0.28571429        0 0.0000000 0.0009803922      0.0
## S-R-CP3        0        0 0.00000000        0 0.0000000 0.0000000000      0.0
## S-A-TA3        1        0 0.00000000        0 0.0000000 0.0000000000      0.0
## S-R-CT4        0        0 0.03571429        0 0.3816794 0.0029411765      0.5
## S-R-CP4        0        0 0.00000000        0 0.0000000 0.0000000000      0.0
## S-A-TA4        0        0 0.03571429        0 0.0000000 0.0009803922      0.0
## B-A-MU1        0        0 0.00000000        0 0.0000000 0.1862745098      0.0
## B-R-ET1        0        0 0.00000000        0 0.0000000 0.0000000000      0.0
## B-A-GU1        0        0 0.00000000        0 0.0000000 0.0068627451      0.0
## B-R-PC2        0        0 0.00000000        0 0.0000000 0.0078431373      0.0
## B-A-MU2        0        0 0.00000000        0 0.0000000 0.0656862745      0.0
## B-A-GU2        0        0 0.00000000        0 0.0000000 0.0225490196      0.0
## B-R-PC3        0        0 0.00000000        1 0.0000000 0.0156862745      0.0
## B-A-MU3        0        0 0.00000000        0 0.0000000 0.1421568627      0.0
## B-A-GU3        0        0 0.00000000        0 0.0000000 0.0313725490      0.0
## B-R-PC4        0        0 0.00000000        0 0.6183206 0.0049019608      0.0
## B-A-MU4        0        0 0.00000000        0 0.0000000 0.4990196078      0.0
## B-A-GU4        0        0 0.00000000        0 0.0000000 0.0098039216      0.0
##            ho-malab   hy-pusar le-melan    le-piau le-taeni mo-costa   mo-lepid
## S-A-ZA1 0.000000000 0.00000000        0 0.00000000        0        0 0.00000000
## S-R-CC1 0.000000000 0.00000000        0 0.00000000        0        0 0.02439024
## S-R-CT1 0.009174312 0.12676056        0 0.20000000        0        0 0.95121951
## S-R-CP1 0.045871560 0.02816901        0 0.00000000        0        0 0.00000000
## S-A-TA1 0.000000000 0.00000000        0 0.00000000        0        0 0.00000000
## S-R-CT2 0.155963303 0.60563380        0 0.06666667        0        0 0.02439024
## S-R-CP2 0.091743119 0.02816901        0 0.20000000        0        0 0.00000000
## S-A-TA2 0.018348624 0.00000000        0 0.00000000        0        0 0.00000000
## S-R-CT3 0.284403670 0.15492958        0 0.13333333        0        0 0.00000000
## S-R-CP3 0.036697248 0.00000000        0 0.06666667        0        0 0.00000000
## S-A-TA3 0.183486239 0.00000000        0 0.00000000        0        0 0.00000000
## S-R-CT4 0.036697248 0.04225352        0 0.00000000        0        0 0.00000000
## S-R-CP4 0.018348624 0.00000000        0 0.13333333        0        0 0.00000000
## S-A-TA4 0.082568807 0.00000000        0 0.13333333        0        0 0.00000000
## B-A-MU1 0.000000000 0.00000000        0 0.00000000        0        0 0.00000000
## B-R-ET1 0.000000000 0.00000000        0 0.00000000        0        0 0.00000000
## B-A-GU1 0.000000000 0.00000000        0 0.00000000        0        0 0.00000000
## B-R-PC2 0.000000000 0.00000000        1 0.00000000        1        0 0.00000000
## B-A-MU2 0.009174312 0.00000000        0 0.00000000        0        0 0.00000000
## B-A-GU2 0.000000000 0.00000000        0 0.00000000        0        0 0.00000000
## B-R-PC3 0.018348624 0.01408451        0 0.00000000        0        1 0.00000000
## B-A-MU3 0.000000000 0.00000000        0 0.00000000        0        0 0.00000000
## B-A-GU3 0.000000000 0.00000000        0 0.00000000        0        0 0.00000000
## B-R-PC4 0.009174312 0.00000000        0 0.06666667        0        0 0.00000000
## B-A-MU4 0.000000000 0.00000000        0 0.00000000        0        0 0.00000000
## B-A-GU4 0.000000000 0.00000000        0 0.00000000        0        0 0.00000000
##            or-nilot    pa-manag pimel-sp   po-retic    po-vivip    pr-brevi
## S-A-ZA1 0.000000000 0.000000000        0 0.00000000 0.000000000 0.032258065
## S-R-CC1 0.002358491 0.000000000        0 0.00000000 0.000000000 0.000000000
## S-R-CT1 0.042452830 0.000000000        1 0.00000000 0.048057260 0.017921147
## S-R-CP1 0.000000000 0.000000000        0 0.00000000 0.015337423 0.000000000
## S-A-TA1 0.000000000 0.000000000        0 0.00000000 0.000000000 0.003584229
## S-R-CT2 0.090801887 0.000000000        0 0.05249344 0.225971370 0.053763441
## S-R-CP2 0.000000000 0.000000000        0 0.00000000 0.032719836 0.017921147
## S-A-TA2 0.000000000 0.000000000        0 0.00000000 0.000000000 0.007168459
## S-R-CT3 0.162735849 0.000000000        0 0.01312336 0.333333333 0.587813620
## S-R-CP3 0.000000000 0.000000000        0 0.00000000 0.010224949 0.000000000
## S-A-TA3 0.000000000 0.000000000        0 0.00000000 0.000000000 0.000000000
## S-R-CT4 0.086084906 0.000000000        0 0.00000000 0.028629857 0.211469534
## S-R-CP4 0.000000000 0.000000000        0 0.00000000 0.081799591 0.000000000
## S-A-TA4 0.001179245 0.000000000        0 0.00000000 0.000000000 0.010752688
## B-A-MU1 0.007075472 0.000000000        0 0.00000000 0.000000000 0.000000000
## B-R-ET1 0.009433962 0.001805054        0 0.08923885 0.000000000 0.000000000
## B-A-GU1 0.003537736 0.019855596        0 0.00000000 0.000000000 0.000000000
## B-R-PC2 0.005896226 0.000000000        0 0.00000000 0.000000000 0.032258065
## B-A-MU2 0.001179245 0.000000000        0 0.02624672 0.008179959 0.000000000
## B-A-GU2 0.042452830 0.184115523        0 0.00000000 0.000000000 0.000000000
## B-R-PC3 0.076650943 0.000000000        0 0.00000000 0.000000000 0.021505376
## B-A-MU3 0.012971698 0.000000000        0 0.12073491 0.049079755 0.003584229
## B-A-GU3 0.291273585 0.451263538        0 0.00000000 0.000000000 0.000000000
## B-R-PC4 0.010613208 0.000000000        0 0.00000000 0.000000000 0.000000000
## B-A-MU4 0.001179245 0.000000000        0 0.69816273 0.166666667 0.000000000
## B-A-GU4 0.152122642 0.342960289        0 0.00000000 0.000000000 0.000000000
##         ps-rhomb ps-genise   se-heter se-piaba se-spilo    st-noton sy-marmo
## S-A-ZA1        0         0 0.00000000        0        0 0.000000000        0
## S-R-CC1        0         0 0.00000000        0        0 0.000000000        0
## S-R-CT1        0         0 0.13513514        1        0 0.004878049        0
## S-R-CP1        0         0 0.04729730        0        0 0.000000000        0
## S-A-TA1        0         0 0.01351351        0        0 0.000000000        0
## S-R-CT2        0         0 0.20270270        0        0 0.121951220        0
## S-R-CP2        0         0 0.00000000        0        0 0.000000000        1
## S-A-TA2        0         0 0.00000000        0        0 0.000000000        0
## S-R-CT3        1         1 0.12837838        0        1 0.560975610        0
## S-R-CP3        0         0 0.00000000        0        0 0.000000000        0
## S-A-TA3        0         0 0.00000000        0        0 0.000000000        0
## S-R-CT4        0         0 0.01013514        0        0 0.312195122        0
## S-R-CP4        0         0 0.01013514        0        0 0.000000000        0
## S-A-TA4        0         0 0.00000000        0        0 0.000000000        0
## B-A-MU1        0         0 0.00000000        0        0 0.000000000        0
## B-R-ET1        0         0 0.00000000        0        0 0.000000000        0
## B-A-GU1        0         0 0.00000000        0        0 0.000000000        0
## B-R-PC2        0         0 0.03378378        0        0 0.000000000        0
## B-A-MU2        0         0 0.00000000        0        0 0.000000000        0
## B-A-GU2        0         0 0.00000000        0        0 0.000000000        0
## B-R-PC3        0         0 0.31418919        0        0 0.000000000        0
## B-A-MU3        0         0 0.00000000        0        0 0.000000000        0
## B-A-GU3        0         0 0.00000000        0        0 0.000000000        0
## B-R-PC4        0         0 0.10472973        0        0 0.000000000        0
## B-A-MU4        0         0 0.00000000        0        0 0.000000000        0
## B-A-GU4        0         0 0.00000000        0        0 0.000000000        0
##          te-chalc   tr-signa
## S-A-ZA1 0.0000000 0.00000000
## S-R-CC1 0.0000000 0.00000000
## S-R-CT1 0.0000000 0.08653846
## S-R-CP1 0.0000000 0.00000000
## S-A-TA1 0.0000000 0.00000000
## S-R-CT2 0.0000000 0.07211538
## S-R-CP2 0.0000000 0.00000000
## S-A-TA2 0.0000000 0.00000000
## S-R-CT3 0.0000000 0.03365385
## S-R-CP3 0.0000000 0.00000000
## S-A-TA3 0.0000000 0.00000000
## S-R-CT4 0.0000000 0.67788462
## S-R-CP4 0.0000000 0.00000000
## S-A-TA4 0.0000000 0.00000000
## B-A-MU1 0.0000000 0.00000000
## B-R-ET1 0.0000000 0.00000000
## B-A-GU1 0.0000000 0.00000000
## B-R-PC2 0.5671642 0.11057692
## B-A-MU2 0.0000000 0.00000000
## B-A-GU2 0.0000000 0.00000000
## B-R-PC3 0.4328358 0.00000000
## B-A-MU3 0.0000000 0.00000000
## B-A-GU3 0.0000000 0.00000000
## B-R-PC4 0.0000000 0.01923077
## B-A-MU4 0.0000000 0.00000000
## B-A-GU4 0.0000000 0.00000000</code></pre>
<div class="sourceCode" id="cb479"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb479-1"><a href="reltrns.html#cb479-1" tabindex="-1"></a><span class="co">#colSums(m_relcol)</span></span>
<span id="cb479-2"><a href="reltrns.html#cb479-2" tabindex="-1"></a><span class="co">#range(m_relcol)</span></span></code></pre></div>
</div>
<div id="transformação-pelo-arcoseno-da-raiz-quadrada" class="section level3" number="20.7.2">
<h3><span class="header-section-number">20.7.2</span> Transformação pelo arcoseno da raiz quadrada</h3>
<p>A seguir é realizada a transformação pelo arcoseno da raiz quadrada, apropriada para ados em proporção como os ados previamente relativisados. Para cada transformação, a função é aplicada aos dados de interesse e o resultado é armazenado em uma nova variável. A função <code>View()</code> é usada para visualizar o resultado de cada transformação na forma de uma tabela. Os códigos para as demais principais transformações estão <a href="reltrns.html#transforma%C3%A7%C3%B5es">AQUI</a></p>
<div class="sourceCode" id="cb480"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb480-1"><a href="reltrns.html#cb480-1" tabindex="-1"></a>m_relcol_asrq <span class="ot">&lt;-</span> <span class="fu">asin</span>(<span class="fu">sqrt</span>(m_relcol))</span>
<span id="cb480-2"><a href="reltrns.html#cb480-2" tabindex="-1"></a><span class="co">#View(m_relcol_asrq)</span></span>
<span id="cb480-3"><a href="reltrns.html#cb480-3" tabindex="-1"></a>m_relcol_asrqpi <span class="ot">&lt;-</span> <span class="dv">2</span><span class="sc">/</span>pi<span class="sc">*</span>(<span class="fu">asin</span>(<span class="fu">sqrt</span>(m_relcol)))</span>
<span id="cb480-4"><a href="reltrns.html#cb480-4" tabindex="-1"></a><span class="co">#View(m_relcol_asrqpi)</span></span>
<span id="cb480-5"><a href="reltrns.html#cb480-5" tabindex="-1"></a><span class="co">#colSums(m_relcol_asrqpi)</span></span>
<span id="cb480-6"><a href="reltrns.html#cb480-6" tabindex="-1"></a><span class="co">#range(m_relcol_asrqpi)</span></span></code></pre></div>
</div>
</div>
<div id="id_501reinicio2" class="section level2" number="20.8">
<h2><span class="header-section-number">20.8</span> REINÍCIO 2</h2>
<p>Aqui estabelecemos a matriz transformada depois de ter sido relativisada como <code>m_trns</code>.</p>
<div class="sourceCode" id="cb481"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb481-1"><a href="reltrns.html#cb481-1" tabindex="-1"></a>m_trns <span class="ot">&lt;-</span> m_relcol_asrqpi</span>
<span id="cb481-2"><a href="reltrns.html#cb481-2" tabindex="-1"></a><span class="co">#m_dists &lt;- dist(m_trns, method = &quot;euclidian&quot;, diag = TRUE, upper = FALSE)</span></span></code></pre></div>
<p>Agora é com você…Refaça toda a análise com as relativizações e transformações adequadas para a matriz de dados fornecida.</p>
</div>
<div id="apêndices-13" class="section level2 unnumbered">
<h2>Apêndices</h2>
<div id="relativizações" class="section level3 unnumbered">
<h3>Relativizações</h3>
<div id="total-das-colunas" class="section level4 unnumbered">
<h4>Total das colunas</h4>
<div class="sourceCode" id="cb482"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb482-1"><a href="reltrns.html#cb482-1" tabindex="-1"></a>m_relcol <span class="ot">&lt;-</span> <span class="fu">decostand</span>(m_bruta,</span>
<span id="cb482-2"><a href="reltrns.html#cb482-2" tabindex="-1"></a>                         <span class="at">method=</span><span class="st">&quot;total&quot;</span>,</span>
<span id="cb482-3"><a href="reltrns.html#cb482-3" tabindex="-1"></a>                         <span class="at">MARGIN =</span> <span class="dv">2</span>)</span>
<span id="cb482-4"><a href="reltrns.html#cb482-4" tabindex="-1"></a><span class="fu">View</span>(m_relcol)</span>
<span id="cb482-5"><a href="reltrns.html#cb482-5" tabindex="-1"></a>m_relcol</span></code></pre></div>
<p>A função <code>decostand()</code> é usada para relativizar os dados armazenados no vetor <code>m_bruta</code>. O parâmetro <code>method</code> especifica o método de relativização, neste caso “total” (relativização pelo total de cada coluna). Outros métodos disponíveis são <code>max</code>, <code>normalize</code>, <code>range</code> e <code>rankm</code> (Figura <a href="reltrns.html#tab:5rels">20.3</a>). O parâmetro <code>MARGIN</code> especifica em qual dimensão os cálculos devem ser feitos (1 para linhas, 2 para colunas). Neste caso, <code>MARGIN=2</code> (colunas). A variável <code>m_relcol</code> armazena o resultado da relativização. Sokal e Rohlf <span class="citation">(<a href="#ref-sokal1995">1995</a>)</span> tratam dos diversos tipos de relativizações e transformações em dados ecológicos.</p>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:5rels">Tabela 20.3: </span><span id="tab:5rels">Tabela 20.4: </span>Métodos de relativização da função <code>decostand</code>
</caption>
<thead>
<tr>
<th style="text-align:center;">
Função
</th>
<th style="text-align:left;">
Descrição
</th>
<th style="text-align:left;">
Uso adequado
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;">
max
</td>
<td style="text-align:left;width: 8cm; ">
Divide cada valor pela maior observação da coluna em que está localizado. Todos os valores resultantes serão menores ou iguais a 1. Adequada para análise em escala relativa
</td>
<td style="text-align:left;width: 8cm; ">
Quando a escala de cada variável é conhecida e a análise deve ser feita em uma escala relativa
</td>
</tr>
<tr>
<td style="text-align:center;">
normalize
</td>
<td style="text-align:left;width: 8cm; ">
Divide cada valor pelo comprimento do vetor. Isso resulta em valores cujo comprimento é sempre igual a 1. Adequada para análise de dados de frequência
</td>
<td style="text-align:left;width: 8cm; ">
Para análise de dados de frequência
</td>
</tr>
<tr>
<td style="text-align:center;">
range
</td>
<td style="text-align:left;width: 8cm; ">
Subtrai o valor mínimo da coluna de cada valor e, em seguida, divide pelo intervalo (ou amplitude) dos valores da coluna. Isso resulta em valores entre 0 e 1.
</td>
<td style="text-align:left;width: 8cm; ">
Quando a amplitude dos valores em cada coluna é importante para a análise
</td>
</tr>
<tr>
<td style="text-align:center;">
rankm
</td>
<td style="text-align:left;width: 8cm; ">
Transforma os valores em suas posições dentro da coluna, em ordem crescente. O menor valor recebe o valor 1 e o maior valor recebe o valor igual ao comprimento da coluna.
</td>
<td style="text-align:left;width: 8cm; ">
Quando a escala absoluta dos valores não é importante, mas a ordem dos valores é significativa.
</td>
</tr>
</tbody>
</table>
</div>
</div>
<div id="transformações" class="section level3 unnumbered">
<h3>Transformações</h3>
<p>Essa seção mostra as diversas transformações nos dados armazenados no vetor <code>m_bruta</code>. Para cada transformação, a função é aplicada aos dados da matriz e o resultado é armazenado em uma nova variável. A função <code>View()</code> pode ser usada para visualizar o resultado de cada transformação na forma de uma tabela. Ela mostra o código que realiza diversas transformações na matriz de dados. Para cada transformação, a função é aplicada aos dados e o resultado é armazenado em uma nova variável.</p>
<div id="log10" class="section level4 unnumbered">
<h4>Log10</h4>
<p>Não aceita zeros, porque o log de zero é indeterminado. Por isso devemos substituir os valores com erro (infinito negativo) por zero, usando a função <code>replace()</code>.</p>
<div class="sourceCode" id="cb483"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb483-1"><a href="reltrns.html#cb483-1" tabindex="-1"></a>m_lg10 <span class="ot">&lt;-</span> <span class="fu">log10</span>(m_bruta)</span>
<span id="cb483-2"><a href="reltrns.html#cb483-2" tabindex="-1"></a><span class="co">#View(m_lg10)</span></span>
<span id="cb483-3"><a href="reltrns.html#cb483-3" tabindex="-1"></a>m_lg10 <span class="ot">&lt;-</span> <span class="fu">replace</span>(m_lg10, <span class="fu">is.infinite</span>(m_lg10), <span class="dv">0</span>)</span>
<span id="cb483-4"><a href="reltrns.html#cb483-4" tabindex="-1"></a><span class="fu">head</span>(m_lg10)</span></code></pre></div>
</div>
<div id="logx1" class="section level4 unnumbered">
<h4>Log(x+1)</h4>
<p>Desaconselhavel para valores que variam entre 0-1.</p>
<div class="sourceCode" id="cb484"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb484-1"><a href="reltrns.html#cb484-1" tabindex="-1"></a>m_lgx1 <span class="ot">&lt;-</span> <span class="fu">log</span>(m_bruta<span class="sc">+</span><span class="dv">1</span>)</span>
<span id="cb484-2"><a href="reltrns.html#cb484-2" tabindex="-1"></a><span class="co">#View(m_lgx1)</span></span></code></pre></div>
</div>
<div id="exponenciais" class="section level4 unnumbered">
<h4>Exponenciais</h4>
<p>“Power transformations”, onde o valor de <code>p</code> estabelece a compressão dos dados.</p>
<div class="sourceCode" id="cb485"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb485-1"><a href="reltrns.html#cb485-1" tabindex="-1"></a>m_bruta_P1 <span class="ot">&lt;-</span> m_bruta<span class="sc">^</span><span class="dv">1</span> <span class="co">#p=1</span></span>
<span id="cb485-2"><a href="reltrns.html#cb485-2" tabindex="-1"></a><span class="co">#View(m_bruta_P1)</span></span>
<span id="cb485-3"><a href="reltrns.html#cb485-3" tabindex="-1"></a>m_bruta_P05 <span class="ot">&lt;-</span> m_bruta<span class="sc">^</span><span class="fl">0.5</span> <span class="co">#p=0,5</span></span>
<span id="cb485-4"><a href="reltrns.html#cb485-4" tabindex="-1"></a><span class="co">#View(m_bruta_P05)</span></span>
<span id="cb485-5"><a href="reltrns.html#cb485-5" tabindex="-1"></a>m_bruta_P01 <span class="ot">&lt;-</span> m_bruta<span class="sc">^</span><span class="fl">0.1</span> <span class="co">#p=0,1</span></span>
<span id="cb485-6"><a href="reltrns.html#cb485-6" tabindex="-1"></a><span class="co">#View(m_bruta_P01)</span></span></code></pre></div>
</div>
<div id="presençaausência" class="section level4 unnumbered">
<h4>Presença/Ausência</h4>
<div class="sourceCode" id="cb486"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb486-1"><a href="reltrns.html#cb486-1" tabindex="-1"></a>m_pa <span class="ot">&lt;-</span> (m_bruta<span class="sc">&gt;</span><span class="dv">0</span>)<span class="sc">*</span><span class="dv">1</span><span class="dt">L</span></span>
<span id="cb486-2"><a href="reltrns.html#cb486-2" tabindex="-1"></a><span class="co">#View(m_pa)</span></span></code></pre></div>
</div>
<div id="raiz-quadrada" class="section level4 unnumbered">
<h4>Raiz quadrada</h4>
<div class="sourceCode" id="cb487"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb487-1"><a href="reltrns.html#cb487-1" tabindex="-1"></a>m_rq <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(m_bruta)</span>
<span id="cb487-2"><a href="reltrns.html#cb487-2" tabindex="-1"></a><span class="co">#View(m_rq)</span></span></code></pre></div>
</div>
<div id="arcoseno-da-raiz-quadrada" class="section level4 unnumbered">
<h4>Arcoseno da raiz quadrada</h4>
<p>Os valores de entrada tem que variar entre 0 e 1. Ideal para matrizes relativizadas. Duas formulações estão disponíveis, com e sem a multiplicação por <code>2/pi</code>. A segunda opção costuma ter melhor efeito na normalização dos dados.</p>
<div class="sourceCode" id="cb488"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb488-1"><a href="reltrns.html#cb488-1" tabindex="-1"></a>m_asrq <span class="ot">&lt;-</span> <span class="fu">asin</span>(<span class="fu">sqrt</span>(m_relcol))</span>
<span id="cb488-2"><a href="reltrns.html#cb488-2" tabindex="-1"></a><span class="co">#View(m_asrq)</span></span>
<span id="cb488-3"><a href="reltrns.html#cb488-3" tabindex="-1"></a>m_asrqpi <span class="ot">&lt;-</span> <span class="dv">2</span><span class="sc">/</span>pi<span class="sc">*</span>(<span class="fu">asin</span>(<span class="fu">sqrt</span>(m_relcol)))</span>
<span id="cb488-4"><a href="reltrns.html#cb488-4" tabindex="-1"></a><span class="fu">View</span>(m_asrqpi)</span></code></pre></div>
</div>
</div>
</div>
<div id="script-limpo-10" class="section level2 unnumbered">
<h2>Script limpo</h2>
<p>Aqui apresento o scrip na íntegra sem os textos ou outros comentários. Você pode copiar e colar no R para executa-lo. Lembre de remover os <span style="color:green"><code>#</code></span> ou <span style="color:green"><code>##</code></span> caso necessite executar essas linhas.</p>
<div class="sourceCode" id="cb489"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb489-1"><a href="reltrns.html#cb489-1" tabindex="-1"></a><span class="do">## dev.off() #apaga os graficos, se houver algum</span></span>
<span id="cb489-2"><a href="reltrns.html#cb489-2" tabindex="-1"></a><span class="do">## rm(list=ls(all=TRUE)) #limpa a memória</span></span>
<span id="cb489-3"><a href="reltrns.html#cb489-3" tabindex="-1"></a><span class="do">## cat(&quot;\014&quot;) #limpa o console</span></span>
<span id="cb489-4"><a href="reltrns.html#cb489-4" tabindex="-1"></a><span class="do">## install.packages(&quot;openxlsx&quot;) #importa arquivos do excel</span></span>
<span id="cb489-5"><a href="reltrns.html#cb489-5" tabindex="-1"></a><span class="do">## install.packages(&quot;moments&quot;) #calcula assimetria e curtose dos dados</span></span>
<span id="cb489-6"><a href="reltrns.html#cb489-6" tabindex="-1"></a><span class="do">## install.packages(&quot;vegan&quot;) #estatisticas para ecologia de comunidades</span></span>
<span id="cb489-7"><a href="reltrns.html#cb489-7" tabindex="-1"></a><span class="do">## getwd()</span></span>
<span id="cb489-8"><a href="reltrns.html#cb489-8" tabindex="-1"></a><span class="do">## setwd(&quot;C:/Seu/Diretório/De/Trabalho&quot;)</span></span>
<span id="cb489-9"><a href="reltrns.html#cb489-9" tabindex="-1"></a><span class="fu">library</span>(openxlsx)</span>
<span id="cb489-10"><a href="reltrns.html#cb489-10" tabindex="-1"></a><span class="co">#dir &lt;- getwd() #criamos um vetor com o diretório  de trbalho </span></span>
<span id="cb489-11"><a href="reltrns.html#cb489-11" tabindex="-1"></a><span class="co">#shell.exec(dir) #abre o diretorio de trabalho no Windows Explorer</span></span>
<span id="cb489-12"><a href="reltrns.html#cb489-12" tabindex="-1"></a>m_bruta <span class="ot">&lt;-</span> <span class="fu">read.xlsx</span>(<span class="st">&quot;D:/Elvio/OneDrive/Disciplinas/_EcoNumerica/5.Matrizes/peixes06.xlsx&quot;</span>,</span>
<span id="cb489-13"><a href="reltrns.html#cb489-13" tabindex="-1"></a>                   <span class="at">rowNames =</span> T, <span class="at">colNames =</span> T,</span>
<span id="cb489-14"><a href="reltrns.html#cb489-14" tabindex="-1"></a>                   <span class="at">sheet =</span> <span class="st">&quot;Sheet1&quot;</span>)</span>
<span id="cb489-15"><a href="reltrns.html#cb489-15" tabindex="-1"></a><span class="fu">str</span>(m_bruta)</span>
<span id="cb489-16"><a href="reltrns.html#cb489-16" tabindex="-1"></a><span class="co">#View(m_bruta)</span></span>
<span id="cb489-17"><a href="reltrns.html#cb489-17" tabindex="-1"></a>m_bruta[<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>,<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>] <span class="co">#[1:5,1:5] mostra apenas as linhas e colunas de 1 a 5.</span></span>
<span id="cb489-18"><a href="reltrns.html#cb489-18" tabindex="-1"></a><span class="do">## #View(m_bruta)</span></span>
<span id="cb489-19"><a href="reltrns.html#cb489-19" tabindex="-1"></a><span class="do">## print(m_bruta[1:8,1:8])</span></span>
<span id="cb489-20"><a href="reltrns.html#cb489-20" tabindex="-1"></a><span class="do">## m_bruta[1:10,1:10]</span></span>
<span id="cb489-21"><a href="reltrns.html#cb489-21" tabindex="-1"></a><span class="do">## str(m_bruta)</span></span>
<span id="cb489-22"><a href="reltrns.html#cb489-22" tabindex="-1"></a><span class="do">## mode(m_bruta)</span></span>
<span id="cb489-23"><a href="reltrns.html#cb489-23" tabindex="-1"></a><span class="do">## class(m_bruta)</span></span>
<span id="cb489-24"><a href="reltrns.html#cb489-24" tabindex="-1"></a><span class="co">#View(m_bruta)</span></span>
<span id="cb489-25"><a href="reltrns.html#cb489-25" tabindex="-1"></a><span class="fu">print</span>(m_bruta)</span>
<span id="cb489-26"><a href="reltrns.html#cb489-26" tabindex="-1"></a><span class="fu">head</span>(m_bruta)</span>
<span id="cb489-27"><a href="reltrns.html#cb489-27" tabindex="-1"></a><span class="fu">range</span>(m_bruta) <span class="co">#menor e maior valores</span></span>
<span id="cb489-28"><a href="reltrns.html#cb489-28" tabindex="-1"></a><span class="fu">length</span>(m_bruta) <span class="co">#no. de colunas</span></span>
<span id="cb489-29"><a href="reltrns.html#cb489-29" tabindex="-1"></a><span class="fu">ncol</span>(m_bruta) <span class="co">#no. de N colunas</span></span>
<span id="cb489-30"><a href="reltrns.html#cb489-30" tabindex="-1"></a><span class="fu">nrow</span>(m_bruta) <span class="co">#no. de M linhas</span></span>
<span id="cb489-31"><a href="reltrns.html#cb489-31" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">lengths</span>(m_bruta)) <span class="co">#soma os nos. de colunas</span></span>
<span id="cb489-32"><a href="reltrns.html#cb489-32" tabindex="-1"></a><span class="fu">length</span>(<span class="fu">as.matrix</span>(m_bruta)) <span class="co">#tamanho da matriz m x n</span></span>
<span id="cb489-33"><a href="reltrns.html#cb489-33" tabindex="-1"></a><span class="fu">sum</span>(m_bruta <span class="sc">==</span> <span class="dv">0</span>) <span class="co"># número de observações igual a zero</span></span>
<span id="cb489-34"><a href="reltrns.html#cb489-34" tabindex="-1"></a><span class="fu">sum</span>(m_bruta <span class="sc">&gt;</span> <span class="dv">0</span>) <span class="co"># número de observações maiores que zero</span></span>
<span id="cb489-35"><a href="reltrns.html#cb489-35" tabindex="-1"></a>zeros <span class="ot">&lt;-</span> (<span class="fu">sum</span>(m_bruta <span class="sc">==</span> <span class="dv">0</span>)<span class="sc">/</span><span class="fu">length</span>(<span class="fu">as.matrix</span>(m_bruta)))<span class="sc">*</span><span class="dv">100</span> <span class="co"># proporção de zeros na matriz</span></span>
<span id="cb489-36"><a href="reltrns.html#cb489-36" tabindex="-1"></a>zeros</span>
<span id="cb489-37"><a href="reltrns.html#cb489-37" tabindex="-1"></a>tamanho <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb489-38"><a href="reltrns.html#cb489-38" tabindex="-1"></a>  Função <span class="ot">=</span> <span class="fu">c</span>(<span class="st">&quot;range&quot;</span>, <span class="st">&quot;lenght&quot;</span>, <span class="st">&quot;m cols&quot;</span>, <span class="st">&quot;n linhas&quot;</span>, <span class="st">&quot;Tamanho&quot;</span>, <span class="st">&quot;Tamanho&quot;</span>,</span>
<span id="cb489-39"><a href="reltrns.html#cb489-39" tabindex="-1"></a>             <span class="st">&quot;Zeros&quot;</span>, <span class="st">&quot;Nao zeros&quot;</span>, <span class="st">&quot;% Zeros&quot;</span>),</span>
<span id="cb489-40"><a href="reltrns.html#cb489-40" tabindex="-1"></a>  <span class="at">Resultado =</span> <span class="fu">c</span>(<span class="fu">paste</span>(<span class="fu">range</span>(m_bruta), <span class="at">collapse =</span> <span class="st">&quot; - &quot;</span>), <span class="fu">length</span>(m_bruta), <span class="fu">ncol</span>(m_bruta),</span>
<span id="cb489-41"><a href="reltrns.html#cb489-41" tabindex="-1"></a>                <span class="fu">nrow</span>(m_bruta), <span class="fu">sum</span>(<span class="fu">lengths</span>(m_bruta)), <span class="fu">length</span>(<span class="fu">as.matrix</span>(m_bruta)), <span class="fu">sum</span>(m_bruta <span class="sc">==</span> <span class="dv">0</span>),</span>
<span id="cb489-42"><a href="reltrns.html#cb489-42" tabindex="-1"></a>                <span class="fu">sum</span>(m_bruta <span class="sc">&gt;</span> <span class="dv">0</span>), <span class="fu">round</span>(zeros, <span class="dv">1</span>)))</span>
<span id="cb489-43"><a href="reltrns.html#cb489-43" tabindex="-1"></a>tamanho</span>
<span id="cb489-44"><a href="reltrns.html#cb489-44" tabindex="-1"></a>m_trab <span class="ot">&lt;-</span> m_bruta</span>
<span id="cb489-45"><a href="reltrns.html#cb489-45" tabindex="-1"></a>m_dists <span class="ot">&lt;-</span> <span class="fu">dist</span>(m_trab, <span class="at">method =</span> <span class="st">&quot;euclidian&quot;</span>, <span class="at">diag =</span> <span class="cn">TRUE</span>, <span class="at">upper =</span> <span class="cn">FALSE</span>)</span>
<span id="cb489-46"><a href="reltrns.html#cb489-46" tabindex="-1"></a><span class="co">#m_dists</span></span>
<span id="cb489-47"><a href="reltrns.html#cb489-47" tabindex="-1"></a><span class="fu">str</span>(m_dists)</span>
<span id="cb489-48"><a href="reltrns.html#cb489-48" tabindex="-1"></a><span class="fu">mode</span>(m_dists)</span>
<span id="cb489-49"><a href="reltrns.html#cb489-49" tabindex="-1"></a><span class="fu">class</span>(m_dists)</span>
<span id="cb489-50"><a href="reltrns.html#cb489-50" tabindex="-1"></a><span class="fu">length</span>(<span class="fu">as.matrix</span>(m_dists))</span>
<span id="cb489-51"><a href="reltrns.html#cb489-51" tabindex="-1"></a><span class="fu">as.matrix</span>(m_dists)[<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>, <span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>]</span>
<span id="cb489-52"><a href="reltrns.html#cb489-52" tabindex="-1"></a><span class="fu">range</span>(m_trab)</span>
<span id="cb489-53"><a href="reltrns.html#cb489-53" tabindex="-1"></a><span class="fu">range</span>(m_dists)</span>
<span id="cb489-54"><a href="reltrns.html#cb489-54" tabindex="-1"></a><span class="fu">min</span>(m_dists)</span>
<span id="cb489-55"><a href="reltrns.html#cb489-55" tabindex="-1"></a><span class="fu">max</span>(m_dists)</span>
<span id="cb489-56"><a href="reltrns.html#cb489-56" tabindex="-1"></a><span class="fu">mean</span>(m_dists) <span class="co">#CENTROIDE!! ou Grand mean</span></span>
<span id="cb489-57"><a href="reltrns.html#cb489-57" tabindex="-1"></a><span class="fu">sd</span>(m_dists)  <span class="co">#standard deviation</span></span>
<span id="cb489-58"><a href="reltrns.html#cb489-58" tabindex="-1"></a>centroide <span class="ot">&lt;-</span> <span class="fu">mean</span>(m_dists)</span>
<span id="cb489-59"><a href="reltrns.html#cb489-59" tabindex="-1"></a>centroide</span>
<span id="cb489-60"><a href="reltrns.html#cb489-60" tabindex="-1"></a><span class="fu">length</span>(m_dists)</span>
<span id="cb489-61"><a href="reltrns.html#cb489-61" tabindex="-1"></a>m <span class="ot">&lt;-</span> <span class="fu">nrow</span>(<span class="fu">as.matrix</span>(m_dists))</span>
<span id="cb489-62"><a href="reltrns.html#cb489-62" tabindex="-1"></a>m</span>
<span id="cb489-63"><a href="reltrns.html#cb489-63" tabindex="-1"></a>m<span class="sc">*</span>(m<span class="dv">-1</span>)<span class="sc">/</span><span class="dv">2</span></span>
<span id="cb489-64"><a href="reltrns.html#cb489-64" tabindex="-1"></a><span class="fu">summary</span>(m_dists)</span>
<span id="cb489-65"><a href="reltrns.html#cb489-65" tabindex="-1"></a>Sumario1 <span class="ot">&lt;-</span> <span class="fu">cbind</span>(<span class="fu">min</span>(m_dists),</span>
<span id="cb489-66"><a href="reltrns.html#cb489-66" tabindex="-1"></a>                  <span class="fu">max</span>(m_dists),</span>
<span id="cb489-67"><a href="reltrns.html#cb489-67" tabindex="-1"></a>                  <span class="fu">sd</span>(m_dists),</span>
<span id="cb489-68"><a href="reltrns.html#cb489-68" tabindex="-1"></a>                  <span class="fu">mean</span>(m_dists),</span>
<span id="cb489-69"><a href="reltrns.html#cb489-69" tabindex="-1"></a>                  <span class="fu">length</span>(m_dists))</span>
<span id="cb489-70"><a href="reltrns.html#cb489-70" tabindex="-1"></a><span class="fu">colnames</span>(Sumario1) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;Minimo&quot;</span>, <span class="st">&quot;Maximo&quot;</span>, <span class="st">&quot;Desv.Padr&quot;</span>, <span class="st">&quot;Media&quot;</span>, <span class="st">&quot;m(m-1)/2&quot;</span>)</span>
<span id="cb489-71"><a href="reltrns.html#cb489-71" tabindex="-1"></a><span class="fu">rownames</span>(Sumario1) <span class="ot">&lt;-</span> (<span class="st">&quot;Valores&quot;</span>)</span>
<span id="cb489-72"><a href="reltrns.html#cb489-72" tabindex="-1"></a>Sumario1</span>
<span id="cb489-73"><a href="reltrns.html#cb489-73" tabindex="-1"></a>dist <span class="ot">&lt;-</span> (<span class="fu">as.matrix</span>(m_dists))</span>
<span id="cb489-74"><a href="reltrns.html#cb489-74" tabindex="-1"></a><span class="co">#View(dist)</span></span>
<span id="cb489-75"><a href="reltrns.html#cb489-75" tabindex="-1"></a><span class="fu">str</span>(dist)</span>
<span id="cb489-76"><a href="reltrns.html#cb489-76" tabindex="-1"></a><span class="fu">mode</span>(dist)</span>
<span id="cb489-77"><a href="reltrns.html#cb489-77" tabindex="-1"></a><span class="fu">class</span>(dist)</span>
<span id="cb489-78"><a href="reltrns.html#cb489-78" tabindex="-1"></a><span class="co">#head(dist)</span></span>
<span id="cb489-79"><a href="reltrns.html#cb489-79" tabindex="-1"></a>dist[<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>, <span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>] <span class="co">#mostra as 5 primeiras linhas e colunas da matriz</span></span>
<span id="cb489-80"><a href="reltrns.html#cb489-80" tabindex="-1"></a><span class="fu">range</span>(m_dists) <span class="co"># intervalo dos valores da matriz</span></span>
<span id="cb489-81"><a href="reltrns.html#cb489-81" tabindex="-1"></a><span class="fu">mean</span>(m_dists) <span class="co"># média dos valores da matriz</span></span>
<span id="cb489-82"><a href="reltrns.html#cb489-82" tabindex="-1"></a><span class="fu">sd</span>(m_dists) <span class="co"># desvio padrão dos valores da matriz</span></span>
<span id="cb489-83"><a href="reltrns.html#cb489-83" tabindex="-1"></a><span class="fu">library</span>(moments)</span>
<span id="cb489-84"><a href="reltrns.html#cb489-84" tabindex="-1"></a>sk <span class="ot">&lt;-</span> <span class="fu">skewness</span>(<span class="fu">as.matrix</span>(m_dists)) <span class="co">#calcula a assimetria da matriz</span></span>
<span id="cb489-85"><a href="reltrns.html#cb489-85" tabindex="-1"></a>ku <span class="ot">&lt;-</span> <span class="fu">kurtosis</span>(<span class="fu">as.matrix</span>(m_dists)) <span class="co">#calcula a curtose da matriz</span></span>
<span id="cb489-86"><a href="reltrns.html#cb489-86" tabindex="-1"></a>sku <span class="ot">&lt;-</span> <span class="fu">cbind</span>(sk,ku) <span class="co"># junta os dois valores em um vetor</span></span>
<span id="cb489-87"><a href="reltrns.html#cb489-87" tabindex="-1"></a><span class="fu">colnames</span>(sku) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;assimetria&quot;</span>, <span class="st">&quot;curtose&quot;</span>) <span class="co"># nomeia as colunas do vetor</span></span>
<span id="cb489-88"><a href="reltrns.html#cb489-88" tabindex="-1"></a>sku[<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>, ] <span class="co"># mostra as primeiras 10 linhas desse vetor</span></span>
<span id="cb489-89"><a href="reltrns.html#cb489-89" tabindex="-1"></a><span class="fu">summary</span>(sku) <span class="co"># mostra um resumo estatístico do vetor</span></span>
<span id="cb489-90"><a href="reltrns.html#cb489-90" tabindex="-1"></a><span class="fu">range</span>(m_dists)</span>
<span id="cb489-91"><a href="reltrns.html#cb489-91" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">1</span>)) <span class="co"># esse comando faz os gráficos aparecerem um acima do outro</span></span>
<span id="cb489-92"><a href="reltrns.html#cb489-92" tabindex="-1"></a><span class="fu">hist</span>(m_dists,</span>
<span id="cb489-93"><a href="reltrns.html#cb489-93" tabindex="-1"></a>     <span class="at">breaks =</span> <span class="dv">20</span>, <span class="co"># determina o número de colunas do histograma</span></span>
<span id="cb489-94"><a href="reltrns.html#cb489-94" tabindex="-1"></a>     <span class="at">xlim =</span> <span class="fu">range</span>(<span class="fu">floor</span>(<span class="fu">min</span>(m_dists)), <span class="fu">ceiling</span>(<span class="fu">max</span>(m_dists))), <span class="co"># limites dos eixos</span></span>
<span id="cb489-95"><a href="reltrns.html#cb489-95" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">&quot;Distr. de Frequências&quot;</span>,</span>
<span id="cb489-96"><a href="reltrns.html#cb489-96" tabindex="-1"></a>     <span class="at">freq =</span> <span class="cn">FALSE</span>, <span class="co"># mostra as frequências relativas em vez das absolutas</span></span>
<span id="cb489-97"><a href="reltrns.html#cb489-97" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">&quot;Histograma e boxplot da matriz de distâncias&quot;</span>)</span>
<span id="cb489-98"><a href="reltrns.html#cb489-98" tabindex="-1"></a><span class="fu">curve</span>(<span class="fu">dnorm</span>(x, <span class="at">mean=</span><span class="fu">mean</span>(m_dists), <span class="at">sd=</span><span class="fu">sd</span>(m_dists)), <span class="at">add=</span><span class="cn">TRUE</span>) <span class="co"># sobrepõe a curva de normalidade</span></span>
<span id="cb489-99"><a href="reltrns.html#cb489-99" tabindex="-1"></a><span class="fu">boxplot.default</span>(m_dists, <span class="at">horizontal =</span> <span class="cn">TRUE</span>, <span class="at">frame =</span> <span class="cn">FALSE</span>,</span>
<span id="cb489-100"><a href="reltrns.html#cb489-100" tabindex="-1"></a>                <span class="at">xlab=</span><span class="st">&quot;Distr. de Frequências&quot;</span>,</span>
<span id="cb489-101"><a href="reltrns.html#cb489-101" tabindex="-1"></a>                <span class="at">ylim=</span><span class="fu">c</span>(<span class="fu">floor</span>(<span class="fu">min</span>(m_dists)), <span class="fu">ceiling</span>(<span class="fu">max</span>(m_dists)))) <span class="co"># limites dos eixos</span></span>
<span id="cb489-102"><a href="reltrns.html#cb489-102" tabindex="-1"></a><span class="do">## dev.off()</span></span>
<span id="cb489-103"><a href="reltrns.html#cb489-103" tabindex="-1"></a><span class="fu">library</span>(vegan)</span>
<span id="cb489-104"><a href="reltrns.html#cb489-104" tabindex="-1"></a>m_relcol <span class="ot">&lt;-</span> <span class="fu">decostand</span>(m_trab,</span>
<span id="cb489-105"><a href="reltrns.html#cb489-105" tabindex="-1"></a>                         <span class="at">method=</span><span class="st">&quot;total&quot;</span>,</span>
<span id="cb489-106"><a href="reltrns.html#cb489-106" tabindex="-1"></a>                         <span class="at">MARGIN =</span> <span class="dv">2</span>)</span>
<span id="cb489-107"><a href="reltrns.html#cb489-107" tabindex="-1"></a><span class="co">#View(m_relcol)</span></span>
<span id="cb489-108"><a href="reltrns.html#cb489-108" tabindex="-1"></a>m_relcol</span>
<span id="cb489-109"><a href="reltrns.html#cb489-109" tabindex="-1"></a><span class="co">#colSums(m_relcol)</span></span>
<span id="cb489-110"><a href="reltrns.html#cb489-110" tabindex="-1"></a><span class="co">#range(m_relcol)</span></span>
<span id="cb489-111"><a href="reltrns.html#cb489-111" tabindex="-1"></a>m_relcol_asrq <span class="ot">&lt;-</span> <span class="fu">asin</span>(<span class="fu">sqrt</span>(m_relcol))</span>
<span id="cb489-112"><a href="reltrns.html#cb489-112" tabindex="-1"></a><span class="co">#View(m_relcol_asrq)</span></span>
<span id="cb489-113"><a href="reltrns.html#cb489-113" tabindex="-1"></a>m_relcol_asrqpi <span class="ot">&lt;-</span> <span class="dv">2</span><span class="sc">/</span>pi<span class="sc">*</span>(<span class="fu">asin</span>(<span class="fu">sqrt</span>(m_relcol)))</span>
<span id="cb489-114"><a href="reltrns.html#cb489-114" tabindex="-1"></a><span class="co">#View(m_relcol_asrqpi)</span></span>
<span id="cb489-115"><a href="reltrns.html#cb489-115" tabindex="-1"></a><span class="co">#colSums(m_relcol_asrqpi)</span></span>
<span id="cb489-116"><a href="reltrns.html#cb489-116" tabindex="-1"></a><span class="co">#range(m_relcol_asrqpi)</span></span>
<span id="cb489-117"><a href="reltrns.html#cb489-117" tabindex="-1"></a>m_trns <span class="ot">&lt;-</span> m_relcol_asrqpi</span>
<span id="cb489-118"><a href="reltrns.html#cb489-118" tabindex="-1"></a><span class="co">#m_dists &lt;- dist(m_trns, method = &quot;euclidian&quot;, diag = TRUE, upper = FALSE)</span></span>
<span id="cb489-119"><a href="reltrns.html#cb489-119" tabindex="-1"></a><span class="do">## m_relcol &lt;- decostand(m_bruta,</span></span>
<span id="cb489-120"><a href="reltrns.html#cb489-120" tabindex="-1"></a><span class="do">##                          method=&quot;total&quot;,</span></span>
<span id="cb489-121"><a href="reltrns.html#cb489-121" tabindex="-1"></a><span class="do">##                          MARGIN = 2)</span></span>
<span id="cb489-122"><a href="reltrns.html#cb489-122" tabindex="-1"></a><span class="do">## View(m_relcol)</span></span>
<span id="cb489-123"><a href="reltrns.html#cb489-123" tabindex="-1"></a><span class="do">## m_relcol</span></span>
<span id="cb489-124"><a href="reltrns.html#cb489-124" tabindex="-1"></a><span class="do">## m_lg10 &lt;- log10(m_bruta)</span></span>
<span id="cb489-125"><a href="reltrns.html#cb489-125" tabindex="-1"></a><span class="do">## #View(m_lg10)</span></span>
<span id="cb489-126"><a href="reltrns.html#cb489-126" tabindex="-1"></a><span class="do">## m_lg10 &lt;- replace(m_lg10, is.infinite(m_lg10), 0)</span></span>
<span id="cb489-127"><a href="reltrns.html#cb489-127" tabindex="-1"></a><span class="do">## head(m_lg10)</span></span>
<span id="cb489-128"><a href="reltrns.html#cb489-128" tabindex="-1"></a><span class="do">## m_lgx1 &lt;- log(m_bruta+1)</span></span>
<span id="cb489-129"><a href="reltrns.html#cb489-129" tabindex="-1"></a><span class="do">## #View(m_lgx1)</span></span>
<span id="cb489-130"><a href="reltrns.html#cb489-130" tabindex="-1"></a><span class="do">## m_bruta_P1 &lt;- m_bruta^1 #p=1</span></span>
<span id="cb489-131"><a href="reltrns.html#cb489-131" tabindex="-1"></a><span class="do">## #View(m_bruta_P1)</span></span>
<span id="cb489-132"><a href="reltrns.html#cb489-132" tabindex="-1"></a><span class="do">## m_bruta_P05 &lt;- m_bruta^0.5 #p=0,5</span></span>
<span id="cb489-133"><a href="reltrns.html#cb489-133" tabindex="-1"></a><span class="do">## #View(m_bruta_P05)</span></span>
<span id="cb489-134"><a href="reltrns.html#cb489-134" tabindex="-1"></a><span class="do">## m_bruta_P01 &lt;- m_bruta^0.1 #p=0,1</span></span>
<span id="cb489-135"><a href="reltrns.html#cb489-135" tabindex="-1"></a><span class="do">## #View(m_bruta_P01)</span></span>
<span id="cb489-136"><a href="reltrns.html#cb489-136" tabindex="-1"></a><span class="do">## m_pa &lt;- (m_bruta&gt;0)*1L</span></span>
<span id="cb489-137"><a href="reltrns.html#cb489-137" tabindex="-1"></a><span class="do">## #View(m_pa)</span></span>
<span id="cb489-138"><a href="reltrns.html#cb489-138" tabindex="-1"></a><span class="do">## m_rq &lt;- sqrt(m_bruta)</span></span>
<span id="cb489-139"><a href="reltrns.html#cb489-139" tabindex="-1"></a><span class="do">## #View(m_rq)</span></span>
<span id="cb489-140"><a href="reltrns.html#cb489-140" tabindex="-1"></a><span class="do">## m_asrq &lt;- asin(sqrt(m_relcol))</span></span>
<span id="cb489-141"><a href="reltrns.html#cb489-141" tabindex="-1"></a><span class="do">## #View(m_asrq)</span></span>
<span id="cb489-142"><a href="reltrns.html#cb489-142" tabindex="-1"></a><span class="do">## m_asrqpi &lt;- 2/pi*(asin(sqrt(m_relcol)))</span></span>
<span id="cb489-143"><a href="reltrns.html#cb489-143" tabindex="-1"></a><span class="do">## View(m_asrqpi)</span></span></code></pre></div>
</div>
<div id="referências-16" class="section level2 unnumbered">
<h2>Referências</h2>

</div>
</div>
<h3>Bibliografia Geral</h3>
<div id="refs" class="references csl-bib-body" entry-spacing="1">
<div id="ref-borcard2018" class="csl-entry">
BORCARD, D.; GILLET, F.; LEGENDRE, P. <strong>Numerical Ecology with R</strong>. Cham: Springer International Publishing, 2018. Disponível em: &lt;<a href="http://link.springer.com/10.1007/978-3-319-71404-2">http://link.springer.com/10.1007/978-3-319-71404-2</a>&gt;
</div>
<div id="ref-horton2015" class="csl-entry">
HORTON, N. J.; KLEINMAN, K. <strong>Using R and RStudio for Data Management, Statistical Analysis, and Graphics</strong>. 0. ed. [s.l.] : Chapman; Hall/CRC, 2015. Disponível em: &lt;<a href="https://www.taylorfrancis.com/books/9781482237375">https://www.taylorfrancis.com/books/9781482237375</a>&gt;
</div>
<div id="ref-legendre1998" class="csl-entry">
LEGENDRE, P.; LEGENDRE, L. <strong>Numerical Ecology</strong>. 2nd English ed ed. Amsterdam, The Netherlands ; New York ; Oxford.
</div>
<div id="ref-sokal1995" class="csl-entry">
SOKAL, R. R.; ROHLF, F. J. <strong>Biometry: The Principles and Practice of Statistics in Biological Research</strong>. 3. ed. New York: W.H. Freeman; Company, 1995. Type: Book.
</div>
<div id="ref-sokal2009" class="csl-entry">
SOKAL, R. R.; ROHLF, F. J. <strong>Introduction to Biostatistics</strong>. 2nd ed., Dover ed ed. Mineola, N.Y: Dover Publications, 2009.
</div>
</div>
  </main>

  <div class="col-md-3 col-lg-2 d-none d-md-block sidebar sidebar-chapter">
    <nav id="toc" data-toggle="toc" aria-label="On this page">
      <h2>On this page</h2>
      <div id="book-on-this-page"></div>

      <div class="book-extra">
        <ul class="list-unstyled">
          <li><a id="book-source" href="#">View source <i class="fab fa-github"></i></a></li>
          <li><a id="book-edit" href="#">Edit this page <i class="fab fa-github"></i></a></li>
        </ul>
      </div>
    </nav>
  </div>

</div>
</div> <!-- .container -->

<footer class="bg-primary text-light mt-5">
  <div class="container"><div class="row">

  <div class="col-12 col-md-6 mt-3">
    <p>"<strong>Fundamentos de Ecologia Numérica</strong>: Disciplina de Ecologia Numérica do Curso de Ciências Biológicas do Campus V da UEPB" was written by Prof. Elvio S. F. Medeiros, Laboratório de Ecologia, Universidade Estadual da Paraíba, Campus V, João Pessoa, PB. It was last built on Last updated: 24/07/2026 16:50:19.</p>
  </div>

  <div class="col-12 col-md-6 mt-3">
    <p>This book was built by the <a class="text-light" href="https://bookdown.org">bookdown</a> R package.</p>
  </div>

</div></div>
</footer>


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
<script type="text/x-mathjax-config">const popovers = document.querySelectorAll('a.footnote-ref[data-toggle="popover"]');
for (let popover of popovers) {
  const div = document.createElement('div');
  div.setAttribute('style', 'position: absolute; top: 0, left:0; width:0, height:0, overflow: hidden; visibility: hidden;');
  div.innerHTML = popover.getAttribute('data-content');

  var has_math = div.querySelector("span.math");
  if (has_math) {
    document.body.appendChild(div);
    MathJax.Hub.Queue(["Typeset", MathJax.Hub, div]);
    MathJax.Hub.Queue(function() {
      popover.setAttribute('data-content', div.innerHTML);
      document.body.removeChild(div);
    })
  }
}
</script>
</body>

</html>
